### ISSUE TITLE
Graalvm native image cli  java.lang.NoClassDefFoundError: Lorg/codehaus/janino/ScriptEvaluator;

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1100]
Jdk version: 
```
java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
```

Native image version: 
```
native-image --version
GraalVM Version 19.3.1 CE
```

This was caused when running Scala `2.13.1` on  7fbc6423a5c81aec1fa7c31e3307fa2452585b95 

with the command ` cli/graalvm-native-image:packageBin` inside of sbt

The stack trace:

>[error] Fatal error: com.oracle.svm.core.util.VMError$HostedError: java.lang.NoClassDefFoundError: Lorg/codehaus/janino/ScriptEvaluator;
[error]         at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:70)
[error]         at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:636)
[error]         at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
[error]         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[error]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Caused by: java.lang.NoClassDefFoundError: Lorg/codehaus/janino/ScriptEvaluator;
[error]         at java.base/java.lang.Class.getDeclaredFields0(Native Method)
[error]         at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3061)
[error]         at java.base/java.lang.Class.getDeclaredField(Class.java:2409)
[error]         at com.oracle.graal.pointsto.infrastructure.OriginalFieldProvider.getJavaField(OriginalFieldProvider.java:43)
[error]         at com.oracle.graal.pointsto.meta.AnalysisField.getJavaField(AnalysisField.java:420)
[error]         at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readUninitializedStaticValue(AnalysisConstantReflectionProvider.java:136)
[error]         at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:87)
[error]         at com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:77)
[error]         at com.oracle.svm.hosted.meta.HostedField.readValue(HostedField.java:156)
[error]         at com.oracle.svm.hosted.image.NativeImageHeap.writeField(NativeImageHeap.java:575)
[error]         at com.oracle.svm.hosted.image.NativeImageHeap.writeStaticFields(NativeImageHeap.java:544)
[error]         at com.oracle.svm.hosted.image.NativeImageHeap.writeHeap(NativeImageHeap.java:295)
[error]         at com.oracle.svm.hosted.image.NativeBootImage.build(NativeBootImage.java:461)
[error]         at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:625)
[error]         ... 7 more
[error] Caused by: java.lang.ClassNotFoundException: org.codehaus.janino.ScriptEvaluator
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]         ... 21 more
[error] Error: Image build request failed with exit status 1
[error] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[error]         at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
[error]         at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
[error]         at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
[error]         at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
[error]         at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1665)
[error] stack trace is suppressed; run last cli / Graalvm-native-image / packageBin for the full output

**Comment by Christewart** [comment]
Possibly related: https://github.com/oracle/graal/issues/1943

**Comment by Christewart** [comment]
Fixed upstream in https://github.com/oracle/graal/issues/1943
