### ISSUE TITLE
Building `bitcoin-s-cli` 2.13.1 fails because of `Cli.scala` implementation

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1104]
With the fix inside of #1101, we can now successfully build `bitcoin-s-cli` with Scala 2.13.x. However if we attempt to actually run it, we get this error 

> ./bitcoin-s-cli
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported constructor java.lang.invoke.MemberName.<init>(Class, String, MethodType, byte) is reachable: All methods from java.lang.invoke should have been replaced during image building.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
        at java.lang.invoke.MemberName.<init>(MemberName.java:812)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
        at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:1102)
        at scala.runtime.Statics$VM.mkHandle(Statics.java:161)
        at scala.runtime.Statics$VM.<clinit>(Statics.java:155)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:475)
        at scala.runtime.Statics.releaseFence(Statics.java:148)
        at scala.collection.immutable.$colon$colon.<init>(List.scala:586)
        at scala.collection.mutable.ListBuffer.addOne(ListBuffer.scala:108)
        at scala.App.delayedInit(App.scala:62)
        at scala.App.delayedInit$(App.scala:61)
        at org.bitcoins.cli.Cli$.delayedInit(Cli.scala:7)
        at org.bitcoins.cli.Cli$.<clinit>(Cli.scala:7)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:475)
        at org.bitcoins.cli.Cli.main(Cli.scala)

I believe this has something to do with [`App`](https://github.com/bitcoin-s/bitcoin-s/blob/7fbc6423a5c81aec1fa7c31e3307fa2452585b95/app/cli/src/main/scala/org/bitcoins/cli/Cli.scala#L7).

Here is the implementation of `App` in Scala 2.12.x 

https://github.com/scala/scala/blob/2.12.x/src/library/scala/App.scala

and here it is with `2.13.x` 

https://github.com/scala/scala/blob/2.13.x/src/library/scala/App.scala

**Comment by Christewart** [comment]
Related to #1100
