### ISSUE TITLE
Building on Mac OS does not output `.so` files

### ISSUE THREAD

**Issue by mecampbellsoup** [bitcoin-s/bitcoin-s#122]
Per the build instructions, when attempting to run the following command I hit an error:

```bash
13:40:24 › cp secp256k1/.libs/libsecp256k1.so lib
cp: secp256k1/.libs/libsecp256k1.so: No such file or directory

13:44:55 › ls -lah secp256k1/.libs
total 2168
drwxr-xr-x   9 mec  staff   288B Mar 20 13:40 .
drwxr-xr-x  33 mec  staff   1.0K Mar 20 13:40 ..
-rwxr-xr-x   1 mec  staff   361K Mar 20 13:40 libsecp256k1.0.dylib
-rw-r--r--   1 mec  staff   654K Mar 20 13:40 libsecp256k1.a
lrwxr-xr-x   1 mec  staff    20B Mar 20 13:40 libsecp256k1.dylib -> libsecp256k1.0.dylib
lrwxr-xr-x   1 mec  staff    18B Mar 20 13:40 libsecp256k1.la -> ../libsecp256k1.la
-rw-r--r--   1 mec  staff   970B Mar 20 13:40 libsecp256k1.lai
-rw-r--r--   1 mec  staff    58K Mar 20 13:40 libsecp256k1_jni.a
lrwxr-xr-x   1 mec  staff    22B Mar 20 13:40 libsecp256k1_jni.la -> ../libsecp256k1_jni.la
```

I believe on Darwin the shared objects are complied as `*.dylib` files, so I did the following instead:

```sh
cp secp256k1/.libs/libsecp256k1.dylib lib
```
This seems to be working OK, but when attempting to start `sbt console` I hit the following (probably related?) Java exception: 

```
14:14:26 › sbt console
[info] Loading project definition from /Users/mec/Sites/crypto/bitcoin-s-core/project
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1147)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1264)
        at java.base/java.util.regex.Pattern.split(Pattern.java:1335)
        at sbt.IO$.pathSplit(IO.scala:797)
        at sbt.IO$.parseClasspath(IO.scala:912)
        at sbt.compiler.CompilerArguments.extClasspath(CompilerArguments.scala:66)
        at sbt.compiler.MixedAnalyzingCompiler$.withBootclasspath(MixedAnalyzingCompiler.scala:188)
        at sbt.compiler.MixedAnalyzingCompiler$.searchClasspathAndLookup(MixedAnalyzingCompiler.scala:166)
        at sbt.compiler.MixedAnalyzingCompiler$.apply(MixedAnalyzingCompiler.scala:176)
        at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
        at sbt.Compiler$.compile(Compiler.scala:155)
        at sbt.Compiler$.compile(Compiler.scala:141)
        at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:879)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:870)
        at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:868)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
[error] (compile:compileIncremental) java.lang.NullPointerException
```

**Comment by mecampbellsoup** [comment]
UPDATE: the `NullPointerException` stems from using JDK version 9 instead of 8.

Also, found someone else had pointed out that Mac OS does not output `.so` files [here](https://github.com/bitcoin-s/bitcoin-s-core/issues/83#issuecomment-326999795).

**Comment by Christewart** [comment]
@mecampbellsoup Hi, yes this is being changed in #120. There are some issues in older verisions of libsecp256k1 for mac's. 

After checking out #120, you should be able to do these commands: 

```
$ cd secp256k1 && ./autogen.sh && ./configure --enable-jni --enable-experimental --enable-module-ecdh && make && cd ../ && sbt -Djava.library.path=secp256k1/.libs/
```

Once the sbt console is fired up, a quick way to test if `libsecp256k1` is linked properly is running this test: 
```
> test-only *ECDigitalSignature*
```

The `ECDigitalSignatureSpec` and `ECDigitalSignatureTest` make's sure we can verify digital signatures with `libsecp256k1`.

**Comment by Christewart** [comment]
If you are feeling brave you can try to figure out why travis does not like `oraclejdk8` for mac os builds on #121 :-)
