### ISSUE TITLE
Reserving Multiple UTXOs causes a constrait violation

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#1584]
This test: will fail with the following stack trace

```
  it should "track multiple utxos state change to reserved" in { param =>
    val WalletWithBitcoindRpc(wallet, _) = param

    for {
      utxos <- wallet.listUtxos()
      reserved <- wallet.markUTXOsAsReserved(utxos)
    } yield {
      assert(reserved.forall(_.state == TxoState.Reserved))
    }
  }
```

```
should track multiple utxos state change to reserved *** FAILED *** (3 seconds, 406 milliseconds)
[info]   org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: txo_spending_info.id)
[info]   at org.sqlite.core.DB.newSQLException(DB.java:1010)
[info]   at org.sqlite.core.DB.newSQLException(DB.java:1022)
[info]   at org.sqlite.core.DB.execute(DB.java:861)
[info]   at org.sqlite.core.DB.executeUpdate(DB.java:902)
[info]   at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[info]   at slick.jdbc.LoggingPreparedStatement.$anonfun$executeUpdate$5(LoggingStatement.scala:170)
[info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
[info]   at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
```

**Comment by benthecarman** [comment]
caused by #1586
