### ISSUE TITLE
App server fails to start with flyway exception

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1653]
**Describe the bug**
I built 8b85751b461d2ec4151f12265ae4fb2cf9fe40c9  and tried to run `./bitcoin-s-server` and I got an exception with respect to flyway:

>./bitcoin-s-server
Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed:
Migration checksum mismatch for migration version 5
 Applied to database : -1956179783
Resolved locally    : 1935316429

        at org.flywaydb.core.Flyway.doValidate(Flyway.java:285)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:74)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:167)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
        at org.flywaydb.core.Flyway.execute(Flyway.java:530)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
        at org.bitcoins.db.DbManagement.migrate(DbManagement.scala:109)
        at org.bitcoins.db.DbManagement.migrate$(DbManagement.scala:91)
        at org.bitcoins.wallet.config.WalletAppConfig.migrate(WalletAppConfig.scala:29)
        at org.bitcoins.wallet.config.WalletAppConfig.initialize(WalletAppConfig.scala:97)
        at org.bitcoins.server.BitcoinSAppConfig.initialize(BitcoinSAppConfig.scala:31)
        at org.bitcoins.server.Main$.runMain(Main.scala:76)
        at org.bitcoins.server.Main$.delayedEndpoint$org$bitcoins$server$Main$1(Main.scala:160)
        at org.bitcoins.server.Main$delayedInit$body.apply(Main.scala:27)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at org.bitcoins.server.Main$.main(Main.scala:27)
        at org.bitcoins.server.Main.main(Main.scala)

**Comment by Christewart** [comment]
This problem was caused by me running the DLC branch (https://github.com/bitcoin-s/bitcoin-s/tree/dlc) from the same data directory as my default data directory for bitcoin-s master. This introduced tables that were only available on the DLC branch, which caused flyway to throw an exception.

Here is what my database schema looked like in `walletdb.sqlite` 

>sqlite3 walletdb.sqlite
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> .tables
addresses                  wallet_dlc_cet_sigs
flyway_schema_history      wallet_dlc_funding_inputs
tx_table                   wallet_dlc_offers
txo_spending_info          wallet_dlcs
wallet_accounts            wallet_incoming_txs
wallet_dlc_accepts         wallet_outgoing_txs


Notice that I had these tables with the prefix `wallet_dlc`. These were the problem. Since I did not have anything valuable in these tables I just decided to drop them. 

I also needed to go and fix my `flyway_schema_history` history table, since it contained migrations from the DLC branch. Here is what `flyway_schema_history` looked like initially: 

>select * from flyway_schema_history;
1|1|<< Flyway Baseline >>|BASELINE|<< Flyway Baseline >>||null|2020-01-29 22:13:29.511|0|1
2|2|wallet db spent to txo state|SQL|V2__wallet_db_spent_to_txo_state.sql|-1295024906||2020-01-29 22:13:29.545|4|1
3|3|txo spending info drop confirmations|SQL|V3__txo_spending_info_drop_confirmations.sql|-1253245802||2020-02-22 14:17:23.634|3|1
4|4|wallet db add transaction table|SQL|V4__wallet_db_add_transaction_table.sql|-60690023||2020-05-01 18:26:36.339|3|1
5|5|wallet db add dlcs|SQL|V5__wallet_db_add_dlcs.sql|-1956179783||2020-06-06 17:04:20.841|3|1
6|6|wallet db dlc outcome sigs table|SQL|V6__wallet_db_dlc_outcome_sigs_table.sql|-87415582||2020-06-06 17:04:20.864|2|1


I deleted rows `5` and `6` since they were specific to the DLC branch, and the node would startup (albeit with a new issue #1655)
