### ISSUE TITLE
Initial block header sync leaks memory

### ISSUE THREAD

**Issue by rorp** [bitcoin-s/bitcoin-s#1714]
Here is what happens when the node is syncing testnet block headers (max heap size is not set):
```
2020-07-28T16:07:11 INFO [P2P] Received headers message with 2000 headers
Uncaught error from thread [bitcoin-s-akka.actor.default-dispatcher-13]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[bitcoin-s]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:172)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:538)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1194)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
	at scala.collection.AbstractIterable.addString(Iterable.scala:920)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
	at scala.collection.AbstractIterable.mkString(Iterable.scala:920)
	at scala.collection.Iterable.toString(Iterable.scala:76)
	at scala.collection.Iterable.toString$(Iterable.scala:76)
	at scala.collection.Seq.toString(Seq.scala:49)
	at scala.collection.Seq.toString$(Seq.scala:49)
	at scala.collection.AbstractSeq.toString(Seq.scala:1152)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at slick.dbio.SuccessAction.getDumpInfo(DBIOAction.scala:312)
	at slick.util.TreePrinter.dump$1(TreePrinter.scala:22)
	at slick.util.TreePrinter.$anonfun$print$3(TreePrinter.scala:44)
	at slick.util.TreePrinter.$anonfun$print$3$adapted(TreePrinter.scala:41)
	at slick.util.TreePrinter$$Lambda$338/0x000000080044a040.apply(Unknown Source)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.util.TreePrinter.dump$1(TreePrinter.scala:41)
	at slick.util.TreePrinter.$anonfun$print$3(TreePrinter.scala:44)
	at slick.util.TreePrinter.$anonfun$print$3$adapted(TreePrinter.scala:41)
	at slick.util.TreePrinter$$Lambda$338/0x000000080044a040.apply(Unknown Source)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.util.TreePrinter.dump$1(TreePrinter.scala:41)
	at slick.util.TreePrinter.$anonfun$print$3(TreePrinter.scala:44)
	at slick.util.TreePrinter.$anonfun$print$3$adapted(TreePrinter.scala:41)
	at slick.util.TreePrinter$$Lambda$338/0x000000080044a040.apply(Unknown Source)
```

`Xmx512m`:
```2020-07-28T16:22:00 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:00 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:01 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:01 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:02 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:02 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:03 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:03 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:04 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:04 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:05 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:06 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:07 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:11 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:17 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:26 INFO [P2P] Received headers message with 2000 headers
2020-07-28T16:22:43 INFO [P2P] Received headers message with 2000 headers
Uncaught error from thread [bitcoin-s-akka.actor.default-dispatcher-5]: Java heap space, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[bitcoin-s]
java.lang.OutOfMemoryError: Java heap space
```

I was able to sync the testnet block headers only after setting `Xmx` to 8GB.

**Comment by rorp** [comment]
![image](https://user-images.githubusercontent.com/2314888/88729837-a0166100-d0e9-11ea-8e2f-13b8a0ab2336.png)

**Comment by rorp** [comment]
It seems that https://github.com/bitcoin-s/bitcoin-s/pull/1697 fixes it.
