### ISSUE TITLE
Database queue fills and throws an exception when syncing filters checkpoints

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1724]
After running chainwork recalculation  as documetned here, I got a database error when starting to sync the node after running chain work recalc: https://github.com/bitcoin-s/bitcoin-s/pull/1697#issuecomment-666581022

The key thing from the error message below is

> Task slick.basic.BasicBackend$DatabaseDef$$anon$3@7334dd54 rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@45c456b3[Running, pool size = 5, active threads = 5, queued tasks = 1000, completed tasks = 2760]

I believe slick has a default of `1000` tasks to be queue for running on the database before it throws and exception, which happens here. Why do we end up 1,000 queued tasks and we can't process them all on startup? Are we not batching upserting of compact filters?

>2020-07-30T18:14:40 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,cfcheckpt,UInt32Impl(57028),ByteVector(4 bytes, 0x40555c33)), CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(399b19db0deb1dfdda6c6a337a1b933be7ce2c3a5e70c02132a0267e00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(0bad5ec75288b82e8a441f2abcc6cd7ff41735684b073411f0971f0ca90f5095)))
2020-07-30T18:14:40 DEBUG [P2P] Unaligned bytes after this: 8132
2020-07-30T18:14:40 DEBUG [P2P] Received message=cfcheckpt from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) state=Normal
2020-07-30T18:14:40 DEBUG [P2P] Got 1781 checkpoints CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(399b19db0deb1dfdda6c6a337a1b933be7ce2c3a5e70c02132a0267e00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(0bad5ec75288b82e8a441f2abcc6cd7ff41735684b073411f0971f0ca90f5095))

**Comment by Christewart** [comment]
This is my log when starting my node in #1733 

https://pastebin.com/UE3sjpZG

**Comment by Christewart** [comment]
So this resolved the problem for me: https://github.com/bitcoin-s/bitcoin-s/issues/1737#issuecomment-667587856

**Comment by benthecarman** [comment]
Currently seeing the same behavior on `master`(`eb09319`). 
```
2020-08-04T16:38:40 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,cfcheckpt,UInt32Impl(55172),ByteVector(4 bytes, 0x58952b44)), CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(4c64682e3ad671ba9e8531e6940c93a9576c45c8390b8c9cedd35cbc00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(3b7c9700f7af2746c9020456ff1c50ef90381db757827dd4968351c931134dd1)))
2020-08-04T16:38:40 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-04T16:38:40 DEBUG [P2P] Received message=cfcheckpt from peer=Peer(localhost/127.0.0.1:18333) state=Normal 
2020-08-04T16:38:40 DEBUG [P2P] Got 1723 checkpoints CompactFilterCheckPointMessage(filterType=Basic, stopHash=DoubleSha256Digest(4c64682e3ad671ba9e8531e6940c93a9576c45c8390b8c9cedd35cbc00000000), filterHeaders=DoubleSha256Digest(22353b4ea01c7b93e55558f3e47489f6a518e8d570e0867bac3f56d013ccfd20)...DoubleSha256Digest(3b7c9700f7af2746c9020456ff1c50ef90381db757827dd4968351c931134dd1))
2020-08-04T16:38:42 INFO [HTTP] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2020-08-04T16:38:42 INFO [HTTP] Starting neutrino node sync
[ERROR] [08/04/2020 11:40:25.094] [bitcoin-s-akka.actor.internal-dispatcher-3] [akka://bitcoin-s/user/P2PClient$-1596559119348] Task slick.basic.BasicBackend$DatabaseDef$$anon$3@410064fb rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@781c2099[Running, pool size = 5, active threads = 5, queued tasks = 1000, completed tasks = 91]
java.util.concurrent.RejectedExecutionException: Task slick.basic.BasicBackend$DatabaseDef$$anon$3@410064fb rejected from slick.util.AsyncExecutor$$anon$1$$anon$2@781c2099[Running, pool size = 5, active threads = 5, queued tasks = 1000, completed tasks = 91]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at slick.util.AsyncExecutor$$anon$1$$anon$4.execute(AsyncExecutor.scala:161)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:265)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:263)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:242)

```

**Comment by Christewart** [comment]
> Currently seeing the same behavior on `master`(`eb09319`).

Just to confirm, you are recalcing chain work ?

If not, could you please confirm that you have these indexes on your database (https://github.com/bitcoin-s/bitcoin-s/issues/1737#issuecomment-667587856)

Also consider running with visualvm attached and monitoring `chaindb` threads to see if they are ever not running (that's how I determined I was missing indexes)

**Comment by benthecarman** [comment]
> Just to confirm, you are recalcing chain work ?

Not recalcing chain work, just trying to sync.

> If not, could you please confirm that you have these indexes on your database (#1737 (comment))

Looks like I only have the chain work index
