### ISSUE TITLE
No common ancestor found in the chain

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1739]
**Describe the bug**
I received these error messages last night when trying to sync my compact block filters. It seems to have stopped all syncing operations. I'm guessing these are new block headers coming in on the testnet network?

It seems that we don't have headers to connect to for this headers message?

>HeadersMessage(CompactSizeUInt(4),000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3..00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)

Finally we fail with this exception

>org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: block_headers.hash)

Here is the full log:
```
2020-08-02T04:02:51 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,headers,UInt32Impl(325),ByteVector(4 bytes, 0xef003c20)), HeadersMessage(CompactSizeUInt(4),000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3..00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-02T04:02:51 DEBUG [P2P] Received message=headers from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) state=Normal 
2020-08-02T04:02:51 INFO [P2P] Received headers message with 4 headers
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000005dde0bd11aebd658a0c770b47dff712942ab4ac9102d61b7a914f2a3)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(000000001c932c0df4c8c9df1e7b1753fa1a12b9bdabb6d21b8cf9d1e51b0e6e)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(0000000070cce55b1620a13f866d60c43c374e6e711329d79f270e6a1f5a360a)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 WARN [chain-verification] No common ancestor found in the chain to connect to DoubleSha256BDigestBE(00000000287529e4cc1ddf6a07104269e995e3b6ee9628026a6c99f40a57f920)
2020-08-02T04:02:51 ERROR [P2P] Error when processing headers message
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: block_headers.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.DB.executeBatch(DB.java:812)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)
	at slick.jdbc.LoggingStatement.$anonfun$executeBatch$1(LoggingStatement.scala:114)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:114)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-08-02T04:02:51 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetCompactFiltersMessage(Basic,UInt32Impl(1742875),DoubleSha256Digest(027340bf7219e5825273b4b59fb7bed001d86aef36ab5eadda19000000000000)) peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)

```

**Comment by Christewart** [comment]
So from trying to run this again today, here are some more things I noticed.

Here is the initial node state

>2020-08-03T17:27:55 INFO [P2P] Started node, best block hash 000000007a403ef62bebb7266f60e8d304d27e9d1f535c14a66cc0102a0926d1 at height 1782875, with 1782121 filter headers and 1742874 filters


1. I added a log at the very beginning of `ChainApi.processHeaders()`. I also added the `prevhash=` that shows the block header we are attempting to connect to. 

2. It's interesting that we don't returned a `Future.failed()` in the case where we cant connect headers. Obviously we are failing to process these headers as indicated by the WARN messages we are returning. It seems that I keep trying to sync _forever_ (I keep requesting headers from the node) even though I am getting fed a "bad chain" (according to my local chain state).  

3. Since we don't return a failed future, we keep syncing even though we didn't properly process the last batch of headers [as you can see here](https://github.com/bitcoin-s/bitcoin-s/blob/626536ac58352eb6b5195b3b3489e218a495a1a3/node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala#L158-L167). It's _really_ important we return a failed future if we can't add a batch of headers, so we don't continue syncing

```
2020-08-03T17:28:17 INFO [chain-verification] processHeaders=Some(DoubleSha256BDigestBE(00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206))...Some(DoubleSha256BDigestBE(0000000005bdbddb59a3cd33b69db94fa67669c41d9d32751512b5d7b68c71cf))
2020-08-03T17:28:17 DEBUG [chain-verification] Attempting to connect 2000 headers to 1 blockchains
2020-08-03T17:28:17 DEBUG [chain-verification] Attempting to add new tip=00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206 with prevhash=000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943 to chain
2020-08-03T17:28:17 WARN [chain-verification] No common ancestor found in the chain to connect to hash=DoubleSha256BDigestBE(00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206) prevHash=DoubleSha256BDigestBE(000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943)
2020-08-03T17:28:17 DEBUG [chain-verification] Attempting to add new tip=000000006c02c8ea6e4ff69651f7fcde348fb9d557a06e6957b65552002a7820 with prevhash=00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206 to chain
2020-08-03T17:28:17 WARN [chain-verification] No common ancestor found in the chain to connect to hash=DoubleSha256BDigestBE(000000006c02c8ea6e4ff69651f7fcde348fb9d557a06e6957b65552002a7820) prevHash=DoubleSha256BDigestBE(00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206)
... //more errors like this that I'm omitting for now
```

**Comment by benthecarman** [comment]
Yeah so it seems your chain tip was reorg'ed out

```
$ bitcoin-cli --testnet getblock 000000007a403ef62bebb7266f60e8d304d27e9d1f535c14a66cc0102a0926d1
{
  "hash": "000000007a403ef62bebb7266f60e8d304d27e9d1f535c14a66cc0102a0926d1",
  "confirmations": -1,
  "strippedsize": 191,
  "size": 191,
  "weight": 764,
  "height": 1782875,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "aef862fc0d9929b7fa6e4b6564e3c72435a40f66bf2aad1c250b629b3cdc442a",
  "tx": [
    "aef862fc0d9929b7fa6e4b6564e3c72435a40f66bf2aad1c250b629b3cdc442a"
  ],
  "time": 1596340964,
  "mediantime": 1596340961,
  "nonce": 1488590511,
  "bits": "1d00ffff",
  "difficulty": 1,
  "chainwork": "0000000000000000000000000000000000000000000001b9ce0abf0f4f94cef3",
  "nTx": 1,
  "previousblockhash": "00000000a6e6e645ab251574852e18450a30453c5402d4dd931f616cd69118fb"
}

```
-1 confirmations means not in best chain

**Comment by benthecarman** [comment]
> It's interesting that we don't returned a Future.failed() in the case where we cant connect headers.

I think this is the correct choice, if we receive an invalid header or have a failure that could be triggered by another party, the `Future.failed()` would give someone else the ability to shutdown our node

**Comment by benthecarman** [comment]
So the problem here is that the `ChainHandler` only caches the last 2016 blocks and if there is a reorg larger than that, we say it has a bad prev block hash because we can't find it.

**Comment by Christewart** [comment]
> > It's interesting that we don't returned a Future.failed() in the case where we cant connect headers.
> 
> I think this is the correct choice, if we receive an invalid header or have a failure that could be triggered by another party, the `Future.failed()` would give someone else the ability to shutdown our node

If they are feeding us invalid headers they should at the very least be disconnected. The alternative is to allow them to keep feeding us invalid headers exhausting our CPU/disk space.

**Comment by benthecarman** [comment]
> If they are feeding us invalid headers they should at the very least be disconnected

That's a good point. However, should probably wait until we support more than a single peer

**Comment by Christewart** [comment]
> > If they are feeding us invalid headers they should at the very least be disconnected
> 
> That's a good point. However, should probably wait until we support more than a single peer

Why? What good can come from being connected? Your node is already borked and your wallet state is not accurate (since you aren't on the latest tip).

**Comment by benthecarman** [comment]
~~So, turns out it was only a 2 block reorg, so I recreated the chain state you should have by removing all the headers after `1782873` and adding the 2 blocks that were re-orged out and mine starts syncing correctly. So it seems this is issue might be with something else, not re-org.~~

Looks like I didn't correctly create the chain state, and I can reproudce

**Comment by benthecarman** [comment]
Looks like since we are requesting a block not in the best chain we are getting sent back the first 2000 blocks

`00000000b873e79784647a6c82962c70d228557d24a747ea4d1b8bbe878e1206` -> `0000000005bdbddb59a3cd33b69db94fa67669c41d9d32751512b5d7b68c71cf`
