### ISSUE TITLE
Database file locked, using bitcoin-s-cli while syncing filters

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1769]
**Describe the bug**
While doing IBD I wanted to check out the state of my database. Here is what I executed in terms of cli commands

>➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
1805050
➜  bin git:(master) ✗ ./bitcoin-s-cli getfilterheadercount
1805047
➜  bin git:(master) ✗ ./bitcoin-s-cli getfiltercount
626599

You can see the `getfiltercount` request being received at the very top of the logs I pasted. This seems to cause the database to become locked and throw an exception. This stops the node from operating causing IBD to fail. You can see that I actually got a valid return for `getfiltercount`, however there may have been a write attempt to the database simultaneously that caused the node to fail.

>2020-08-06T15:56:47 DEBUG [chain-verification] getFilterCount result: count=626599
[INFO] [08/06/2020 10:56:47.440] [bitcoin-s-akka.actor.default-dispatcher-14] [akka.actor.ActorSystemImpl(bitcoin-s)] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/1.8.0_242, Host: localhost:9999, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,83 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,30 bytes total),HttpProtocol(HTTP/1.1)))
[ERROR] [08/06/2020 10:56:47.472] [bitcoin-s-akka.actor.internal-dispatcher-25] [akka://bitcoin-s/user/P2PClient$-1596728123902] [SQLITE_BUSY]  The database file is locked (database is locked)
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:1010)
        at org.sqlite.core.DB.newSQLException(DB.java:1022)
        at org.sqlite.core.DB.throwex(DB.java:987)
        at org.sqlite.core.DB.exec(DB.java:185)
        at org.sqlite.SQLiteConnection.commit(SQLiteConnection.java:404)
        at slick.jdbc.JdbcActionComponent$Commit$.$anonfun$run$1(JdbcActionComponent.scala:44)
        at slick.jdbc.JdbcBackend$BaseSession.endInTransaction(JdbcBackend.scala:517)
        at slick.jdbc.JdbcActionComponent$Commit$.run(JdbcActionComponent.scala:44)
        at slick.jdbc.JdbcActionComponent$Commit$.run(JdbcActionComponent.scala:42)
        at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:579)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-08-06T15:56:47 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetCompactFiltersMessage(Basic,UInt32Impl(626700),DoubleSha256Digest(bb2948ffabdc05a02938f64e0f7cc06d79502933772b161292ab0000

**Comment by benthecarman** [comment]
the sync is too fast now lol

**Comment by Christewart** [comment]
Root cause was fixed in #2121
