### ISSUE TITLE
getconfirmedbalance not working

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1780]
This is the address on the testnet blockchain: https://blockstream.info/testnet/address/tb1qufh4hy0nse2mn46tsvzs0yp2thew9736fvat06

```
./bitcoin-s-cli getutxos
2ada5ad20661496580dfde529d0f7228db03728479f2fc8ef2306a4ca89ab80001000000 1815403 sats
0644f13e2623cd3020ca38ed97e10fbe54f5dbfa0022da90262b83bfe0b4f7c700000000 30000000 sats
b8a89c1c4bb9b744baf640199fa1bf25e1bedb9d6fc8d1102220801b805604d101000000 20000000 sats
c171dee042da941d568b1c516047d84a6e0aadb8d6d34fe2bf8f1b11ca2eee4d00000000 10000000 sats

➜  bin git:(master) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getbalance
0.60000000 BTC
```

I would expect after that many confirms that `getconfirmedbalance` and `getbalance would return the same thing.

**Comment by benthecarman** [comment]
I think the same thing that is causing #1770 is causing this. It seems utxos are never changed from pending received to received

**Comment by Christewart** [comment]
This was not fixed in #1782 

You can se I waited for a few blocks to be generated and to check my `confirmedbalance` after running 1a8013242bcf8ac0fa696ac725973481c58b4bb4 

>➜  bin git:(master) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getbalance
0.60000000 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
1805894
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
1805894
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
1805897
➜  bin git:(master) ✗ ./bitcoin-s-cli getconfirmedbalance
0E-8 BTC

**Comment by benthecarman** [comment]
worked for me :tm: 


![image](https://user-images.githubusercontent.com/15256660/89717674-880ecf00-d97e-11ea-9e81-3347c4472215.png)

Maybe there is another case where the header callback isn't being called as mine node synced a bunch of blocks when it turned on and it seems you are synced and watching blocks as they come in

**Comment by benthecarman** [comment]
> Maybe there is another case where the header callback isn't being called as mine node synced a bunch of blocks when it turned on and it seems you are synced and watching blocks as they come in

Yep, able to reproduce it if I am fully synced

**Comment by benthecarman** [comment]
Okay the issue is a tricky one.

So, I believe the problem is that our Wallet's chainApi != our Node's chainApi. This is happens because the `DataMessageHandler` will be constantly updating its chainApi every message it receives, however, the wallet will use the same one it starts when we first boot up the node. This would be fine if we did not cache the last 2016 headers for calculating things like `getBlockBlockHeader` as this causes the wallet's chain handler's cache to be stuck at where it was first booted up. Ideally, it would be best if the node used the cached version so it would have speedy sync times, and the wallet only made calls to the database.

Maybe we can add a flag to the `ChainHandler` signifying to use the cache or not.
Or just create a different `ChainApi` that doesn't have a cache and use it only for the wallet.

As a temp fix we can just change `getNumberOfConfirmations` to not use the cached chain tip and instead get it from the db

**Comment by Christewart** [comment]
So digging into this deeper and running on 813f24c23c of #1789 one issue is that there is a very old utxo in my database that that needs to be updated from `PendingConfirmationsReceived` -> `Confirmed`. It is included in block [00b89aa84c6a30f28efcf279847203db28720f9d52dedf8065496106d25ada2a](https://blockstream.info/testnet/tx/00b89aa84c6a30f28efcf279847203db28720f9d52dedf8065496106d25ada2a) which as of the time of this writing is ~ 136,000 deep in the testnet blockchain.

From running and looking at visualvm it appears that we are having issues traversing our blockchain that far in the past. You can see that the `blocking-io-dispactcher-28` thread is constantly running

![Screenshot from 2020-08-14 12-49-49](https://user-images.githubusercontent.com/3514957/90278951-e3810700-de2d-11ea-8fe6-112beca9db9b.png)

Here is the thread dump

>"bitcoin-s-akka.actor.default-blocking-io-dispatcher-28" #55 prio=5 os_prio=0 cpu=203444,77ms elapsed=204,29s tid=0x00007fb25804a000 nid=0xac610 runnable  [0x00007fb2320f6000]
   java.lang.Thread.State: RUNNABLE
        at scodec.bits.ByteVector$View.apply(ByteVector.scala:1556)
        at scodec.bits.ByteVector$Chunk.getImpl(ByteVector.scala:1608)
        at scodec.bits.ByteVector.get(ByteVector.scala:97)
        at scodec.bits.ByteVector.apply(ByteVector.scala:107)
        at scodec.bits.ByteVector.go$9(ByteVector.scala:1362)
        at scodec.bits.ByteVector.$eq$eq$eq(ByteVector.scala:1366)
        at scodec.bits.ByteVector.equals(ByteVector.scala:1377)
        at org.bitcoins.crypto.DoubleSha256DigestBE.equals(HashDigest.scala:136)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.$anonfun$connectWalkBackwards$1(BaseBlockChain.scala:248)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.$anonfun$connectWalkBackwards$1$adapted(BaseBlockChain.scala:248)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject$$Lambda$1777/0x000000084099b040.apply(Unknown Source)
        at scala.collection.IterableOnceOps.find(IterableOnce.scala:612)
        at scala.collection.IterableOnceOps.find$(IterableOnce.scala:608)
        at scala.collection.AbstractIterable.find(Iterable.scala:920)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectWalkBackwards(BaseBlockChain.scala:248)
        at org.bitcoins.chain.blockchain.BaseBlockChainCompObject.connectWalkBackwards$(BaseBlockChain.scala:243)
        at org.bitcoins.chain.blockchain.Blockchain$.connectWalkBackwards(Blockchain.scala:14)
        at org.bitcoins.chain.models.BlockHeaderDAO.$anonfun$getNAncestors$3(BlockHeaderDAO.scala:187)
        at org.bitcoins.chain.models.BlockHeaderDAO$$Lambda$1776/0x000000084099a040.apply(Unknown Source)
        at scala.Option.map(Option.scala:242)
        at org.bitcoins.chain.models.BlockHeaderDAO.$anonfun$getNAncestors$2(BlockHeaderDAO.scala:185)
        at org.bitcoins.chain.models.BlockHeaderDAO$$Lambda$1775/0x0000000840999840.apply(Unknown Source)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$770/0x000000084056fc40.apply$mcV$sp(Unknown Source)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.6/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.6/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.6/Thread.java:834)


The key thing here is that [`BaseBlockChain.connectWalkBackwards`](https://github.com/bitcoin-s/bitcoin-s/blob/86f68b3b622a4531748169cc475a5df52ac4c23e/chain/src/main/scala/org/bitcoins/chain/blockchain/BaseBlockChain.scala#L248) is taking a very long time to run for utxos that are deep in the chain, particularily this line: 

>ancestors.find(_.hashBE == current.previousBlockHashBE)

**Comment by Christewart** [comment]
This is not working on mainnet either a4dc8053a2a855d38acad6af6c88c302369ec881. I have not attempted a rescan to fix this.

>➜  bin git:(master) ✗ ./bitcoin-s-cli getbalance
1.04971941 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getconfirmedbalance
0.10000000 BTC
➜  bin git:(master) ✗ ./bitcoin-s-cli getblockcount
646430
➜  bin git:(master) ✗ ./bitcoin-s-cli getfilterheadercount
646430
➜  bin git:(master) ✗ ./bitcoin-s-cli getfiltercount
646430

**Comment by Christewart** [comment]
After my rescan completed, I do get the full balance now

>./bitcoin-s-cli getconfirmedbalance
1.04971941 BTC
