### ISSUE TITLE
CI builds seems to be stalling regularily 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1856]
https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/719253951#L794

This is on #1854 which only changes compiler settings, maybe this is an infra issue with travis? I thought I would file an issue at least to start documentation if it is something on our end

![Screenshot from 2020-08-19 08-56-01](https://user-images.githubusercontent.com/3514957/90643981-d41d0780-e1f9-11ea-89de-d8539ba52faf.png)

**Comment by Christewart** [comment]
This seems to be happening on #1850 too https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/719038157

**Comment by benthecarman** [comment]
![image](https://user-images.githubusercontent.com/15256660/90681096-76ec7a80-e228-11ea-95b7-34c7074f8aed.png)

https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/719360229

**Comment by benthecarman** [comment]
Another one

![image](https://user-images.githubusercontent.com/15256660/90695359-e3bf3f00-e23f-11ea-8245-2ec76c3e0ce0.png)

**Comment by Christewart** [comment]
So this morning as a test I tried rebasing #1840  onto the latest master to see if this fixes the issue

From what i've seen from restarting the build 4-5 times:

1. I haven't seen any sqlite builds fails with this error
2. I have seen postgres fail on #1840 once.

I believe `numThreads` -- as it's set in #1840 -- should apply to both postgres and sqlite3 which means each should have one thread able to access the database. So i'm unsure of why i've seen it fail on postgres. I'll keep restarting for now

**Comment by Christewart** [comment]
So I believe this test case is the culprit, i saw this happen locally and it seems to also be where we are stalling on CI. I haven't figured out how to reproduce it all the time though.

https://github.com/bitcoin-s/bitcoin-s/blob/8529eb7939e2a7880034fd7def8759eeb076810e/wallet-test/src/test/scala/org/bitcoins/wallet/FundTransactionHandlingTest.scala#L195

**Comment by Christewart** [comment]
So here is where it's occuring, you can see the code associated with the console output here https://github.com/Christewart/bitcoin-s-core/tree/2020-08-20-issue-1856

>[info] - must fund a simple raw transaction that requires one utxo (5 seconds, 711 milliseconds)
[info] - must fund a transaction that requires all utxos in our wallet (3 seconds, 931 milliseconds)
[info] - must not care about the number of destinations (3 seconds, 715 milliseconds)
[info] - must fail to fund a raw transaction if we don't have enough money in our wallet (3 seconds, 626 milliseconds)
[info] - must fail to fund a raw transaction if we have the _exact_ amount of money in the wallet because of the fee (3 seconds, 658 milliseconds)
[info] - must fund from a specific account (3 seconds, 598 milliseconds)
[info] - must fail to fund from an account that does not have the funds (3 seconds, 788 milliseconds)
[info] - must fail to fund from an account with only immature coinbases (3 seconds, 668 milliseconds)
Before fundTxF

So it seems it's happening somewhere inside of `wallet.fundRawTransaction()`

https://github.com/Christewart/bitcoin-s-core/commit/5b1a8df61005bfee50cd6e747ee6509950c6cf30#diff-888b0458b0a36a60f78a7eb23167238dR213

**Comment by Christewart** [comment]
Finally got it to spit out the error message:

https://github.com/Christewart/bitcoin-s-core/commit/2b47d80750952afca1322d4b0fb5a3e25391b84a#diff-fb2568212ca68c906f438db200708763R144

>2020-08-20T18:57:44 ERROR [WALLET] Failed to fetch addrInfosWithUtxoF
java.lang.RuntimeException: Not enough value in given outputs (600000000 sats) to make transaction spending 1000000000 sats
        at org.bitcoins.wallet.api.CoinSelector.addUtxos$1(CoinSelector.scala:76)
        at org.bitcoins.wallet.api.CoinSelector.accumulate(CoinSelector.scala:95)
        at org.bitcoins.wallet.api.CoinSelector.accumulate$(CoinSelector.scala:57)
        at org.bitcoins.wallet.api.CoinSelector$.accumulate(CoinSelector.scala:99)
        at org.bitcoins.wallet.api.CoinSelector.accumulateLargest(CoinSelector.scala:38)
        at org.bitcoins.wallet.api.CoinSelector.accumulateLargest$(CoinSelector.scala:31)
        at org.bitcoins.wallet.api.CoinSelector$.accumulateLargest(CoinSelector.scala:99)
        at org.bitcoins.wallet.api.CoinSelector$.selectByAlgo(CoinSelector.scala:125)
        at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$11(FundTransactionHandling.scala:115)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
13:57:44.518 ERROR WALLET - Failed to fetch addrInfosWithUtxoF
java.lang.RuntimeException: Not enough value in given outputs (600000000 sats) to make transaction spending 1000000000 sats
        at org.bitcoins.wallet.api.CoinSelector.addUtxos$1(CoinSelector.scala:76)
        at org.bitcoins.wallet.api.CoinSelector.accumulate(CoinSelector.scala:95)
        at org.bitcoins.wallet.api.CoinSelector.accumulate$(CoinSelector.scala:57)
        at org.bitcoins.wallet.api.CoinSelector$.accumulate(CoinSelector.scala:99)
        at org.bitcoins.wallet.api.CoinSelector.accumulateLargest(CoinSelector.scala:38)
        at org.bitcoins.wallet.api.CoinSelector.accumulateLargest$(CoinSelector.scala:31)
        at org.bitcoins.wallet.api.CoinSelector$.accumulateLargest(CoinSelector.scala:99)
        at org.bitcoins.wallet.api.CoinSelector$.selectByAlgo(CoinSelector.scala:125)
        at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$11(FundTransactionHandling.scala:115)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Christewart** [comment]
Here is the new point it stalls on #1866 and commit 6208aabbc6249f41a1d15c75f08b1783f9300ce5

![Screenshot from 2020-08-21 06-58-44](https://user-images.githubusercontent.com/3514957/90888430-d909c480-e37b-11ea-9753-2ecbecc4b167.png)

**Comment by benthecarman** [comment]
https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/720009299#L854

![image](https://user-images.githubusercontent.com/15256660/90932467-56592780-e3c4-11ea-9fc1-fc43d79fca1c.png)

**Comment by Christewart** [comment]
^ I just saw this again, the interesting thing to note though is that this in a test row that runs

>TEST_COMMAND="appCommonsTest/test bitcoindRpcTest/test bitcoindRpc/coverageReport bitcoindRpc/coverageAggregate bitcoindRpc/coveralls eclairRpcTest/test eclairRpc/coverageReport eclairRpc/coverageAggregate eclairRpc/coveralls"

So this isn't running any `chainTest`,`walletTest`, or `nodeTest` code.
