### ISSUE TITLE
flyway validation failure when running off of master for the wallet project

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1858]
I wanted to fire my node up and start testing things. When i try and start my node off of master on 68ec48c3873183a06abc891e5a45e038949bd584 I get a flyway validation failure for the wallet project

>Exception in thread "main" org.flywaydb.core.api.FlywayException: Validate failed:
Migration checksum mismatch for migration version 7
-> Applied to database : -2090493367
-> Resolved locally    : 698719628
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:285)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:74)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:167)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
        at org.flywaydb.core.Flyway.execute(Flyway.java:530)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
        at org.bitcoins.db.DbManagement.migrate(DbManagement.scala:109)
        at org.bitcoins.db.DbManagement.migrate$(DbManagement.scala:91)
        at org.bitcoins.wallet.config.WalletAppConfig.migrate(WalletAppConfig.scala:30)
        at org.bitcoins.wallet.config.WalletAppConfig.initialize(WalletAppConfig.scala:105)
        at org.bitcoins.server.BitcoinSAppConfig.initialize(BitcoinSAppConfig.scala:31)
        at org.bitcoins.server.Main$.runMain(Main.scala:128)
        at org.bitcoins.server.Main$.delayedEndpoint$org$bitcoins$server$Main$1(Main.scala:214)
        at org.bitcoins.server.Main$delayedInit$body.apply(Main.scala:31)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at org.bitcoins.server.Main$.main(Main.scala:31)
        at org.bitcoins.server.Main.main(Main.scala)

**Comment by Christewart** [comment]
My flyway history for wallet

>sqlite> select * from flyway_schema_history
   ...> ;
1|1|<< Flyway Baseline >>|BASELINE|<< Flyway Baseline >>||null|2020-01-29 22:13:29.511|0|1
2|2|wallet db spent to txo state|SQL|V2__wallet_db_spent_to_txo_state.sql|-1295024906||2020-01-29 22:13:29.545|4|1
3|3|txo spending info drop confirmations|SQL|V3__txo_spending_info_drop_confirmations.sql|-1253245802||2020-02-22 14:17:23.634|3|1
4|4|wallet db add transaction table|SQL|V4__wallet_db_add_transaction_table.sql|-60690023||2020-05-01 18:26:36.339|3|1
5|5|add address tags|SQL|V5__add_address_tags.sql|1935316429||2020-07-10 13:41:34.596|2|1
6|6|unique spendinginfodb outpoint|SQL|V6__unique_spendinginfodb_outpoint.sql|619337585||2020-07-17 13:36:49.912|2|1
7|7|add address tag pk|SQL|V7__add_address_tag_pk.sql|-2090493367||2020-08-16 13:43:42.440|3|1

**Comment by Christewart** [comment]
This was introduced in #1798 here https://github.com/bitcoin-s/bitcoin-s/pull/1798/files#diff-196347cdf5cabafd4aa741eda1fbb3b0R6

**Comment by Christewart** [comment]
Since an already existing migration was modified, the only way to work around this was by dropping the migration that already existed in `flyway_schema_history`.

>delete from flyway_schema_history where version=7;
