### ISSUE TITLE
V8__add_script_pub_keys.sql migration fails for me 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1861]
When I start my node on testnet, this is the error I get when running wallet migrations. This was introduced in #1798 

Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
Migration V8__add_script_pub_keys.sql failed
--------------------------------------------
SQL State  : null
Error Code : 19
Message    : [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: txo_spending_info.value)
Location   : sqlite/wallet/migration/V8__add_script_pub_keys.sql (/home/suredbits/dev/bitcoin-s/app/server/target/universal/stage/bin/file:/home/suredbits/dev/bitcoin-s/app/server/target/universal/stage/lib/org.bitcoin-s.bitcoin-s-wallet-0.3.0 370-68ec48c3-SNAPSHOT.jar!/sqlite/wallet/migration/V8__add_script_pub_keys.sql)
Line       : 8
Statement  : INSERT INTO "txo_spending_info" ("id","tx_outpoint","script_pub_key_id","hd_privkey_path","redeem_script","script_witness","txid","block_hash","txo_state") SELECT t."id",t."tx_outpoint",s."id",t."hd_privkey_path",t."redeem_script",t."script_witness",t."txid",t."block_hash",t."txo_state" FROM "txo_spending_info_backup" t, "pub_key_scripts" s WHERE s."script_pub_key" = t."script_pub_key"

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:369)
        at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
        at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:199)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
        at org.flywaydb.core.Flyway.execute(Flyway.java:530)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
        at org.bitcoins.db.DbManagement.migrate(DbManagement.scala:109)
        at org.bitcoins.db.DbManagement.migrate$(DbManagement.scala:91)
        at org.bitcoins.wallet.config.WalletAppConfig.migrate(WalletAppConfig.scala:30)
        at org.bitcoins.wallet.config.WalletAppConfig.initialize(WalletAppConfig.scala:105)
        at org.bitcoins.server.BitcoinSAppConfig.initialize(BitcoinSAppConfig.scala:31)
        at org.bitcoins.server.Main$.runMain(Main.scala:128)
        at org.bitcoins.server.Main$.delayedEndpoint$org$bitcoins$server$Main$1(Main.scala:214)
        at org.bitcoins.server.Main$delayedInit$body.apply(Main.scala:31)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:73)
        at scala.App.$anonfun$main$1$adapted(App.scala:73)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
        at scala.App.main(App.scala:73)
        at scala.App.main$(App.scala:71)
        at org.bitcoins.server.Main$.main(Main.scala:31)
        at org.bitcoins.server.Main.main(Main.scala)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException:
Migration V8__add_script_pub_keys.sql failed
--------------------------------------------
SQL State  : null
Error Code : 19
Message    : [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: txo_spending_info.value)
Location   : sqlite/wallet/migration/V8__add_script_pub_keys.sql (/home/suredbits/dev/bitcoin-s/app/server/target/universal/stage/bin/file:/home/suredbits/dev/bitcoin-s/app/server/target/universal/stage/lib/org.bitcoin-s.bitcoin-s-wallet-0.3.0 370-68ec48c3-SNAPSHOT.jar!/sqlite/wallet/migration/V8__add_script_pub_keys.sql)
Line       : 8
Statement  : INSERT INTO "txo_spending_info" ("id","tx_outpoint","script_pub_key_id","hd_privkey_path","redeem_script","script_witness","txid","block_hash","txo_state") SELECT t."id",t."tx_outpoint",s."id",t."hd_privkey_path",t."redeem_script",t."script_witness",t."txid",t."block_hash",t."txo_state" FROM "txo_spending_info_backup" t, "pub_key_scripts" s WHERE s."script_pub_key" = t."script_pub_key"

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:274)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:220)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:127)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:88)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:33)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:77)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:74)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:74)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366)
        ... 39 more
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (NOT NULL constraint failed: txo_spending_info.value)
        at org.sqlite.core.DB.newSQLException(DB.java:1010)
        at org.sqlite.core.DB.newSQLException(DB.java:1022)
        at org.sqlite.core.DB.execute(DB.java:861)
        at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:53)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:244)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:208)
        ... 47 more

**Comment by Christewart** [comment]
Fixed in #1862
