### ISSUE TITLE
[error] Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to baseline schema history table "main"."flyway_schema_history" as it already contains migrations

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1904]
I ran `sbt bundle/run` and got this flyway exception. This was run on c9c18fabc5ebb4ef27e91b7b0238b8e64f696684

>[error] Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to baseline schema history table "main"."flyway_schema_history" as it already contains migrations
[error]         at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:98)
[error]         at org.flywaydb.core.Flyway.doBaseline(Flyway.java:206)
[error]         at org.flywaydb.core.Flyway.access$200(Flyway.java:74)
[error]         at org.flywaydb.core.Flyway$5.execute(Flyway.java:352)
[error]         at org.flywaydb.core.Flyway$5.execute(Flyway.java:344)
[error]         at org.flywaydb.core.Flyway.execute(Flyway.java:530)
[error]         at org.flywaydb.core.Flyway.baseline(Flyway.java:344)
[error]         at org.bitcoins.db.DbManagement.migrate(DbManagement.scala:109)
[error]         at org.bitcoins.db.DbManagement.migrate$(DbManagement.scala:92)
[error]         at org.bitcoins.wallet.config.WalletAppConfig.migrate(WalletAppConfig.scala:30)
[error]         at org.bitcoins.wallet.config.WalletAppConfig.initialize(WalletAppConfig.scala:105)
[error]         at org.bitcoins.server.BitcoinSAppConfig.start(BitcoinSAppConfig.scala:35)
[error]         at org.bitcoins.server.Main$.runMain(Main.scala:126)

Contents of DB: 

>sqlite> select * from flyway_schema_history;
1|1|wallet db baseline|SQL|V1__wallet_db_baseline.sql|-847182410||2020-06-04 17:44:23.673|1|1
2|2|wallet db spent to txo state|SQL|V2__wallet_db_spent_to_txo_state.sql|-1295024906||2020-06-04 17:44:23.685|1|1
3|3|txo spending info drop confirmations|SQL|V3__txo_spending_info_drop_confirmations.sql|-1253245802||2020-06-04 17:44:23.692|0|1
4|4|wallet db add transaction table|SQL|V4__wallet_db_add_transaction_table.sql|-60690023||2020-06-04 17:44:23.700|0|1
5|5|wallet db add dlcs|SQL|V5__wallet_db_add_dlcs.sql|-1956179783||2020-06-05 23:41:21.312|5|1
6|6|wallet db dlc outcome sigs table|SQL|V6__wallet_db_dlc_outcome_sigs_table.sql|-87415582||2020-06-05 23:41:21.324|1|1

**Comment by Christewart** [comment]
The problem is that dlcs share/shared the same database as wallet migrations, causing them to conflict. The solution in _this_ case is to drop the DLC migrations since this is just a `regtest` wallet, as they will be in a separate db in the future with work of #1899
