### ISSUE TITLE
Filter headers failing to sync

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1919]
This morning i'm trying to sync my node and failing to sync my filter headers. This was run on  267cf06fa7a033e83313883de6511b673b5913b5  . If you look at the logs it does appear i sync block headers ok

This is where things stop happening with my node:

>2020-08-27T13:51:24 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-27T13:51:24 DEBUG [P2P] Received message=cfheaders from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) state=Normal 
2020-08-27T13:51:24 INFO [P2P] Got 386 compact filter header hashes
2020-08-27T13:52:48 INFO [P2P] Stopping node
2020-08-27T13:52:48 WARN [P2P] Cannot disconnect client that is not connected to 

As you can see, there is about ~1.5 minutes of nothing happening until I kill my node

Logs: 
https://pastebin.com/RjUi7yDE

**Comment by Christewart** [comment]
With logging from #1922 i finally get a stack trace! 

>2020-08-27T15:14:21 INFO [P2P] Got 617 compact filter header hashes
2020-08-27T15:14:21 ERROR [P2P] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=DoubleSha256Digest(85061c010005768f6f334abab2c0a235509cde4a0df0a3f788409d0964e56c34), stopHash=DoubleSha256Digest(af902dbdaaad738b7434c0b83ce727193f1470dea8ecfea56521000000000000) filterHeaders=DoubleSha256Digest(9adae09b0ae7e792c66c7c7601b78466e465259395ed31933a96c44270017a0d)...DoubleSha256Digest(d33f4838765908733dda21afcafaafa182d64dedb5372845e93ca2fec4b1edbb))
java.lang.IllegalArgumentException: requirement failed: Previous filter header does not exist: CompactFilterDb(hashBE=DoubleSha256BDigestBE(b078454e92cd04dd28f2d87bf9b6176c4cf7b6a2dca7936e24c2c67522698303),filterHashBE=DoubleSha256BDigestBE(0d7a017042c4963a9331ed95932565e46684b701767c6cc692e7e70a9be0da9a),previousFilterHeaderBE=DoubleSha256BDigestBE(346ce564099d4088f7a3f00d4ade9c5035a2c0b2ba4a336f8f760500011c0685),blockHashBE=DoubleSha256BDigestBE(0000000000003891fc5d08c1eb7957549646e924e87823bfbf1f1c265a4d963a),height=1826918)
	at scala.Predef$.require(Predef.scala:340)
	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processFilterHeaders$6(ChainHandler.scala:244)
	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processFilterHeaders$6$adapted(ChainHandler.scala:234)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2020-08-27T15:15:00 INFO [P2P] Stopping node
2020-08-27T15:15:00 WARN [P2P] Cannot disconnect client that is not connected to socket=neutrino.testnet3.suredbits.com/34.210.154.40:18333!
2020-08-27T15:15:00 INFO [P2P] Awaiting disconnect

**Comment by Christewart** [comment]
So the issue here is a reorg occurred on testnet that reorged `0000000000002334d3b293a8ee37156de9718e1d0a46874e8aa03d70b7b44a76` out of the chain. However it looks we did not reorg the filter headers (not sure about filters). Here is the filter header i have in my database for block height `1826917`

>select * from cfheaders where height=1826917;
c2f6c43f6e7a73af2a70ca97cb594c89d5085a95d13d599e06fd71a5eaa139ff|433134703fd8d7b3b49598ee9de829a577749570b2285e34d4db0f68e7457634|95bcaaee738609ab7eb51e91d709b1bb046cdd01aec8a7a8ba03c4f4265b5ff0|0000000000002334d3b293a8ee37156de9718e1d0a46874e8aa03d70b7b44a76|1826917

>bitcoin-cli getblockheader 0000000000002334d3b293a8ee37156de9718e1d0a46874e8aa03d70b7b44a76
{
  "hash": "0000000000002334d3b293a8ee37156de9718e1d0a46874e8aa03d70b7b44a76",
  "confirmations": -1,
  "height": 1826917,
  "version": 536870912,
  "versionHex": "20000000",
  "merkleroot": "472c9dd5e74ee860167cc49bf863ed4e044b7944b7c62d9c9894e9c6ea2ff181",
  "time": 1598528035,
  "mediantime": 1598527883,
  "nonce": 764668682,
  "bits": "1a3fffc0",
  "difficulty": 262144,
  "chainwork": "0000000000000000000000000000000000000000000001c04bdbeb92443d61fd",
  "nTx": 1,
  "previousblockhash": "00000000000004f1b0a6414d32ac75960233ac34af6216e24b639bbd01540c77"
}

So now when I go to start my node, it cannot add filter header because the filterheader I receive from my peer does not connect to the best filterheader I have in my database.

**Comment by Christewart** [comment]
This just happened to me again on bd94ff15f977ffe2ac087fae3d17c2a7167e332c

>2020-09-01T18:38:36 ERROR [P2P] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=2c3accf91207fa0f6c7e50c8939e3b1cd2adbf0ffa9b55c87ae5224a8f40e731, stopHash=000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca filterHeaders=e34fde99dd48f442c65ba97577867e903a5e11dffd6567e0820eac8712215e2e...e34fde99dd48f442c65ba97577867e903a5e11dffd6567e0820eac8712215e2e)
java.lang.IllegalArgumentException: requirement failed: Previous filter header does not exist: CompactFilterDb(hashBE=DoubleSha256BDigestBE(b497b09c96a9b036421610c67d465573aca18e6786eb222e74535622e0ce9ad9),filterHashBE=DoubleSha256BDigestBE(e34fde99dd48f442c65ba97577867e903a5e11dffd6567e0820eac8712215e2e),previousFilterHeaderBE=DoubleSha256BDigestBE(2c3accf91207fa0f6c7e50c8939e3b1cd2adbf0ffa9b55c87ae5224a8f40e731),blockHashBE=DoubleSha256BDigestBE(000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca),height=1830861)
	at scala.Predef$.require(Predef.scala:340)
	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processFilterHeaders$6(ChainHandler.scala:242)
	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processFilterHeaders$6$adapted(ChainHandler.scala:232)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)

**Comment by Christewart** [comment]
More information, here the current state of my testnet3 chaindb `cfheaders` table:

### `cf_headers` table
[block 000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b at height 183059](https://blockstream.info/testnet/block/000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b)
>sqlite> select * from cfheaders where block_hash='000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b';
ea8e76b42efd6cf980a6f19693a19b318ec375b4df25ca830932592ce5e58904|8bad4262b1cf1a9ce8faa715c7d2259c2697e0c33e7e0d5fc44e6b8f643d3fe9|a2264b9d7b9cf87bc7648639123dae352482e264065ecba352b61774ddeeaa9d|000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b|1830859

[block 000000000000007de9d84e2b1523626bceb03f32fd16a535b6044c2563aab729 at height 183060](https://blockstream.info/testnet/block/000000000000007de9d84e2b1523626bceb03f32fd16a535b6044c2563aab729)
>sqlite> select * from cfheaders where block_hash='000000000000007de9d84e2b1523626bceb03f32fd16a535b6044c2563aab729';

[block 000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca at height 183061](https://blockstream.info/testnet/block/000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca)
>sqlite> select * from cfheaders where block_hash='000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca';

### `block_headers` table

[block at 1830859]
>sqlite> select * from block_headers where hash='000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b';
1830859|000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b|541065216|00000000fd8af7e8a556ce19a1b1e2417517fef332ed3ac4846d4c3fea2126ae|93a05c94bef1272023ee9e71b131b7d9d7de657d591a86a72f961d88b99dfc51|1598983976|436469756|3767478585|00004020ae2621ea3f4c6d84c43aed32f3fe177541e2b1a119ce56a5e8f78afd0000000051fc9db9881d962fa7861a597d65ded7d9b731b1719eee232027f1be945ca093288f4e5ffcff031a39298fe0|000000000000000000000000000000000000000000000001c12f74cf4527f045af

[blocks at 1830860 2 blocks!!]
>sqlite> select * from block_headers where height=1830860;
1830860|00000000ce479c436ba724be7e1f74d1613af4e00f792c711fe20d99f8515802|536870912|000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b|783d51482b8aa7f52a9f5e7bef3d522a0a45f367f53d3e672a219ffe58f850f7|1598985177|486604799|201777975|000000203b4f2da24b3d50f74bf14cc87a1ff7bce638718695f5a2236103000000000000f750f858fe9f212a673e3df567f3450a2a523def7b5e9f2af5a78a2b48513d78d9934e5fffff001d37e3060c|000000000000000000000000000000000000000000000001c12f74cf4627f145b0
1830860|000000000000007de9d84e2b1523626bceb03f32fd16a535b6044c2563aab729|536870912|000000000000036123a2f595867138e6bcf71f7ac84cf14bf7503d4ba22d4f3b|c7f580e96bbefb40df93651afa3bb0aff61d8b44535379da96341f3b44664442|1598985162|436469756|2657564444|000000203b4f2da24b3d50f74bf14cc87a1ff7bce638718695f5a2236103000000000000424466443b1f3496da795353448b1df6afb03bfa1a6593df40fbbe6be980f5c7ca934e5ffcff031a1c37679e|000000000000000000000000000000000000000000000001c12fb4cf85283045ef

[block at 1830861]
>sqlite> select * from block_headers where hash='000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca';
1830861|000000000000014f597d54dbdbe7a06982254bc5e57e6ac0d88cc73f41818eca|536870912|000000000000007de9d84e2b1523626bceb03f32fd16a535b6044c2563aab729|7e53a8a39c00085a1a84be0215e2005896584ec425aef6e74b88c86ff76fccfd|1598985508|436469756|85065288|0000002029b7aa63254c04b635a516fd323fb0ce6b6223152b4ed8e97d00000000000000fdcc6ff76fc8884be7f6ae25c44e58965800e21502be841a5a08009ca3a8537e24954e5ffcff031a48fe1105|000000000000000000000000000000000000000000000001c12ff4cfc52870462f

**Comment by Christewart** [comment]
So basically the filter header i have at height 1830860 is reorged out of the chain , this testnet block [does not exist](https://blockstream.info/testnet/search?q=00000000ce479c436ba724be7e1f74d1613af4e00f792c711fe20d99f8515802)

>sqlite> select * from cfheaders where block_hash = '00000000ce479c436ba724be7e1f74d1613af4e00f792c711fe20d99f8515802';
97789e4ea4249d1fa918ab579b477ca8da7e987b717d9c25f6aaf83092aeb074|59793b86eb2e326b24f19ab8baaec5cdb6eb2f8b34c122dcaabd1347bf780132|ea8e76b42efd6cf980a6f19693a19b318ec375b4df25ca830932592ce5e58904|00000000ce479c436ba724be7e1f74d1613af4e00f792c711fe20d99f8515802|1830860

**Comment by Christewart** [comment]
So i think the solution to this would be performing some validation in [`ChainHandler.nextHeaderBatchRange`](https://github.com/bitcoin-s/bitcoin-s/blob/a4dc8053a2a855d38acad6af6c88c302369ec881/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L138) before returning `(Int,DoubleSha256Digest)`. We basically should check that what we are is in the current best chain we know about?
