### ISSUE TITLE
CET sigs provided are not valid

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1927]
I was going through the flow of creating a DLC this morning. I've added all the messages to pastebin

Here is the original offer from Alice:
https://pastebin.com/v3p3jnNV

Here is the accept from Bob:
https://pastebin.com/gimGsFwA

Here are CET sigs from Alice:

https://pastebin.com/k5FGR43M

Finally when i try to accept the sigs for Bob i get this error:

>java.lang.IllegalArgumentException: CET sigs provided are not valid! got Map(Sha256DigestBEImpl(cd7e619b1f54dd5f2cfcaa84bf75a6757cdfdc46159a7c40a4bba172f9ead751) -> ECAdaptorSignature(ByteVector(162 bytes, 0x0091f221c3758db8b7b78a9ac6338f52f4ebc38254f6d65ce8b0a1025631020a68f30a10bc4a678864a7ec863b9f5f735e0905a3c355493feeeab62e1b824159bd01d626966e97f763e6834c0d469a5748ac864acbf26c29d1cb8019d4b51b0ebf13f69e82486ec10f4ef30c9df83965d913bc93adec15f3f3d4c7220f2cf01bd86c221beacbd5ba7b023dc1050f84fbdb1ca910701e0fabe4d6c56480b1e7ee6e89)), Sha256DigestBEImpl(c8b2314e8cb6513b3693d6c2f092dc4085f27239772232ff18903f0ee74080f9) -> ECAdaptorSignature(ByteVector(162 bytes, 0x01d2f98349b479852a9d4cf2cd0021c270e5fd67c02a6d00e3e9a90044d335562517928116fbd0ea9d3682f109594b109a08283df3657093270f46254c8d7156430186412f4508cecd17ceba520416ecb41e0c94934af47981514c259c57ae2d8fc05a5cf49fdabdbb945289908a9dc158b66284926fba8dd477439a74c5f825b7caac83593fdc38d0d4855d7715dea6106d6e814eea84d8bf0a5d01044b6801b910)))
	at org.bitcoins.wallet.DLCWallet.$anonfun$addDLCSigs$5(DLCWallet.scala:518)
	at org.bitcoins.wallet.DLCWallet.$anonfun$addDLCSigs$5$adapted(DLCWallet.scala:515)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)

**Comment by nkohen** [comment]
I ran on this commit: `2c8461fca73958f10e41a027637e72f6b84c020c` and had no issues executing a DLC between two clients:

Offer:
```
{
  "contractInfo": [
    {
      "sha256": "cd7e619b1f54dd5f2cfcaa84bf75a6757cdfdc46159a7c40a4bba172f9ead751",
      "sats": 100000
    },
    {
      "sha256": "c8b2314e8cb6513b3693d6c2f092dc4085f27239772232ff18903f0ee74080f9",
      "sats": 0
    }
  ],
  "oracleInfo": "e2ef5cb7df942c6204b7c93bfb9e20b826c61e1c3a2b719a9f13e0092ca0a31715e6d02ca0dc976f13d21213a9210b6164692b9d9da784ca9a35fdea809625fb",
  "pubKeys": {
    "fundingKey": "02d63fec4b8a6705a34b32e5476a5a07c20774fe2abcf88eeea320c9714bc3010e",
    "payoutAddress": "bcrt1qqjl2xk8s58pmm2lxzj8a96jyswq3pmury29uqp"
  },
  "totalCollateral": 40000,
  "fundingInputs": [
    {
      "outpoint": "2b3d2360aff3b35e93c1468ddfd158917b6cceb1b180e97cbb97364d8355525700000000",
      "output": "009435770000000016001464293a0edadfe394f3965dcecf0d8f84271e5c10"
    }
  ],
  "changeAddress": "bcrt1qajxkfm28ggqk6yk74sgsv4mlj3687z05k89npv",
  "feeRate": 91,
  "timeouts": {
    "contractMaturity": 100,
    "contractTimeout": 200
  }
}
```

Accept:
```
{
  "totalCollateral": 60000,
  "pubKeys": {
    "fundingKey": "02cd7e2537f91ec413f076e7c3b5806ac78cec88c5453c26e0890fb2608ce9bbbb",
    "payoutAddress": "bcrt1qlty6geusmw0h9fw7rzpseljrqjhcr3mfygv7pl"
  },
  "fundingInputs": [
    {
      "outpoint": "f387c8d23d7c04d965a1efcbb82764531fa8c58cda53a7beed0b590fb1315ed901000000",
      "output": "009435770000000016001438280b940e70bcf04ea0211d08b2182f50d7ba13"
    }
  ],
  "changeAddress": "bcrt1qcg4x62rvzz9dgk96vrsq2a59nfu2ar0qwshjpt",
  "cetSigs": {
    "outcomeSigs": [
      {
        "cd7e619b1f54dd5f2cfcaa84bf75a6757cdfdc46159a7c40a4bba172f9ead751": "0174ce4e798f00b5fbc20e4e9652d2ab04350e591a3fac919dc1021a389c449bbae255da870e03bdd8fe7d543e99cb00514d291fa137a76cdf18db9f6cda3d206f01e502886a082b7a18e147fe0a50f6fb591509a722f3e02c52bb43e9123386e4b07c22826a91b5923e7a57ae274c000ef97397ac8e009c93f37fdfa4bf7d44d4019be7eb9daa470c7c6ec46e999b55333d4df76e2233026f4eccfe3bf1d379665c"
      },
      {
        "c8b2314e8cb6513b3693d6c2f092dc4085f27239772232ff18903f0ee74080f9": "00fe938c93ceb6c33e36ae03616eb2c9028b6a73f38261642c979d08736ce316e76cb3a5d9998c9068d418b9bd0af7b494d82db7c40468e2aa9bb264f1d1d3f8f801a18667ac455109e7f342b7fa582c363ffd0bb6b1f4ddc1142b346493b5b3dcae732a2f5372aa65817c0171c534aba4b93e6bff39d786ee42eb5e73ed67d01ef727a73ceb1709624035a29c06d5bd78d856d1db88ca8fe0457173d591ed080be1"
      }
    ],
    "refundSig": "220202cd7e2537f91ec413f076e7c3b5806ac78cec88c5453c26e0890fb2608ce9bbbb483045022100d7454f22fc1228e47f5a72de544c616e97ea4d7e2246b2d95b6fd87248e5fc10022071359451d2def4968c40bfd35b7d3a449736684001fe7059ae981041990b518001"
  },
  "eventId": "1209a30efef51a974c64e3d2b68131efc1d2d90762a432a04ba59cc74c86d5c9"
}
```

Sign:
```
{
  "cetSigs": {
    "outcomeSigs": [
      {
        "cd7e619b1f54dd5f2cfcaa84bf75a6757cdfdc46159a7c40a4bba172f9ead751": "00ea63565d5df862040f2902ffde19193453e91bf9174813658cbce56e7f4c19941283415ad24daf4a611a78f52db0f987d222db804daeb04beeb95f8bc4753dee0119ddddf517d27735c8c55d539d64e11811073e0fae8b81919cdcbe3260284e72f1634677694ec90898162c69927212a9b5e5f4ae3738d622165b306c56c95726b956511a60680720d60aeb074e1fdd4c89c0ee8310f09e31d5e4f440558cd2b1"
      },
      {
        "c8b2314e8cb6513b3693d6c2f092dc4085f27239772232ff18903f0ee74080f9": "00b001e1463f58e95361a325536094666495f593c45fe22f9dd3ee9233cbc2e0a4b697180a4ba0d59204f94d80f2084cc78adee53233510811e0bde7dfe56f497800d8ceabef2f4777945d7fb0b623bf1ac61946622739f954437a84d3260a667f9a0769a7736baa85e71870ba8ae3f126e65b1338b2f7ae69f89ac000dddfe107989e5a02877dc14dba037a89c13a9235d19aeda75f73067742e0341a3bd366aeec"
      }
    ],
    "refundSig": "220202d63fec4b8a6705a34b32e5476a5a07c20774fe2abcf88eeea320c9714bc3010e473044022047214314c8d9bc68303e3d765bdc8a3124924cea03ae6199e811fff7524b8b4702201f2eb0525de3b4a7f1910107d2b8c83199967229f28c99a62cc83379012085f801"
  },
  "fundingSigs": {
    "2b3d2360aff3b35e93c1468ddfd158917b6cceb1b180e97cbb97364d8355525700000000": [
      "22020333dea605a7d2c223de68c1189bd5e171cb94bd35712122eff08a9cdbed5dca8d47304402206a68d03c2c1b9015a1be0921d2d9947c917740b27949d8e85275fa957655dc0a02200fc11e6cb2925f5f8fef15aa8503e322ea0ed8bdd73f611d0b2a9f3f983da90a01"
    ]
  },
  "eventId": "1209a30efef51a974c64e3d2b68131efc1d2d90762a432a04ba59cc74c86d5c9"
}
```
Successfully added sigs to DLC 1209a30efef51a974c64e3d2b68131efc1d2d90762a432a04ba59cc74c86d5c9
```

```

**Comment by Christewart** [comment]
I tried re-running this and it worked
