### ISSUE TITLE
Syncing fitler headers fails primary key fail

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1933]
I'm running on 453e02b58b01cd703f39f167c3e0b40a29e55f03

>2020-08-29T14:35:40 INFO [P2P] Requesting compact filter headers from=98000 to=DoubleSha256BDigestBE(000000004956cc2edd1a8caa05eacfa3c69f4c490bfc9ace820257834115ab35)
2020-08-29T14:35:40 INFO [P2P] Got 2000 compact filter header hashes
2020-08-29T14:35:40 ERROR [P2P] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=0000000000000000000000000000000000000000000000000000000000000000, stopHash=00000000a6299059b2bff3479bc569019792e75f3c0f39b10a0bc85eac1b1615 filterHeaders=c03705b2d6fb76a59664f1d63fe8fdbb2dc076d18175fdc51d11c43afaf78a4c...7f4f429ac93cc021dd1e713be69e538ea0c2903b6507e22afddee61499d1c88e)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.DB.executeBatch(DB.java:812)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.LoggingStatement.$anonfun$executeBatch$1(LoggingStatement.scala:114)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:114)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-29T14:35:40 ERROR [P2P] Cannot send a message to our peer when we are not connected! payload=GetCompactFilterHeadersMessage(Basic,UInt32Impl(98000),DoubleSha256Digest(35ab154183570282ce9afc0b494c9fc6a3cfea05aa8c1add2ecc564900000000)) peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)
2020-08-29T14:36:37 INFO [P2P] Stopping node
2020-08-29T14:36:37 WARN [P2P] Cannot disconnect client that is not connected to socket=neutrino.testnet3.suredbits.com/34.210.154.40:18333!
2020-08-29T14:36:37 INFO [P2P] Awaiting disconnect

**Comment by Christewart** [comment]
It seems to be something to do with the genesis filter header on testnet 

>2020-08-29T15:07:50 INFO [P2P] Got 1 compact filter header hashes
2020-08-29T15:07:50 INFO [P2P] header=FilterHeader(hashBE=DoubleSha256BDigestBE(21584579b7eb08997773e5aeff3a7f932700042d0ed2a6129012b7d7ae81b750),filterHashBE=c03705b2d6fb76a59664f1d63fe8fdbb2dc076d18175fdc51d11c43afaf78a4c,prevHeaderHashBE=0000000000000000000000000000000000000000000000000000000000000000)

You can see that the `prevHeaderHash=00..00` which means that it doesn't have a previous hash

**Comment by Christewart** [comment]
I think this is some sort of async bug, i've tried running this multiple times and it fails at different points. 

>select COUNT(*) from cfheaders; 
12000

and 

>select COUNT(*) from cfheaders;
29000

**Comment by Christewart** [comment]
It seems the bug was introduced between 2a1c3998385d001587f6cdffe7ee3a927b41cdbc and  9a1dfdfdbd5ce10a7583c3f6427070cecd16e016

I synced just fine off of 2a1c3998385d001587f6cdffe7ee3a927b41cdbc

**Comment by Christewart** [comment]
This is what git bisect told me this morning, but i don't think this is right

```
e3452275619b81ec6384c15b6c9a34b47e04cb02 is the first bad commit
commit e3452275619b81ec6384c15b6c9a34b47e04cb02
Author: Chris Stewart <stewart.chris1234@gmail.com>
Date:   Wed Aug 26 12:31:08 2020 -0500

    docs: Remove e2e dlc info from documentation, add some notes about using gui bundled with node (#1905)

 docs/applications/gui.md | 22 +++++++++++++++++++---
 docs/getting-setup.md    | 22 ----------------------
 docs/wallet/dlc.md       |  8 +++++++-
 3 files changed, 26 insertions(+), 26 deletions(-)
```

EDIT: 

ok re-ran bisect and here is where i end up which i think is right: 

```
79f757311e0fbc351dfee06cad5d254f233a02e3 is the first bad commit
commit 79f757311e0fbc351dfee06cad5d254f233a02e3
Author: Ben Carman <benthecarman@live.com>
Date:   Wed Aug 26 12:56:19 2020 -0500

    Send get filters message if we haven't cached any yet (#1900)

 .../org/bitcoins/node/networking/peer/DataMessageHandler.scala    | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)
```
