### ISSUE TITLE
Attempting to create duplicate filter headers: A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#1940]
This happened on: `5909a5`
Node had not been ran since thurs/fri and ran to sync, and this failure happened

logs: 
```
2020-08-31T16:31:18 DEBUG [chain-verification] Attempting to add new tip=0000000035f0a74769f5bce202ef866c8851a42eab0ac9d3cab2f6fa2f1121b3 with prevhash=0000000000000082d787f789e451535ee1035a5e7877ff90b84772490c647a53 to chain of 2016 headers with tip 0000000000000082d787f789e451535ee1035a5e7877ff90b84772490c647a53
2020-08-31T16:31:18 DEBUG [chain-verification] Successfully verified=0000000035f0a74769f5bce202ef866c8851a42eab0ac9d3cab2f6fa2f1121b3, connecting to chain
2020-08-31T16:31:18 DEBUG [chain-verification] Attempting to add new tip=0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf with prevhash=0000000035f0a74769f5bce202ef866c8851a42eab0ac9d3cab2f6fa2f1121b3 to chain
2020-08-31T16:31:18 DEBUG [chain-verification] Attempting to add new tip=0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf with prevhash=0000000035f0a74769f5bce202ef866c8851a42eab0ac9d3cab2f6fa2f1121b3 to chain of 2016 headers with tip 0000000035f0a74769f5bce202ef866c8851a42eab0ac9d3cab2f6fa2f1121b3
2020-08-31T16:31:18 DEBUG [chain-verification] Successfully verified=0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf, connecting to chain
2020-08-31T16:31:18 DEBUG [chain-verification] Attempting to add new tip=000000000000029592b3ed610b42cd132075ea90251cdc8cb7e1c05c88b11076 with prevhash=0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf to chain
2020-08-31T16:31:18 DEBUG [chain-verification] Attempting to add new tip=000000000000029592b3ed610b42cd132075ea90251cdc8cb7e1c05c88b11076 with prevhash=0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf to chain of 2016 headers with tip 0000000000000166c93ce644e307267a2ea0653927e5f499b7de6714bf93cbdf
2020-08-31T16:31:18 DEBUG [chain-verification] Successfully verified=000000000000029592b3ed610b42cd132075ea90251cdc8cb7e1c05c88b11076, connecting to chain
2020-08-31T16:31:19 INFO [chain-verification] Processed headers from height=1829591 to 1830636. Best hash=000000000000029592b3ed610b42cd132075ea90251cdc8cb7e1c05c88b11076
2020-08-31T16:31:19 DEBUG [chain-verification] Querying for block count
2020-08-31T16:31:19 DEBUG [P2P] Received headers=1045 in one message, which is less than max. This means we are synced, not requesting more.
2020-08-31T16:31:19 DEBUG [chain-verification] getBlockCount result: count=1830636
2020-08-31T16:31:20 DEBUG [chain-verification] Querying for block count
2020-08-31T16:31:20 DEBUG [chain-verification] getBlockCount result: count=1830636
2020-08-31T16:31:20 INFO [P2P] Requesting compact filter headers from=0 to=DoubleSha256BDigestBE(00000000a6299059b2bff3479bc569019792e75f3c0f39b10a0bc85eac1b1615)
2020-08-31T16:31:20 DEBUG [P2P] Sending getcfheaders=GetCompactFilterHeadersMessage(Basic,UInt32Impl(0),DoubleSha256Digest(15161bac5ec80b0ab1390f3c5fe792970169c59b47f3bfb2599029a600000000)) to peer Peer(/127.0.0.1:18333)
2020-08-31T16:31:20 DEBUG [P2P] Sending msg=getcfheaders to peer=/127.0.0.1:18333
2020-08-31T16:31:20 DEBUG [WALLET] Updating states of 0 pending utxos...
2020-08-31T16:31:20 INFO [WALLET] No txos to be confirmed
2020-08-31T16:31:20 DEBUG [P2P] Received 64092 TCP bytes
2020-08-31T16:31:20 DEBUG [P2P] Parsed 1 message(s) from bytes: NetworkMessage(NetworkHeader(TestNet3,cfheaders,UInt32Impl(64068),ByteVector(4 bytes, 0x10fd32fa)), CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=0000000000000000000000000000000000000000000000000000000000000000, stopHash=00000000a6299059b2bff3479bc569019792e75f3c0f39b10a0bc85eac1b1615 filterHeaders=c03705b2d6fb76a59664f1d63fe8fdbb2dc076d18175fdc51d11c43afaf78a4c...7f4f429ac93cc021dd1e713be69e538ea0c2903b6507e22afddee61499d1c88e))
2020-08-31T16:31:20 DEBUG [P2P] Unaligned bytes after this: 0
2020-08-31T16:31:20 DEBUG [P2P] Received message=cfheaders from peer=Peer(/127.0.0.1:18333) state=Normal 
2020-08-31T16:31:20 INFO [P2P] Got 2000 compact filter header hashes
2020-08-31T16:31:20 ERROR [P2P] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=0000000000000000000000000000000000000000000000000000000000000000, stopHash=00000000a6299059b2bff3479bc569019792e75f3c0f39b10a0bc85eac1b1615 filterHeaders=c03705b2d6fb76a59664f1d63fe8fdbb2dc076d18175fdc51d11c43afaf78a4c...7f4f429ac93cc021dd1e713be69e538ea0c2903b6507e22afddee61499d1c88e)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.DB.executeBatch(DB.java:812)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:72)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.LoggingStatement.$anonfun$executeBatch$1(LoggingStatement.scala:114)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:87)
	at slick.jdbc.LoggingStatement.executeBatch(LoggingStatement.scala:114)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1794)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scal
```

**Comment by benthecarman** [comment]
Seems it was caused by #1926

**Comment by Christewart** [comment]
Hmm, are you sure that #1926 just _doesn't_ fix #1919?

**Comment by benthecarman** [comment]
No, I think there is just a bug in the logic, my `getBestFilterHeader` is returning `None` even though I have 1.8M of them.

**Comment by Christewart** [comment]
5909a5 doesn't seem to exist?

**Comment by benthecarman** [comment]
> 5909a5 doesn't seem to exist?

https://github.com/bitcoin-s/bitcoin-s/commit/5909a57f09332918842b75bc4830c9774cbf3f9b
