### ISSUE TITLE
Starting mainnet neutrino node after a long time fails with timeout

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#1953]
If you look carefully at the logs below, we sit here on this line for 12.5 seconds before starting the node times out. This was run on  bac0dc120196cd3cf92088f8606be93e85dc7e08

>2020-09-01T20:25:47 DEBUG [chain-verification] Querying for best block hash

>2020-09-01T20:25:46 INFO [HTTP] Initialized chain api
2020-09-01T20:25:46 INFO [WALLET] Using pre-existing wallet
2020-09-01T20:25:46 INFO [P2P] Starting node
2020-09-01T20:25:47 INFO [P2P] Attempting to connect to peer=neutrino.suredbits.com/35.163.36.246:8333
2020-09-01T20:25:47 DEBUG [P2P] Tcp connection to: neutrino.suredbits.com/35.163.36.246:8333
2020-09-01T20:25:47 DEBUG [P2P] Local: /192.168.1.187:60328
2020-09-01T20:25:47 INFO [P2P] Connection established with peer=Peer(neutrino.suredbits.com/35.163.36.246:8333)
2020-09-01T20:25:47 DEBUG [chain-verification] Querying for best block hash
2020-09-01T20:26:00 ERROR [P2P] Failed to connect with peer=Peer(neutrino.suredbits.com/35.163.36.246:8333) with err=org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 250 milliseconds waiting periods
2020-09-01T20:26:00 ERROR [P2P] Cannot start Neutrino node
org.bitcoins.rpc.util.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with 250 milliseconds waiting periods
	at org.bitcoins.node.Node.$anonfun$start$4(Node.scala:123)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-09-01T20:26:48 INFO [P2P] We've been disconnected by Peer(neutrino.suredbits.com/35.163.36.246:8333) command=PeerClosed

last header in the database: 

>sqlite> select * from block_headers order by height desc limit 1;
630643|0000000000000000000b26eef024cd6d7002eb41823629b68b5dac8f033291f8|1073676288|000000000000000000015c60156d2935b7826b9cd485a98a9b470e834b6f045d|49c998fb71c407f7588e1074f69246b3b0e3e10d6582256ae2d32dbac00edf02|1589665379|387021369|1593365392|0000ff3f5d046f4b830e479b8aa985d49c6b82b735296d15605c0100000000000000000002df0ec0ba2dd3e26a2582650de1e3b0b34692f674108e58f707c471fb98c949635ec05e397a111790d3f85e|0F86CDA17306F272136B8E58

**Comment by Christewart** [comment]
I'm unsure of what is happenign here, visualvm isn't reporting any threads being used (including chaindb.1!) 

![Screenshot from 2020-09-01 15-50-30](https://user-images.githubusercontent.com/3514957/91904667-ede33380-ec6a-11ea-9c28-4c4160dcdef4.png)

**Comment by Christewart** [comment]
Ok, i finally got it to spit out an error message, we might have to ban using `.max` `.min` `.maxBy` as they do not work in the case of empty Vectors!

> 2020-09-01T20:53:38 DEBUG [chain-verification] Querying for best block hash
2020-09-01T20:53:38 ERROR [chain-verification] Failed to get best block header
java.lang.UnsupportedOperationException: empty.max
	at scala.collection.IterableOnceOps.max(IterableOnce.scala:952)
	at scala.collection.IterableOnceOps.max$(IterableOnce.scala:950)
	at scala.collection.AbstractIterable.max(Iterable.scala:920)
	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$getBestBlockHeader$1(ChainHandler.scala:70)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)

**Comment by Christewart** [comment]
Fixed in #1951
