### ISSUE TITLE
Cannot resolve db.conf file on startup

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2124]
When starting the app server or the oracle server it will always fail on the current `master`(6ce7d3d7019). I get the following:

```
[error] Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: db.conf @ jar:file:/tmp/sbt_5beb9f72/target/4792f2c5/312eee0d/bitcoin-s-db-commons_2.13-0.4.0+30-6ce7d3d7+20201005-1143-SNAPSHOT.jar!/db.conf: 11: Could not resolve substitution to a value: ${bitcoin-s.datadir}
[error] 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
[error] 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error] 	at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
[error] 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error] 	at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:88)
[error] 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
[error] 	at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
[error] 	at com.typesafe.config.impl.ConfigConcatenation.resolveSubstitutions(ConfigConcatenation.java:205)
[error] 	at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)

```

**Comment by benthecarman** [comment]
Reverting #2113 fixes this

**Comment by Christewart** [comment]
db.conf was deleted in #2121
