### ISSUE TITLE
Error initializing key manager, err=org.bitcoins.core.wallet.keymanagement.KeyManagerUnlockError$JsonParsingError: key not found: mnemonicSeed         at scala.sys.package$.error(package.scala:27)

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2245]
This occurs on 42e9cbb1f21

I run `./bitcoin-s-server` and then i get this error on startup

>2020-11-06T15:12:58UTC ERROR [BIP39LockedKeyManager$] JSON parsing error when unlocking wallet: key not found: mnemonicSeed
2020-11-06T15:12:58UTC ERROR [BitcoinSServerMain] Error on server startup!
java.lang.RuntimeException: Error initializing key manager, err=org.bitcoins.core.wallet.keymanagement.KeyManagerUnlockError$JsonParsingError: key not found: mnemonicSeed
        at scala.sys.package$.error(package.scala:27)
        at org.bitcoins.wallet.config.WalletAppConfig$.$anonfun$createHDWallet$1(WalletAppConfig.scala:241)
        at org.bitcoins.wallet.config.WalletAppConfig$.$anonfun$createHDWallet$1$adapted(WalletAppConfig.scala:226)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)

**Comment by Christewart** [comment]
The problem was that #2217 breaks configuration for wallets v0.4 and backwards. 

You NEED to specify the default passphrase in your `bitcoin-s.conf` You can do it this like 

>bitcoin-s.wallet.aesPassword = "changeMe"
