### ISSUE TITLE
Handle block mined on the network correctly during IBD

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2263]
This issue is for the case when an initial block download is ongoing but a block is mined on the network during the sync process. 

We will receive the newly mined block and (for some reason?) request the full block from our peer and then process it in our wallet. 

This results in an error being thrown when trying to update our [state descriptor](https://github.com/bitcoin-s/bitcoin-s/blob/49a58133ec2478bc72d67c31727c6af852ba658c/wallet/src/main/scala/org/bitcoins/wallet/internal/TransactionProcessing.scala#L62-L61) in the wallet. The block will have no associated height in the database and result in an error that looks like this

>>2020-11-15T15:18:29UTC ERROR [Wallet$WalletImpl] Error processing of block=DoubleSha256BDigestBE(0000000000000008d3788a734090d276b75e9d67e7afab2f2aa360c2df2b16f0).
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-11-15T15:18:29UTC DEBUG [Wallet$WalletImpl] Updating wallet signal completion for DoubleSha256Digest(f0162bdfc260a32a2fabafe7679d5eb776d29040738a78d30800000000000000)
2020-11-15T15:18:29UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error: 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

This was observed on  744d8d18ab5468fdb7c0140de66665dfe0191ded  but I suspect this is a bug we have had for a long time now.

**Comment by Christewart** [comment]
Done in #5201
