### ISSUE TITLE
Multinonce DLC Optimizations and changes needed

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2273]
- [x] `signdlc` and `adddlcsigs` cli commands from file
- [x] Add dlc from file commands to gui
- [x] extend cli timeout
- [ ] delete signatures on completion
- [x] add outcome to db, add agg oracle sig for remote claimed
- [x] increase akka parse limit
- [x] execute DLC search optimizations (currently we look through all possible outcomes linearly)
- [x] add better logging to DLCWallet

Bugs:

- [x] GUI crypto bug (gets NPE from getting the curve?) (only on my branch)
- [x] DLCStatus json parsing

Add more if you think of any cc @nkohen

**Comment by benthecarman** [comment]
Stack trace from gui bug

```
[error] java.lang.NullPointerException
[error] 	at org.bitcoins.crypto.CryptoParams.curve(CryptoParams.scala:20)
[error] 	at org.bitcoins.gui.WalletGUIModel.$anonfun$new$1(WalletGUIModel.scala:17)
[error] 	at scala.util.Try$.apply(Try.scala:210)
[error] 	at org.bitcoins.gui.WalletGUIModel.<init>(WalletGUIModel.scala:17)
```

**Comment by nkohen** [comment]
Look into why file sizes are around 2x expected

**Comment by benthecarman** [comment]
GUI NPE is caused by having the breeze-viz dep. 

Filed an issue: https://github.com/scalanlp/breeze/issues/796

Edit: fixed by adding `.exclude("bouncycastle", "bcprov-jdk14")` to the breeze-viz dep
