### ISSUE TITLE
SignTest NPE

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#2303]
Saw this on [CI](https://travis-ci.org/github/bitcoin-s/bitcoin-s/jobs/746800951#L921)
```
[info] - must sign arbitrary data correctly with low R values *** FAILED *** (308 milliseconds)

[info]   java.lang.NullPointerException:

[info]   at scala.concurrent.Future.$anonfun$zipWith$1(Future.scala:417)

[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)

[info]   at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:164)

[info]   at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)

[info]   at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)

[info]   at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:249)

[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)

[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)

[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)

[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)

[info]   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)

[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)

[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)

[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)

[info]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)

[info]   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)

[info]   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)

[info]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)

[info]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Christewart** [comment]
This should be fixed in #2292 

I think once you rebase it should be fixed :tm:
