### ISSUE TITLE
intellij freezes whenever compiling any submodule in the bitcoin-s project

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2333]
I am running the latest release of intellij 

https://blog.jetbrains.com/idea/2020/12/intellij-idea-2020-3/

with the Scala plugin at version 

![Screenshot from 2020-12-07 08-32-51](https://user-images.githubusercontent.com/3514957/101363338-e71a1d00-3866-11eb-9789-7a813af5b6b1.png)

Whenever I attempt to run a test, or build a module, I end up with an error usually at the compiler settings phase.

_**It's important to note this occuring when I disable sbt for building the project, rather I am attempting to use the built in intellij build tool, which is what intellij defaults to when a new user is setting up the environment**_

![Screenshot from 2020-12-07 08-53-33](https://user-images.githubusercontent.com/3514957/101365768-cc957300-3869-11eb-88f7-e7ac0dd713de.png)

![Screenshot from 2020-12-07 08-46-03](https://user-images.githubusercontent.com/3514957/101364846-a7543500-3868-11eb-9b8b-54d2c692abd7.png)

(look at the bottom right dialog that says `Read Compilation settings`. 

This causes my entire intellij instance to freeze, which I cannot see to recover without manually killing the process. 

Here is the stack trace

>2020-12-07 08:45:44,426 [ 841317]  ERROR - aemon.impl.PassExecutorService - Access to existential argument methods before initialization
java.lang.IllegalStateException: Access to existential argument methods before initialization
        at org.jetbrains.plugins.scala.lang.psi.types.ScExistentialArgument$Deferred.assertInitialized(ScExistentialArgument.scala:67)
        at org.jetbrains.plugins.scala.lang.psi.types.ScExistentialArgument$Deferred.lower(ScExistentialArgument.scala:84)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateExistentialArg(SubtypeUpdater.scala:47)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:153)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:86)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.$anonfun$updateParameterizedType$2(SubtypeUpdater.scala:80)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.$anonfun$updateParameterizedType$2$adapted(SubtypeUpdater.scala:77)
        at org.jetbrains.plugins.scala.extensions.package$IterableOfNullablesExt$.smartMapWithIndex$extension(package.scala:267)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateParameterizedType(SubtypeUpdater.scala:77)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:155)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.recursiveUpdate(SubtypeUpdater.scala:167)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$.recursiveUpdate$extension(Extensions.scala:18)
        at org.jetbrains.plugins.scala.lang.psi.types.ScExistentialType$.notBoundArgs(ScExistentialType.scala:209)
        at org.jetbrains.plugins.scala.lang.psi.types.ScExistentialType$.apply(ScExistentialType.scala:153)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateExistentialType(SubtypeUpdater.scala:60)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:154)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:90)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.$anonfun$updateCompoundType$8(SubtypeUpdater.scala:37)
        at org.jetbrains.plugins.scala.extensions.package$IterableOfNullablesExt$.smartMap$extension(package.scala:286)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateCompoundType(SubtypeUpdater.scala:37)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:152)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:90)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateTypePolymorphicType(SubtypeUpdater.scala:131)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:159)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:90)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.apply(ScSubstitutor.scala:62)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil$ExistentialAbstractionBuilder.$anonfun$existentialArgumentSubst$3(MostSpecificUtil.scala:100)
        at org.jetbrains.plugins.scala.lang.psi.types.ScExistentialArgument$Deferred.initialize(ScExistentialArgument.scala:75)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.$anonfun$isAsSpecificAs$4(MostSpecificUtil.scala:131)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.$anonfun$isAsSpecificAs$4$adapted(MostSpecificUtil.scala:130)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$.org$jetbrains$plugins$scala$lang$psi$types$recursiveUpdate$Extensions$$$anonfun$foreachSubtypeUpdate$1(Extensions.scala:44)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$$anonfun$foreachSubtypeUpdate$extension$1.apply(Extensions.scala:43)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$$anonfun$foreachSubtypeUpdate$extension$1.apply(Extensions.scala:43)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SimpleUpdate.apply(Update.scala:19)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SimpleUpdate.apply$(Update.scala:19)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$$anonfun$foreachSubtypeUpdate$extension$1.apply(Extensions.scala:43)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$$anonfun$foreachSubtypeUpdate$extension$1.apply(Extensions.scala:43)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:78)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateParameterizedType(SubtypeUpdater.scala:76)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:155)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor.recursiveUpdateImpl(ScSubstitutor.scala:86)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.$anonfun$updateParameterizedType$2(SubtypeUpdater.scala:80)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.$anonfun$updateParameterizedType$2$adapted(SubtypeUpdater.scala:77)
        at org.jetbrains.plugins.scala.extensions.package$IterableOfNullablesExt$.smartMapWithIndex$extension(package.scala:267)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateParameterizedType(SubtypeUpdater.scala:77)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.updateSubtypes(SubtypeUpdater.scala:155)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.SubtypeUpdater.recursiveUpdate(SubtypeUpdater.scala:167)
        at org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.Extensions$.visitRecursively$extension(Extensions.scala:29)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.calcParams$1(MostSpecificUtil.scala:130)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.isAsSpecificAs(MostSpecificUtil.scala:140)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.relativeWeight(MostSpecificUtil.scala:259)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.isMoreSpecific(MostSpecificUtil.scala:271)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.$anonfun$notMoreSpecificThan$1(MostSpecificUtil.scala:74)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MostSpecificUtil.$anonfun$notMoreSpecificThan$1$adapted(MostSpecificUtil.scala:74)
        at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:172)
        at scala.collection.immutable.Set$Set1.filterImpl(Set.scala:156)
        at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:217)
        at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:217)
        at scala.collection.immutable.Set$Set1.filter(Set.scala:156)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.$anonfun$collectCompatibleCandidates$2(ImplicitCollector.scala:264)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.$anonfun$collectCompatibleCandidates$2$adapted(ImplicitCollector.scala:261)
        at scala.Option.foreach(Option.scala:437)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.collectCompatibleCandidates(ImplicitCollector.scala:261)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.compatible(ImplicitCollector.scala:186)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.$anonfun$collect$5(ImplicitCollector.scala:152)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollectorCache.getOrCompute(ImplicitCollectorCache.scala:46)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.calc$1(ImplicitCollector.scala:148)
        at org.jetbrains.plugins.scala.lang.psi.implicits.ImplicitCollector.collect(ImplicitCollector.scala:164)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.findImplicits(InferUtil.scala:177)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.updateTypeWithImplicitParameters(InferUtil.scala:120)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.updateTypeWithImplicitParameters(InferUtil.scala:85)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.updatedWithImplicitParameters$extension(ScExpression.scala:271)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.implicitSearchFails$1(InferUtil.scala:288)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.cantFindImplicitsFor$1(InferUtil.scala:299)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.doLocalTypeInference$1(InferUtil.scala:338)
        at org.jetbrains.plugins.scala.lang.psi.api.InferUtil$.updateAccordingToExpectedType(InferUtil.scala:343)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl$ScMethodCallEx$.updateAccordingToExpectedType$extension(ExpectedTypesImpl.scala:726)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.$anonfun$expectedExprTypes$10(ExpectedTypesImpl.scala:299)
        at scala.util.Either.map(Either.scala:382)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.$anonfun$expectedExprTypes$9(ExpectedTypesImpl.scala:299)
        at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:924)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.expectedTypesForArg$1(ExpectedTypesImpl.scala:298)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.expectedExprTypes(ExpectedTypesImpl.scala:441)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree2$1(ScExpression.scala:183)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.expectedTypesEx$extension(ScExpression.scala:181)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ExpectedTypesImpl.expectedExprType(ExpectedTypesImpl.scala:63)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.expectedTypeEx$extension(ScExpression.scala:177)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.expectedType$extension(ScExpression.scala:174)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$getContextInfo$5(ReferenceExpressionResolver.scala:79)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolveWithName$1(ReferenceExpressionResolver.scala:136)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.addExpectedTypeProblems$default$1$1(MethodResolveProcessor.scala:225)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.problemsFor(MethodResolveProcessor.scala:476)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkResultsApplicability(MethodResolveProcessor.scala:759)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.candidates(MethodResolveProcessor.scala:587)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.collectCandidates(MethodResolveProcessor.scala:166)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.candidatesS(MethodResolveProcessor.scala:137)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:145)
        at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:76)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.doResolve(ReferenceExpressionResolver.scala:623)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:196)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree2$1(ScReferenceExpressionImpl.scala:553)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.shapeResolveImpl(ScReferenceExpressionImpl.scala:551)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$shapeResolve$1(ScReferenceExpressionImpl.scala:69)
        at scala.Option.fold(Option.scala:263)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.shapeResolve(ScReferenceExpressionImpl.scala:70)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:147)
        at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:76)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.smartResolve$1(ReferenceExpressionResolver.scala:156)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:198)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree1$1(ScReferenceExpressionImpl.scala:549)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveImpl(ScReferenceExpressionImpl.scala:547)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$multiResolveScala$1(ScReferenceExpressionImpl.scala:63)
        at scala.Option.fold(Option.scala:263)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveScala(ScReferenceExpressionImpl.scala:64)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.bind(ScReferenceImpl.scala:44)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.innerType(ScReferenceExpressionImpl.scala:171)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree4$1(ScExpression.scala:191)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:191)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree5$1(ScExpression.scala:233)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getTypeWithoutImplicits$extension(ScExpression.scala:222)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.liftedTree1$1(ScExpression.scala:139)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.getTypeAfterImplicitConversion(ScExpression.scala:120)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression.getTypeAfterImplicitConversion$(ScExpression.scala:120)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.getTypeAfterImplicitConversion(ScReferenceExpressionImpl.scala:44)
        at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.doNoNamed$1(Compatibility.scala:339)
        at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkConformanceExt(Compatibility.scala:447)
        at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.checkParameterListConformance$1(Compatibility.scala:539)
        at org.jetbrains.plugins.scala.lang.psi.types.Compatibility$.compatible(Compatibility.scala:569)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkSimpleApplication$1(MethodResolveProcessor.scala:415)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.problemsFor(MethodResolveProcessor.scala:471)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.checkResultsApplicability(MethodResolveProcessor.scala:759)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor$.candidates(MethodResolveProcessor.scala:587)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.collectCandidates(MethodResolveProcessor.scala:163)
        at org.jetbrains.plugins.scala.lang.resolve.processor.MethodResolveProcessor.candidatesS(MethodResolveProcessor.scala:137)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver$$anon$1.candidatesS(ReferenceExpressionResolver.scala:151)
        at org.jetbrains.plugins.scala.lang.resolve.processor.BaseProcessor.candidates(BaseProcessor.scala:76)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.smartResolve$1(ReferenceExpressionResolver.scala:156)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolveWithName(ReferenceExpressionResolver.scala:198)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.$anonfun$resolve$1(ReferenceExpressionResolver.scala:107)
        at org.jetbrains.plugins.scala.lang.resolve.ReferenceExpressionResolver.resolve(ReferenceExpressionResolver.scala:124)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.liftedTree1$1(ScReferenceExpressionImpl.scala:549)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveImpl(ScReferenceExpressionImpl.scala:547)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.$anonfun$multiResolveScala$1(ScReferenceExpressionImpl.scala:63)
        at scala.Option.fold(Option.scala:263)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.multiResolveScala(ScReferenceExpressionImpl.scala:64)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceImpl.bind(ScReferenceImpl.scala:44)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScReferenceExpressionImpl.innerType(ScReferenceExpressionImpl.scala:171)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.liftedTree4$1(ScExpression.scala:191)
        at org.jetbrains.plugins.scala.lang.psi.api.expr.ScExpression$Ext$.getNonValueType$extension(ScExpression.scala:191)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.tryToGetInnerTypeExt(MethodInvocationImpl.scala:91)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.liftedTree1$1(MethodInvocationImpl.scala:71)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.innerTypeExt(MethodInvocationImpl.scala:69)
        at org.jetbrains.plugins.scala.lang.psi.impl.expr.MethodInvocationImpl.applyOrUpdateElement(MethodInvocationImpl.scala:63)
        at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider$ResolveMethodCall$.unapply(ScalaInlayParameterHintsProvider.scala:123)
        at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider.getParameterHints(ScalaInlayParameterHintsProvider.scala:29)
        at com.intellij.codeInsight.hints.InlayParameterHintsProvider.getParameterHints(InlayParameterHintsProvider.java:29)
        at org.jetbrains.plugins.scala.codeInsight.hints.ScalaInlayParameterHintsProvider.getParameterHints(ScalaInlayParameterHintsProvider.scala:22)
        at com.intellij.codeInsight.hints.ParameterHintsPass.process(ParameterHintsPass.java:74)
        at com.intellij.codeInsight.hints.ParameterHintsPass.lambda$doCollectInformation$0(ParameterHintsPass.java:66)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.intellij.codeInsight.hints.ParameterHintsPass.doCollectInformation(ParameterHintsPass.java:66)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
        at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
        at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-12-07 08:45:44,428 [ 841319]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2020.3  Build #IC-203.5981.155
2020-12-07 08:45:44,428 [ 841319]  ERROR - aemon.impl.PassExecutorService - JDK: 11.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2020-12-07 08:45:44,428 [ 841319]  ERROR - aemon.impl.PassExecutorService - OS: Linux
2020-12-07 08:45:44,428 [ 841319]  ERROR - aemon.impl.PassExecutorService - Plugin to blame: Scala version: 2020.3.16
2020-12-07 08:45:44,428 [ 841319]  ERROR - aemon.impl.PassExecutorService - Last Action: Run

[6]  + 15975 suspended (tty output)  sh idea.sh

#### Resources 

https://plugins.jetbrains.com/plugin/1347-scala

**Comment by Christewart** [comment]
I've tried downgrading my version of intellij back to 2020.2 and everythign works as expected. It appears that this is a regression in between either 

1. intellij versions 2020.2.4 and 2020.3
2. Scala plugin versions 2020.2.49 and 2020.3.16

These are the versions of the scala plugin/intellij for 2020.2 release
![Screenshot from 2020-12-07 09-11-24](https://user-images.githubusercontent.com/3514957/101367969-36168100-386c-11eb-92eb-f142d9a9404f.png)
![Screenshot from 2020-12-07 09-10-47](https://user-images.githubusercontent.com/3514957/101367971-36af1780-386c-11eb-8c68-b39c54ccbcb7.png)

**Comment by Christewart** [comment]
Filed and issue on the scala plugin issue tracker: https://youtrack.jetbrains.com/issue/SCL-18542

**Comment by Christewart** [comment]
It appears that intellij pushed out an update to the scala plugin. I updated my scala plugin to 2020.3.17 and things work! 

![Screenshot from 2020-12-09 10-02-29](https://user-images.githubusercontent.com/3514957/101654156-cc31df00-3a05-11eb-82a3-2f463a2d4dc2.png)

![Screenshot from 2020-12-09 10-03-14](https://user-images.githubusercontent.com/3514957/101654180-d227c000-3a05-11eb-864e-eb2013bfb7b3.png)

**Comment by Christewart** [comment]
@benthecarman confirmed that this works for him too. I'm closing this issue
