### ISSUE TITLE
generatetoaddress 3 [address] causes errors inside bitcoin-s

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2365]
I don't think this is being caused by #2306, but I just want to document when/where i saw this behavior.

I am testing #2306 on commit 126ac1c5ab4c468ef700f87fd03d6c709ee909a7 . I'm attempting to fund a new wallet to test out the multi wallet functionality. I've specified a new wallet in the configuration called `bitcoin-s.wallet.walletName = "test-wallet"` 

To fund this wallet generated an address, and then now am attempting to fund it with bitcoind 

```
./bitcoin-cli -regtest generatetoaddress 3 bcrt1qpmpuy5fgwej7j4kve0zvpzfhy5zzhmjtgey7mm

[
  "6087d5843a85f0d2930ece808a21a35649e18e120a03b0548718be0833ee91a3",
  "4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180",
  "0d88d14aa14ab8a9ad33d7864f29d1e80a9ffe2dfada29710dbff19212ea0282"
]

```

This caused the following errors inside the bitcoin-s project: 

>[info] 2020-12-15T18:48:33UTC INFO [NeutrinoNode] Our peer=Peer(/127.0.0.1:18444) has been initialized
[info] 2020-12-15T18:48:33UTC INFO [NeutrinoNode] Our node has been full started. It took=491ms
[info] 2020-12-15T18:48:33UTC INFO [NeutrinoNode] Started node, best block hash 1f0040edd11d4229b3f7a353ec7b654460926e5ad16da6e69598adb738e1caf1 at height 1005, with 1005 filter headers and 1005 filters
[info] 2020-12-15T18:48:34UTC INFO [DbValidate] Successfully validated 9 migrations (execution time 00:00.003s)
[info] 2020-12-15T18:48:34UTC INFO [DbMigrate] Current version of schema "main": 9
[info] 2020-12-15T18:48:34UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2020-12-15T18:48:34UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
[info] 2020-12-15T18:48:34UTC INFO [BitcoinSServerMain] Starting neutrino node sync
[info] 2020-12-15T18:48:34UTC INFO [NeutrinoNode] Starting sync node, height=1005 hash=1f0040edd11d4229b3f7a353ec7b654460926e5ad16da6e69598adb738e1caf1
[info] 2020-12-15T18:48:34UTC INFO [BitcoinSServerMain] Done starting Main!
[info] 2020-12-15T18:50:38UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/1.8.0_272, Host: localhost:9999, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,82 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,28 bytes total),HttpProtocol(HTTP/1.1)))
[info] 2020-12-15T18:50:42UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/1.8.0_272, Host: localhost:9999, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,84 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,34 bytes total),HttpProtocol(HTTP/1.1)))
[info] 2020-12-15T18:50:58UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/1.8.0_272, Host: localhost:9999, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,84 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,70 bytes total),HttpProtocol(HTTP/1.1)))
[info] 2020-12-15T18:51:17UTC INFO [DataMessageHandler] Received inv=InventoryMessage(1 inv(s), Inventory(MsgBlock,DoubleSha256Digest(80418792ef13e49c649812026ce809a09a82e21b85c870e4bc52b22c4bf95741)))
[info] 2020-12-15T18:51:17UTC INFO [DataMessageHandler] Received block message with hash 4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180
[info] 2020-12-15T18:51:17UTC WARN [Blockchain$] No common ancestor found in the chain with tip=1f0040edd11d4229b3f7a353ec7b654460926e5ad16da6e69598adb738e1caf1 to connect to hash=DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180) prevHash=DoubleSha256BDigestBE(6087d5843a85f0d2930ece808a21a35649e18e120a03b0548718be0833ee91a3)
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] No txos to be confirmed
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Processing block=DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180)
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Adding UTXO to wallet: 82f42ff831f044fbe16ed4e3f6ca805791649134a36579d30fb5e6da7d215cf5:0
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Successfully inserted UTXO 82f42ff831f044fbe16ed4e3f6ca805791649134a36579d30fb5e6da7d215cf5:0 into DB
[info] 2020-12-15T18:51:17UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error:
[info] java.util.NoSuchElementException: None.get
[info]  at scala.None$.get(Option.scala:627)
[info]  at scala.None$.get(Option.scala:626)
[info]  at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2020-12-15T18:51:17UTC ERROR [Wallet$WalletImpl] Error processing of block=DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180).
[info] java.util.NoSuchElementException: None.get
[info]  at scala.None$.get(Option.scala:627)
[info]  at scala.None$.get(Option.scala:626)
[info]  at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2020-12-15T18:51:17UTC INFO [DataMessageHandler] Received inv=InventoryMessage(1 inv(s), Inventory(MsgBlock,DoubleSha256Digest(8202ea1292f1bf0d7129dafa2dfe9f0ae8d1294f86d733ada9b84aa14ad1880d)))
[info] 2020-12-15T18:51:17UTC INFO [DataMessageHandler] Received block message with hash 0d88d14aa14ab8a9ad33d7864f29d1e80a9ffe2dfada29710dbff19212ea0282
[info] 2020-12-15T18:51:17UTC WARN [Blockchain$] No common ancestor found in the chain with tip=1f0040edd11d4229b3f7a353ec7b654460926e5ad16da6e69598adb738e1caf1 to connect to hash=DoubleSha256BDigestBE(0d88d14aa14ab8a9ad33d7864f29d1e80a9ffe2dfada29710dbff19212ea0282) prevHash=DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180)
[info] 2020-12-15T18:51:17UTC WARN [Wallet$WalletImpl] Given txos exist in block (4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180) that we do not have or that has been reorged! Vector(SegwitV0SpendingInfo(TransactionOutPoint(f55c217ddae6b50fd37965a3349164915780caf6e3d46ee1fb44f031f82ff482:0),TransactionOutput(78125000 sats,wpkh(0ec3c251287665e956cccbc4c0893725042bee4b)),m/84'/1'/0'/0/0,P2WPKHWitnessV0(List(03b07980ce1654bebe1f7c70ea6d5408c9b5454517e90049f79ce2ab7bd42df661, )),DoubleSha256BDigestBE(f55c217ddae6b50fd37965a3349164915780caf6e3d46ee1fb44f031f82ff482),PendingConfirmationsReceived,Some(1),Some(DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180))))
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] 1 txos are now confirmed!
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Processing block=DoubleSha256BDigestBE(0d88d14aa14ab8a9ad33d7864f29d1e80a9ffe2dfada29710dbff19212ea0282)
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Adding UTXO to wallet: c479f6d0c536f0fdf5029ccd7ec33ca14e10533628744319b963b725bc4796b9:0
[info] 2020-12-15T18:51:17UTC INFO [Wallet$WalletImpl] Successfully inserted UTXO c479f6d0c536f0fdf5029ccd7ec33ca14e10533628744319b963b725bc4796b9:0 into DB
[info] 2020-12-15T18:51:17UTC ERROR [Wallet$WalletImpl] Error processing of block=DoubleSha256BDigestBE(0d88d14aa14ab8a9ad33d7864f29d1e80a9ffe2dfada29710dbff19212ea0282).
[info] java.util.NoSuchElementException: None.get
[info]  at scala.None$.get(Option.scala:627)
[info]  at scala.None$.get(Option.scala:626)
[info]  at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2020-12-15T18:51:17UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error:
[info] java.util.NoSuchElementException: None.get
[info]  at scala.None$.get(Option.scala:627)
[info]  at scala.None$.get(Option.scala:626)
[info]  at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processBlock$7(TransactionProcessing.scala:62)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

I restarted my node after seeing these errors, and I ended up with the correct block height and a balance in my `test-wallet`. 

>➜  bin git:(126ac1c5ab4) ✗ ./bitcoin-s-cli getblockcount
1009
➜  bin git:(126ac1c5ab4) ✗ ./bitcoin-s-cli getbalance
1.56250000 BTC

**Comment by Christewart** [comment]
So here is the key part of the logs 


>[info] 2020-12-15T18:51:17UTC INFO [DataMessageHandler] Received block message with hash 4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180
[info] 2020-12-15T18:51:17UTC WARN [Blockchain$] No common ancestor found in the chain with tip=1f0040edd11d4229b3f7a353ec7b654460926e5ad16da6e69598adb738e1caf1 to connect to hash=DoubleSha256BDigestBE(4157f94b2cb252bce470c8851be2829aa009e86c021298649ce413ef92874180) prevHash=DoubleSha256BDigestBE(6087d5843a85f0d2930ece808a21a35649e18e120a03b0548718be0833ee91a3)

This means we are (probably) experiencing a reorg, and have missed a block. Therefore we don't have the block header in our chainstate. This is related to #2260 . If we cannot connect a block header into a `BlockHeader` to our chain state, we shouldn't be executing callbacks.

**Comment by Christewart** [comment]
So i think the problem here is that `processWithHeaders()` does not propagate errors in connecting the new headers to the blockchains. It will only propagate an error if we fail to insert them into the database. 

https://github.com/bitcoin-s/bitcoin-s/blob/8836ed5e4fb1d56e41e19a9d6c912c378f7c7c23/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L113

This means that this line does not fail here, which means we continue to execute block callbacks. 

https://github.com/bitcoin-s/bitcoin-s/blob/7172b4a049b8a18568e5e69d3f947ea6b32d4803/node/src/main/scala/org/bitcoins/node/networking/peer/DataMessageHandler.scala#L262

This results in the error message we have above I believe.
