### ISSUE TITLE
Restoring seeds doesn't work

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2527]
Here are the steps I attempted to restore a seed with a bitcoin-s that _had_ been used before 

1. Copy `seeds/` directory on other machine to new machine under `$HOME/.bitcoin-s/seeds/` (this overwrote the existing `seeds/`!)
2. Start up `appServer`

I get this error message. This makes some sense since we do have accounts registered already! However I am unsure (and we should document in #2526 ) of how to best re-write these accounts. 

>2021-01-16T21:42:20UTC ERROR [BitcoinSServerMain] Failed to startup server!
java.lang.RuntimeException: Divergent xpubs for account=AccountDb(tpubDCmi9UYwCHx8Sthgo9tJLWeW8tBWBJiADKamYMv8EKcBLpMYot7Tbs7xffjJSNNMuvj2bcKWmcnRsmKaE9rBGmTvyYb4jAJjgxijH7KVKhJ,m/44'/1'/0'). Existing database xpub=tpubDCmi9UYwCHx8Sthgo9tJLWeW8tBWBJiADKamYMv8EKcBLpMYot7Tbs7xffjJSNNMuvj2bcKWmcnRsmKaE9rBGmTvyYb4jAJjgxijH7KVKhJ, key manager's xpub=tpubDCjb411SPoHwZSN1SouGhG9gZPKzVU8uKmFYitB43Tf5KTaDD3k319PTedrhYtdvafwpRyjc11kBTK9mBmy7TRDQFksk1BJCmU4U7ss7VAZ. It is possible we have a different key manager being used than expected, key manager=org.bitcoins.keymanager.bip39.BIP39KeyManager@29049587
	at org.bitcoins.wallet.Wallet.$anonfun$checkRootAccount$1(Wallet.scala:130)
2021-01-16T21:42:20UTC ERROR [BitcoinSServerMain] Error on server startup!
java.lang.RuntimeException: Divergent xpubs for account=AccountDb(tpubDCmi9UYwCHx8Sthgo9tJLWeW8tBWBJiADKamYMv8EKcBLpMYot7Tbs7xffjJSNNMuvj2bcKWmcnRsmKaE9rBGmTvyYb4jAJjgxijH7KVKhJ,m/44'/1'/0'). Existing database xpub=tpubDCmi9UYwCHx8Sthgo9tJLWeW8tBWBJiADKamYMv8EKcBLpMYot7Tbs7xffjJSNNMuvj2bcKWmcnRsmKaE9rBGmTvyYb4jAJjgxijH7KVKhJ, key manager's xpub=tpubDCjb411SPoHwZSN1SouGhG9gZPKzVU8uKmFYitB43Tf5KTaDD3k319PTedrhYtdvafwpRyjc11kBTK9mBmy7TRDQFksk1BJCmU4U7ss7VAZ. It is possible we have a different key manager being used than expected, key manager=org.bitcoins.keymanager.bip39.BIP39KeyManager@29049587
	at org.bitcoins.wallet.Wallet.$anonfun$checkRootAccount$1(Wallet.scala:130)

Another possible solution is renaming the `seeds/encrypted-bitcoin-s-seed.json` file to have a unique wallet name like `old-wallet-encrypted-bitcoin-s-seed.json` and then using the `bitcoin-s.wallet.walletName = "old-wallet"` setting to create a unique wallet. This seems like another possible solution.

**Comment by Christewart** [comment]
> Another possible solution is renaming the seeds/encrypted-bitcoin-s-seed.json file to have a unique wallet name like old-wallet-encrypted-bitcoin-s-seed.json and then using the bitcoin-s.wallet.walletName = "old-wallet" setting to create a unique wallet. This seems like another possible solution.

I tried this, and then started a rescan with `bitcoin-s-cli rescan` 

It seems that the rescan was actually working, here is the logs that it finished with 

> ... //more logs above here that i am omitting for brevity
2021-01-16T21:54:25UTC INFO [Wallet$WalletImpl] Processing block=DoubleSha256BDigestBE(000000000000000770c73af6798fd4a3c88131add214b7151d0cad10e12b7e91)
2021-01-16T21:54:26UTC INFO [Wallet$WalletImpl] Finished processing of block=DoubleSha256BDigestBE(000000000000000770c73af6798fd4a3c88131add214b7151d0cad10e12b7e91).
2021-01-16T21:54:26UTC INFO [Wallet$WalletImpl] Matched 117 blocks on rescan

117 blocks does seem like the right answer for blocks matched, however if I follow this up with a 

>./bitcoin-s-cli getbalance
0E-8 BTC

this is not right! My balance on my other machine that i imported this seed from is `0.99886536` :/. 

I'm not sure if this is a problem with `getbalance` or what, because from looking at the logs it seems like the rescan actually worked.

**Comment by Christewart** [comment]
I'm not why it was believed this was fixed in #2539 -- but that is just a doc change

**Comment by Christewart** [comment]
So i tested this on  6670b121d0abeb92e6ae655c14a8c5fa920a2646 and it didn't solve my problem. I've attached a picture that somewhat shows the whole picture

If you look closely at the bottom right, you will see this log 

>[Wallet$WalletImpl] Matched 118 blocks on rescan
2021-01-21T16:56:04UTC INFO [Wallet$WalletImpl] Finished rescanning the wallet

note the timestamp, 

and then if you look at the upper right hand console, you will see i queried my balance at `11:01` and the balance isn't showing up.

![Screenshot from 2021-01-21 11-03-48](https://user-images.githubusercontent.com/3514957/105384883-5ca03980-5bd8-11eb-9998-40e281a9c2b6.png)
