### ISSUE TITLE
Can't run eclair rpc tests locally

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2636]
Logs:

```
[info] EclairRpcClientTest:
[info] EclairRpcClient
[info] - must have our EclairRpcClient work with .hashCode() and equals *** FAILED *** (2 seconds, 712 milliseconds)
[info]   java.lang.IllegalArgumentException: port out of range:-1
[info]   at java.base/java.net.InetSocketAddress.checkPort(InetSocketAddress.java:153)
[info]   at java.base/java.net.InetSocketAddress.<init>(InetSocketAddress.java:234)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.toInetSocketAddress(EclairInstance.scala:70)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.$anonfun$fromConfig$1(EclairInstance.scala:164)
[info]   at scala.Option.map(Option.scala:242)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.fromConfig(EclairInstance.scala:164)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.fromConfig(EclairInstance.scala:102)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.fromConfigFile(EclairInstance.scala:93)
[info]   at org.bitcoins.eclair.rpc.config.EclairInstance$.fromDatadir(EclairInstance.scala:81)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.eclairInstance(EclairRpcTestUtil.scala:182)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.eclairInstance$(EclairRpcTestUtil.scala:179)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil$.eclairInstance(EclairRpcTestUtil.scala:843)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.eclairInstance(EclairRpcTestUtil.scala:191)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.eclairInstance$(EclairRpcTestUtil.scala:187)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil$.eclairInstance(EclairRpcTestUtil.scala:843)
[info]   at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.$anonfun$createNodePair$1(EclairRpcTestUtil.scala:536)
[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[info]   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[info]   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[info]   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by benthecarman** [comment]
Looks like the zmq address being generated is `tcp://127.0.0.1/<unresolved>:55216`

**Comment by benthecarman** [comment]
After hacking around that issue I now just get

```
fatal error: java.lang.String.isBlank()Z
fatal error: java.lang.String.isBlank()Z
fatal error: java.lang.String.isBlank()Z
fatal error: java.lang.String.isBlank()Z
```

**Comment by Christewart** [comment]
> After hacking around that issue I now just get
> 
> ```
> fatal error: java.lang.String.isBlank()Z
> fatal error: java.lang.String.isBlank()Z
> fatal error: java.lang.String.isBlank()Z
> fatal error: java.lang.String.isBlank()Z
> ```

Likely running on a version of Java < 11 

`isBlank()` wasn't added until java 11
https://stackoverflow.com/a/51299127/967713

**Comment by Christewart** [comment]
fixed by running on java 11
