### ISSUE TITLE
OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2701]
This seems to only occur on our Postgres test suite on CI. I'm _guessing_ that it has something to do with tearing down of fixtures.

> [info] org.bitcoins.node.NeutrinoNodeWithWalletTest *** ABORTED *** (19 seconds, 975 milliseconds)
[info]   akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
[info]   at akka.http.impl.engine.client.OutgoingConnectionBlueprint$.$anonfun$apply$6(OutgoingConnectionBlueprint.scala:123)
[info]   at akka.http.impl.engine.client.OutgoingConnectionBlueprint$.$anonfun$apply$6$adapted(OutgoingConnectionBlueprint.scala:123)
[info]   at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
[info]   at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:523)
[info]   at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502)
[info]   at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:773)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788)
[info]   at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info]   at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info]   at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691)
[info]   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
[info]   at akka.actor.ActorCell.invoke(ActorCell.scala:547)
[info]   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info]   at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info]   at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[info] ScalaTest
[info] Run completed in 1 minute, 1 second.
[info] Total number of tests run: 28
[info] Suites: completed 12, aborted 1
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error: Total 29, Failed 0, Errors 1, Passed 28
[error] Error during tests:
[error] 	org.bitcoins.node.NeutrinoNodeWithWalletTest
[error] (nodeTest / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 67 s (01:07), completed Feb 20, 2021 12:55:05 PM

Error: Process completed with exit code 1.

![Screenshot from 2021-02-20 07-00-01](https://user-images.githubusercontent.com/3514957/108596238-46a5a600-7349-11eb-94de-0f6752093c34.png)

**Comment by Christewart** [comment]
Related: https://github.com/akka/akka-http/issues/768

**Comment by Christewart** [comment]
Looks like we have another issue for this on our tracker already: #531
