### ISSUE TITLE
JSON serialization Incorrect on DLC branch

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-s/bitcoin-s#2746]
One of our JSON serializations is broken that is used by the gui for representing DLC Status.

Tests should be added so this doesn't happen again.

**Comment by benthecarman** [comment]
```
2021-03-02T20:49:19UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Offer
2021-03-02T20:49:19UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: 3000a722ee6ee176e86486e16068ce62c120a1f29f0b3d7f61a09e598ce2fb1d:1
2021-03-02T20:49:19UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(945906 sats,wpkh(52b36e6cce926af4c45368b03abd53a1314153cf))
2021-03-02T20:49:19UTC INFO [DLCWallet$DLCWalletImpl] Created offer with tempContractId afd6e6de4edc1ca24d292adec9a63f637c230feff6dbd36b773e6bf7558c5a4c
2021-03-02T20:49:20UTC INFO [Server] Unhandled error in server:
java.lang.ClassCastException: upickle.core.Types$Writer$MapWriter cannot be cast to upickle.core.Types$TaggedWriter
	at upickle.core.Types.upickle$core$Types$$scanChildren(Types.scala:241)
	at upickle.core.Types$TaggedWriter$Node.findWriter(Types.scala:278)
	at upickle.core.Types$TaggedWriter.write0(Types.scala:265)
	at upickle.core.Types$TaggedWriter.write0$(Types.scala:264)
	at upickle.core.Types$TaggedWriter$Node.write0(Types.scala:277)
	at upickle.core.Types$Writer.write(Types.scala:114)
	at upickle.core.Types$Writer.write$(Types.scala:112)
	at upickle.core.Types$TaggedWriter$Node.write(Types.scala:277)
	at upickle.core.Types$Writer.transform(Types.scala:110)
	at upickle.core.Types$Writer.transform$(Types.scala:110)
	at upickle.core.Types$TaggedWriter$Node.transform(Types.scala:277)
	at upickle.Api$transform.transform(Api.scala:82)
	at upickle.Api$transform.to(Api.scala:84)
	at upickle.Api.writeJs(Api.scala:54)
	at upickle.Api.writeJs$(Api.scala:54)
	at upickle.default$.writeJs(Api.scala:102)
	at org.bitcoins.server.WalletRoutes$$anonfun$handleCommand$1.$anonfun$applyOrElse$34(WalletRoutes.scala:248)
	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
	at scala.collection.immutable.Vector1.map(Vector.scala:375)
	at org.bitcoins.server.WalletRoutes$$anonfun$handleCommand$1.$anonfun$applyOrElse$33(WalletRoutes.scala:248)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
