### ISSUE TITLE
git clone might not work out of the box

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2889]
Need to investigate this further, but if I use our recommended clone step

https://bitcoin-s.org/docs/next/getting-setup#step-2-bitcoin-s-repository

>git clone --depth 100 --recursive git@github.com:bitcoin-s/bitcoin-s.git

I get this error

> sbt                                                                                                                  ✔  11325  08:08:33
[info] welcome to sbt 1.5.0 (GraalVM Community Java 11.0.9)
[info] loading global plugins from /home/chris/.sbt/1.0/plugins
[info] loading settings for project bitcoin-s-build from plugins.sbt ...
[info] loading project definition from /tmp/bitcoin-s/project
[info] compiling 4 Scala sources to /tmp/bitcoin-s/project/target/scala-2.12/sbt-1.0/classes ...
[info] loading settings for project bitcoin-s from build.sbt,inThisBuild.sbt ...
[info] loading settings for project bitcoindRpc from bitcoind-rpc.sbt ...
[info] loading settings for project eclairRpc from eclair-rpc.sbt ...
/tmp/bitcoin-s/lnd-rpc/lnd-rpc.sbt:13: warning: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
scalacOptions in Compile += {
              ^
[info] loading settings for project lndRpc from lnd-rpc.sbt ...
[info] loading settings for project secp256k1jni from secp256k1jni.sbt ...
[info] loading settings for project appCommons from commons.sbt ...
[info] loading settings for project oracleServer from oracle-server.sbt ...
[info] loading settings for project oracleServerTest from oracle-server-test.sbt ...
[info] loading settings for project appServer from server.sbt ...
[info] loading settings for project appServerTest from server-test.sbt ...
[info] loading settings for project cli from cli.sbt ...
[info] loading settings for project cliTest from cli-test.sbt ...
[info] loading settings for project bundle from bundle.sbt ...
[info] loading settings for project gui from gui.sbt ...
[info] loading settings for project chain from chain.sbt ...
[info] loading settings for project bitcoindRpcTest from bitcoind-rpc-test.sbt ...
[info] loading settings for project eclairRpcTest from eclair-rpc-test.sbt ...
[info] loading settings for project docs from docs.sbt ...
[info] loading settings for project keyManager from key-manager.sbt ...
[info] resolving key references (67666 settings) ...
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:529)
        at scala.None$.get(Option.scala:527)
        at $174312435b30d4ac30d7$.$anonfun$$sbtdef$1(/tmp/bitcoin-s/bitcoin-s-docs/docs.sbt:24)
        at scala.Function1.$anonfun$compose$1(Function1.scala:49)
        at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
        at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
        at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
        at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
        at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.util.NoSuchElementException: None.get
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)

This was added in #2766

but i'm guessing this is probably related to not fetching deep enough to get tags. We use the `--depth` parameter to workaround for #2830

**Comment by benthecarman** [comment]
I think this just needs to remove the `in` and change it to a `/`

**Comment by Christewart** [comment]
I think this is the main point of the error, are you referencing the first warning? (`scalacOptions in Compile += {...`)

>java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:529)
at scala.None$.get(Option.scala:527)
at $174312435b30d4ac30d7$.$anonfun$$sbtdef$1(/tmp/bitcoin-s/bitcoin-s-docs/docs.sbt:24)
at scala.Function1.$anonfun$compose$1(Function1.scala:49)
at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.util.NoSuchElementException: None.get
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
