### ISSUE TITLE
[info] java.security.InvalidKeyException: Illegal key size

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2904]
This was seen on  444a0c1552ea4ca282b69e409bda08c18b27a558  when doing `bundle/run` when testing #2901 . The error occurred on server startup

The jdk i was using for this

> java -version
openjdk version "1.8.0_41"
OpenJDK Runtime Environment (build 1.8.0_41-b04)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)

Error:
>[info] 2021-04-13T20:08:32UTC ERROR [BitcoinSServerMain] Error on server startup!
[info] java.security.InvalidKeyException: Illegal key size
[info]  at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1043)
[info]  at javax.crypto.Cipher.implInit(Cipher.java:809)
[info]  at javax.crypto.Cipher.chooseProvider(Cipher.java:868)
[info]  at javax.crypto.Cipher.init(Cipher.java:1400)
[info]  at javax.crypto.Cipher.init(Cipher.java:1331)
[error] java.security.InvalidKeyException: Illegal key size
[error]         at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1043)
[info]  at org.bitcoins.crypto.AesCrypt$.decryptionCipher(AesCrypt.scala:289)
[error]         at javax.crypto.Cipher.implInit(Cipher.java:809)
[info]  at org.bitcoins.crypto.AesCrypt$.decrypt(AesCrypt.scala:298)
[error]         at javax.crypto.Cipher.chooseProvider(Cipher.java:868)
[info]  at org.bitcoins.keymanager.EncryptedSeed.decryptStr(EncryptedMnemonic.scala:49)
[error]         at javax.crypto.Cipher.init(Cipher.java:1400)
[info]  at org.bitcoins.keymanager.EncryptedSeed.toMnemonic(EncryptedMnemonic.scala:62)
[error]         at javax.crypto.Cipher.init(Cipher.java:1331)
[info]  at org.bitcoins.keymanager.WalletStorage$.decryptSeed(WalletStorage.scala:300)
[error]         at org.bitcoins.crypto.AesCrypt$.decryptionCipher(AesCrypt.scala:289)
[error]         at org.bitcoins.crypto.AesCrypt$.decrypt(AesCrypt.scala:298)
[info]  at org.bitcoins.keymanager.WalletStorage$.$anonfun$decryptSeedFromDisk$2(WalletStorage.scala:341)

**Comment by Christewart** [comment]
FWIW, when switching to this jdk things work ok. I tried these three versions and things seem to work

> java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

> java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 25.272-b10-jvmci-20.3-b06, mixed mode)

> java -version
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment (build 15.0.2+7-27)
OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
