### ISSUE TITLE
BitcoindChainHandlerViaZmqTest timing out on CI

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#2925]
`org.bitcoins.chain.blockchain.BitcoindChainHandlerViaZmqTest` is sporadically failing on PostgreSQL Tests on CI:
```
[info] ChainHandlerTest:
[info] - must peer with bitcoind via zmq and have blockchain info relayed *** FAILED *** (23 seconds, 47 milliseconds)
[info]   org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 50 attempts with interval=100 milliseconds waiting periods
[info]   at org.bitcoins.chain.blockchain.BitcoindChainHandlerViaZmqTest.$anonfun$new$6(BitcoindChainHandlerViaZmqTest.scala:39)
[info]   at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]   at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info]   at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info]   at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info]   at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by Christewart** [comment]
fixed in #2990
