### ISSUE TITLE
Script invariant incorrect for mainnet block ConditionalScriptPubKey cannot wrap P2SH

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2960]
I was doing some scanning for the mainnet blockchain this morning and had this invariant be broken on block `000000000000000000014bba07e99147a8e6c817bcb9147a5e5bc866819d2672` .

>2021-04-24T15:17:57UTC INFO [ScanBitcoind] Searching block at height=674952 hashBE=000000000000000000014bba07e99147a8e6c817bcb9147a5e5bc866819d2672
2021-04-24T15:17:57UTC ERROR [ScanBitcoind] Failed to startup server!
java.lang.IllegalArgumentException: requirement failed: ConditionalScriptPubKey cannot wrap P2SH
        at scala.Predef$.require(Predef.scala:338)
        at org.bitcoins.core.protocol.script.ConditionalScriptPubKey.$init$(ScriptPubKey.scala:618)
        at org.bitcoins.core.protocol.script.NonStandardIfConditionalScriptPubKey$NonStandardIfConditionalScriptPubKeyImpl.<init>(ScriptPubKey.scala:740)
        at org.bitcoins.core.protocol.script.NonStandardIfConditionalScriptPubKey$.$anonfun$fromAsm$7(ScriptPubKey.scala:750)
        at org.bitcoins.core.protocol.script.ScriptFactory.buildScript(ScriptFactory.scala:19)
        at org.bitcoins.core.protocol.script.ScriptFactory.buildScript$(ScriptFactory.scala:14)
        at org.bitcoins.core.protocol.script.NonStandardIfConditionalScriptPubKey$.buildScript(ScriptPubKey.scala:735)
        at org.bitcoins.core.protocol.script.NonStandardIfConditionalScriptPubKey$.fromAsm(ScriptPubKey.scala:752)
        at org.bitcoins.core.protocol.script.RawScriptPubKey$.fromAsm(ScriptPubKey.scala:1044)
        at org.bitcoins.core.protocol.script.NonWitnessScriptPubKey$.fromAsm(ScriptPubKey.scala:1077)
        at org.bitcoins.core.protocol.script.ScriptPubKey$.fromAsm(ScriptPubKey.scala:1096)
        at org.bitcoins.core.protocol.script.P2SHScriptSignature$.parseRedeemScript(ScriptSignature.scala:297)
        at org.bitcoins.core.protocol.script.P2SHScriptSignature$.isRedeemScript(ScriptSignature.scala:263)
        at org.bitcoins.core.protocol.script.P2SHScriptSignature$.isValidAsm(ScriptSignature.scala:252)

Found with #2961

**Comment by Christewart** [comment]
This is the transaction causing the problem. Take a look at the redeemScripts/scriptSigs! Someone was having some fun

https://blockstream.info/tx/9c677e67180896dfc61f7d4076680239aa80692b5b055498de8559f3dc04ba15

Hex:
>0100000004c58a3b58b6c85991463323083dba1f4a583adee919f04c8274a818b2f781ae210000000041013f003d632103184b16f5d6c01e2d6ded3f8a292e5b81608318ecb8e93aa3747bc88b8dbf256cac67a914f5862841f254a1483eab66909ae588e45d617c5e8768ffffffffea35085c4c63eeee8ac84bde8142ce5f5d24fa9f889519fca89bcc75cff547d60100000041013f003d632103184b16f5d6c01e2d6ded3f8a292e5b81608318ecb8e93aa3747bc88b8dbf256cac67a914f5862841f254a1483eab66909ae588e45d617c5e8768ffffffff1d8aebbe8867b8485bf931004236d90df4d06201c4b3527b68cbdfc0b7b640b60100000041013f003d632103184b16f5d6c01e2d6ded3f8a292e5b81608318ecb8e93aa3747bc88b8dbf256cac67a914f5862841f254a1483eab66909ae588e45d617c5e8768ffffffff3f719fc0eedfc9359ad7c102894424021dd16d225cb5dcef5e9d684d24436b7a01000000420231ec003d632103184b16f5d6c01e2d6ded3f8a292e5b81608318ecb8e93aa3747bc88b8dbf256cac67a914a49d5f95f680ee066d035b2887664422ff0128788768ffffffff01404b4c00000000001976a9147dfad7921c921d7506dad9b81aec0515674a876388ac00000000
