### ISSUE TITLE
Corrupted dlcdb.sqlite with offer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#2964]
I've managed to corrupt the dlcdb.sqlite it seems with this announcement: https://test.oracle.suredbits.com/event/fd73835c169e7ebad8e64f631e0e02987a368221470243371c7e87a2ead4ff03

on commit: 0.5.0-176-bb8b3c01-ADAPTOR-ECDSA-DLC-SNAPSHOT

The totalCollatera: `0.001` my collateral: `0.0005` refund date: `2021-04-27`. I was betting on NO

When i try to restart the server, i get this error

>[info] 2021-04-25T20:32:48UTC INFO [HikariDataSource] bitcoin-s-db-pool - Start completed.
[info] 2021-04-25T20:32:48UTC INFO [Server] Unhandled error in server:
[info] java.lang.IllegalArgumentException: Invalid hexadecimal character 'I' at index 0
[info]  at scodec.bits.ByteVector$.$anonfun$fromValidHex$1(ByteVector.scala:1816)
[info]  at scala.util.Either.fold(Either.scala:190)
[info]  at scodec.bits.ByteVector$.fromValidHex(ByteVector.scala:1816)
[info]  at org.bitcoins.crypto.CryptoBytesUtil.decodeHex(CryptoBytesUtil.scala:12)
[info]  at org.bitcoins.crypto.CryptoBytesUtil.decodeHex$(CryptoBytesUtil.scala:11)
[info]  at org.bitcoins.crypto.CryptoBytesUtil$.decodeHex(CryptoBytesUtil.scala:104)
[info]  at org.bitcoins.crypto.Factory.fromHex(Factory.scala:13)
[info]  at org.bitcoins.db.DbCommonsColumnMappers.$anonfun$uint64Mapper$2(DbCommonsColumnMappers.scala:160)
[info]  at slick.jdbc.JdbcTypesComponent$MappedJdbcType$$anon$1.comap(JdbcTypesComponent.scala:51)
[info]  at slick.jdbc.JdbcTypesComponent$MappedJdbcType.getValue(JdbcTypesComponent.scala:31)
[info]  at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26)
[info]  at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
[info]  at slick.relational.ProductResultConverter.read(ResultConverter.scala:54)
[info]  at slick.relational.ProductResultConverter.read(ResultConverter.scala:44)
[info]  at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:134)
[info]  at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
[info]  at slick.jdbc.StatementInvoker$$anon$2.extractValue(StatementInvoker.scala:67)
[info]  at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
[info]  at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
[info]  at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
[info]  at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
[info]  at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
[info]  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[info]  at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[info]  at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
[info]  at slick.jdbc.Invoker.foreach(Invoker.scala:48)
[info]  at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
[info]  at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
[info]  at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
[info]  at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
[info]  at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
[info]  at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
[info]  at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
[info]  at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
[info]  at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
[info]  at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
[info]  at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[info]  at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]  at java.base/java.lang.Thread.run(Thread.java:829)
[info] 2021-04-25T20:32:48UTC INFO [ActorSystemImpl] http-rpc-server: Response for

**Comment by Christewart** [comment]
Taken care of in #3170
