### ISSUE TITLE
Invalid digital signature on invoice returned from eclair

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#297]
```
lnbcrtpwrlzq9pp5phdlf0s83aw96rymm03d4awyjehtlj5yfkhml79ytv8yv8c3qlasdqh2fjkvatwvssxjmnkda5kxegxqrrssqr4xl2lk0325hkxy03pvsrq3fjma7elqm2lczc5mqef38vjw4ruyz57p392xn6ezry2v460yukz675z45km7evqzjvkl06sthgvgjssq3ztaep
```

**Comment by Christewart** [comment]
Fails on this CI run as well: https://travis-ci.org/bitcoin-s/bitcoin-s-core/jobs/482483230#L2069

**Comment by Christewart** [comment]
Another failure: 

```
lnbcrt30000ppwy5cjnpp5u3hgeyslektvp0vu44nuq7t3w2pgfrg23azaauwuhxexhz76gupsdxa0v3xgatjv96xjmmwygarxvpsxqkzycmgv9hxuetvygazyarfvd4k2unnygkzyetkv4h8gg36yfeh2cnnvdexjcn9ygkzyat4d9jzyw3z8qcrjve3xqenwtt9xqexxtf5v3nryttpvgerjtf5v43nwv3sx3sk2cf4xg3zcgn90p3ksctwvajjyw3zvf5hgenfdejhsg3vyfehjmtzdakzyw3zgy386qr3drq7t6xj0jnat64a2ys2ndx0vc0p6cdyn58hre9zw44u0r4j4rv23sqwvqu94myt82hzqfaczw4vvxkxlfw9ezkhffzp6num7tacqyjg4ww
```

**Comment by Christewart** [comment]
All of these invoices appear to be invalid according to eclair

```bashrc
chris@chris:~$ $node1 checkinvoice lnbcrtpwrlzq9pp5phdlf0s83aw96rymm03d4awyjehtlj5yfkhml79ytv8yv8c3qlasdqh2fjkvatwvssxjmnkda5kxegxqrrssqr4xl2lk0325hkxy03pvsrq3fjma7elqm2lczc5mqef38vjw4ruyz57p392xn6ezry2v460yukz675z45km7evqzjvkl06sthgvgjssq3ztaep
invalid payment request key not found: b
chris@chris:~$ $node1 checkinvoice lnbcrtpwrlzq9pp5phdlf0s83aw96rymm03d4awyjehtlj5yfkhml79ytv8yv8c3qlasdqh2fjkvatwvssxjmnkda5kxegxqrrssqr4xl2lk0325hkxy03pvsrq3fjma7elqm2lczc5mqef38vjw4ruyz57p392xn6ezry2v460yukz675z45km7evqzjvkl06sthgvgjssq3ztaep
invalid payment request key not found: b
chris@chris:~$ $node1 checkinvoice lnbcrt30000ppwy5cjnpp5u3hgeyslektvp0vu44nuq7t3w2pgfrg23azaauwuhxexhz76gupsdxa0v3xgatjv96xjmmwygarxvpsxqkzycmgv9hxuetvygazyarfvd4k2unnygkzyetkv4h8gg36yfeh2cnnvdexjcn9ygkzyat4d9jzyw3z8qcrjve3xqenwtt9xqexxtf5v3nryttpvgerjtf5v43nwv3sx3sk2cf4xg3zcgn90p3ksctwvajjyw3zvf5hgenfdejhsg3vyfehjmtzdakzyw3zgy386qr3drq7t6xj0jnat64a2ys2ndx0vc0p6cdyn58hre9zw44u0r4j4rv23sqwvqu94myt82hzqfaczw4vvxkxlfw9ezkhffzp6num7tacqyjg4ww
invalid payment request key not found: b
chris@chris:~$ $node1 checkpayment lnbcrt30000ppwy5cjnpp5u3hgeyslektvp0vu44nuq7t3w2pgfrg23azaauwuhxexhz76gupsdxa0v3xgatjv96xjmmwygarxvpsxqkzycmgv9hxuetvygazyarfvd4k2unnygkzyetkv4h8gg36yfeh2cnnvdexjcn9ygkzyat4d9jzyw3z8qcrjve3xqenwtt9xqexxtf5v3nryttpvgerjtf5v43nwv3sx3sk2cf4xg3zcgn90p3ksctwvajjyw3zvf5hgenfdejhsg3vyfehjmtzdakzyw3zgy386qr3drq7t6xj0jnat64a2ys2ndx0vc0p6cdyn58hre9zw44u0r4j4rv23sqwvqu94myt82hzqfaczw4vvxkxlfw9ezkhffzp6num7tacqyjg4ww
command failed: payment identifier must be a payment request or a payment hash
chris@chris:~$ $node1 checkpayment lnbcrtpwytm8lpp5r79lu8cpt2ft00g2385v57wyjht9zaw2fvr0epn283hlxl54yxfqdq6w35xjueqd9ejqcfqdehhgefq8yxqrrssqr3hjgvstudct2u8hqc72w0cscxe9rzlfjume0ccrjy2w3x7mzl57zt4em3z25ww6yyvzfqgz20j78s56eseu2t7rwtv2fty5ly96acp72f9nw
command failed: payment identifier must be a payment request or a payment hash
```

**Comment by nkohen** [comment]
```
[info]   java.lang.IllegalArgumentException: requirement failed: Did not receive a valid digital signature for the invoice lnbcrtpw9xudtpp5cdryw4mgyhk03n0kn3mymzpzkqqcquv6cayt4px2dwmfzt8yf83qdqj2fjkvatwv304getnwsxqrrssqr67w35kjrl635hpsr6xn05l4g5ru4kmz86lxf6k5nyrfrgskclk5ys0yg87zqt34vr0mgj9y4gwktcpsnc0s8ur9krrzq3zhsvmzagqmuwt6h
[info]   at scala.Predef$.require(Predef.scala:281)
[info]   at org.bitcoins.core.protocol.ln.LnInvoice.<init>(LnInvoice.scala:20)
[info]   at org.bitcoins.core.protocol.ln.LnInvoice$LnInvoiceImpl.<init>(LnInvoice.scala:120)
[info]   at org.bitcoins.core.protocol.ln.LnInvoice$.apply(LnInvoice.scala:230)
[info]   at org.bitcoins.core.protocol.ln.LnInvoice$.apply(LnInvoice.scala:178)
[info]   at org.bitcoins.core.protocol.ln.LnInvoice$.$anonfun$fromString$5(LnInvoice.scala:216)
```

**Comment by Christewart** [comment]
https://travis-ci.org/bitcoin-s/bitcoin-s-core/jobs/493215099#L2270
