### ISSUE TITLE
`UnsatisfiedLinkError` on macOS

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-s/bitcoin-s#305]
Linking to libsecp256k1 does not work out of the box on macOS.  

Output from sbt, majority omitted for brevity: 
```scala
$ sbt coreTest/test
[info] org.bitcoins.core.crypto.ECPublicKeyTest *** ABORTED ***
[info]   java.lang.UnsatisfiedLinkError: org.bitcoin.NativeSecp256k1.secp256k1_ec_seckey_verify(Ljava/nio/ByteBuffer;J)I
[info]   at org.bitcoin.NativeSecp256k1.secp256k1_ec_seckey_verify(Native Method)
[info]   at org.bitcoin.NativeSecp256k1.secKeyVerify(NativeSecp256k1.java:133)
[info]   at org.bitcoins.core.crypto.ECPrivateKey$ECPrivateKeyImpl.<init>(ECKey.scala:140)
[info]   at org.bitcoins.core.crypto.ECPrivateKey$.fromBytes(ECKey.scala:156)
[info]   at org.bitcoins.core.crypto.ECPrivateKey$.fromBytes(ECKey.scala:150)
[info]   at org.bitcoins.core.crypto.ECPrivateKey$.fromBytes(ECKey.scala:132)
[info]   at org.bitcoins.core.util.Factory.fromHex(Factory.scala:13)
[info]   at org.bitcoins.core.util.Factory.fromHex$(Factory.scala:13)
[info]   at org.bitcoins.core.crypto.ECPrivateKey$.fromHex(ECKey.scala:132)
[info]   at org.bitcoins.core.util.Factory.apply(Factory.scala:22)
[info]   ...
```

macOS information: 

```
OS: macOS High Sierra 10.13.6 17G65 x86_64 
Kernel: 17.7.0 
Uptime: 20 hours  
CPU: Intel i5-4250U (4) @ 1.30GHz 
GPU: Intel HD Graphics 5000 
Memory: 2101MiB / 4096MiB
```

**Comment by torkelrogstad** [comment]
Fixed it by updating binaries. After compiling: 

```
cp secp256k1/.libs/libsecp256k1* secp256k1jni/natives/osx_64 
```

I could make a PR with updated binaries, but we should somehow verify that the original ones are broken and the ones I have produced work for more machines.

**Comment by Christewart** [comment]
#308 addresses this
