### ISSUE TITLE
bitcoin-s gui balance thread getting exception on startup

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3098]
This occurred on a9bdd2d2 when doing `bundle/run` on mainnet connected to a bitcoind rpc backend

> [info] 2021-05-17T14:43:09UTC INFO [BitcoinSServerMain] version=0.6.0-24-a9bdd2d2-ADAPTOR-ECDSA-DLC-SNAPSHOT

>[error] Exception in thread "bitcoin-s-gui-balance-1621262594819" ujson.ParseException: expected whitespace or eof got "s" at index 9
[error]         at ujson.CharParser.die(CharParser.scala:84)
[error]         at ujson.CharParser.parse(CharParser.scala:64)
[error]         at ujson.StringParser$.transform(StringParser.scala:28)
[error]         at ujson.StringParser$.transform(StringParser.scala:27)
[error]         at ujson.Readable$fromTransformer.transform(Readable.scala:13)
[error]         at ujson.package$.transform(package.scala:4)
[error]         at ujson.package$.$anonfun$read$1(package.scala:10)
[error]         at upickle.core.TraceVisitor$.withTrace(TraceVisitor.scala:18)
[error]         at ujson.package$.read(package.scala:10)
[error]         at org.bitcoins.gui.WalletGUIModel.org$bitcoins$gui$WalletGUIModel$$updateBalance(WalletGUIModel.scala:111)
[error]         at org.bitcoins.gui.WalletGUIModel$UpdateBalanceRunnable$.run(WalletGUIModel.scala:29)

**Comment by Christewart** [comment]
Done in #3174
