### ISSUE TITLE
DLC wallet refactor leads to unique constraint violation with contract

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3127]
Creating offer on 74f9d6bef79d590cb28449c0f24035c4ae9c3571  results in this error with this contract: 

https://test.oracle.suredbits.com/contract/enum/57505dcdfe8746d9adf3454df538244a425f302c07642d9dc4a4f635fbf08d30/73b0922c0be29cef8dad4e2377960a243484452dbfcb65b26ca328b71b477b8d

>2021-05-22T17:56:42UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Offer
2021-05-22T17:56:42UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-05-22T17:56:42UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: oracle_announcement_data.announcement_signature)
2021-05-22T17:56:42UTC INFO [Server] Unhandled error in server:
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: oracle_announcement_data.announcement_signature)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.execute(DB.java:863)
	at org.sqlite.core.DB.executeUpdate(DB.java:904)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$17(JdbcActionComponent.scala:533)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement(JdbcBackend.scala:432)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement$(JdbcBackend.scala:429)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:660)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$16(JdbcActionComponent.scala:530)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:575)
	at scala.collection.IterableOnceOps.copyToArray(IterableOnce.scala:874)

**Comment by Christewart** [comment]
I actually think this happens when you try to use a contract twice, i think we don't need to create the oracle announcement twice. We need a way to use the same contract info to enter two DLCs with separate people i believe
