### ISSUE TITLE
Error syncing compact filters A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3128]
This was seen on eafaff9e with a sqlite database on mainnet on mac os x 

>2021-05-23T13:02:09UTC INFO [BitcoinSServerMain] version=0.6.0-52-eafaff9e-20210523-0751-SNAPSHOT

>2021-05-23T13:02:14UTC INFO [NeutrinoNode] Our node has been full started. It took=1032ms
2021-05-23T13:02:14UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000000000133d6f66dea1103ec33d587a65ed2c20804c18b310843 at height 684657, with 684656 filter headers and 131999 filters
2021-05-23T13:02:14UTC INFO [Wallet$WalletImpl] Starting Wallet
2021-05-23T13:02:14UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.001s)
2021-05-23T13:02:14UTC INFO [DbMigrate] Current version of schema "main": 10
2021-05-23T13:02:14UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-05-23T13:02:14UTC INFO [BitcoinSServerMain] Starting neutrino node sync
2021-05-23T13:02:14UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2021-05-23T13:02:14UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=684657, stopBlockHash=0000000000000000000133d6f66dea1103ec33d587a65ed2c20804c18b310843)
2021-05-23T13:02:14UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=132000, stopBlockHash=0000000000000f502e0d9dadc742dfd326b03fd10f6c33534ccc6cdd6322477e)
2021-05-23T13:02:14UTC INFO [NeutrinoNode] Starting sync node, height=684657 hash=0000000000000000000133d6f66dea1103ec33d587a65ed2c20804c18b310843
2021-05-23T13:02:14UTC INFO [BitcoinSServerMain] Done starting Main!
2021-05-23T13:02:15UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,64 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,142 bytes total),HttpProtocol(HTTP/1.1)))
2021-05-23T13:02:15UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,83 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,32 bytes total),HttpProtocol(HTTP/1.1)))
2021-05-23T13:02:15UTC INFO [DataMessageHandler] Received headers message with 1 headers
2021-05-23T13:02:16UTC INFO [DataMessageHandler] Got 1 compact filter header hashes
2021-05-23T13:02:16UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=132000, stopBlockHash=0000000000000f502e0d9dadc742dfd326b03fd10f6c33534ccc6cdd6322477e)
2021-05-23T13:02:17UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2021-05-23T13:02:17UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=133000, stopBlockHash=000000000000080f8a582276851e83a4d46108c5b83049d9542abc99e53a903d)
2021-05-23T13:02:17UTC INFO [DataMessageHandler] Got 2 compact filter header hashes
2021-05-23T13:02:17UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-05-23T13:02:17UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
2021-05-23T13:02:17UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=370310e56d350e8d3bd669688b67fbcec84d7888661722e9a031d11139786da8, stopHash=000000000000000000065ce66d8d16a325fb0b6e7fa510d55ffe5e155f02e7aa filterHeaders=2f60033c6457acd89f223b1cc29a5be1283fb9d919818cde7c980d0fd4af69a7...9c875b6787ee01026821c63af800f70794872451313d101b55c5aa4db8068dfb)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.DB.executeBatch(DB.java:814)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-23T13:02:17UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-05-23T13:02:17UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2021-05-23T13:02:17UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(7e472263dd6ccc4c53336c0fd13fb026d3df42c7ad9d0d2e500f000000000000),ByteVector(862 bytes, #-800729791))
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.DB.executeBatch(DB.java:814)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-23T13:02:18UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-05-23T13:02:18UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2021-05-23T13:02:18UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(b3522836a65b080133a57dc11c10e34825b7dade7b74ebbdae08000000000000),ByteVector(1774 bytes, #-108058219))
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.throwex(DB.java:989)
	at org.sqlite.core.DB.executeBatch(DB.java:814)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)

**Comment by Christewart** [comment]
I tried this on 7468cbec238bb78c0a77d47fd11ea1f29c45d003 to see if the bug was introduced in #3092, but the same behavior occurs there.

**Comment by Christewart** [comment]
So i believe this is a race condition between 

1. [Data message handler calling `sendFirstGetCompactFilterCommand`](https://github.com/Christewart/bitcoin-s-core/commit/3a8f2dd43b4cbb5461217d7e83c2a3b0f1bfe167#diff-61413f0a707d1e3e49431ad34fcb1af04b4fa36148e75c7abc692bebc07822b7R74) 
2. [Node.sync() calling `sendNextGetCompactFilterCommand`](https://github.com/Christewart/bitcoin-s-core/commit/3a8f2dd43b4cbb5461217d7e83c2a3b0f1bfe167#diff-0a8f00449df9bc71b4e93bb2864d8b26805f7190febebc6030da29f36ad4d57bR106)

When we are first starting up the node, if we have a filter header batch size LESS THAN 2,000 filter headers (i.e. we ran the node recently), we will send requests in `Node.sync()` and inside of `DataMessageHandler` to request filters.

The second request that completes will fail with a bunch of uniquness violations in `cfilters` because the first request has inserted these filters already. 

Ultimately i think our logic is incorrect in `Node.syncFilters()`. It seems we aren't determining if our block headers are synced or not. If our block headers are NOT synced, we should be doing nothing with filters inside of `Node.sync()`

https://github.com/bitcoin-s/bitcoin-s/blob/3a8f2dd43b4cbb5461217d7e83c2a3b0f1bfe167/node/src/main/scala/org/bitcoins/node/NeutrinoNode.scala#L81 

Logs: 

>2021-05-23T17:27:08UTC INFO [BitcoinSServerMain] Done starting Main!
2021-05-23T17:27:08UTC INFO [DataMessageHandler] Starting to fetch filter headers in data message handler
2021-05-23T17:27:09UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2021-05-23T17:27:09UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=278000, stopBlockHash=0000000000000001ed51db67f98e83ac76209fe00dabc2a42c80cbc9a4ef6c45)
2021-05-23T17:27:09UTC INFO [DataMessageHandler] Got 1 compact filter header hashes
2021-05-23T17:27:09UTC INFO [DataMessageHandler] Done syncing filter headers, beginning to sync filters in datamessagehandler
2021-05-23T17:27:09UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=278000, stopBlockHash=0000000000000001ed51db67f98e83ac76209fe00dabc2a42c80cbc9a4ef6c45)
2021-05-23T17:27:11UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2021-05-23T17:27:11UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=279000, stopBlockHash=00000000000000029b0adb904fd89e7ece37a17a02f90f1628d38791abeeec47)
2021-05-23T17:27:11UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2021-05-23T17:27:11UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2021-05-23T17:27:11UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(456cefa4c9cb802ca4c2ab0de09f2076ac838ef967db51ed0100000000000000),ByteVector(2376 bytes, #-435675928))
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
