### ISSUE TITLE
 Error when constructing offer requirement failed: Cannot have threshold (1) above the number of oracles (0)

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3135]
This occurred on 6be3f884 (#3134 )

2021-05-24T19:42:01UTC INFO [BitcoinSServerMain] version=0.6.0-46-6be3f884-ADAPTOR-ECDSA-DLC-SNAPSHOT

This was using this contract info from the oracle explorer: 

https://test.oracle.suredbits.com/contract/enum/75b08299654dca23b80cf359db6afb6cfd6e55bc898b5397d3c0fe796dfc13f0/12fb3e5f091086329ed0d2a12c3fcfa80111a36ef3fc1ac9c2567076a57d6a73

Weirdly enough the serialized offer is still put in the dialog box. You can see it in the background of this image. It seems to be a valid offer, as when i take it over to another wallet, the wallet produces a valid accept message for it.

![Screenshot from 2021-05-24 14-47-00](https://user-images.githubusercontent.com/3514957/119400050-40ec9300-bc9f-11eb-9e8d-888074961d1f.png)

The error message

>java.lang.IllegalArgumentException: requirement failed: Cannot have threshold (1) above the number of oracles (0)
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.core.protocol.dlc.models.MultiOracleInfo.$init$(OracleInfo.scala:234)
	at org.bitcoins.core.protocol.dlc.models.EnumMultiOracleInfo.<init>(OracleInfo.scala:277)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.getContractInfo(DLCDataManagement.scala:140)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.getContractInfo$(DLCDataManagement.scala:124)
	at org.bitcoins.dlc.wallet.DLCWallet.getContractInfo(DLCWallet.scala:37)
	at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$findDLC$5(DLCWallet.scala:1227)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)

**Comment by Christewart** [comment]
Done in #3134
