### ISSUE TITLE
Change isn't reflected on GUI

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3156]
I had 10,000,000 sats in the wallet, entered into a DLC with nadav for 50,000 sats. Now I don't have any balance in my wallet under `unconfirmed` or `confirmed`, but oddly enough my total balance seems correct

![Screenshot from 2021-05-26 15-34-31](https://user-images.githubusercontent.com/3514957/119727554-0b2ee200-be38-11eb-87da-8cc6abc960c7.png)

**Comment by nkohen** [comment]
I had the same behavior with the following error on startup, but when I restarted it worked fine (showed as confirmed). I wonder if this has to do with the fact that bundle syncs while booting and something weird happened as it discovered the new utxos?

```
[error] Exception in thread "bitcoin-s-gui-balance-1622060598745" java.lang.IllegalStateException: Not on FX application thread; currentThread = bitcoin-s-gui-balance-1622060598745
[error] 	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:293)
[error] 	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:447)
[error] 	at javafx.scene.Parent$3.onProposedChange(Parent.java:474)
[error] 	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:113)
[error] 	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
[error] 	at javafx.scene.control.skin.LabeledSkinBase.updateChildren(LabeledSkinBase.java:283)
[error] 	at javafx.scene.control.skin.LabeledSkinBase.lambda$new$11(LabeledSkinBase.java:220)
[error] 	at com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
[error] 	at javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
[error] 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
[error] 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
[error] 	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
[error] 	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
[error] 	at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:231)
[error] 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
[error] 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
[error] 	at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:175)
[error] 	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
[error] 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
[error] 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
[error] 	at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:175)
[error] 	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
[error] 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
[error] 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
[error] 	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
[error] 	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
[error] 	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
[error] 	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
[error] 	at scalafx.beans.property.StringProperty.value_$eq(StringProperty.scala:59)
[error] 	at org.bitcoins.gui.WalletGUIModel.org$bitcoins$gui$WalletGUIModel$$updateBalance(WalletGUIModel.scala:126)
[error] 	at org.bitcoins.gui.WalletGUIModel$UpdateBalanceRunnable$.run(WalletGUIModel.scala:30)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Christewart** [comment]
ohh.... that makes total sense. i think we have some serious threading issues with GUI. That is probably the root cause
