### ISSUE TITLE
Weirdness when DLC funding inputs are unconfirmed at sign time

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#3182]
`5e1d2301e76e8c001400e50edff89d2d8203027859a3f436baff93950d16f0e7` was an unconfirmed funding input into this DLC funding tx: `29373b52de8688aa12d8fface5140daea95b396937844a6304cc306906256f7c` and they both just got confirmed together and I got:
```
[info] 2021-05-27T19:00:02UTC INFO [BitcoindRpcBackendUtil$] Fetching 1 hashes from bitcoind
[info] 2021-05-27T19:00:06UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006b4d6cf73681e3e87e07558696ba9a6dd362aa86379d5
[info] 2021-05-27T19:00:10UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=00000000000000000006b4d6cf73681e3e87e07558696ba9a6dd362aa86379d5.
[info] java.lang.IllegalArgumentException: requirement failed: If we have spent a spendinginfodb, the spendingTxId must be defined. Outpoint=TransactionOutPoint(5e1d2301e76e8c001400e50edff89d2d8203027859a3f436baff93950d16f0e7:2)
[info] 	at scala.Predef$.require(Predef.scala:337)
[info] 	at org.bitcoins.core.api.wallet.db.SpendingInfoDb.$init$(SpendingInfoDb.scala:126)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.<init>(SpendingInfoDb.scala:33)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copy(SpendingInfoDb.scala:32)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copyWithState(SpendingInfoDb.scala:41)
[info] 	at org.bitcoins.core.api.wallet.db.SegwitV0SpendingInfo.copyWithState(SpendingInfoDb.scala:24)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.processExistingReceivedTxo(TransactionProcessing.scala:386)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processReceivedUtxos$2(TransactionProcessing.scala:223)
[info] 	at scala.collection.immutable.Vector1.map(Vector.scala:1872)
[info] 	at scala.collection.immutable.Vector1.map(Vector.scala:375)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.processReceivedUtxos(TransactionProcessing.scala:222)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.processReceivedUtxos$(TransactionProcessing.scala:213)
[info] 	at org.bitcoins.dlc.wallet.DLCWallet.org$bitcoins$dlc$wallet$internal$DLCTransactionProcessing$$super$processReceivedUtxos(DLCWallet.scala:37)
[info] 	at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.processReceivedUtxos(DLCTransactionProcessing.scala:207)
[info] 	at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.processReceivedUtxos$(DLCTransactionProcessing.scala:201)
[info] 	at org.bitcoins.dlc.wallet.DLCWallet.processReceivedUtxos(DLCWallet.scala:37)
[info] 	at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processTransactionImpl$3(TransactionProcessing.scala:280)
[info] 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info] 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by nkohen** [comment]
For context, the funding input is a change address on a previous DLC, and currently that previous DLC is showing up as broadcasted (and not as confirmed) locally with my new DLC showing up as signed (and not confirmed) locally

**Comment by nkohen** [comment]
For even further context, I am not the initiator of the first DLC (so I did the broadcast) and am the initiator of the second (so I didn't do the broadcast)

**Comment by Christewart** [comment]
Ben and i have both tried to reproduce this, and have had no luck. I tried on #3185  and ben tried on #3189, neither of us could reproduce
