### ISSUE TITLE
secp256k1 library not building / available by default

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#3302]
**Describe the bug**
secp256k1 library does not appear to be present, but appears to be required

**To Reproduce**
Checkout bitcoin-s repo
sbt bundle/run
In either Neutrino Config or Bitcoin RPC Config tabs, click Launch Wallet
Notice log line [info] UnsatisfiedLinkError: java.io.IOException: Couldn't load library library secp256k1
Connection fails and ultimately times out

**Expected behavior**
secp256k1 library would be available through build process

**Logs**
[info] UnsatisfiedLinkError: java.io.IOException: Couldn't load library library secp256k1
...
[info] 2021-06-21T14:54:58UTC INFO [PeerMessageReceiver] Connection established with peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)
[info] 2021-06-21T14:54:58UTC INFO [P2PClientActor] We've been disconnected by Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) command=PeerClosed
[info] 2021-06-21T14:54:58UTC ERROR [OneForOneStrategy] Cannot disconnect from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) when in state=Initializing
[info] java.lang.RuntimeException: Cannot disconnect from peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) when in state=Initializing

**Platform (please complete the following information):**
 - OS: macOS
 - Version: top of tree

**Additional context**

**Comment by benthecarman** [comment]
How was this resolved?

**Comment by Christewart** [comment]
> How was this resolved?

So neither of us seem to be able to reproduce. @user411 was able to do a few DLCs with me this morning before with no issues and i didn't have any problems on my mac either. 

Did a user you are helping end up having a problem?

**Comment by benthecarman** [comment]
> Did a user you are helping end up having a problem

No I just saw you guys did a DLC so I figured you got it working

**Comment by user411** [comment]
Not sure how anything resolved, but the message doesn't seem to be in the logs today. II have built and run several more packages inside the project by now, but didn't consciously do anything to solve the issue.

**Comment by Christewart** [comment]
I'm going to close this as we can't seem to reproduce on my mac or Ivans.

**Comment by user411** [comment]
Have not been able to build libsecp256k1 locally and use it yet. Trying to build had to change configs per https://github.com/bitcoin-s/bitcoin-s/issues/3382 Eventually ran into

ivan@babyMBP secp256k1-zkp % make check-java
Compiling src/java/org/bitcoin/NativeSecp256k1.java src/java/org/bitcoin/NativeSecp256k1Util.java src/java/org/bitcoin/NativeSecp256k1Test.java src/java/org/bitcoin/Secp256k1Context.java

 libsecp256k1 enabled: false

Exception in thread "main" org.bitcoin.NativeSecp256k1Util$AssertFailException: FAIL: isEnabled
	at org.bitcoin.NativeSecp256k1Util.assertEquals(NativeSecp256k1Util.java:28)
	at org.bitcoin.NativeSecp256k1Test.main(NativeSecp256k1Test.java:380)
make: *** [check-java] Error 1
ivan@babyMBP secp256k1-zkp % java -version
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.45+27-CA (build 11.0.10+9-LTS, mixed mode)

ivan@babyMBP secp256k1-zkp % uname -a
Darwin babyMBP 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64

![Screen Shot 2021-07-08 at 10 58 24 AM](https://user-images.githubusercontent.com/22351459/124962250-a391b800-dfdb-11eb-8a3b-1141a22de330.png)

**Comment by Christewart** [comment]
So i'm able to run libsecp256k1 on 028b6f89 with no issues. Here is the env I am running against

<img width="1439" alt="Screen Shot 2021-07-08 at 12 29 56 PM" src="https://user-images.githubusercontent.com/3514957/124965916-3f292580-dfe8-11eb-9c67-e6d6cdc46f80.png">

<img width="1439" alt="Screen Shot 2021-07-08 at 12 30 43 PM" src="https://user-images.githubusercontent.com/3514957/124965986-5536e600-dfe8-11eb-838e-f5c7c6aa14f8.png">

<img width="586" alt="Screen Shot 2021-07-08 at 12 31 57 PM" src="https://user-images.githubusercontent.com/3514957/124966109-81526700-dfe8-11eb-9ccb-72f0997547ab.png">

**Comment by Christewart** [comment]
So i believe i have found the issue. The reason you are getting these errors are because your jdks are old. They likely do not understand/support the fact that mac now can have 2 different chip archs. Here are the versions/dates of the jdks you tried 

>openjdk version "11.0.10" 2021-01-19 LTS

>openjdk version "11.0.2" 2019-01-15

The `2019` jdk definitely doesn't support m1,  it appears that the january release for zulu should support apple silicon. I don't know why it doesn't work. 

https://docs.azul.com/zulu/zulurelnotes-january2021/ZuluReleaseNotes/SupportedPlatforms.htm

I can reproduce locally that `11.0.10` doesn't work as well for me. If you upgrade to zulu `11.0.11` it should be fine.

**Comment by Christewart** [comment]
It apperas that the `cs java --available` command does not allow us to install the newest zulu builds (`11.0.11`) 

https://get-coursier.io/docs/2.0.8/cli-java#jvm-index

<img width="1013" alt="Screen Shot 2021-07-08 at 12 54 20 PM" src="https://user-images.githubusercontent.com/3514957/124968856-a1cff080-dfeb-11eb-8f86-1e99dc9891d9.png">

You will need to manually download the latest zulu jdk from 

https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk

**Comment by user411** [comment]
Works for me with the downloaded jdk. secp256k1jni/test runs and I don't see the console log line about the library starting bundle/run.

@Christewart What JDK were you using to begin with that wasn't having this issue?

**Comment by Christewart** [comment]
I've been using the zulu jdk i linked above for awhile. 

When I purchased this new mac, I kept downloading jdks (not using `cs`!) until i got one that could run on m1. I _assumed_ the `cs` tool would give us access to the latest zulu build and you would download it. You know what they say about assuming things... 


It appears that `cs` doesn't keep up to date with the latest jdks, so this might be an issue we run into again with developers on m1. Fortunately, I don't think these new apple laptops are that popular yet, so hopefully all the associated build tooling catches up to support m1 jdks.

**Comment by Christewart** [comment]
It looks like the coursier repo has this documented, but no one appears to be working on it https://github.com/coursier/coursier/issues/2069#issue-936410037

**Comment by Christewart** [comment]
We should probably add a note here on getting setup for the case where you are running m1 https://bitcoin-s.org/docs/getting-setup#step-1-developer-runtimes
