### ISSUE TITLE
Tx fails to broadcast when IBD is going on in testnet3

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3305]
Occurred on 97785561

I started up my node, and began syncing testnet compact filter headers. While doing this, I needed to send a testnet transaction. I tried to do so, and it appears I got disconnected from my peer almost instantaneously. Perhaps bitcoin core does this by default, but we should have some logic to handle this case to immediately broadcast the tx when we are done with IBD at minimum.

```
[info] 2021-06-21T16:34:24UTC INFO [BitcoinSServerMain] version=1.6.0-151-97785561-SNAPSHOT
[info] 2021-06-21T16:34:24UTC INFO [BitcoinSServerMain] using directory /home/chris/.bitcoin-s/testnet3
[info] 2021-06-21T16:34:25UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
[info] 2021-06-21T16:34:25UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/chaindb.sqlite (SQLite 3.34)
[info] 2021-06-21T16:34:25UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/nodedb.sqlite (SQLite 3.34)
[info] 2021-06-21T16:34:25UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.017s)
[info] 2021-06-21T16:34:25UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.017s)
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Current version of schema "main": 6
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Current version of schema "main": 2
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:25UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/dlcdb.sqlite (SQLite 3.34)
[info] 2021-06-21T16:34:25UTC INFO [DbValidate] Successfully validated 1 migration (execution time 00:00.005s)
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Current version of schema "main": 1
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:25UTC INFO [DLCAppConfig] Applied 0 to the dlc project
[info] 2021-06-21T16:34:25UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/old-wallet/walletdb.sqlite (SQLite 3.34)
[info] 2021-06-21T16:34:25UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.009s)
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Current version of schema "main": 10
[info] 2021-06-21T16:34:25UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:25UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
[info] 2021-06-21T16:34:25UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
[info] 2021-06-21T16:34:26UTC INFO [BitcoinSServerMain] Chain work already calculated
[info] 2021-06-21T16:34:26UTC INFO [BitcoinSServerMain] Using fee provider: MempoolSpaceProvider(HourFeeTarget)
[info] 2021-06-21T16:34:26UTC INFO [BitcoinSServerMain] Initialized chain api
[info] 2021-06-21T16:34:26UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
[info] 2021-06-21T16:34:26UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
[info] 2021-06-21T16:34:26UTC INFO [DLCAppConfig$] Using pre-existing wallet
[info] 2021-06-21T16:34:27UTC INFO [BitcoinSServerMain] Done configuring wallet, it took=1548ms
[info] 2021-06-21T16:34:27UTC INFO [BitcoinSServerMain] Done configuring node, it took=1550ms
[info] 2021-06-21T16:34:27UTC INFO [NeutrinoNode] Starting node
[info] 2021-06-21T16:34:27UTC INFO [PeerMessageSender] Attempting to connect to peer=neutrino.testnet3.suredbits.com/34.210.154.40:18333
[info] 2021-06-21T16:34:27UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.005s)
[info] 2021-06-21T16:34:27UTC INFO [DbMigrate] Current version of schema "main": 6
[info] 2021-06-21T16:34:27UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:27UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.001s)
[info] 2021-06-21T16:34:27UTC INFO [DbMigrate] Current version of schema "main": 2
[info] 2021-06-21T16:34:27UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:27UTC INFO [PeerMessageReceiver] Connection established with peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)
[info] 2021-06-21T16:34:28UTC INFO [NeutrinoNode] Our peer=Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333) has been initialized
[info] 2021-06-21T16:34:28UTC INFO [NeutrinoNode] Our node has been full started. It took=1306ms
[info] 2021-06-21T16:34:28UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000007f836da973759a0f9dd51ec21f86c236c46cb2f3abee527ee at height 1973862, with 1275999 filter headers and 0 filters
[info] 2021-06-21T16:34:28UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
[info] 2021-06-21T16:34:28UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.008s)
[info] 2021-06-21T16:34:28UTC INFO [DbMigrate] Current version of schema "main": 10
[info] 2021-06-21T16:34:28UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2021-06-21T16:34:29UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=4023ms
[info] 2021-06-21T16:34:29UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
[info] 2021-06-21T16:34:35UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=1276000, stopBlockHash=000000000001d0fef18d520d29ff7b0fe3197b27fade5621373d586a206d9d2e)
[info] 2021-06-21T16:34:35UTC INFO [NeutrinoNode] Starting sync node, height=1973862 hash=0000000000000007f836da973759a0f9dd51ec21f86c236c46cb2f3abee527ee
[info] 2021-06-21T16:34:35UTC INFO [BitcoinSServerMain] Done starting Main! It took 9802ms
[info] 2021-06-21T16:34:37UTC INFO [DataMessageHandler] Received headers message with 2000 headers
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Sending 0.25 BTC to tb1qnvr297y8xzxtcn2pcl0qkk0qzngk3xpd376y8y at feerate 42 sats/vbyte
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: 541825539aeb3aa5d9bb050c0c3ba44d40dfd400f683b7b0b84622d72a28b689:1
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(49937828 sats,wpkh(5bf5476715be1f97ed4e9f861a3c850cbe6109db))
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Processing TX from our wallet, transaction=536982efee1e20650b3620e004ebd2e3865cd7a30207ac297e268753b1d08a5b with blockHash=None
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 5b8ad0b15387267e29ac0702a3d75c86e3d2eb04e020360b65201eeeef826953:1
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 5b8ad0b15387267e29ac0702a3d75c86e3d2eb04e020360b65201eeeef826953:1 into DB
[info] 2021-06-21T16:34:57UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
[info] 2021-06-21T16:34:57UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
[info] 2021-06-21T16:34:57UTC INFO [DLCWallet$DLCWalletImpl] Processing of internal transaction=536982efee1e20650b3620e004ebd2e3865cd7a30207ac297e268753b1d08a5b resulted in changeOutputs=1 and spentUTXOs=1
[info] 2021-06-21T16:34:57UTC INFO [HikariDataSource] bitcoin-s-node-db - Starting...
[info] 2021-06-21T16:34:57UTC INFO [HikariDataSource] bitcoin-s-node-db - Start completed.
[info] 2021-06-21T16:35:00UTC INFO [DataMessageHandler] Received maximum amount of headers in one header message. This means we are not synced, requesting more
[info] 2021-06-21T16:35:00UTC INFO [DataMessageHandler] Got 2000 compact filter header hashes
[info] 2021-06-21T16:35:22UTC INFO [ActorSystemImpl] Request timeout encountered for request [POST / Strict(140 bytes)]
[info] 2021-06-21T16:35:27UTC INFO [Server] Unhandled error in server:
[info] java.lang.RuntimeException: Error broadcasting transaction Vector(536982efee1e20650b3620e004ebd2e3865cd7a30207ac297e268753b1d08a5b), peer is disconnected Peer(neutrino.testnet3.suredbits.com/34.210.154.40:18333)
[info]  at org.bitcoins.node.Node.$anonfun$broadcastTransactions$9(Node.scala:241)
[info]  at org.bitcoins.node.Node.$anonfun$broadcastTransactions$9$adapted(Node.scala:233)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by benthecarman** [comment]
It says it fails because you're not connected to the peer? Maybe an unrelated error

**Comment by Christewart** [comment]
Ben's right, this error is unrelated.
