### ISSUE TITLE
TorController cannot connect

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3547]
Stack trace from a user on bbd3cd2b

I've seen very similar errors from other users as well

>2021-08-13T16:45:16UTC INFO [LandingPaneModel] Writing bundle config to /Users/mateuszfaltyn/.bitcoin-s/bitcoin-s-bundle.conf
2021-08-13T16:45:16UTC INFO [BitcoinSServerMain] version=1.7.0-87-bbd3cd2b-SNAPSHOT
2021-08-13T16:45:17UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
2021-08-13T16:45:17UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/mateuszfaltyn/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2021-08-13T16:45:17UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.026s)
2021-08-13T16:45:17UTC INFO [DbMigrate] Current version of schema "main": 2
2021-08-13T16:45:17UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:17UTC INFO [DLCAppConfig] Applied 0 to the dlc project
2021-08-13T16:45:17UTC INFO [BitcoinSServerMain] Start on network MainNet
2021-08-13T16:45:17UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/mateuszfaltyn/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2021-08-13T16:45:17UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.014s)
2021-08-13T16:45:17UTC INFO [DbMigrate] Current version of schema "main": 10
2021-08-13T16:45:17UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:18UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/mateuszfaltyn/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2021-08-13T16:45:18UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.003s)
2021-08-13T16:45:18UTC INFO [DbMigrate] Current version of schema "main": 2
2021-08-13T16:45:18UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:18UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/mateuszfaltyn/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2021-08-13T16:45:18UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.010s)
2021-08-13T16:45:18UTC INFO [DbMigrate] Current version of schema "main": 6
2021-08-13T16:45:18UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:18UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2021-08-13T16:45:18UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2021-08-13T16:45:19UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, /Users/mateuszfaltyn/.bitcoin-s/tor/osx_64/tor
2021-08-13T16:45:19UTC INFO [TorClient$] Using tor daemon already written to datadir=/Users/mateuszfaltyn/.bitcoin-s/tor
2021-08-13T16:45:19UTC INFO [BitcoinSServerMain] Chain work already calculated
2021-08-13T16:45:19UTC INFO [BitcoinSServerMain] Using fee provider: MempoolSpaceProvider(HourFeeTarget,MainNet,Some(Socks5ProxyParams(127.0.0.1/<unresolved>:9050,None,true)))
2021-08-13T16:45:20UTC INFO [BitcoinSServerMain] Initialized chain api
2021-08-13T16:45:20UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2021-08-13T16:45:20UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2021-08-13T16:45:20UTC INFO [DLCAppConfig$] Using pre-existing wallet
2021-08-13T16:45:20UTC INFO [BitcoinSServerMain] Done configuring wallet, it took=1527ms
2021-08-13T16:45:20UTC INFO [BitcoinSServerMain] Done configuring node, it took=1535ms
2021-08-13T16:45:20UTC INFO [NeutrinoNode] Starting node
2021-08-13T16:45:20UTC INFO [P2PClientActor] connecting to SOCKS5 proxy 127.0.0.1/<unresolved>:9050
2021-08-13T16:45:20UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.007s)
2021-08-13T16:45:20UTC INFO [DbMigrate] Current version of schema "main": 6
2021-08-13T16:45:20UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:20UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.002s)
2021-08-13T16:45:20UTC INFO [DbMigrate] Current version of schema "main": 2
2021-08-13T16:45:20UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:20UTC INFO [P2PClientActor] connected to SOCKS5 proxy /127.0.0.1:9050
2021-08-13T16:45:20UTC INFO [P2PClientActor] connecting to neutrino.suredbits.com/<unresolved>:8333 via SOCKS5 /127.0.0.1:9050
2021-08-13T16:45:21UTC INFO [P2PClientActor] connected to neutrino.suredbits.com/<unresolved>:8333 via SOCKS5 proxy /127.0.0.1:9050
2021-08-13T16:45:21UTC INFO [PeerMessageReceiver] Connection established with peer=Peer(neutrino.suredbits.com:8333)
2021-08-13T16:45:22UTC INFO [NeutrinoNode] Our peer=Peer(neutrino.suredbits.com:8333) has been initialized
2021-08-13T16:45:22UTC INFO [NeutrinoNode] Our node has been full started. It took=1893ms
2021-08-13T16:45:22UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000000000506b84f7a44e66433001c1dc6a5ed9e76ce52f48a94d9 at height 694962, with 694962 filter headers and 694962 filters
2021-08-13T16:45:22UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
2021-08-13T16:45:22UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.011s)
2021-08-13T16:45:22UTC INFO [DbMigrate] Current version of schema "main": 10
2021-08-13T16:45:22UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-13T16:45:23UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: true
2021-08-13T16:45:24UTC ERROR [TorController] Cannot connect
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$4(TcpOutgoingConnection.scala:111)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:111)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
2021-08-13T16:47:36UTC INFO [P2PClientActor] We've been disconnected by Peer(neutrino.suredbits.com:8333) command=PeerClosed

**Comment by rorp** [comment]
What address it cannot connect?
