### ISSUE TITLE
NoSuchFileException: .bitcoin-s/tor/TorLogs.txt

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3556]
This was introduced in #3549 and doesn't work on mac according to @user411

My guesses 

1. The log file is getting created after we call `.start()` and we check if it exists too soon causing a race condition
2. the log file is different on mac?

**Comment by Christewart** [comment]
My logs when reproducing 

>2021-08-16T20:27:13UTC INFO [LandingPaneModel] Writing bundle config to /Users/chris/.bitcoin-s/bitcoin-s-bundle.conf
2021-08-16T20:27:13UTC INFO [BitcoinSServerMain] version=1.7.0-90-6a66f9bf-20210816-1513-SNAPSHOT
2021-08-16T20:27:13UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
2021-08-16T20:27:13UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/chris/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2021-08-16T20:27:13UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.008s)
2021-08-16T20:27:13UTC INFO [DbMigrate] Current version of schema "main": 2
2021-08-16T20:27:13UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-16T20:27:13UTC INFO [DLCAppConfig] Applied 0 to the dlc project
2021-08-16T20:27:13UTC INFO [BitcoinSServerMain] Start on network MainNet
2021-08-16T20:27:13UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/chris/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2021-08-16T20:27:13UTC INFO [DbValidate] Successfully validated 10 migrations (execution time 00:00.002s)
2021-08-16T20:27:13UTC INFO [DbMigrate] Current version of schema "main": 10
2021-08-16T20:27:13UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-16T20:27:13UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, /Users/chris/.bitcoin-s/tor/osx_64/tor
2021-08-16T20:27:13UTC INFO [TorClient$] Tor executable is not written to datadir /Users/chris/.bitcoin-s/tor, creating...
2021-08-16T20:27:13UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, /Users/chris/.bitcoin-s/tor/osx_64/tor
2021-08-16T20:27:13UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/chris/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2021-08-16T20:27:13UTC INFO [DbValidate] Successfully validated 2 migrations (execution time 00:00.001s)
2021-08-16T20:27:13UTC INFO [DbMigrate] Current version of schema "main": 2
2021-08-16T20:27:13UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-16T20:27:13UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/Users/chris/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2021-08-16T20:27:13UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.002s)
2021-08-16T20:27:13UTC INFO [DbMigrate] Current version of schema "main": 6
2021-08-16T20:27:13UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2021-08-16T20:27:13UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2021-08-16T20:27:13UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2021-08-16T20:27:13UTC ERROR [BitcoinSServerMain] Failed to startup server!
java.nio.file.NoSuchFileException: /Users/chris/.bitcoin-s/tor/TorLogs.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at java.base/java.nio.file.Files.lines(Files.java:4038)
	at java.base/java.nio.file.Files.lines(Files.java:4130)
	at org.bitcoins.tor.config.TorAppConfig.checkIfLogExists(TorAppConfig.scala:81)
	at org.bitcoins.tor.config.TorAppConfig.$anonfun$isBinaryFullyStarted$1(TorAppConfig.scala:76)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-08-16T20:27:13UTC ERROR [BitcoinSServerMain] Failed to initialize configuration for BitcoinServerMain
java.nio.file.NoSuchFileException: /Users/chris/.bitcoin-s/tor/TorLogs.txt
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at java.base/java.nio.file.Files.lines(Files.java:4038)
	at java.base/java.nio.file.Files.lines(Files.java:4130)
	at org.bitcoins.tor.config.TorAppConfig.checkIfLogExists(TorAppConfig.scala:81)
	at org.bitcoins.tor.config.TorAppConfig.$anonfun$isBinaryFullyStarted$1(TorAppConfig.scala:76)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:672)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
