### ISSUE TITLE
NeutrinoNodeWithWalletTest rescan information org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_FOREIGNKEY]

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3617]
When trying to solve for #3000 I came across another exception being caused in the `NeutrinoNodeWithWalletTest` suite

https://github.com/bitcoin-s/bitcoin-s/pull/3615/checks?check_run_id=3445903629#step:5:2142

![Screenshot from 2021-08-27 13-26-13](https://user-images.githubusercontent.com/3514957/131172534-6116c383-b182-4a41-8a8d-76c2f7791965.png)

Here are some relevant logs I believe from CI: 

It seems like the wallet tables do not exist?

>18:15:36.213 ERROR Wallet$WalletImpl - Error processing of block=43a5b129568bc4c192c80a9351b6fbbafb76d3725c312fc9c72d431e1beb0c3f.
java.sql.SQLException: Unexpected result: Cannot upsert either a UTXO or a SPK record for SegwitV0SpendingInfo(TransactionOutPoint(55d81ba89e719eff692e879ead16c81e179e66d82b637c7298244d4034ffc353:1),TransactionOutput(300000000 sats,wpkh(d00b7092c4688e22396609cba5fe2574ae7c65cf)),m/84'/1'/0'/0/2,P2WPKHWitnessV0(List(0355fbb2755ad989eb6b8fd6fc03261641ab66fc78bd272aefd3c7cdb8f2aedbfa, )),DoubleSha256BDigestBE(55d81ba89e719eff692e879ead16c81e179e66d82b637c7298244d4034ffc353),ConfirmedReceived,None,Some(1))
	at org.bitcoins.wallet.models.SpendingInfoDAO.$anonfun$upsert$10(SpendingInfoDAO.scala:172)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
18:15:36.214 ERROR DataMessageHandler - onBlockReceived Callback failed with error: 
java.sql.SQLException: Unexpected result: Cannot upsert either a UTXO or a SPK record for SegwitV0SpendingInfo(TransactionOutPoint(55d81ba89e719eff692e879ead16c81e179e66d82b637c7298244d4034ffc353:1),TransactionOutput(300000000 sats,wpkh(d00b7092c4688e22396609cba5fe2574ae7c65cf)),m/84'/1'/0'/0/2,P2WPKHWitnessV0(List(0355fbb2755ad989eb6b8fd6fc03261641ab66fc78bd272aefd3c7cdb8f2aedbfa, )),DoubleSha256BDigestBE(55d81ba89e719eff692e879ead16c81e179e66d82b637c7298244d4034ffc353),ConfirmedReceived,None,Some(1))
	at org.bitcoins.wallet.models.SpendingInfoDAO.$anonfun$upsert$10(SpendingInfoDAO.scala:172)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
18:15:36.215 INFO DataMessageHandler - Received block message with hash 03532c7507c0568fe66f37fd1e9011ce2c464eb31c1d5ce9cbde10852d162949
18:15:36.215 ERROR SafeDatabase - Error when executing query SynchronousDatabaseAction.Fused
18:15:36.217 ERROR SafeDatabase - org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_FOREIGNKEY]  A foreign key constraint failed (FOREIGN KEY constraint failed)

**Comment by Christewart** [comment]
Some more context on this with this log: https://github.com/Christewart/bitcoin-s-core/blob/9a18eb237754b5165f5de26e794bdbfba94ec268/wallet/src/main/scala/org/bitcoins/wallet/models/SpendingInfoDAO.scala#L172


>01:34:56.500 ERROR DataMessageHandler - onBlockReceived Callback failed with error: 
java.sql.SQLException: Unexpected result: (None,Some(ScriptPubKeyDb(wpkh(79b992bd391cbc252495d6e85e3194e60546e1d6),Some(4)))) Cannot upsert either a UTXO or a SPK record for SegwitV0SpendingInfo(TransactionOutPoint(6928f3b84b1ede8b2a7fcda60fd0c4d705cc3dcfba05fe2132faf61cb7a1dff3:1),TransactionOutput(20000000 sats,wpkh(79b992bd391cbc252495d6e85e3194e60546e1d6)),m/84'/1'/1'/0/0,P2WPKHWitnessV0(List(03e5c39bdf8b8bac58b8a6a9fe4f283c761fe6b51aab2aa67a9d64b13e44e759ba, )),DoubleSha256BDigestBE(6928f3b84b1ede8b2a7fcda60fd0c4d705cc3dcfba05fe2132faf61cb7a1dff3),ConfirmedReceived,None,Some(4))

So it appears the `utxo` is not getting inserted somehow.
