### ISSUE TITLE
Unable to resolve onion address with dlc node

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3637]
This is happening on f2a28741 when connecting my macbook with my desktop node. The macbook is unable to resolve the onion address for my desktop. This happens after i take my offer from my desktop and my desktops onion address and try to accept the DLC from my macbook.

It does seem like tor is running fine on my macbook and desktop, the process is running on both.

This is from my macbook
 
<img width="1431" alt="Screen Shot 2021-08-31 at 10 50 18 AM" src="https://user-images.githubusercontent.com/3514957/131534958-24a40dd8-7662-4639-80e8-0f3702c8bd6c.png">

>2021-08-31T15:33:47UTC INFO [Server] Unhandled error in server:
java.net.UnknownHostException: dmqnyzfhdeq4tdgnl7jtnrmwsklyzhf4lsbmwufmz3pzzongzxd3ilyd.onion
	at akka.io.dns.DnsProtocol$Resolved.address(DnsProtocol.scala:107)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Christewart** [comment]
@benthecarman pointed out on slack that it looked like my tor proxy was not enabled. This is because on the startup screen i didn't check the tor checkbox as i was connecting to a locally running neutrino node

<img width="1431" alt="Screen Shot 2021-08-31 at 10 56 56 AM" src="https://user-images.githubusercontent.com/3514957/131536180-ade7f04e-593f-4367-9a5a-809147de5429.png">

Checking this box fixed the problem for me.
