### ISSUE TITLE
Cannot open krystal bull after merging master xpub

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3681]
I am running on 48213d9b81d52ddfaa98577640fe527f4fa4678e which added checks for the master xpub on server startup

I am attempting to start my oracle server that references my krystal bull datadir (`$HOME/.krystal-bull/`)

>./bitcoin-s-oracle-server --datadir $HOME/.krystal-bull

and i get this error

>2021-09-21T14:43:05UTC ERROR [OracleServerMain] Failed to startup server!
java.lang.RuntimeException: org.bitcoins.keymanager.ReadMnemonicError$DecryptionError$: Could not decrypt mnemonic!
        at scala.sys.package$.error(package.scala:27)
        at org.bitcoins.dlc.oracle.config.DLCOracleAppConfig.$anonfun$initializeKeyManager$1(DLCOracleAppConfig.scala:149)
        at org.bitcoins.dlc.oracle.config.DLCOracleAppConfig.$anonfun$initializeKeyManager$1$adapted(DLCOracleAppConfig.scala:144)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Christewart** [comment]
This was unrelated and not a bug
