### ISSUE TITLE
java.lang.RuntimeException: Request failed: requirement failed: Error, no oracles used

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3686]
**Describe the bug**
After starting via `bundle/run` on 911fd342 I get an error on startup that is logged everytime we query the backend dlc wallet to update dlc status state. I also have no dlcs in my table on startup.

It seems we have a bug around casting a transactions inside of the `DLCTransactionProcessing`. I'm not sure how can get a base transaction in this flow though, the txid was [`3f929128e70d4186a194a35c5062263938526015e1ead85a453bd5cf71b7b9b9`](https://mempool.space/tx/3f929128e70d4186a194a35c5062263938526015e1ead85a453bd5cf71b7b9b9)

>2021-09-11T22:48:45UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=700105, stopBlockHash=00000000000000000008b05b8ed352c360524f74cd2c70653427142c79331966)
2021-09-11T22:48:45UTC INFO [DataMessageHandler] We are synced
2021-09-11T22:48:45UTC INFO [DataMessageHandler] Processing 1 filters
2021-09-11T22:49:04UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 3f929128e70d4186a194a35c5062263938526015e1ead85a453bd5cf71b7b9b9 for 1 DLC(s)
2021-09-11T22:49:05UTC ERROR [DataMessageHandler] onTxReceived Callback failed with error: 
java.lang.ClassCastException: class org.bitcoins.core.protocol.transaction.BaseTransaction cannot be cast to class org.bitcoins.core.protocol.transaction.WitnessTransaction (org.bitcoins.core.protocol.transaction.BaseTransaction and org.bitcoins.core.protocol.transaction.WitnessTransaction are in unnamed module of loader 'app')
	at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.$anonfun$calculateAndSetOutcome$16(DLCTransactionProcessing.scala:97)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2021-09-11T22:49:09UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
	at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1439)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2021-09-11T22:49:09UTC ERROR [WalletGUIModel] Error fetching accounting
java.lang.RuntimeException: Request failed: requirement failed: Error, no oracles used
	at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:1596)
	at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:1949)
	at scala.util.Try$.apply(Try.scala:210)
	at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:1891)
	at org.bitcoins.gui.WalletGUIModel.org$bitcoins$gui$WalletGUIModel$$updateWalletAccounting(WalletGUIModel.scala:172)
	at org.bitcoins.gui.WalletGUIModel$UpdateWalletInfoRunnable$.$anonfun$run$1(WalletGUIModel.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scalafx.application.Platform$$anon$1.run(Platform.scala:148)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
2021-09-11T22:49:09UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
	at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1439)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2021-09-11T22:49:09UTC ERROR [TaskInvocation] Request failed: requirement failed: Error, no oracles used
java.lang.RuntimeException: Request failed: requirement failed: Error, no oracles used
	at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:1596)
	at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:1949)
	at scala.util.Try$.apply(Try.scala:210)
	at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:1891)
	at org.bitcoins.gui.dlc.DLCPaneModel.$anonfun$getDLCs$1(DLCPaneModel.scala:43)
	at org.bitcoins.core.util.FutureUtil$.$anonfun$makeAsync$1(FutureUtil.scala:103)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2021-09-11T22:49:19UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
	at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
	at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1439)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)

<img width="1274" alt="Screen Shot 2021-09-22 at 5 54 36 PM" src="https://user-images.githubusercontent.com/3514957/134432869-6467d1b0-5a1a-422f-8bf6-7c2eea3a1d0f.png">

**Comment by Christewart** [comment]
So this is the raw hex for the tx `3f929128e70d4186a194a35c5062263938526015e1ead85a453bd5cf71b7b9b9`

>020000000001016baefa7c71b18e8f46100d56ef88c6e1fd8920c4fcda08417c5644db58de654c0100000000feffffff01400d030000000000160014e49eebc00d906a600d0843edb91e397fa3027ec4040047304402203e259c359bee8d8fe0572149ebc027173784d3b11b2f35973255b56ceb19dc1b022045dd4a9971398ddc139d5281d26402d4724b277ad6223f09cdaf48dd389d0f9b01473044022054658972cbddbd2c198b72d6f24e348ed3ab3b93e56b161abd6ede9add5c72e2022060980a31f267ce404b8398ac85f3d88708b5ff84401ff349b9986e34165ce6ec0147522102d4f3a2163c77260eca590c2c91a26365f6e890ba6d73804708ae0bb1b4faf52f2102f20e68c812235817712b2246e91e1b7a27009bac2ebb9caf459a77003b10170a52ae00000000

this is what is in my `tx_table` on my wallet

>020000000001016baefa7c71b18e8f46100d56ef88c6e1fd8920c4fcda08417c5644db58de654c0100000000feffffff01400d030000000000160014e49eebc00d906a600d0843edb91e397fa3027ec4040047304402203e259c359bee8d8fe0572149ebc027173784d3b11b2f35973255b56ceb19dc1b022045dd4a9971398ddc139d5281d26402d4724b277ad6223f09cdaf48dd389d0f9b01473044022054658972cbddbd2c198b72d6f24e348ed3ab3b93e56b161abd6ede9add5c72e2022060980a31f267ce404b8398ac85f3d88708b5ff84401ff349b9986e34165ce6ec0147522102d4f3a2163c77260eca590c2c91a26365f6e890ba6d73804708ae0bb1b4faf52f2102f20e68c812235817712b2246e91e1b7a27009bac2ebb9caf459a77003b10170a52ae00000000

and it appears to get parsed as a `WitnessTransaction` in my console

![Screenshot from 2021-09-23 08-38-00](https://user-images.githubusercontent.com/3514957/134517203-3366cc5d-e50b-4ebc-a613-52f98b000534.png)

**Comment by Christewart** [comment]
### More context 

This occurred when my counterparty in the DLC claimed the DLC, which triggered [this `RemoteClaimed` code flow that lead to the error](https://github.com/bitcoin-s/bitcoin-s/blob/099e4469b449c3b45ebede031139e67ddf055fe6/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/internal/DLCTransactionProcessing.scala#L75). I have no idea how the transaction that our counterparty published is getting classified as a `BaseTransaction`. From what I can tell, the tx `3f929128e70d4186a194a35c5062263938526015e1ead85a453bd5cf71b7b9b9` can both be validly parsed as a `BaseTransaction` and a `WitnessTransaction`. The correct parsing is a `WitnessTransaction`, when attempting to parse as a `BaseTransaction` you get a bunch of crazy scriptpubkeys in the outputs that don't make sense. 

The question I cannot find the answer to, is how does this get read as a `BaseTransaction` coming out of the database. I've looked through the [`DbColumnMappers.txMapper` code](https://github.com/bitcoin-s/bitcoin-s/blob/48213d9b81d52ddfaa98577640fe527f4fa4678e/db-commons/src/main/scala/org/bitcoins/db/DbCommonsColumnMappers.scala#L242) for reading a tx from the database and cannot identify how this is happening.

### Workaround

I went to the `dlcdb.sqlite` database and manually updated 

1. `global_dlc_data` to add the [`aggregate_signature`](https://oracle.suredbits.com/announcement/ddcfc10c70fef5d23e066771b9d27021e3442b24878f3f0f66b7790182e29f41) posted on the explorer 
2. `dlc_announcements` to set the `used` column to `1` for my `announcement_id`
3. `oracle_nonces` to set the `OUTCOME=Raducanu` as indicated on the explorer

and then my wallet booted up ok with all my DLCs in the table view

**Comment by jharveyb** [comment]
This issue is still present on 1.8; I ran into it with a counterparty claiming the DLC, for a numeric contract with 7353 CETs. I'm running the server and wallet GUI separately.

The published CET:

https://blockstream.info/testnet/tx/99586b94df2956f990028340314b5daacd11a1b0ea1adee2f41925e90650ca68?expand

From server logs:

```
2021-10-21T18:00:09UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,64 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,7889 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:18UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 68ca5006e92519f4e2de1aeab0a111cdaa5d4b3140830290f95629df946b5899:0 amt=133250 sats
2021-10-21T18:00:18UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 68ca5006e92519f4e2de1aeab0a111cdaa5d4b3140830290f95629df946b5899:0 into DB
2021-10-21T18:00:18UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 99586b94df2956f990028340314b5daacd11a1b0ea1adee2f41925e90650ca68 for 1 DLC(s)
2021-10-21T18:00:19UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,84 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,92 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:19UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,79 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,139 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:19UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,67 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,432 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:19UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,64 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,7889 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:20UTC ERROR [DataMessageHandler] onTxReceived Callback failed with error: 
java.lang.ClassCastException: class org.bitcoins.core.protocol.transaction.BaseTransaction cannot be cast to class org.bitcoins.core.protocol.transaction.WitnessTransaction (org.bitcoins.core.protocol.transaction.BaseTransaction and org.bitcoins.core.protocol.transaction.WitnessTransaction are in unnamed module of loader 'app')
        at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.$anonfun$calculateAndSetOutcome$16(DLCTransactionProcessing.scala:97)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-10-21T18:00:29UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,84 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(200 OK,List(),HttpEntity.Strict(application/json,92 bytes total),HttpProtocol(HTTP/1.1)))
2021-10-21T18:00:29UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
        at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1439)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2021-10-21T18:00:29UTC INFO [ActorSystemImpl] http-rpc-server: Response for
  Request : HttpRequest(HttpMethod(POST),http://localhost:10000/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.11, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,79 bytes total),HttpProtocol(HTTP/1.1))
  Response: Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(application/json,84 bytes total),HttpProtocol(HTTP/1.1)))
```

**Comment by Christewart** [comment]
Follow up with script templates for fixing this 

Obtain `closing_tx_id` from the log, use that `closing_tx_id` to find it's parent txid (`funding_tx_id`)

>update global_dlc_data set aggregate_signature=? where funding_tx_id=?

> select dlc_id from global_dlc_data where funding_tx_id=?

use the `dlc_id` in the next step.

>update dlc_announcements set used=1 where dlc_id=?

>select announcement_id from dlc_announcements where dlc_id=?

now use that `announcement_id` here:

>update oracle_nonces SET outcome=? where announcement_id=?

**Comment by Christewart** [comment]
done in #3829
