### ISSUE TITLE
bitcoind backend does not update confirmations properly on mac

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3695]
This is running on 2191eb20 on my macbook with a sqlite database. 

I did a DLC with funding txid `5d81ad28079abc2713f8c98518cbeb423284e22024d196e9fb1bc3adfc67cbb3` which has one confirmation on it. 

My desktop wallet says that the status is `CONFIRMED` whereas my macbook still has the status of the transaction as `BROADCAST`. 

My macbook: 

<img width="1274" alt="Screen Shot 2021-09-27 at 9 28 35 AM" src="https://user-images.githubusercontent.com/3514957/134928553-d1122c7c-1f81-4bab-9063-f9833c851f97.png">

also my bitcoind on my macbook HAS seen the transaction (we broadcast via this bitcoind) and it has one confirmation on it

<img width="1299" alt="Screen Shot 2021-09-27 at 9 30 03 AM" src="https://user-images.githubusercontent.com/3514957/134928858-983a7078-c738-43cc-be8e-c5df10f91fa5.png">

here are the logs i see on my macbook: 

>2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] DLC 705478661ec9e57733cf9247860a9ed2c8f7926a92a098226bd354dcadfde296 sigs are verified and stored, ready to broadcast
2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] Created funding transaction 5d81ad28079abc2713f8c98518cbeb423284e22024d196e9fb1bc3adfc67cbb3 for contract 705478661ec9e57733cf9247860a9ed2c8f7926a92a098226bd354dcadfde296
2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] Broadcasting funding transaction 5d81ad28079abc2713f8c98518cbeb423284e22024d196e9fb1bc3adfc67cbb3 for contract 705478661ec9e57733cf9247860a9ed2c8f7926a92a098226bd354dcadfde296
2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: b3cb67fcadc31bfbe996d12420e2843242ebcb1885c9f81327bc9a0728ad815d:1 amt=14262870 sats
2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO b3cb67fcadc31bfbe996d12420e2843242ebcb1885c9f81327bc9a0728ad815d:1 into DB
2021-09-27T14:00:36UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 5d81ad28079abc2713f8c98518cbeb423284e22024d196e9fb1bc3adfc67cbb3 for 1 DLC(s)
2021-09-27T14:11:43UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=59s476ms).
2021-09-27T14:11:47UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=59s480ms).
2021-09-27T14:11:48UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=59s474ms).
2021-09-27T14:24:44UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=12m31s813ms).
2021-09-27T14:24:49UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=12m31s814ms).
2021-09-27T14:24:50UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=12m31s817ms).

Perhaps it is something to do with the thread starvation warnings?

**Comment by Christewart** [comment]
here is what i see on the other side of the DLC (offerer) from my desktop running on 2191eb20

It appears that the state of the DLC got updated properly to `CONFIRMED` since the funding tx does have one confirmation on it now.

![Screenshot from 2021-09-27 09-31-21](https://user-images.githubusercontent.com/3514957/134929167-6b8193f0-426d-48a8-b74c-1c3fd864387c.png)

Logs: 

>2021-09-27T14:21:46UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000059daca216cb3a4c2ef933026c3c0b2dd0e58da6287656
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: b3cb67fcadc31bfbe996d12420e2843242ebcb1885c9f81327bc9a0728ad815d:0 amt=48723626 sats
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO b3cb67fcadc31bfbe996d12420e2843242ebcb1885c9f81327bc9a0728ad815d:0 into DB
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 5d81ad28079abc2713f8c98518cbeb423284e22024d196e9fb1bc3adfc67cbb3 for 1 DLC(s)
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000059daca216cb3a4c2ef933026c3c0b2dd0e58da6287656. It took 6514ms
2021-09-27T14:21:52UTC INFO [DLCWallet$DLCWalletImpl] 2 txos are now confirmed!

**Comment by Christewart** [comment]
One very frustrating thing about trying to track this down is it appears that visualvm doesn't work with m1 cpus. I'm still trying to figure out how to get monitoring tools working on m1

**Comment by Christewart** [comment]
So i tried starting up my node again this morning, and it appears I'm having more issues. It seems that no syncing is happening between bitcoind and my wallet. I am running the bitcoind node locally on my macbook.

<img width="1434" alt="Screen Shot 2021-09-28 at 11 02 54 AM" src="https://user-images.githubusercontent.com/3514957/135124099-4d28c3cf-1c49-4ddb-b807-b961015dcff6.png">
<img width="1434" alt="Screen Shot 2021-09-28 at 11 03 05 AM" src="https://user-images.githubusercontent.com/3514957/135124105-34697385-e46d-4fd0-805e-b0116b7a99a2.png">

If you look at the second image, you can see the `Deribit-BTC-28SEP21` announcement is still in the `BROADCAST` state and you can also see that my wallet's sync height is `700,213` which means my wallet is missing roughly ~2,000 blocks. The current block height as of this writing is `702,608` according to the bitcoind my bitcoin-s wallet is connected to

**Comment by Christewart** [comment]
This is very weird, so looking at the logs closer, it does appear that we are connected to bitcoind. There is this key line in the logs

>2021-09-28T17:23:03UTC INFO [BitcoindRpcBackendUtil$] Syncing from 700213 to 702616

but my sync height does not get updated in the wallet! It stays at `700,213`. That means there must be some sort of exception being swallowed after this log line

https://github.com/bitcoin-s/bitcoin-s/blob/132479d2716a6861905ec870b3c048d37aaf8cca/app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala#L78

**Comment by Christewart** [comment]
I'm guessing there is an exception thrown when calling out to bitcoind.

https://github.com/bitcoin-s/bitcoin-s/blob/132479d2716a6861905ec870b3c048d37aaf8cca/app/server/src/main/scala/org/bitcoins/server/BitcoindRpcBackendUtil.scala#L80-L88


The reason this error isn't getting propagated is because we aren't flatMaping on the future returned by `BitcoindRpcBackendUtil.syncWalletToBitcoind()` here

https://github.com/bitcoin-s/bitcoin-s/blob/2191eb2049f2ecfc0f8482fb65cbc9aa60b27752/app/server/src/main/scala/org/bitcoins/server/BitcoinSServerMain.scala#L213

so if there is an exception thrown, we swallow it. Originally we choose to not wait for this to complete because syncing the wallet to bitcoind could take a long time, we didn't want to wait for the server to bind to the socket until the wallet is done syncing against bitcoind.

**Comment by Christewart** [comment]
Finally got the exception causing this: 

>2021-09-28T17:56:19UTC INFO [BitcoindRpcBackendUtil$] Syncing from 700213 to 702617
2021-09-28T17:56:19UTC ERROR [BitcoinSServerMain] Error syncing bitcoin-s wallet with bitcoind
java.util.concurrent.ExecutionException: Boxed Exception
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolve(Promise.scala:99)
	at scala.concurrent.impl.Promise$Transformation.handleFailure(Promise.scala:408)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
	at org.bitcoins.rpc.client.common.BitcoindRpcClient.getFilter(BitcoindRpcClient.scala:214)
	at org.bitcoins.server.BitcoindRpcBackendUtil$.doSync(BitcoindRpcBackendUtil.scala:84)
	at org.bitcoins.server.BitcoindRpcBackendUtil$.$anonfun$syncWalletToBitcoind$3(BitcoindRpcBackendUtil.scala:62)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	... 12 common frames omitted
2021-09-28T17:56:19UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: true
2021-09-28T17:56:20UTC INFO [TorProtocolHandler] Tor version 0.4.5.7
2021-09-28T17:56:20UTC INFO [DLCServer] Bound at /[0:0:0:0:0:0:0:0]:2862
2021-09-28T17:56:20UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2021-09-28T17:56:20UTC INFO [BitcoinSServerMain] Done starting Main!
2021-09-28T17:56:20UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
2021-09-28T17:56:20UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
