### ISSUE TITLE
`executedlc` doesn't work when funding tx is in mempool with bitcoind backend

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3715]
I'm running on  961f113c28dd8029706b78da274611bcdc1b8d24  trying to do #3631 

I'm at the final step of executing my DLC. I'm using bitcoind as a backend. My funding transaction is still in the mempool as of this writing. The txid of the funding tx is [`0d74896958cee0b142a189211cac215f9f0455462290966d65ebf9fb1865de91`](https://mempool.space/tx/0d74896958cee0b142a189211cac215f9f0455462290966d65ebf9fb1865de91). 

I attempted to close the DLC with this command: 

```
./bitcoin-s-cli executedlc a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439  fdd8688010323032302d75732d656c656374696f6ed3b04a6d7b90c9c43c09ebe5250d583e1c3fc423219b26f6a02ec394a130000a0001ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1447a59ba58797e55b967aa79c89ffec67023578009c4dc1e3dee2fd75277993590c44656d6f637261745f77696e
Request failed: Error -26: non-final
```

This appears to be coming from my bitcoind (`0.21.1`), here are the logs

```
[info] 2021-10-03T22:03:04UTC INFO [DLCWallet$DLCWalletImpl] Executing dlc with contractId=a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439 sigs=Vector(fdd8688010323032302d75732d656c656374696f6ed3b04a6d7b90c9c43c09ebe5250d583e1c3fc423219b26f6a02ec394a130000a0001ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1447a59ba58797e55b967aa79c89ffec67023578009c4dc1e3dee2fd75277993590c44656d6f637261745f77696e)
[info] 2021-10-03T22:03:05UTC INFO [DLCWallet$DLCWalletImpl] Created DLC execution transaction 3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1 for contract a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439
[info] 2021-10-03T22:03:05UTC INFO [DLCWallet$DLCWalletImpl] Updating DLC (a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439) closing txId to txIdBE=3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1
[info] 2021-10-03T22:03:05UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1 for 1 DLC(s)
[info] 2021-10-03T22:03:05UTC INFO [DLCWallet$DLCWalletImpl] Deleting unneeded DLC signatures for contract a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439
[info] 2021-10-03T22:03:05UTC ERROR [BitcoindV21RpcClient] org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: non-final
[info] 2021-10-03T22:03:05UTC INFO [Server] Unhandled error in server:
[info] org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: non-final
[info]  at org.bitcoins.rpc.BitcoindException$.$anonfun$all$12(BitcoindException.scala:57)
[info]  at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
[info]  at scala.Option.map(Option.scala:242)
[info]  at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
[info]  at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
[info]  at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
[info]  at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
[info]  at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
[info]  at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
[info]  at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
[info]  at play.api.libs.json.JsValue.validate(JsValue.scala:17)
[info]  at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
[info]  at play.api.libs.json.JsObject.validate(JsValue.scala:126)
[info]  at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
[info]  at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
[info]  at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
[info]  at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:438)
[info]  at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

It looks like this is something to do with the fact the funding transaction is unconfirmed. I broadcast the funding transaction from the same wallet i'm attempting to broadcast the CET from.

**Comment by Christewart** [comment]
Even though this DLC failed to broadcast, it appears that my internal DLC wallet state got updated. The closing tx that failed to broadcast was `3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1`

```
  {
    "state": "Claimed",
    "dlcId": "2f1224d3ab1f2456d020e7777009153e2ee5db2d127b94774580e428f5a899b9",
    "isInitiator": false,
    "lastUpdated": "2021-10-03T22:03:05.556Z",
    "tempContractId": "a4e127a34eb1fc998018bfc4a7e1a6943f6588d765b1e36ca6b9c7cc67b7eaa8",
    "contractId": "a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439",
    "contractInfo": "fdd82efd011200000000000186a0fda7103b030e52657075626c6963616e5f77696e00000000000000000c44656d6f637261745f77696e00000000000186a0056f74686572000000000000ea60fda712c7fdd824c3988fabec9820690f366271c9ceac00fbec1412075f9b319bb0db1f86460519dd9c61478949f2c00c35aeb8e53a1507616072cb802891e2c189a9fa65a0493de5d3b04a6d7b90c9c43c09ebe5250d583e1c3fc423219b26f6a02ec394a130000afdd8225f0001ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1460189600fdd8062400030e52657075626c6963616e5f77696e0c44656d6f637261745f77696e056f7468657210323032302d75732d656c656374696f6e",
    "contractMaturity": 704409,
    "contractTimeout": 705417,
    "feeRate": 1,
    "totalCollateral": 100000,
    "localCollateral": 40000,
    "remoteCollateral": 60000,
    "fundingTxId": "0d74896958cee0b142a189211cac215f9f0455462290966d65ebf9fb1865de91",
    "closingTxId": "3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1",
    "oracleSigs": [
      "ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1447a59ba58797e55b967aa79c89ffec67023578009c4dc1e3dee2fd7527799359"
    ],
    "outcomes": "Democrat_win",
    "oracles": [
      "fdd824c3988fabec9820690f366271c9ceac00fbec1412075f9b319bb0db1f86460519dd9c61478949f2c00c35aeb8e53a1507616072cb802891e2c189a9fa65a0493de5d3b04a6d7b90c9c43c09ebe5250d583e1c3fc423219b26f6a02ec394a130000afdd8225f0001ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1460189600fdd8062400030e52657075626c6963616e5f77696e0c44656d6f637261745f77696e056f7468657210323032302d75732d656c656374696f6e"
    ],
    "myPayout": 0,
    "counterPartyPayout": 100000,
    "pnl": -40000,
    "rateOfReturn": -1
  }
```

**Comment by Christewart** [comment]
it looks like this is related to lock times https://github.com/bitcoin/bitcoin/blob/6f0cbc75be7644c276650fd98bfdb6358b827399/src/validation.cpp#L586

**Comment by Christewart** [comment]
so i just tried to settle this again on my other wallet, and it also failed to broadcast the bitcoin transaction. I thought there might be a possibility that it would be valid now.

```
[info] 2021-10-08T23:26:52UTC INFO [BitcoindRpcBackendUtil$] We are synced!                                                                                                       
[info] 2021-10-08T23:26:52UTC INFO [TorProtocolHandler] Tor version 0.4.5.7                                                                                                       
[info] 2021-10-08T23:26:52UTC INFO [DLCServer] Bound at /[0:0:0:0:0:0:0:0]:2862                                                                                                   
[info] 2021-10-08T23:26:52UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999                                                                                      
[info] 2021-10-08T23:26:52UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...                                                                                              
[info] 2021-10-08T23:26:52UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.                                                                                         
[info] 2021-10-08T23:26:52UTC INFO [BitcoinSServerMain] Done starting Main!                                                                                                       
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Executing dlc with contractId=a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439 sigs=Vector(fdd8688010
323032302d75732d656c656374696f6ed3b04a6d7b90c9c43c09ebe5250d583e1c3fc423219b26f6a02ec394a130000a0001ae3e30df5a203ad10ee89a909df0c8ccea4836e94e0a5d34c3cdab758fcaee1447a59ba58797e5
5b967aa79c89ffec67023578009c4dc1e3dee2fd75277993590c44656d6f637261745f77696e)                                                                                                     
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Created DLC execution transaction 3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1 for contract a995a
eca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439                                                                                                                       
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Updating DLC (a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439) closing txId to txIdBE=3cad29be34216e
279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1                                                                                                                                
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: d1c47854273c6ab94ea01a4a0d24f8e3c496f25391f1139d276e2134be29ad3c:0 amt=100000 sats            
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO d1c47854273c6ab94ea01a4a0d24f8e3c496f25391f1139d276e2134be29ad3c:0 into DB                
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1 for 1 DLC(s)                          
[info] 2021-10-08T23:28:06UTC INFO [DLCWallet$DLCWalletImpl] Deleting unneeded DLC signatures for contract a995aeca167f1c28c2b936e5bb4d87cba061dd9147217501c3523e377fd23439       
[info] 2021-10-08T23:28:06UTC ERROR [BitcoindV21RpcClient] org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: non-final                                                
[info] 2021-10-08T23:28:06UTC INFO [Server] Unhandled error in server:                                                                                                            
[info] org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: non-final                                                                                                    
[info]  at org.bitcoins.rpc.BitcoindException$.$anonfun$all$12(BitcoindException.scala:57)                                                                                        
[info]  at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)                                                                          
[info]  at scala.Option.map(Option.scala:242)
```

**Comment by Christewart** [comment]
Here is the raw CET `3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1`

```
0200000000010191de6518fbf9eb656d9690224655049f5f21ac1c2189a142b1e0ce586989740d0100000000feffffff01a0860100000000001600141df0a84b2d2e611dd595101bfed6320143c47ebb04004730440220646d8f3f195e637fc4475dd11d877585381d551b4697e2abe8736ec5e1d30ef702205fc03eed9fb06d8ebfbb1206c48cc750b316dc231ddab9d8d65574ec0234bbc40147304402204b563bd1c9cc42f3341a395365d49e21674083fef46f65a33f7cb87fdd49eb4b02206a616cc4995f5a391ce6e7d249ead2e9b1ec8842325b11f4edb63687a3cc535b0147522102869f5d3931620521f3eef85c0e7adf64a4db330d2dfde3aa871172274f210fe02102ddac49d9514ba9bda03c72ecf15679c0fd85c197bfb9a59f2fd8c737dd4bdd1a52ae99bf0a00
```

decoded 

```
{
  "txid": "3cad29be34216e279d13f19153f296c4e3f8240d4a1aa04eb96a3c275478c4d1",
  "wtxid": "d0258134d187fed3c6ff0001c6e3c0e07458b2628b9a4d41d8a5634479065807",
  "version": 2,
  "size": 302,
  "vsize": 137,
  "weight": 548,
  "locktime": 704409,
  "vin": [
    {
      "txid": "0d74896958cee0b142a189211cac215f9f0455462290966d65ebf9fb1865de91",
      "hex": "91de6518fbf9eb656d9690224655049f5f21ac1c2189a142b1e0ce586989740d0100000000feffffff",
      "vout": 1,
      "scriptSig": [
        
      ],
      "txinwitness": {
        "hex": "04004730440220646d8f3f195e637fc4475dd11d877585381d551b4697e2abe8736ec5e1d30ef702205fc03eed9fb06d8ebfbb1206c48cc750b316dc231ddab9d8d65574ec0234bbc40147304402204b563bd1c9cc42f3341a395365d49e21674083fef46f65a33f7cb87fdd49eb4b02206a616cc4995f5a391ce6e7d249ead2e9b1ec8842325b11f4edb63687a3cc535b0147522102869f5d3931620521f3eef85c0e7adf64a4db330d2dfde3aa871172274f210fe02102ddac49d9514ba9bda03c72ecf15679c0fd85c197bfb9a59f2fd8c737dd4bdd1a52ae",
        "scriptType": "P2WSH",
        "script": [
          "OP_2",
          "BytesToPushOntoStackImpl(33)",
          "ByteVector(33 bytes, 0x02869f5d3931620521f3eef85c0e7adf64a4db330d2dfde3aa871172274f210fe0)",
          "BytesToPushOntoStackImpl(33)",
          "ByteVector(33 bytes, 0x02ddac49d9514ba9bda03c72ecf15679c0fd85c197bfb9a59f2fd8c737dd4bdd1a)",
          "OP_2",
          "OP_CHECKMULTISIG"
        ],
        "stack": [
          "304402204b563bd1c9cc42f3341a395365d49e21674083fef46f65a33f7cb87fdd49eb4b02206a616cc4995f5a391ce6e7d249ead2e9b1ec8842325b11f4edb63687a3cc535b01",
          "30440220646d8f3f195e637fc4475dd11d877585381d551b4697e2abe8736ec5e1d30ef702205fc03eed9fb06d8ebfbb1206c48cc750b316dc231ddab9d8d65574ec0234bbc401",
          ""
        ]
      },
      "sequence": 4294967294
    }
  ],
  "vout": [
    {
      "value": 100000,
      "n": 0,
      "scriptPubKey": [
        "OP_0",
        "BytesToPushOntoStackImpl(20)",
        "ByteVector(20 bytes, 0x1df0a84b2d2e611dd595101bfed6320143c47ebb)"
      ],
      "hex": "a0860100000000001600141df0a84b2d2e611dd595101bfed6320143c47ebb"
    }
  ]
}
```

**Comment by Christewart** [comment]
This locktime was manually set in the election example 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

https://bitcoin-s.org/docs/next/wallet/wallet-election-example#offer
