### ISSUE TITLE
`sendtoaddress` fails because rounding is necessary

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3751]
```
[info] 2021-10-13T19:17:20UTC INFO [DLCWallet$DLCWalletImpl] Sending 0.0035663618 BTC to 3PZXMMJctickpiTGjoiTorpRf6C3iUCpXk at feerate 8 sats/byte
[info] 2021-10-13T19:17:20UTC INFO [Server] Unhandled error in server:
[info] java.lang.ArithmeticException: Rounding necessary
[info]  at java.base/java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4621)
[info]  at java.base/java.math.BigDecimal.needIncrement(BigDecimal.java:4677)
[info]  at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4585)
[info]  at java.base/java.math.BigDecimal.setScale(BigDecimal.java:2891)
[info]  at java.base/java.math.BigDecimal.longValueExact(BigDecimal.java:3563)
[info]  at scala.math.BigDecimal.toLongExact(BigDecimal.scala:675)
[info]  at org.bitcoins.core.currency.Bitcoins.satoshis(CurrencyUnits.scala:151)
[info]  at org.bitcoins.core.currency.CurrencyUnit.$plus(CurrencyUnits.scala:49)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.$anonfun$accumulate$1(CoinSelector.scala:60)
[info]  at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
[info]  at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
[info]  at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulate(CoinSelector.scala:59)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulate$(CoinSelector.scala:55)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.accumulate(CoinSelector.scala:97)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulateLargest(CoinSelector.scala:37)
[info]  at org.bitcoins.core.api.wallet.CoinSelector.accumulateLargest$(CoinSelector.scala:30)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.accumulateLargest(CoinSelector.scala:97)
[info]  at org.bitcoins.core.api.wallet.CoinSelector$.selectByAlgo(CoinSelector.scala:123)
[info]  at org.bitcoins.wallet.internal.FundTransactionHandling.$anonfun$fundRawTransactionInternal$9(FundTransactionHandling.scala:88)
[info]  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] 2021-10-13T19:17:20UTC INFO [ActorSystemImpl] http-rpc-server: Response for
[info]   Request : HttpRequest(HttpMethod(POST),http://localhost:9999/,List(Timeout-Access: <function1>, Accept-Encoding: gzip, deflate, User-Agent: Java/11.0.9, Host, Accept: text/html, image/gif, image/jpeg, */*;q=0.2, */*;q=0.2, Connection: keep-alive),HttpEntity.Strict(application/json,140 bytes total),HttpProtocol(HTTP/1.1))
[info]   Response: Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(application/json,60 bytes total),HttpProtocol(HTTP/1.1)))
```

**Comment by Christewart** [comment]
So tired to do this from another wallet, and also encountered errors. I believe the conversion tool i used produces too many decimal points for the bitcoin currency unit: 

https://moneyexchangerate.org/currencyexchange/usd/btc/199

`0.0035663618` is what it gave me for $200

**Comment by Christewart** [comment]
It gave two decimals extra
