### ISSUE TITLE
DLC wallet rescan fails with an exception

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3957]
This occurred when initiaiting a rescan from the wallet-server-ui project. This was running with a neutrino backend on 524c5212e0e2206201fcdbec0bbd6e25c4e88012

### Logs

```
2022-01-03T19:06:09UTC INFO [DLCWallet$DLCWalletImpl] Starting rescanning the wallet from None to None
2022-01-03T19:06:21UTC INFO [DLCWallet$DLCWalletImpl] Beginning to search for matches between 681761:717050 against 241 spks
2022-01-03T19:06:22UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:22UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=681761 to end=681860
2022-01-03T19:06:23UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:23UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=681861 to end=681960
2022-01-03T19:06:23UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 681989
2022-01-03T19:06:23UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
2022-01-03T19:06:30UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000c0815ee0709331d2b0a10a4d73c09bc636e5e9966cdd7
2022-01-03T19:06:30UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000c0815ee0709331d2b0a10a4d73c09bc636e5e9966cdd7
2022-01-03T19:06:31UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000c0815ee0709331d2b0a10a4d73c09bc636e5e9966cdd7. It took 1288ms
2022-01-03T19:06:31UTC INFO [DLCWallet$DLCWalletImpl] Found 1 matches from start=681961 to end=682060
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682061 to end=682160
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682161 to end=682260
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682261 to end=682360
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682361 to end=682460
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682461 to end=682560
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:33UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682561 to end=682660
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682661 to end=682760
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682761 to end=682860
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:34UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682861 to end=682960
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=682961 to end=683060
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683061 to end=683160
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:35UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683161 to end=683260
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683261 to end=683360
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683361 to end=683460
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:36UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683461 to end=683560
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683561 to end=683660
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683661 to end=683760
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:37UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683761 to end=683860
2022-01-03T19:06:38UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:38UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683861 to end=683960
2022-01-03T19:06:38UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:38UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=683961 to end=684060
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684061 to end=684160
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684161 to end=684260
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:39UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684261 to end=684360
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684361 to end=684460
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684461 to end=684560
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 684564
2022-01-03T19:06:40UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
2022-01-03T19:06:47UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000089f0ff1c189a48b79f2220e7a243174c310884333ee22
2022-01-03T19:06:47UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000089f0ff1c189a48b79f2220e7a243174c310884333ee22
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 624aab4f7d0ac7968b706da1fadc2d59f2d4925c2e32070982c472b3c8fc050a:1 amt=25000000 sats
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 624aab4f7d0ac7968b706da1fadc2d59f2d4925c2e32070982c472b3c8fc050a:1 into DB
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=284ms
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: c4ddbb3f1ae1f2481f64baa47cc48ad218bc5d7b1514e2d0d68b03d29af15a0f:0 amt=50000000 sats
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO c4ddbb3f1ae1f2481f64baa47cc48ad218bc5d7b1514e2d0d68b03d29af15a0f:0 into DB
2022-01-03T19:06:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=145ms
2022-01-03T19:06:49UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000089f0ff1c189a48b79f2220e7a243174c310884333ee22. It took 2067ms
2022-01-03T19:06:49UTC INFO [DLCWallet$DLCWalletImpl] Found 1 matches from start=684561 to end=684660
2022-01-03T19:06:49UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:49UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684661 to end=684760
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684761 to end=684860
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684861 to end=684960
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:50UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=684961 to end=685060
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685061 to end=685160
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 685200
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 685175
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 685210
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 685211
2022-01-03T19:06:51UTC INFO [DLCWallet$DLCWalletImpl] Requesting 4 block(s)
2022-01-03T19:07:06UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000006b4d6cf73681e3e87e07558696ba9a6dd362aa86379d5
2022-01-03T19:07:06UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006b4d6cf73681e3e87e07558696ba9a6dd362aa86379d5
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 29373b52de8688aa12d8fface5140daea95b396937844a6304cc306906256f7c:2 amt=49934175 sats
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 29373b52de8688aa12d8fface5140daea95b396937844a6304cc306906256f7c:2 into DB
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 29373b52de8688aa12d8fface5140daea95b396937844a6304cc306906256f7c for 1 DLC(s)
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=243ms
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
2022-01-03T19:07:08UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 spent outputs, it took=167ms
2022-01-03T19:07:09UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000006b4d6cf73681e3e87e07558696ba9a6dd362aa86379d5. It took 2703ms
2022-01-03T19:07:19UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000005d76271da00b8833c1e6f69074d2bd93fcbc8a499fe3e
2022-01-03T19:07:19UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000005d76271da00b8833c1e6f69074d2bd93fcbc8a499fe3e
2022-01-03T19:07:20UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 2f4ce75d041920a0739dbfb9701c0c46e185227b020f3bdd7a176486d6a8b00e:0 amt=82640 sats
2022-01-03T19:07:20UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 2f4ce75d041920a0739dbfb9701c0c46e185227b020f3bdd7a176486d6a8b00e:0 into DB
2022-01-03T19:07:20UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=246ms
2022-01-03T19:07:20UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 2f4ce75d041920a0739dbfb9701c0c46e185227b020f3bdd7a176486d6a8b00e for 1 DLC(s)
2022-01-03T19:07:20UTC INFO [DLCWallet$DLCWalletImpl] Deleting unneeded DLC signatures for contract 13db8d94fc1802c02b49ee5cac936c9bd8e3570fb1d7e691ab8b4c700c5ead86
2022-01-03T19:07:21UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000005d76271da00b8833c1e6f69074d2bd93fcbc8a499fe3e. It took 1580ms
2022-01-03T19:07:25UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000065438330e26dd28ecd3d149a03c11037d68dc8505e184
2022-01-03T19:07:25UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000065438330e26dd28ecd3d149a03c11037d68dc8505e184
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: c4d9617c1a15532d469920cf5898ca5f2c0200291c06e881021f25dbafff71d9:17 amt=547 sats
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: c4d9617c1a15532d469920cf5898ca5f2c0200291c06e881021f25dbafff71d9:381 amt=547 sats
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO c4d9617c1a15532d469920cf5898ca5f2c0200291c06e881021f25dbafff71d9:17 into DB
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO c4d9617c1a15532d469920cf5898ca5f2c0200291c06e881021f25dbafff71d9:381 into DB
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 2 received outputs, it took=149ms
2022-01-03T19:07:26UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000065438330e26dd28ecd3d149a03c11037d68dc8505e184. It took 1416ms
2022-01-03T19:07:29UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000006174a20ca0f40006fd5942f3e92626f4855875b409476
2022-01-03T19:07:29UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006174a20ca0f40006fd5942f3e92626f4855875b409476
2022-01-03T19:07:30UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: d7474dae208f469b875c29baea244318c0d80006f9e3671eaeeabdfa42facdc0:0 amt=128236 sats
2022-01-03T19:07:30UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO d7474dae208f469b875c29baea244318c0d80006f9e3671eaeeabdfa42facdc0:0 into DB
2022-01-03T19:07:30UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=272ms
2022-01-03T19:07:31UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000006174a20ca0f40006fd5942f3e92626f4855875b409476. It took 1618ms
2022-01-03T19:07:31UTC INFO [DLCWallet$DLCWalletImpl] Found 4 matches from start=685161 to end=685260
2022-01-03T19:07:31UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:31UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685261 to end=685360
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685361 to end=685460
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685461 to end=685560
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:32UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685561 to end=685660
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685661 to end=685760
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685761 to end=685860
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 685960
2022-01-03T19:07:33UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
2022-01-03T19:07:40UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000008933d568ebba50d23871391bdd95f67bd9973929a743d
2022-01-03T19:07:40UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000008933d568ebba50d23871391bdd95f67bd9973929a743d
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: fe269ace93add8b728362b3e13efe7c7e8f2b64f8777fa065becf1667f8fcd9a:0 amt=531353 sats
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO fe269ace93add8b728362b3e13efe7c7e8f2b64f8777fa065becf1667f8fcd9a:0 into DB
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=216ms
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 17a32f9d1e093ddef7ea2ca8c38ed09aab641da402ffe9fe8c8abc60c2b79a11:0 amt=632134 sats
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 17a32f9d1e093ddef7ea2ca8c38ed09aab641da402ffe9fe8c8abc60c2b79a11:0 into DB
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=166ms
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000008933d568ebba50d23871391bdd95f67bd9973929a743d. It took 2082ms
2022-01-03T19:07:42UTC INFO [DLCWallet$DLCWalletImpl] Found 1 matches from start=685861 to end=685960
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=685961 to end=686060
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 686119
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 686147
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 686149
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 686138
2022-01-03T19:07:43UTC INFO [DLCWallet$DLCWalletImpl] Requesting 4 block(s)
2022-01-03T19:07:47UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000be32a07cadc0a1a083c3d1b2629a3e0fe02a9b2c95edd
2022-01-03T19:07:47UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000be32a07cadc0a1a083c3d1b2629a3e0fe02a9b2c95edd
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 8230ac027235bd470072f7db15e4c77f3c81bc25f4d638c4da8f787b9d9a9039:1 amt=602703 sats
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 8230ac027235bd470072f7db15e4c77f3c81bc25f4d638c4da8f787b9d9a9039:1 into DB
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 8230ac027235bd470072f7db15e4c77f3c81bc25f4d638c4da8f787b9d9a9039 for 1 DLC(s)
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=145ms
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 spent outputs, it took=197ms
2022-01-03T19:07:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000be32a07cadc0a1a083c3d1b2629a3e0fe02a9b2c95edd. It took 1301ms
2022-01-03T19:07:53UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000003b96e060a3f73260e2b7f6f17ad716bd2a5aa5c942377
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000003b96e060a3f73260e2b7f6f17ad716bd2a5aa5c942377
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: bef88d690bcd8e0ac36e3cba26b2007698b9a367545d5e7645d8d106d6c0f27f:1 amt=552070 sats
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO bef88d690bcd8e0ac36e3cba26b2007698b9a367545d5e7645d8d106d6c0f27f:1 into DB
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Processing tx bef88d690bcd8e0ac36e3cba26b2007698b9a367545d5e7645d8d106d6c0f27f for 1 DLC(s)
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=160ms
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 spent outputs, it took=137ms
2022-01-03T19:07:53UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000003b96e060a3f73260e2b7f6f17ad716bd2a5aa5c942377. It took 795ms
2022-01-03T19:07:59UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000027207a685ca11b821bfcb5941f2ed02a5658c6cee8316
2022-01-03T19:07:59UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000027207a685ca11b821bfcb5941f2ed02a5658c6cee8316
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 2bd499402783111f4d11fd2c963f30050750204d3c0e4a00d734a0036149767b:1 amt=24938945 sats
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 2bd499402783111f4d11fd2c963f30050750204d3c0e4a00d734a0036149767b:1 into DB
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 2bd499402783111f4d11fd2c963f30050750204d3c0e4a00d734a0036149767b for 1 DLC(s)
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=217ms
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 spent outputs, it took=136ms
2022-01-03T19:08:01UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000027207a685ca11b821bfcb5941f2ed02a5658c6cee8316. It took 1914ms
2022-01-03T19:08:09UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000542c632fa7edf52b186f108fa4fe04acf776e0db2594d
2022-01-03T19:08:09UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000542c632fa7edf52b186f108fa4fe04acf776e0db2594d
2022-01-03T19:08:10UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: 6e492bc3b3e943781e62a54e776989ae272891d15d0aa26aec4ffc1a379e229d:0 amt=15996 sats
2022-01-03T19:08:10UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 6e492bc3b3e943781e62a54e776989ae272891d15d0aa26aec4ffc1a379e229d:0 into DB
2022-01-03T19:08:10UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=222ms
2022-01-03T19:08:10UTC INFO [DLCWallet$DLCWalletImpl] Processing tx 6e492bc3b3e943781e62a54e776989ae272891d15d0aa26aec4ffc1a379e229d for 1 DLC(s)
2022-01-03T19:08:10UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=0000000000000000000542c632fa7edf52b186f108fa4fe04acf776e0db2594d.
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.$anonfun$calculateAndSetOutcome$12(DLCTransactionProcessing.scala:155)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-01-03T19:08:10UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error: 
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at org.bitcoins.dlc.wallet.internal.DLCTransactionProcessing.$anonfun$calculateAndSetOutcome$12(DLCTransactionProcessing.scala:155)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-01-03T19:08:10UTC INFO [DLCWallet$DLCWalletImpl] Finished rescanning the wallet. It took 120564ms
```

**Comment by Christewart** [comment]
Same as #3869
