### ISSUE TITLE
Contract ids broken by changes to offer serialization (#3854)

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#3969]
Since we changed offer serialization in #3854 , all `contractId`s for numeric DLCs are broken in master. Likely we are going to have write migration code to update all `contractId`s at minimum, but likely we should update all stored DLCs that have the old serialization format.

>The temporary_contract_id MUST be the SHA256 hash of the offer_dlc message.

https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#requirements-1

I realized this when trying to get to the bottom of #3869

I get this error when trying to rescan on https://github.com/bitcoin-s/bitcoin-s/pull/3965/commits/ed9adb7771f6a294b19989b3be5038012502dff7 on my desktop. It seems to be a different error that the original issue. I'm not sure if it means this issue is fixed and this is a new unique issue, or of its related to new bug in #3965 

```
2022-01-08T17:12:55UTC INFO [DLCWallet$DLCWalletImpl] Found 1 matches from start=703891 to end=703990
2022-01-08T17:12:56UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-01-08T17:12:56UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=703991 to end=704090
2022-01-08T17:12:56UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 704147
2022-01-08T17:12:56UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
2022-01-08T17:12:57UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000d495f73083e0395ecdf432d8ffebff2d06789a8489722
2022-01-08T17:12:57UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000d495f73083e0395ecdf432d8ffebff2d06789a8489722
2022-01-08T17:13:02UTC INFO [DLCWallet$DLCWalletImpl] Adding UTXO to wallet: de13c464b401ef130c7c67b2fa456b127f4461f0978957d63a12959c3cb6e98d:1 amt=33580 sats
2022-01-08T17:13:02UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO de13c464b401ef130c7c67b2fa456b127f4461f0978957d63a12959c3cb6e98d:1 into DB
2022-01-08T17:13:02UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=187ms
2022-01-08T17:13:03UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=0000000000000000000d495f73083e0395ecdf432d8ffebff2d06789a8489722.
java.lang.IllegalArgumentException: requirement failed: Offer and accept (without sigs) must refer to same event, offer.tempContractId=3924d10fa61467ffb2aabc9b9d718bb8efd04a3e93f338b8eacd8bc2877252a6 tempContractId=ca253ce6d58a0a3574ac957fe3c85b664166165c06f5ed869c322baf3344056d
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.core.protocol.dlc.build.DLCTxBuilder.<init>(DLCTxBuilder.scala:97)
        at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$builderFromDbData$8(DLCDataManagement.scala:434)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-01-08T17:13:03UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error:
java.lang.IllegalArgumentException: requirement failed: Offer and accept (without sigs) must refer to same event, offer.tempContractId=3924d10fa61467ffb2aabc9b9d718bb8efd04a3e93f338b8eacd8bc2877252a6 tempContractId=ca253ce6d58a0a3574ac957fe3c85b664166165c06f5ed869c322baf3344056d
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.core.protocol.dlc.build.DLCTxBuilder.<init>(DLCTxBuilder.scala:97)
        at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$builderFromDbData$8(DLCDataManagement.scala:434)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

_Originally posted by @Christewart in https://github.com/bitcoin-s/bitcoin-s/issues/3869#issuecomment-1008068407_

**Comment by Christewart** [comment]
I think only table needs to be updated is `global_dlc_data` which has a `tempContractId` and `contractId` fields in the table

https://github.com/bitcoin-s/bitcoin-s/blob/4ca586ca462cd0bf029cfe43f698d9e49da4aa6e/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/models/DLCDAO.scala#L125-L129

I'm not sure how to best implement this. There are a couple things to consider 

1. The breaking change in #3854 is only for numeric contracts, thus we don't need to update enum contracts
2. We need some sort of a signal to indicate we have run the migration on numeric contracts, so we don't try to apply it every time to the server is spun up.

One path is to add a new column to `global_dlc_data` for the [`DLCSerializationVersion`](https://github.com/bitcoin-s/bitcoin-s/blob/8857af2b66e8d493814d0bb7b817d8d46579709d/core/src/main/scala/org/bitcoins/core/protocol/tlv/DLCSerializationVersion.scala#L8). Currently we only have this field available to us on the [`PayoutFunctionV0TLV`](https://github.com/bitcoin-s/bitcoin-s/pull/3854/files#diff-399b8d6b850d879ac7bc1c0ce7eb87a8570c32183c34cde40f263bfb84d58886R1201). 

Unfortunately we cannot determine the serialization type from `global_dlc_data` alone, we need to retrieve the full serialized version of the offer message from various tables to determine if we are dealing with a DLC that needs to have its contractId updated because the serialization changed.

If we write a database migration, then we can detect if the wallet is running an old version of the database [similar to here](https://github.com/bitcoin-s/bitcoin-s/blob/ee3ee531912f39f2fa88ad387f85382aa10b1bc4/dlc-oracle/src/main/scala/org/bitcoins/dlc/oracle/config/DLCOracleAppConfig.scala#L190) and if so, attempt to migration all numeric contracts to the new format. I believe this exact same principle could be used to upgrade our wallet's DLCs whenever we get https://github.com/discreetlogcontracts/dlcspecs/pull/163 merged into the DLC spec too.
