### ISSUE TITLE
Receiving block in the middle of Tor DLC negotion stopped exchange?

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#4028]
**Describe the bug**
I was doing a Tor DLC contract setup from the web UI and made an offer I manually sent to counterparty. Counterparty accepted the offer with the web UI and chose Tor negotiation to complete. After receiving an Accept state, a block was received from the network and there was an "Error fetching accounting" ending with the recipient having a contract in Accepted state and locally having a contract in Signed state and the process stopped. Unclear how to complete.

[Update]
This contract later made it to broadcasted state, but not before I had tried this process a second time and hit the same Accepted/Signed state between clients. Which also appeared to fail, then made it to Broadcasted state. Second log attached.

**To Reproduce**
1. Follow steps above

**Expected behavior**
Contract negotiaton is successful

**Logs**
[Received Block Mid Tor DLC Exchange.txt](https://github.com/bitcoin-s/bitcoin-s/files/7973587/Received.Block.Mid.Tor.DLC.Exchange.txt)
[Second time received block mit tor DLC exchange.txt](https://github.com/bitcoin-s/bitcoin-s/files/7973657/Second.time.received.block.mit.tor.DLC.exchange.txt)

**Platform (please complete the following information):**
Linux x64, web UI over bundle

**Comment by Christewart** [comment]
The logs

from a quick glance, i think this is because there are a lot of adaptor signatures that need to be computed (`28757`) rather than a block coming in 
```
[info] 2022-01-31T19:10:54UTC INFO [DLCWallet$DLCWalletImpl] Created offer with tempContractId fff5d3d746e92d0ae9235695308148c2c574aec1e4e9a1907d16ce9ec7e09bce
[info] 2022-01-31T19:13:05UTC INFO [DLCServer] Received a connection from /127.0.0.1:33938
[info] 2022-01-31T19:14:31UTC INFO [DLCDataHandler] Received LnMessage DLCAcceptTLV
[info] 2022-01-31T19:14:32UTC INFO [DLCWallet$DLCWalletImpl] Verifying 28757 CET Signatures
[info] 2022-01-31T19:14:39UTC INFO [HikariLogging] "chain-pool-usage":{"max":3536.0,"min":0.0,"median":0.0,"mean":0.8555543827355456,"75thPercentile":0.0,"95thPercentile":8.0,"98thPercentile":18.0,"99thPercentile":19.0,"999thPercentile":24.0}
[info] 2022-01-31T19:14:39UTC INFO [HikariLogging] "chain-activity-update":{"active":0,"idle":1,"waiting":0,"total":1,"maxThreads":1,"activeThreads":0,"maxQueueSize":5000,"queueSize":0}
[info] 2022-01-31T19:14:40UTC INFO [HikariLogging] "wallet-pool-usage":{"max":8.0,"min":0.0,"median":0.0,"mean":0.0036849940150413406,"75thPercentile":0.0,"95thPercentile":0.0,"98thPercentile":0.0,"99thPercentile":0.0,"999thPercentile":0.0}
[info] 2022-01-31T19:14:40UTC INFO [HikariLogging] "wallet-activity-update":{"active":0,"idle":1,"waiting":0,"total":1,"maxThreads":1,"activeThreads":0,"maxQueueSize":5000,"queueSize":0}
[info] 2022-01-31T19:14:47UTC INFO [HikariLogging] "node-pool-usage":{"max":8.0,"min":0.0,"median":0.0,"mean":1.3322111089429949,"75thPercentile":4.0,"95thPercentile":4.0,"98thPercentile":4.0,"99thPercentile":4.0,"999thPercentile":8.0}
[info] 2022-01-31T19:14:47UTC INFO [HikariLogging] "node-activity-update":{"active":0,"idle":1,"waiting":0,"total":1,"maxThreads":1,"activeThreads":0,"maxQueueSize":5000,"queueSize":0}
[info] 2022-01-31T19:15:44UTC INFO [ActorSystemImpl] Request timeout encountered for request [POST / Strict(79 bytes)]
[info] 2022-01-31T19:15:44UTC ERROR [WalletGUIModel] Error fetching accounting
[info] java.lang.RuntimeException: The server was not able to produce a timely response to your request.
[info] Please try again in a short while!
[info] 	at org.bitcoins.cli.ConsoleCli$.error$1(ConsoleCli.scala:1695)
[info] 	at org.bitcoins.cli.ConsoleCli$.$anonfun$exec$1(ConsoleCli.scala:2072)
[info] 	at scala.util.Try$.apply(Try.scala:210)
[info] 	at org.bitcoins.cli.ConsoleCli$.exec(ConsoleCli.scala:2009)
[info] 	at org.bitcoins.gui.WalletGUIModel.org$bitcoins$gui$WalletGUIModel$$updateWalletAccounting(WalletGUIModel.scala:168)
[info] 	at org.bitcoins.gui.WalletGUIModel$UpdateWalletInfoRunnable$.$anonfun$run$1(WalletGUIModel.scala:38)
[info] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info] 	at scalafx.application.Platform$$anon$1.run(Platform.scala:148)
[info] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
[info] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[info] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
[info] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[info] 	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
[info] 	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
[info] 	at java.base/java.lang.Thread.run(Thread.java:829)
[info] 2022-01-31T19:16:40UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for contract 73ed5824929b539c8002fae48a9834b7415cd8976cc166608e1d340bcb16bb36
[info] 2022-01-31T19:16:48UTC INFO [DLCWallet$DLCWalletImpl] Creating funding sigs for 73ed5824929b539c8002fae48a9834b7415cd8976cc166608e1d340bcb16bb36
[info] 2022-01-31T19:16:48UTC INFO [DLCWallet$DLCWalletImpl] DLC 73ed5824929b539c8002fae48a9834b7415cd8976cc166608e1d340bcb16bb36 is signed
```
