### ISSUE TITLE
Tor not starting for me on linux

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4047]
I tried to start with `bundle/run` on linux and startup times out after 120 seconds because is not starting

This is on 70c6bcef2a5b55824301ba92413281734713dcc2

```
[info] 2022-02-04T20:41:54UTC INFO [BitcoinSServerMain] Start on network MainNet
[info] 2022-02-04T20:41:54UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, /home/chris/.bitcoin-s/tor/linux_64/tor
[info] 2022-02-04T20:41:54UTC INFO [TorClient$] Using tor daemon already written to datadir=/home/chris/.bitcoin-s/tor
[info] Feb 04 14:41:55.016 [notice] Tor 0.4.6.9 (git-ea2ada6d1459f829) running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1m, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
[info] Feb 04 14:41:55.016 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
[info] Feb 04 14:41:55.016 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
[info] Feb 04 14:41:55.018 [warn] Failed to parse/validate config: Unknown option 'file'.  Failing.
[info] Feb 04 14:41:55.018 [err] Reading config failed--see warnings above.
[info] 2022-02-04T20:41:55UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
[info] 2022-02-04T20:41:55UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
[info] 2022-02-04T20:41:55UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.015s)
[info] 2022-02-04T20:41:55UTC INFO [DbMigrate] Current version of schema "main": 6
[info] 2022-02-04T20:41:55UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2022-02-04T20:41:55UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json
[info] 2022-02-04T20:41:55UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
[info] 2022-02-04T20:41:55UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
[info] 2022-02-04T20:41:56UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
[info] 2022-02-04T20:41:56UTC INFO [DbValidate] Successfully validated 12 migrations (execution time 00:00.009s)
[info] 2022-02-04T20:41:56UTC INFO [DbMigrate] Current version of schema "main": 12
[info] 2022-02-04T20:41:56UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
[info] 2022-02-04T20:41:56UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
[info] 2022-02-04T20:41:56UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
[info] 2022-02-04T20:42:56UTC ERROR [BitcoinSServerMain] Failed to startup server!
[info] org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 60 attempts with interval=1 second waiting periods
[info]  at org.bitcoins.tor.config.TorAppConfig.isBinaryFullyStarted(TorAppConfig.scala:168)
[info]  at org.bitcoins.tor.config.TorAppConfig.$anonfun$start$3(TorAppConfig.scala:131)
[info]  at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[info]  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[info]  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[info] 2022-02-04T20:42:56UTC ERROR [BitcoinSServerMain] Failed to initialize configuration for BitcoinServerMain
[info] org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 60 attempts with interval=1 second waiting periods
[info]  at org.bitcoins.tor.config.TorAppConfig.isBinaryFullyStarted(TorAppConfig.scala:168)
[info]  at org.bitcoins.tor.config.TorAppConfig.$anonfun$start$3(TorAppConfig.scala:131)
[info]  at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[info]  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[info]  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[info] 2022-02-04T20:42:56UTC ERROR [Dispatcher] Condition timed out after 60 attempts with interval=1 second waiting periods
[info] org.bitcoins.asyncutil.AsyncUtil$RpcRetryException: Condition timed out after 60 attempts with interval=1 second waiting periods
[info]  at org.bitcoins.tor.config.TorAppConfig.isBinaryFullyStarted(TorAppConfig.scala:168)
[info]  at org.bitcoins.tor.config.TorAppConfig.$anonfun$start$3(TorAppConfig.scala:131)
[info]  at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[info]  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[info]  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
[info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
[info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
[info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by benthecarman** [comment]
Looks like something is wrong with the tor config

```
[info] Feb 04 14:41:55.018 [warn] Failed to parse/validate config: Unknown option 'file'.  Failing.
```
