### ISSUE TITLE
Error no oracles used

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4050]
When attempting to login to my umbrel wallet this morning i get this error when i put in my password. I cannot proceed any further. This was on 2066447c

Related issues are #3686 #3826 . The notable difference is that this issue was with a `bitcoind` backend, not a `neutrino` backend.

![Screenshot from 2022-02-06 07-34-35](https://user-images.githubusercontent.com/3514957/152683455-e7d10114-3c6d-48a8-acc9-daf48626137b.png)

Stack trace 

```
2022-02-06T13:21:46UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000000941e92474ee4430498bf1ff0dea90f4d5d2abd3f3671. It took 19710ms
2022-02-06T13:32:49UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
        at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1670)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-02-06T13:32:49UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Error, no oracles used
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.getOracleOutcomeAndSigs(DLCStatusBuilder.scala:221)
        at org.bitcoins.dlc.wallet.util.DLCStatusBuilder$.buildClosedDLCStatus(DLCStatusBuilder.scala:159)
        at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$buildDLCStatus$5(DLCWallet.scala:1670)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by Christewart** [comment]
I tried to reproduce this between my macbook and desktop with a neutrino backend on 5aeecdb89306fecff74934a6f0fed7bed51facc2  and failed

```
[info] 2022-02-07T19:27:14UTC INFO [DLCWallet$DLCWalletImpl] Processing spent utxos in tx fddaad66c12941f7fc7cb31b05dac6070dc0cee4e2c353ab82372191b02f36d6 for 1 DLC(s)
[info] 2022-02-07T19:27:14UTC INFO [DLCWallet$DLCWalletImpl] Calculating RemotedClaimed outcome for dlcId=ec4988eaac138f69a2ae1c42ed8e868239b2278fe63aef8906d412384318bc85 closingTx=Some(fddaad66c12941f7fc7cb31b05dac6070dc0cee4e2c353ab82372191b02f36d6)
[info] 2022-02-07T19:27:14UTC INFO [DLCWallet$DLCWalletImpl] Done calculating RemoteClaimed outcome for dlcId=ec4988eaac138f69a2ae1c42ed8e868239b2278fe63aef8906d412384318bc85
[info] 2022-02-07T19:27:14UTC INFO [DLCWallet$DLCWalletImpl] Deleting unneeded DLC signatures for contract 645b48c60a4b303d0603241db9698629cf75224fe611d50aef870ea487a459bc
```

One last thing that needs to be investigated is if bitcoind gives us all withness data when we make an RPC call.

**Comment by Christewart** [comment]
I'm not sure if this is a conicdence or not, but an anecdote is that both this issue and #3686 were enum contracts and not numeric.

**Comment by Christewart** [comment]
I have not seen this in a month, hopefully its fixed :crossed_fingers: . Not sure where it got fixed, likely in a PR that makes the dlc wallet more transactional at the db level.
