### ISSUE TITLE
Very large testnet transactions cannot be inserted into SQLite database

### ISSUE THREAD

**Issue by user411** [bitcoin-s/bitcoin-s#4072]
**Describe the bug**
Doing a rescan --force from the UI on testnet corrupts the wallet. Backend will no longer talk with frontend.

**To Reproduce**
1. Startup on testnet
2. Use the web UI to click the Rescan button.

**Expected behavior**
Wallet working

**Logs**
[testnet-rescan-wallet.txt](https://github.com/bitcoin-s/bitcoin-s/files/8043949/testnet-rescan-wallet.txt)

**Platform (please complete the following information):**
mac m1

**Comment by Christewart** [comment]
This seems to be the meat and potatoes for the error log

```
2022-02-10T17:54:14UTC INFO [DLCWallet$DLCWalletImpl] Found 5 matches from start=2138992 to end=2139091
2022-02-10T17:54:14UTC INFO [DLCWallet$DLCWalletImpl] Requesting 0 block(s)
2022-02-10T17:54:14UTC INFO [DLCWallet$DLCWalletImpl] Found 0 matches from start=2139092 to end=2139191
2022-02-10T17:54:14UTC INFO [DLCWallet$DLCWalletImpl] Found a match in block 2139229
2022-02-10T17:54:14UTC INFO [DLCWallet$DLCWalletImpl] Requesting 1 block(s)
2022-02-10T17:54:16UTC INFO [DataMessageHandler] Received block message with hash 0000000018e1f87464ee8a624b15ec4eda1392280ce6ea68b8d76c17ce6af65a
2022-02-10T17:54:16UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000018e1f87464ee8a624b15ec4eda1392280ce6ea68b8d76c17ce6af65a
2022-02-10T17:54:16UTC ERROR [SafeDatabase] Error when executing query result [select "id", "script_pub_key", "script_type" from "pub_key_scripts" where "script_pub_key" in ('156a133c3c206c6f6f6b20746f20746865206c656674', 'fe46d10c006a4e40d10c006c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f61
... a bunch more hex that i truncated because its too big for a github comment ....
6b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572205747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a6c65747320626c6f617420796f7572206469736b0a', '160014b58245934886f191a2af01c0cf355774e1a8d508', '2b6a24aa21a9ed4a4bd774834353344036b0ed9dbbb10a23cb45a9b973c8bed7792d407f14c9f004ea6d20ac')]
2022-02-10T17:54:16UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
2022-02-10T17:54:16UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=0000000018e1f87464ee8a624b15ec4eda1392280ce6ea68b8d76c17ce6af65a.
org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:375)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:489)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-02-10T17:54:16UTC ERROR [DataMessageHandler] onBlockReceived Callback failed with error: 
org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:375)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:489)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Christewart** [comment]
This is the tx in question  that i believe is causing the problem

Take a look at the second output on the coinbase tx

https://mempool.space/testnet/tx/3401fec33c75b67ee682511fca4ba1d2f5441913303a2da33e8606dacb29bdb8
