### ISSUE TITLE
`java.lang.NoSuchMethodError: 'org.bitcoins.crypto.Sha256Digest `

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4137]
User cannot startup on 8d04ca1c

```
2022-02-27T00:00:52UTC INFO [BitcoinSServerMain] version=1.8.0-157-8d04ca1c-SNAPSHOT
2022-02-27T00:00:52UTC INFO [BitcoinSServerMain] Starting appServer
2022-02-27T00:00:53UTC INFO [TorAppConfig] Starting Tor daemon
2022-02-27T00:00:53UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=C:\Users\bigbi\.bitcoin-s\seeds\encrypted-bitcoin-s-seed.json
2022-02-27T00:00:53UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-02-27T00:00:53UTC INFO [TorClient$] Using prepackaged Tor from bitcoin-s resources, C:\Users\bigbi\.bitcoin-s\tor\windows_64\tor.exe
2022-02-27T00:00:53UTC INFO [TorClient$] Using tor daemon already written to datadir=C:\Users\bigbi\.bitcoin-s\tor
2022-02-27T00:00:53UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
2022-02-27T00:00:53UTC INFO [DatabaseFactory] Database: jdbc:sqlite:C:/Users/bigbi/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-02-27T00:00:53UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.017s)
2022-02-27T00:00:53UTC INFO [DbMigrate] Current version of schema "main": 6
2022-02-27T00:00:53UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-27T00:00:53UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=C:\Users\bigbi\.bitcoin-s\seeds\encrypted-bitcoin-s-seed.json
2022-02-27T00:00:53UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-02-27T00:00:53UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-02-27T00:00:53UTC INFO [DatabaseFactory] Database: jdbc:sqlite:C:/Users/bigbi/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-02-27T00:00:53UTC INFO [DbValidate] Successfully validated 14 migrations (execution time 00:00.010s)
2022-02-27T00:00:53UTC INFO [DbMigrate] Current version of schema "main": 13
2022-02-27T00:00:53UTC INFO [DbMigrate] Migrating schema "main" to version 14 - compute spk hashes
2022-02-27T00:00:54UTC ERROR [ActorSystemImpl] Uncaught error from thread [bitcoin-s-gui-1645920047926-akka.actor.default-dispatcher-5]: 'org.bitcoins.crypto.Sha256Digest org.bitcoins.core.api.wallet.db.ScriptPubKeyDb$.hash(org.bitcoins.core.protocol.script.ScriptPubKey)', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[bitcoin-s-gui-1645920047926]
java.lang.NoSuchMethodError: 'org.bitcoins.crypto.Sha256Digest org.bitcoins.core.api.wallet.db.ScriptPubKeyDb$.hash(org.bitcoins.core.protocol.script.ScriptPubKey)'
	at sqlite.wallet.migration.V14__compute_spk_hashes.migrate(V14__compute_spk_hashes.scala:18)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:64)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.access$000(JavaMigrationExecutor.java:35)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor$1.call(JavaMigrationExecutor.java:56)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor$1.call(JavaMigrationExecutor.java:53)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
	at org.flywaydb.core.Flyway.execute(Flyway.java:530)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.bitcoins.db.DbManagement.migrate(DbManagement.scala:167)
	at org.bitcoins.db.DbManagement.migrate$(DbManagement.scala:157)
	at org.bitcoins.wallet.config.WalletAppConfig.migrate(WalletAppConfig.scala:34)
	at org.bitcoins.wallet.config.WalletAppConfig.$anonfun$start$2(WalletAppConfig.scala:188)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
This user was on windows. This was likely caused by #4149
