### ISSUE TITLE
Error syncing bitcoin-s wallet with bitcoind

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4138]
This was seen on  99418c79 with a bitcoind backend on my umbrel node.

This seems to have stopped all processing of blocks on my wallet. The workaround is rebooting umbrel.

```
2022-02-26T19:18:06UTC INFO [BitcoinSServerMain] version=1.8.0-172-99418c79-SNAPSHOT
2022-02-26T19:18:06UTC INFO [BitcoinSServerMain] Starting appServer
2022-02-26T19:18:17UTC INFO [VersionPrinter] Flyway Community Edition 6.4.2 by Redgate
2022-02-26T19:18:19UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2022-02-26T19:18:21UTC INFO [DbValidate] Successfully validated 5 migrations (execution time 00:00.155s)
2022-02-26T19:18:21UTC INFO [DbMigrate] Current version of schema "main": 5
2022-02-26T19:18:21UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-26T19:18:21UTC INFO [DLCAppConfig] Running serialization version migration code
2022-02-26T19:18:22UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json
2022-02-26T19:18:22UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-02-26T19:18:22UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-02-26T19:18:22UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.075s)
2022-02-26T19:18:22UTC INFO [DbMigrate] Current version of schema "main": 6
2022-02-26T19:18:22UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-26T19:18:23UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json
2022-02-26T19:18:24UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-02-26T19:18:25UTC INFO [DbValidate] Successfully validated 12 migrations (execution time 00:00.220s)
2022-02-26T19:18:25UTC INFO [DbMigrate] Current version of schema "main": 12
2022-02-26T19:18:25UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-26T19:18:27UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
2022-02-26T19:18:27UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-02-26T19:18:27UTC INFO [DatabaseFactory] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2022-02-26T19:18:27UTC INFO [DbValidate] Successfully validated 3 migrations (execution time 00:00.014s)
2022-02-26T19:18:27UTC INFO [DbMigrate] Current version of schema "main": 3
2022-02-26T19:18:27UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-26T19:18:27UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-02-26T19:18:29UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-02-26T19:18:29UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
2022-02-26T19:18:29UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-02-26T19:18:30UTC INFO [DLCAppConfig] Applied 0 to the dlc project
2022-02-26T19:18:31UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=25488ms
2022-02-26T19:18:31UTC INFO [BitcoinSServerMain] startBitcoindBackend()
2022-02-26T19:18:44UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Loading P2P addresses…
2022-02-26T19:18:44UTC INFO [BitcoinSServerMain] Started bitcoind
2022-02-26T19:18:44UTC INFO [BitcoinSServerMain] Creating wallet
2022-02-26T19:18:44UTC INFO [BitcoinSServerMain] Using fee provider: org.bitcoins.rpc.client.v22.BitcoindV22RpcClient@5a39df6d
2022-02-26T19:18:44UTC INFO [DLCAppConfig$] Using pre-existing wallet
2022-02-26T19:18:45UTC INFO [BitcoinSServerMain] Starting wallet
2022-02-26T19:18:45UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
2022-02-26T19:18:45UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json
2022-02-26T19:18:45UTC INFO [DbValidate] Successfully validated 12 migrations (execution time 00:00.046s)
2022-02-26T19:18:45UTC INFO [DbMigrate] Current version of schema "main": 12
2022-02-26T19:18:45UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-02-26T19:18:50UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: false
2022-02-26T19:18:51UTC INFO [DLCServer] Bound at /0.0.0.0:2862
2022-02-26T19:18:52UTC INFO [Server] Started Bitcoin-S HTTP server at /0.0.0.0:9999
2022-02-26T19:18:52UTC INFO [Server] Started Bitcoin-S websocket at /0.0.0.0:19999
2022-02-26T19:18:52UTC INFO [BitcoindRpcBackendUtil$] Syncing wallet to bitcoind
2022-02-26T19:18:52UTC INFO [BitcoinSServerMain] Done starting Main!
2022-02-26T19:18:52UTC INFO [BitcoinSServerMain] Done start BitcoinSServerMain, it took=46091ms
2022-02-26T19:18:52UTC INFO [BitcoindRpcBackendUtil$] bitcoindHeight=725042 walletStateOpt=Some(0000000000000000000561ca23c591571c77118f93d7c916ae5572ddd937d6c4 725044)
2022-02-26T19:18:52UTC ERROR [BitcoindRpcBackendUtil$] Bitcoind and wallet are in incompatible states, wallet height: 725044, bitcoind height: 725042
2022-02-26T19:18:52UTC ERROR [BitcoinSServerMain] Error syncing bitcoin-s wallet with bitcoind
java.lang.RuntimeException: Bitcoind and wallet are in incompatible states, wallet height: 725044, bitcoind height: 725042
	at org.bitcoins.server.BitcoindRpcBackendUtil$.doSync(BitcoindRpcBackendUtil.scala:81)
	at org.bitcoins.server.BitcoindRpcBackendUtil$.$anonfun$syncWalletToBitcoind$5(BitcoindRpcBackendUtil.scala:66)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2022-02-26T21:00:06UTC INFO [DLCWallet$DLCWalletImpl] Unreserving utxos Vector(TransactionOutPoint(e1cbcec6c43d5bf461b33c53bd7b46f683eea743571938f600669ee33a211ba4:1), TransactionOutPoint(c3989d19f0534dbea53a00894d4a9558cec39e7bf5fa9f790de0691ace03fa97:1), TransactionOutPoint(593e8a0ceceed8aac4fd0568e8580598ce7c94af27e71bd6a435a8a1a3e04a49:0))
2022-02-26T21:00:06UTC INFO [DLCWallet$DLCWalletImpl] 3 txos are now confirmed!
2022-02-26T21:01:27UTC INFO [DLCWallet$DLCWalletImpl] Sending 0.00125000 BTC to bc1qdkf7g6grzt0rkr473yzm3j53076ppdjv0f2aep at feerate 3 sats/vbyte
2022-02-26T21:01:27UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=0.00125000 BTC with feeRate=3 sats/vbyte
2022-02-26T21:01:27UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(e1cbcec6c43d5bf461b33c53bd7b46f683eea743571938f600669ee33a211ba4:1), TransactionOutPoint(c3989d19f0534dbea53a00894d4a9558cec39e7bf5fa9f790de0691ace03fa97:1), TransactionOutPoint(e1a204cfe2d05992bc6db3dacec66e4e4a4e876b1831acb3692958d4796f935c:1), TransactionOutPoint(593e8a0ceceed8aac4fd0568e8580598ce7c94af27e71bd6a435a8a1a3e04a49:0))
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(e1cbcec6c43d5bf461b33c53bd7b46f683eea743571938f600669ee33a211ba4:1) state=ConfirmedReceived, TransactionOutPoint(c3989d19f0534dbea53a00894d4a9558cec39e7bf5fa9f790de0691ace03fa97:1) state=ConfirmedReceived, TransactionOutPoint(e1a204cfe2d05992bc6db3dacec66e4e4a4e876b1831acb3692958d4796f935c:1) state=ConfirmedReceived, TransactionOutPoint(593e8a0ceceed8aac4fd0568e8580598ce7c94af27e71bd6a435a8a1a3e04a49:0) state=ConfirmedReceived)
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(57065 sats,wpkh(5f990a2987d844b3d5ff391c41b079f3935866b6))
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(11429 sats,wpkh(7a3392e9ec9e82025d1865c35290057bad23c5f9))
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] UTXO 2 details: TransactionOutput(68600 sats,wpkh(561e0f2579ad64abbd565af2f440e73a51050b50))
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] UTXO 3 details: TransactionOutput(7137 sats,wpkh(9ae00dc1aed0f66187295fe7fd510dbb44a87681))
2022-02-26T21:01:28UTC INFO [DLCWallet$DLCWalletImpl] Processing TX from our wallet, transaction=82bee50e771a60983d2acf42f23935d17bfa983f0177f474141bf43e2b44b566 with blockHash=None
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 82bee50e771a60983d2acf42f23935d17bfa983f0177f474141bf43e2b44b566:1 amt=18199 sats into DB
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=324ms
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 4 spent outputs, it took=280ms
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Processing of internal transaction=82bee50e771a60983d2acf42f23935d17bfa983f0177f474141bf43e2b44b566 resulted in changeOutputs=1 and spentUTXOs=4
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=13ms
2022-02-26T21:01:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 4 spent outputs, it took=190ms
2022-02-27T00:06:24UTC ERROR [BitcoindV22RpcClient] org.bitcoins.rpc.BitcoindException$VerifyAlreadyInChain: Error -27: Transaction already in block chain
2022-02-27T00:06:24UTC ERROR [WalletAppConfig$] Failed to broadcast txs
org.bitcoins.rpc.BitcoindException$VerifyAlreadyInChain: Error -27: Transaction already in block chain
	at org.bitcoins.rpc.BitcoindException$.$anonfun$all$13(BitcoindException.scala:58)
	at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
```

**Comment by Christewart** [comment]
Done in #4386
