### ISSUE TITLE
External address flag not enabled can cause `UNIQUE constraint failed: funding_inputs.out_point`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4176]
This happened on  a747f84bbb4f051b82df62b5cf3dd62ed751ec87

I wanted to test out some external payout functionality. I booted up the wallet the first time and forgot to set the configuration `bitcoin-s.wallet.allowExternalDLCAddresses = true`. When i tried to submit an offer to the backend with an external payout address, it failed as expected.

I restarted `appServer` with the configuration properly set, and now i get the `funding_inputs.out_point` error. I'm wondering if this is because we insert the utxos into the funding inputs table before checking the configuration flag.

```
[info] 2022-03-10T13:58:31UTC INFO [ChainHandler] Processed filters from height=726706 to 726706. Best filter.blockHash=00000000000000000003fea18410ba9d94e41d74ef6406caee849c9749c2a288
[info] 2022-03-10T14:03:25UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Offer
[info] 2022-03-10T14:03:25UTC INFO [Server] Unhandled error in server:
[info] java.lang.IllegalArgumentException: External DLC addresses are not allowed
[info]  at org.bitcoins.dlc.wallet.DLCWallet.createDLCOffer(DLCWallet.scala:283)
[info]  at org.bitcoins.core.api.dlc.wallet.DLCWalletApi.createDLCOffer(DLCWalletApi.scala:36)
[info]  at org.bitcoins.core.api.dlc.wallet.DLCWalletApi.createDLCOffer$(DLCWalletApi.scala:21)
[info]  at org.bitcoins.dlc.wallet.DLCWallet.createDLCOffer(DLCWallet.scala:49)
[info]  at org.bitcoins.server.WalletRoutes$$anonfun$handleCommand$1.$anonfun$applyOrElse$76(WalletRoutes.scala:367)
[info]  at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:51)
[info]  at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
[info]  at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
[info]  at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
[info]  at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:36)
[info]  at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:40)
[info]  at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:44)
[info]  at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:36)
[info]  at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:45)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResult$2(BasicDirectives.scala:68)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRouteResultWith$2(BasicDirectives.scala:74)
[info]  at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:161)
[info]  at akka.http.scaladsl.server.directives.ExecutionDirectives.$anonfun$handleExceptions$2(ExecutionDirectives.scala:32)
[info]  at akka.http.scaladsl.server.Route$.$anonfun$createAsyncHandler$1(Route.scala:110)
[info]  at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1428)
[info]  at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
[info]  at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
[info]  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
[info]  at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
[info]  at akka.actor.Actor.aroundReceive(Actor.scala:537)
[info]  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
[info]  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:548)
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
[info]  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
[info]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[info]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[info]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[info]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[info]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
^C
...
sbt:bitcoin-s> appServer/run
...
[info] 2022-03-10T14:06:00UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Offer
[info] 2022-03-10T14:06:00UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=50000 sats with feeRate=5 sats/vbyte
[info] 2022-03-10T14:06:00UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(c23e3c9982f3cd1776c9a1269ed5d858324d2e41bddb32b152c97d7d30527ae0:1))
[info] 2022-03-10T14:06:01UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1q0ulnfz92kssa0nxxn2l4arpqn9wmm8k5vtu2v4 isChange=true
[info] 2022-03-10T14:06:01UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(c23e3c9982f3cd1776c9a1269ed5d858324d2e41bddb32b152c97d7d30527ae0:1) state=ConfirmedReceived)
[info] 2022-03-10T14:06:01UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(3811595 sats,wpkh(5102f12d334a054e3adac923692327e33cb4d63c))
[info] 2022-03-10T14:06:01UTC INFO [DLCWallet$DLCWalletImpl] Created offer with tempContractId fbf5e09aa079f8f169431a6961423024a7af3eef29232a3ee5d905176dfbdcf4
[info] 2022-03-10T14:06:01UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:62424
[info] 2022-03-10T14:06:01UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:62424
[info] 2022-03-10T14:06:01UTC INFO [DLCClient] connecting to v573gl64h5zik544qvi725vxliiwwpsedarsziidp254u3cfnxlp6zqd.onion/<unresolved>:2862 via SOCKS5 localhost/127.0.0.1:62424
[info] 2022-03-10T14:06:07UTC INFO [DLCClient] connected to v573gl64h5zik544qvi725vxliiwwpsedarsziidp254u3cfnxlp6zqd.onion/<unresolved>:2862 via SOCKS5 proxy localhost/127.0.0.1:62424
[info] 2022-03-10T14:06:27UTC INFO [DLCServer] Received a connection from /127.0.0.1:48454
[info] 2022-03-10T14:06:28UTC INFO [DLCDataHandler] Received LnMessage DLCAcceptTLV
[info] 2022-03-10T14:06:28UTC INFO [DLCWallet$DLCWalletImpl] Verifying 4 CET Signatures
[info] 2022-03-10T14:06:28UTC ERROR [SafeDatabase] Error when executing query sequence
[info] 2022-03-10T14:06:28UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
[info] 2022-03-10T14:06:28UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(DLCAcceptTLV(Sha256DigestImpl(fbf5e09aa079f8f169431a6961423024a7af3eef29232a3ee5d905176dfbdcf4),50000 sats,ECPublicKey(026ea385be8e0ed4514da74ec0a8c569daf7a42df11efe2a324cc502d60dec0d25),wsh(181fa5c29f9f35be4f896acf97063035d064acdc54d9b2661b205e4ace3808f0),UInt64Impl(3611549756014467768),Vector(FundingInputV0TLV(UInt64Impl(2984614082209165784),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(a022828f02b52847e330d5dfea37f07a0d7e56f1532d3d3d8c42ca95f7aef754:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(4d54cd2a193656b1ec08d998c45d13d8f02a4f7671ad5c97154546a6ce138445:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(2989626 sats,wpkh(d371833b173880d26b23317d9985a11fee1b16d0)), TransactionOutput(30710250 sats,wpkh(bdaff89912cded6b47aa423844177f48b10e2ee9)), TransactionOutput(101870 sats,wsh(f01ccf1fd8d2b4de1f014d7181ed911c1750682f613ba246395d2eee82c8fdeb))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(03e66ec8db5c015f97c1022d962101d537acda9e13cf48b9f1e1a66f074585a1e1, 304402206e643a984867dc8a032db04cb6fe2d32af77da9421b5155aba0914fe058f41b1022052f8feeabc72b023af104b70b8ccce4fb6487e7e6a4c79730f4195aa18c4dced01)), P2WPKHWitnessV0(List(02de701b634ee3524d01c08a014a80100bb60c149d3b544713839954bdcbb6a990, 304402207a6c33d060a1fa326b6372adb104f2cc1ec2f6c2e8aa776d70ca8e7385eee43f0220131ea1e22900075d1ffb39f357db74adfaf290a5575f23fbc9f9682769da301201)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(493676516842920444),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(6490d4741248da69312dc416ff4294e6534429584d11bff41bcf344980e8df93:4),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(f2e927e867950e46597ceec39d05ada7d2624f8c3d6caacee5503a67b785f682:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(100170 sats,wsh(f3b182759011ecb36391ff3f383ddefe27c1c3941fd2f7731063f53d7d1bb7c7)), TransactionOutput(45372 sats,wpkh(a3ae1599bbb7f8434c924e3617ba98ab3d06afd9)), TransactionOutput(163085 sats,wpkh(0c13579e316dd7c1bbccc040180a0e7f25b2c145))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(030a5982dd7742c83f1a5c4bc50cfd0aa30d6236bb43adfbd56d3c3e532c747a2c, 304402207da4f06692588afdbc365920ec55b0cc64c58173a680367e1702e1caeacb92140220689c73990f6c1d0e6511791d38f8b5d41338a7eb9c8ca1dbb67030d27d2a15ae01)), P2WPKHWitnessV0(List(028f4541b2eecdde1a8f44941b947c516ebe01bc84e20367d7e026394cd789383e, 304402205abf731bd0487dc0fc4ff2f08661c8cc29d09bcd6a8d43ea4ffcda3ed97c80c30220401d4a40ad48fc70205e30fa0135ec77541a6b0e23cf3e50c5764761876bf78901)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(ffdbd0d6197a878e031e825bd276634c4d0a7c6a),UInt64Impl(9868466984249472317),org.bitcoins.core.protocol.tlv.CETSignaturesV0TLV@e98b0fc7,ECDigitalSignature(304402201a5d5eef989c4f1f62307cda1795e2c3ca013d8213680a3561b5fde9d000312c02203b4c033c6aaa7c6cf33d0dfdcefde0dbe8c66b2c4053bc452ab3d2fc010c0a0a),NoNegotiationFieldsTLV))
[info] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
[info]  at org.sqlite.core.DB.newSQLException(DB.java:1030)
[info]  at org.sqlite.core.DB.newSQLException(DB.java:1042)
[info]  at org.sqlite.core.DB.throwex(DB.java:1007)
[info]  at org.sqlite.core.DB.executeBatch(DB.java:832)
[info]  at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
[info]  at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
[info]  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
[info]  at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
[info]  at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
[info]  at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
[info]  at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
[info]  at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
[info]  at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
[info]  at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
[info]  at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
[info]  at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[info]  at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[info]  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info]  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Christewart** [comment]
I think my initial diagnosis is incorrect as we fail fast is the external address flag is not set. 

See: https://github.com/bitcoin-s/bitcoin-s/blob/a747f84bbb4f051b82df62b5cf3dd62ed751ec87/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/DLCWallet.scala#L280

I now think this is a duplicate of #4145
