### ISSUE TITLE
Get eclair tests working with a default bitcoind of `0.17.0`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#421]
When I run `$ bloop test eclairRpcTest` with a default bitcoind of `0.17.x` series, i get the following error 

```
- should detect what network we are on *** FAILED *** (1 millisecond)
  java.lang.IllegalArgumentException: requirement failed: bitcoind version must be v0.16, got v0.17
  at scala.Predef$.require(Predef.scala:281)
  at org.bitcoins.rpc.client.common.BitcoindRpcClient.<init>(BitcoindRpcClient.scala:34)
  at org.bitcoins.rpc.client.v16.BitcoindV16RpcClient.<init>(BitcoindV16RpcClient.scala:27)
  at org.bitcoins.testkit.eclair.rpc.EclairRpcTestUtil.$anonfun$startedBitcoindRpcClient$1(EclairRpcTestUtil.scala:67)
  at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
  at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  ...
Execution took 1.341s
```

**Comment by torkelrogstad** [comment]
The Eclair version we're using requires a bitcoind with some RPC calls from 0.16. It can be done with 0.17 if it's started with some special flags that undeprecates the calls, but that's not implemented in our RPC client. 

I'd say the way to fix this issue is to upgrade our Eclair RPC client to most recent Eclair version.
