### ISSUE TITLE
Too many scripts in `select from pub_key_scripts`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4220]
on ecbe08e9 with this many scripts in `pub_key_scripts`

![Screenshot from 2022-03-27 13-59-42](https://user-images.githubusercontent.com/3514957/160296476-8bafb60e-3b8d-4923-b73c-ae1d2fe896f5.png)

```
2022-03-27T17:01:20UTC INFO [BitcoinSServerMain] version=1.9.0-86-ecbe08e9-SNAPSHOT jdkVersion=18
...
2022-03-25T19:27:42UTC ERROR [SafeDatabase] Error when executing query result [select "id", "script_pub_key", "script_type", "hash" from "pub_key_scripts" where "hash" in [ a ton of script hashes here]

2022-03-25T19:27:42UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
2022-03-25T19:27:42UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=000000000000000000028114bcd6982237211ad18d66c3eed3ff84e13caf0c2f.
org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:375)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:489)
```

**Comment by Christewart** [comment]
I think this again last night when trying to test #4219.

I'm guessing this is where this exception occurs, we search the database for all spks in a given block up front:

https://github.com/bitcoin-s/bitcoin-s/pull/4219/files#diff-fd826a398083437abb5cf5acafa8af283c5420c626aa902469a5b743b8dfa094R668
