### ISSUE TITLE
`A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)` when constructing an accept

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4229]
Seen on 33171fd069

```
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId cd2d2618baf13bd71bfcf1351b0740983e106701578bd41191b3117d8756edc2
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=10000 sats with feeRate=7 sats/vbyte
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(bab8e86c4a2c58c763ba63eebb70b463a904392e3dc67d5d0f726bdb778c7b25:1), TransactionOutPoint(4215922096524287a59d69f45a6782496a03f44719a7094cbbb2b25b5373cb8e:1))
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1q94aq9ptd7aww22qykcjna6wyawrd9eev546vmh path=m/84'/0'/0'/1/3 isChange=true
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(bab8e86c4a2c58c763ba63eebb70b463a904392e3dc67d5d0f726bdb778c7b25:1) state=BroadcastReceived, TransactionOutPoint(4215922096524287a59d69f45a6782496a03f44719a7094cbbb2b25b5373cb8e:1) state=PendingConfirmationsReceived)
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(235924 sats,wpkh(86da168c712ef17574530026809d8f4cd9ed43a8))
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(9996 sats,wpkh(437f56debc0befa7ef737b886fbbf1428298d634))
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId cd2d2618baf13bd71bfcf1351b0740983e106701578bd41191b3117d8756edc2
2022-03-30T18:25:04UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for 9801a112a02f601579364d50e0e2e5051b371ebf92860bc9b86a6453dd78b138
2022-03-30T18:25:04UTC ERROR [SafeDatabase] Error when executing query flatMap slick.dbio.DBIOAction$$Lambda$1027/0x000000080111b128@26fde020
2022-03-30T18:25:04UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
2022-03-30T18:25:04UTC INFO [Server] Unhandled error in server:
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: funding_inputs.out_point)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.DB.executeBatch(DB.java:832)
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Christewart** [comment]
Possibly related to #4176 #4145 #3846 #3844
