### ISSUE TITLE
`requirement failed: Offer and accept (without sigs) must refer to same event`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4240]
DLC was created on 22051d25 and attempted to execute on 24125eaca3a3d12ae5918b48c2a3056a9ed1e8bf

The wallet was production testing for bitcoin 2022 with the [same oracle announcement](https://oracle.suredbits.com/contract/enum/909cf3468cb172b479b832762dce5579232b6caba66d3c0c4bb1e266a44de5ff)

```
2022-04-03T18:47:17UTC INFO [DLCWallet$DLCWalletImpl] Executing dlc with contractId=df92b4dc0dda757890e08921976f4a73084b7cd05d1d161d604d283a94cbc480 sigs=Vector(fdd86890285072656d696572204c6561677565204372797374616c2050616c6163652076204d616e20436974793a6093a42d9e4fb8af718daf1c92678e14f7b83ed0637038428077404c1b9b2e000149d598f3d64841c81bb8bab4f223760d1e824b3eae3bd141b706148307f11c1ba8b2f8692af4f2b1af249ae5bfd469b9597035e27eafa159688ebceedb5cfdcf0444726177)
2022-04-03T18:47:18UTC INFO [Server] Unhandled error in server:
java.lang.IllegalArgumentException: requirement failed: Offer and accept (without sigs) must refer to same event, offer.tempContractId=b5c859b44ea74cd98741c2b8e04af92c1b247edd8ad365b82d7a0d68b22a6a2f tempContractId=652a5cb047f62dbff35aeacf2c1ffe10a14f45fe60db6b406f3f43e1e347bfa5
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.core.protocol.dlc.build.DLCTxBuilder.<init>(DLCTxBuilder.scala:98)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$builderFromDbData$2(DLCDataManagement.scala:432)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$builderFromDbData$1(DLCDataManagement.scala:430)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
fixed in #4290 / #4296
