### ISSUE TITLE
Executing DLC results in exception `java.lang.RuntimeException: Input 0 was invalid: ScriptErrorSigNullFail`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4253]
This occurred on 1bc3962c when attempting to execute a DLC

```
2022-04-07T12:17:26UTC INFO [DLCWallet$DLCWalletImpl] Executing dlc with contractId=df92b4dc0dda757890e08921976f4a73084b7cd05d1d161d604d283a94cbc480 sigs=Vector(fdd86890285072656d696572204c6561677565204372797374616c2050616c6163652076204d616e20436974793a6093a42d9e4fb8af718daf1c92678e14f7b83ed0637038428077404c1b9b2e000149d598f3d64841c81bb8bab4f223760d1e824b3eae3bd141b706148307f11c1ba8b2f8692af4f2b1af249ae5bfd469b9597035e27eafa159688ebceedb5cfdcf0444726177)
2022-04-07T12:17:27UTC INFO [Server] Unhandled error in server:
java.lang.RuntimeException: Input 0 was invalid: ScriptErrorSigNullFail
	at org.bitcoins.core.util.BitcoinScriptUtil.verifyPSBTInputScript(BitcoinScriptUtil.scala:714)
	at org.bitcoins.core.util.BitcoinScriptUtil.verifyPSBTInputScript$(BitcoinScriptUtil.scala:691)
	at org.bitcoins.core.util.BitcoinScriptUtil$.verifyPSBTInputScript(BitcoinScriptUtil.scala:719)
	at org.bitcoins.core.psbt.PSBT.$anonfun$extractTransactionAndValidate$3(PSBT.scala:754)
	at scala.util.Success.flatMap(Try.scala:258)
	at org.bitcoins.core.psbt.PSBT.$anonfun$extractTransactionAndValidate$2(PSBT.scala:753)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:926)
	at org.bitcoins.core.psbt.PSBT.extractTransactionAndValidate(PSBT.scala:751)
	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner$.$anonfun$completeFundingTx$4(DLCTxSigner.scala:514)
	at scala.util.Success.flatMap(Try.scala:258)
	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner$.completeFundingTx(DLCTxSigner.scala:514)
	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner.$anonfun$completeFundingTx$1(DLCTxSigner.scala:118)
	at scala.util.Success.flatMap(Try.scala:258)
	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner.completeFundingTx(DLCTxSigner.scala:113)
	at org.bitcoins.core.protocol.dlc.execution.DLCExecutor.setupDLC(DLCExecutor.scala:72)
	at org.bitcoins.core.protocol.dlc.execution.DLCExecutor.setupDLCAccept(DLCExecutor.scala:42)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$executorAndSetupFromDb$2(DLCDataManagement.scala:646)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-04-07T12:17:54UTC INFO [DLCWallet$DLCWalletImpl] Unreserving utxos Vector(TransactionOutPoint(bab8e86c4a2c58c763ba63eebb70b463a904392e3dc67d5d0f726bdb778c7b25:1))
2022-04-07T12:17:54UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
```

**Comment by Christewart** [comment]
fixed in #4290 / #4296
