### ISSUE TITLE
Error when sweeping wallet `Error -26: insufficient fee, rejecting replacement`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4254]
This was on 1bc3962c when attempting to sweep the wallet to get a fresh set of utxos to avoid issues like #4229

```
2022-04-07T18:30:00UTC INFO [DLCWallet$DLCWalletImpl] Found 6 matches from start=730831 to end=730872
2022-04-07T18:30:00UTC INFO [DLCWallet$DLCWalletImpl] Matched 20 blocks on rescan
2022-04-07T18:30:00UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:30:00UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:30:00UTC INFO [DLCClient] connecting to i3bfhauurptgypgnolqmj7xxv7pcs5c6udtzthbgojc7eaxx6zbbjyad.onion/<unresolved>:2862 via SOCKS5 localhost/127.0.0.1:64029
2022-04-07T18:30:00UTC INFO [DLCWallet$DLCWalletImpl] addressCount=67 externalGap=17
2022-04-07T18:30:00UTC INFO [DLCWallet$DLCWalletImpl] We have a small number of addresses preloaded into the wallet
2022-04-07T18:30:00UTC INFO [DLCWallet$DLCWalletImpl] Finished rescanning the wallet. It took 1101866ms
2022-04-07T18:30:02UTC INFO [DLCClient] connected to i3bfhauurptgypgnolqmj7xxv7pcs5c6udtzthbgojc7eaxx6zbbjyad.onion/<unresolved>:2862 via SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 182518380ff3e05a9c2be80034d5822b99df44098fe03b507ea05f7bc39fe113
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=5000 sats with feeRate=4 sats/vbyte
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(88501f0a6126bdb173898bbf8d53581a8525452badee4baf91331cec0c1a8eeb:1), TransactionOutPoint(01d848a453f0e52394a095297bc0304331b0bac53961ad4dccedaa9bfaabb231:0))
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1qg0dep4j8v72e4tqjj8j297hghze3e337ljvm94 path=m/84'/0'/0'/1/19 isChange=true
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(88501f0a6126bdb173898bbf8d53581a8525452badee4baf91331cec0c1a8eeb:1) state=ConfirmedReceived, TransactionOutPoint(01d848a453f0e52394a095297bc0304331b0bac53961ad4dccedaa9bfaabb231:0) state=ConfirmedReceived)
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(4626 sats,wpkh(a16a3d592db7e3b3dbad468b3770b27797c30ed6))
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] UTXO 1 details: TransactionOutput(5454 sats,wpkh(9c13a0dfe5e42b82d05d8aae229deb710040755e))
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId 182518380ff3e05a9c2be80034d5822b99df44098fe03b507ea05f7bc39fe113
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for a52dcd89394f4bc63338429c8dfcd340b11cf30e5766c6a5b4bd9c60ca8a23d8
2022-04-07T18:30:02UTC INFO [DLCWallet$DLCWalletImpl] Created DLCAccept for tempContractId 182518380ff3e05a9c2be80034d5822b99df44098fe03b507ea05f7bc39fe113 with contract Id a52dcd89394f4bc63338429c8dfcd340b11cf30e5766c6a5b4bd9c60ca8a23d8
2022-04-07T18:42:47UTC INFO [BitcoindRpcBackendUtil$] Bitcoind has new block(s), requesting... 1 blocks
2022-04-07T18:42:47UTC INFO [BitcoindRpcBackendUtil$] Fetching 1 blocks from bitcoind
2022-04-07T18:42:57UTC INFO [BitcoindRpcBackendUtil$] Skipping scanning the blockchain since a previously scheduled task is still running
2022-04-07T18:42:57UTC INFO [BitcoindRpcBackendUtil$] Skipping scanning the mempool since a previously scheduled task is still running
2022-04-07T18:42:58UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000000b0cb3b10f7af7c85992095ff0944318ce0dd7b398a9b
2022-04-07T18:43:07UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000000b0cb3b10f7af7c85992095ff0944318ce0dd7b398a9b. It took 8287ms
2022-04-07T18:43:07UTC INFO [BitcoindRpcBackendUtil$] Skipping scanning the blockchain since a previously scheduled task is still running
2022-04-07T18:49:38UTC INFO [DLCServer] Received a connection from /127.0.0.1:36578
2022-04-07T18:49:39UTC INFO [DLCDataHandler] Received LnMessage SendOfferTLV
2022-04-07T18:49:51UTC INFO [DLCClient] connecting to SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:49:51UTC INFO [DLCClient] connected to SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:49:51UTC INFO [DLCClient] connecting to i3bfhauurptgypgnolqmj7xxv7pcs5c6udtzthbgojc7eaxx6zbbjyad.onion/<unresolved>:2862 via SOCKS5 localhost/127.0.0.1:64029
2022-04-07T18:49:55UTC INFO [DLCClient] connected to i3bfhauurptgypgnolqmj7xxv7pcs5c6udtzthbgojc7eaxx6zbbjyad.onion/<unresolved>:2862 via SOCKS5 proxy localhost/127.0.0.1:64029
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Creating DLC Accept for tempContractId 4319a3eda63dc97073be0896691b61c782b66b69fe5c448fcf44b1338a360a70
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Attempting to fund a tx for amt=5000 sats with feeRate=4 sats/vbyte
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Reserving utxos=Vector(TransactionOutPoint(e6e8170cb436d60121c5117641e7d728c7d6d85183b74784736f2e53bc6053ae:2))
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1qkfr4huc0k0wrzw87nkh72vzrjzn0kgywmvrd9w path=m/84'/0'/0'/1/20 isChange=true
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Spending UTXOs: Vector(TransactionOutPoint(e6e8170cb436d60121c5117641e7d728c7d6d85183b74784736f2e53bc6053ae:2) state=ConfirmedReceived)
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] UTXO 0 details: TransactionOutput(9789 sats,wpkh(dc9771be037290e84f960ab86f8c097315e50e49))
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Initializing DLC from received offer with tempContractId 4319a3eda63dc97073be0896691b61c782b66b69fe5c448fcf44b1338a360a70
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Creating CET Sigs for e856bb8b21e3f7e50dc199e4213f68acc65757e01aebd116aa8c6c75f1e4a8f2
2022-04-07T18:49:55UTC INFO [DLCWallet$DLCWalletImpl] Created DLCAccept for tempContractId 4319a3eda63dc97073be0896691b61c782b66b69fe5c448fcf44b1338a360a70 with contract Id e856bb8b21e3f7e50dc199e4213f68acc65757e01aebd116aa8c6c75f1e4a8f2
2022-04-07T18:50:31UTC INFO [DLCWallet$DLCWalletImpl] Generated new address=bc1q9ufdsgurn3rx347frwue28m94c2j86z49xys7y path=m/84'/0'/0'/0/52 isChange=false
2022-04-07T18:50:47UTC INFO [DLCWallet$DLCWalletImpl] Sweeping wallet balance=1016680 sats to address=bc1q9ufdsgurn3rx347frwue28m94c2j86z49xys7y
2022-04-07T18:50:47UTC INFO [DLCWallet$DLCWalletImpl] Sending to bc1q9ufdsgurn3rx347frwue28m94c2j86z49xys7y at feerate 4 sats/vbyte
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] Processing TX from our wallet, transaction=14d13aaf221648a61a826df20c09f58307d27baf13928de1a945f01deed69e97 with blockHash=None
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 14d13aaf221648a61a826df20c09f58307d27baf13928de1a945f01deed69e97:0 amt=1014344 sats into DB
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, it took=35ms
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] 8 txos are now confirmed!
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 8 spent outputs, it took=51ms
2022-04-07T18:50:48UTC INFO [DLCWallet$DLCWalletImpl] Processing of internal transaction=14d13aaf221648a61a826df20c09f58307d27baf13928de1a945f01deed69e97 resulted in changeOutputs=1 and spentUTXOs=8
2022-04-07T18:50:48UTC ERROR [BitcoindV22RpcClient] org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: insufficient fee, rejecting replacement 14d13aaf221648a61a826df20c09f58307d27baf13928de1a945f01deed69e97; new feerate 0.00004000 BTC/kvB <= old feerate 0.00004015 BTC/kvB
2022-04-07T18:50:48UTC INFO [Server] Unhandled error in server:
org.bitcoins.rpc.BitcoindException$VerifyRejected: Error -26: insufficient fee, rejecting replacement 14d13aaf221648a61a826df20c09f58307d27baf13928de1a945f01deed69e97; new feerate 0.00004000 BTC/kvB <= old feerate 0.00004015 BTC/kvB
	at org.bitcoins.rpc.BitcoindException$.$anonfun$all$12(BitcoindException.scala:57)
	at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:126)
	at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
	at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
	at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
	at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:443)
	at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
fixed in #4290 / #4296
