### ISSUE TITLE
Failed to process `LnMessage(DLCAcceptTLV)` ` requirement failed: Funding ScriptSignatureParams did not match offer funding inputs`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4256]
Seen on 6b3be779 . Maybe related to #4255 ?

```
2022-04-08T19:46:27UTC INFO [DLCServer] Received a connection from /127.0.0.1:38862
2022-04-08T19:46:28UTC INFO [DLCDataHandler] Received LnMessage DLCAcceptTLV
2022-04-08T19:46:28UTC INFO [DLCWallet$DLCWalletImpl] Verifying 2 CET Signatures
2022-04-08T19:46:29UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(DLCAcceptTLV(Sha256DigestImpl(2a956dcd3d345db30169c5c8ef4fdda01f3803a6a91ae4a84a9257b5100955cf),10000 sats,ECPublicKey(022b875e87efd8028bc44894f1d0f4fcce8ae8445abb1eadaa0d560f51b2ba6ff0),wsh(93037e6eaebd4d664831b2d6500a8f8c37d6f4a307c4c4f02d476459381cccbb),UInt64Impl(7905270604907022231),Vector(FundingInputV0TLV(UInt64Impl(10347967855633322532),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(b047f5fdb1b854c8ad207bea1103f4431d4aefb448bdacec12ab77193f0a08a5:0),EmptyScriptSignature,UInt32Impl(4294967294))),Vector(TransactionOutput(10000 sats,wpkh(20896ff88ca36f090c1ca2de89b7e539956cd934))),UInt32Impl(1649376000),IndexedSeq(P2WSHWitnessV0(List(522102337f74688f664b96b2baf71dc45f9430160ee9aaee3592b922dc3501165c15232103370e2d305865e0900d20f8b2f11eaaa4d1ffc9a503e5e481a06443f62397ad1552ae, 304402201dea8467380153051447c79e16fd438e3dba91620b615368ffc1a6bea8582bf8022069eba4f7e33aafdf27d4ac9daead5476268f5f233eca5f6de0a71e54dbbcc5b201, 3045022100e02a931b24c3e51551d1ffcb300b34784a5a459f1928f25bd9088092667a250d0220108dfcfcf4bdcfa193043d152f447210a2b5eefc60677bf4fffe30b6c85c501b01, )))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(12504171043149483775),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(e6e8170cb436d60121c5117641e7d728c7d6d85183b74784736f2e53bc6053ae:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(e6e8170cb436d60121c5117641e7d728c7d6d85183b74784736f2e53bc6053ae:2),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(5c4ffa8f8be4452d7d25b3ac0684456a6fa74159b8ca74fe4d3ad43f12588361:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(88501f0a6126bdb173898bbf8d53581a8525452badee4baf91331cec0c1a8eeb:1),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(1465524 sats,wpkh(28f5719c2f4357fde05ff3372e37e7d4f951ee85)), TransactionOutput(9124 sats,wpkh(f9eb7ab127d9614033f75f2e04282461d366352c)), TransactionOutput(10194 sats,wsh(de2497affb736416890d4519b16c13e6c06157404aec92b93f796a8ac6e6ba9c))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(02f64f822eb08c4ddd5afc8961eb15ef7fde0c4ad264ca62798aa34692a70d7e4f, 3044022067d991f533ff57a1240b7d3e52f964d4193c77aba8a0118ee9d0f4765eee3de302201a7419cedf2b90ffee2f6bb71bbb7d2122df1b15112f2f52e1d6bc19202ebcd101)), P2WPKHWitnessV0(List(03959f6a09bdae706fed344fc1c1c6c3e9f3b92efdda469cd9cb2321903cbf5928, 304402201f106234222b6a7a9f508ea52be54eaf1ac1b87f8b575541ed73b4e640e1f3d502203b39eb79a9517291bc71c157e02b98b3ddcf7693b011e5958f7692f4b0fa0b6001)), P2WPKHWitnessV0(List(020355533db028908c474ced87626b49aa79ab3d1d835b13beaa25eba6ef03590c, 3044022025476f5f33c6c30c1013eeb7e1ae26db5f72fa771621d770cc298487e8e7a13f02201dcd174446ea71e7e2d79fb93f18c071d43660aca739a409b13a5c99bd7daece01)), P2WPKHWitnessV0(List(03e29b72ecdedadde09b44ec2c4499eef9ce0b87a004127d63243679ac59613b0d, 3044022031abf1f2719680ff6153c5a7e5c6f6d76d47d71ea929c92a4ac4c86e7470a74d0220723a6cf372912f2b4cd1bbc97acf0cdbdd47037e11d36ed854b3b915ce937dfb01)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(76cc2bf1676732ead74f052899c561448a109bf5),UInt64Impl(2072995892688999397),org.bitcoins.core.protocol.tlv.CETSignaturesV0TLV@227aa986,ECDigitalSignature(304402205fc337554ad6c9a24bebcbe5241fbfde77853942ec40725e2c2158ec4c0672b302205334b898c70f8c80e18a7c529dda89ba529d4a13489b64174e9791b30be587fc),NoNegotiationFieldsTLV)) 
java.lang.IllegalArgumentException: requirement failed: Funding ScriptSignatureParams did not match offer funding inputs
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.core.protocol.dlc.sign.DLCTxSigner.<init>(DLCTxSigner.scala:61)
	at org.bitcoins.dlc.wallet.internal.DLCDataManagement.$anonfun$signerFromDb$3(DLCDataManagement.scala:511)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
fixed in #4290 / #4296
