### ISSUE TITLE
`[SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)` when processing block

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4297]
Seen on 4b964074 when processing a block on my umbrel this morning. I'm not sure what the root cause is

```
 2022-04-28T03:11:57UTC INFO [BitcoindRpcBackendUtil$] Fetching 1 blocks from bitcoind
2022-04-28T03:11:58UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000779b40ecfb60de84f11fc7e598c668fa4623987d25fd2
2022-04-28T03:11:59UTC ERROR [SafeDatabase] Error when executing query flatMap slick.dbio.DBIOAction$$Lambda$1087/0x000000080111a680@51b4f6f2
2022-04-28T03:11:59UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
2022-04-28T03:11:59UTC ERROR [BitcoindRpcBackendUtil$] Requesting blocks from bitcoind polling failed, range=[733898, 733899]
org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:311)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:375)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:365)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:489)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-04-28T03:11:59UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=0000000000000000000779b40ecfb60de84f11fc7e598c668fa4623987d25fd2.
org.sqlite.SQLiteException: [SQLITE_TOOBIG]  String or BLOB exceeds size limit (statement too long)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4
```

**Comment by Christewart** [comment]
Restarting my umbrel seemed to fix this. I'm still unsure what the root cause is

**Comment by Christewart** [comment]
This happened on another users umbrel wallet. I think this might have happened on all users wallets. I'm going to reach out to more users to see if everyone's wallet got corrupted by this.

**Comment by Christewart** [comment]
Likely culprit: https://mempool.space/tx/4051940733182aaa096b3423bc0fcf975795a8f47f16bbc84a919ae1a2efe68b

**Comment by Christewart** [comment]
I can reproduce this bug on 4b96407 and i can also reproduce on the latest master 79b4f096ecf9c21d125c2d37585182c7470dc47c
