### ISSUE TITLE
Wallet is attempting to rebroadcast transaction even when the tx is already in the blockchain

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4303]
Seen from a user's logs on 4b964074

```
2022-04-28T21:51:50UTC INFO [WalletAppConfig$] Rebroadcasting 8 transactions, txids=Vector(DoubleSha256BDigestBE(00bc1d8498f247e22eba02fe9442146348bc2379f388c012bf6835b407164bda), DoubleSha256BDigestBE(081ce598ae2bcd3ef7c60f8c7dd70bf3e794327117a08b04913d7611dac2a8a1), DoubleSha256BDigestBE(282855b97e5d2878da06f88c439979cf3a33239e7342868dd98398fece01b936), DoubleSha256BDigestBE(62d36d46e2afbcee4c347a29b9d289035d9d20f584b055a4c737d76aa221e5fe), DoubleSha256BDigestBE(643fba9a2fcb76d9d3d93a9e882f8a60078202debf796f9bb4e114e8db5a3473), DoubleSha256BDigestBE(80ab4badffcc53a1427c30458b348d1e4f7c56a0a57df21beac45783d0517cf1), DoubleSha256BDigestBE(99edc752c5dcbaa6159bcfdd6df5138fa063fc3da66fffaa3ef9fa5440b4dfad), DoubleSha256BDigestBE(d65ea08d972fa3d0b65577696785df55b9a07788b5d1c95967b132d6223e6074))
2022-04-28T21:51:50UTC ERROR [BitcoindV22RpcClient] org.bitcoins.rpc.BitcoindException$VerifyAlreadyInChain: Error -27: Transaction already in block chain
2022-04-28T21:51:50UTC ERROR [WalletAppConfig$] Failed to broadcast txs
org.bitcoins.rpc.BitcoindException$VerifyAlreadyInChain: Error -27: Transaction already in block chain
	at org.bitcoins.rpc.BitcoindException$.$anonfun$all$13(BitcoindException.scala:58)
	at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:126)
	at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
	at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
	at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
	at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:443)
	at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
These probably need to be removed from the table when we process a block that contains the transaction.
