### ISSUE TITLE
`jlink` build results in `java.lang.NoClassDefFoundError: scala/reflect/ClassTag$cache$` 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4325]
I saw this on c911808996fa8aa3e9b13f956d6462867afe5c8a when trying to run with this webpack config @user411 provided: 

https://github.com/bitcoin-s/bitcoin-s-ts/pull/130#issuecomment-1121211695

I'm not sure about the webpack config provided, but it seems that regardless this is a build error.

```
✔ Compiling Renderer Code
Issues checking in progress...
[2635142:0509/102753.935672:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
bitcoin-s-oracle-server error: Exception in thread "main" bitcoin-s-oracle-server error: java.lang.NoClassDefFoundError: scala/reflect/ClassTag$cache$
        at scala.reflect.ClassTag$.apply(ClassTag.scala:157)
        at scala.collection.immutable.ArraySeq$ofRef.elemTag(ArraySeq.scala:328)
        at scala.collection.immutable.Vector$.from(Vector.scala:46)
bitcoin-s-oracle-server error:  at scala.collection.immutable.Vector$.from(Vector.scala:34)
        at scala.collection.IterableFactory.apply(Factory.scala:103)
        at scala.collection.IterableFactory.apply$(Factory.scala:103)
bitcoin-s-oracle-server error:  at scala.collection.immutable.Vector$.apply(Vector.scala:34)
        at org.bitcoins.commons.util.DatadirParser.baseConfig$lzycompute(DatadirParser.scala:38)
        at org.bitcoins.commons.util.DatadirParser.baseConfig(DatadirParser.scala:34)
bitcoin-s-oracle-server error:  at org.bitcoins.commons.util.DatadirParser.datadir$lzycompute(DatadirParser.scala:54)
        at org.bitcoins.commons.util.DatadirParser.datadir(DatadirParser.scala:53)
        at org.bitcoins.commons.util.DatadirParser.networkDir(DatadirParser.scala:63)
bitcoin-s-oracle-server error:  at org.bitcoins.oracle.server.OracleServerMain$.delayedEndpoint$org$bitcoins$oracle$server$OracleServerMain$1(OracleServerMain.scala:83)
        at org.bitcoins.oracle.server.OracleServerMain$delayedInit$body.apply(OracleServerMain.scala:70)
bitcoin-s-oracle-server error:  at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
bitcoin-s-oracle-server error:  at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
bitcoin-s-oracle-server error:  at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at org.bitcoins.oracle.server.OracleServerMain$.main(OracleServerMain.scala:70)
        at org.bitcoins.oracle.server.OracleServerMain.main(OracleServerMain.scala)
bitcoin-s-oracle-server error: Caused by: java.lang.ClassNotFoundException: scala.reflect.ClassTag$cache$
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
bitcoin-s-oracle-server error:  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 26 more
```

**Comment by Christewart** [comment]
I don't think this is an error, i think my local state was somehow messed up. I haven't seen this since the initial report and builds seem to be working fine
