### ISSUE TITLE
`java.lang.IllegalArgumentException: requirement failed: Cannot add utxos to wallet if we have none! got=Vector()`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4351]
This occurred on 3dc70938 on my umbrel node when rescanning

```
2022-05-25T14:45:28UTC INFO [DLCWallet$DLCWalletImpl] Processing spent utxos in tx 6c630afa50112a6647c51e7aa2d7320e96cb03bc36109e17b6da54ef7e8b705a for 1 DLC(s)
2022-05-25T14:45:29UTC ERROR [DLCWallet$DLCWalletImpl] Failed to process transaction=6999f6da460fe019385b9276277d0c2f889d0f5aca71d7a5dcb0c9a5f8dc98f7 blockHash=Some(DoubleSha256BDigestBE(00000000000000000000ae50544dd754d879e5c113004fa13101b98a7bb13b4d))
java.lang.IllegalArgumentException: requirement failed: Cannot add utxos to wallet if we have none! got=Vector()
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.wallet.internal.TransactionProcessing.addReceivedUTXOs(TransactionProcessing.scala:571)
        at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processNewReceivedTx$24(TransactionProcessing.scala:763)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-05-25T14:45:29UTC ERROR [DLCWallet$DLCWalletImpl] Failed to rescan wallet
java.lang.IllegalArgumentException: requirement failed: Cannot add utxos to wallet if we have none! got=Vector()
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.wallet.internal.TransactionProcessing.addReceivedUTXOs(TransactionProcessing.scala:571)
        at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processNewReceivedTx$24(TransactionProcessing.scala:763)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-05-25T14:45:29UTC ERROR [DLCWallet$DLCWalletImpl] Error processing of block=00000000000000000000ae50544dd754d879e5c113004fa13101b98a7bb13b4d.
java.lang.IllegalArgumentException: requirement failed: Cannot add utxos to wallet if we have none! got=Vector()
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.wallet.internal.TransactionProcessing.addReceivedUTXOs(TransactionProcessing.scala:571)
        at org.bitcoins.wallet.internal.TransactionProcessing.$anonfun$processNewReceivedTx$24(TransactionProcessing.scala:763)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
This is the transaction that caused this exception [`6999f6da460fe019385b9276277d0c2f889d0f5aca71d7a5dcb0c9a5f8dc98f7`](https://mempool.space/tx/6999f6da460fe019385b9276277d0c2f889d0f5aca71d7a5dcb0c9a5f8dc98f7)

I believe the output causing the exception is at index 0 corresponding to address [`bc1q5hmfsf5da0l2fadfdp8ea3032aeltvpp4cwuw9sf99j8jjyu0rkqh7f2qv`](https://mempool.space/address/bc1q5hmfsf5da0l2fadfdp8ea3032aeltvpp4cwuw9sf99j8jjyu0rkqh7f2qv)

The spk that corresponds to that address does live in my `pub_key_scripts` table 

![Screenshot from 2022-05-25 14-40-32](https://user-images.githubusercontent.com/3514957/170353931-aca2251a-c65c-4faf-938d-3dcdfd1dda72.png)

but the address does not exist in my `addresses` table

![Screenshot from 2022-05-25 14-42-00](https://user-images.githubusercontent.com/3514957/170354171-09cf8887-2008-4953-931b-0bed503e2216.png)
