### ISSUE TITLE
Need to retry connecting to bitcoind when we get error `org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4358]
Seen on 3dc70938 on umbrel

I rebooted my umbrel and apparently bitcoind was not in sync. When the wallet tried to start up, it got this error message. Notably, it does not try to re-connect to bitcoind after blocks are done verifying.
 

```
2022-06-01T12:21:51UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=38029ms
2022-06-01T12:21:51UTC INFO [BitcoinSServerMain] startBitcoindBackend()
2022-06-01T12:22:19UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
2022-06-01T12:22:19UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
2022-06-01T12:22:19UTC ERROR [BitcoinSServerMain] Failed to startup server!
org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
        at org.bitcoins.rpc.BitcoindException$.$anonfun$all$14(BitcoindException.scala:59)
        at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
        at scala.Option.map(Option.scala:242)
        at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
        at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
        at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
        at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
        at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
        at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
        at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
        at play.api.libs.json.JsValue.validate(JsValue.scala:17)
        at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
        at play.api.libs.json.JsObject.validate(JsValue.scala:126)
        at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
        at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
        at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
        at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:443)
        at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
Done in #4386
