### ISSUE TITLE
`Read NULL value (null) for ResultSet column <computed> slick.SlickException: Read NULL value (null) for ResultSet column <computed>`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4437]
This occurred on startup on 20bf1e6a . It appears to be related to syncing the node.

It happens consistently when i startup.

I checked out  305e920784724c5dcaf380965a1bf4d5f3c0f705 (commit before #4408 ) and everything works ok so it looks like this was introduced in #4408 

```
2022-06-29T15:54:00UTC INFO [BitcoinSServerMain] version=1.9.2-25-20bf1e6a-SNAPSHOT jdkVersion=1.8.0_292
2022-06-29T15:54:00UTC INFO [BitcoinSServerMain] Starting appServer
2022-06-29T15:54:00UTC INFO [TorAppConfig] Starting Tor daemon
2022-06-29T15:54:00UTC INFO [TorClient$] Using tor daemon already written to datadir=/home/chris/.bitcoin-s/tor
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.878 [notice] Tor 0.4.6.10 (git-22fd351cf582aa2b) running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.878 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.878 [notice] Configuration file "/var/tmp/dist/tor/etc/tor/torrc" not present, using reasonable defaults.
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.884 [notice] Opening Socks listener on 127.0.0.1:9050
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.884 [notice] Opened Socks listener connection (ready) on 127.0.0.1:9050
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.884 [notice] Opening Control listener on 127.0.0.1:40197
2022-06-29T15:54:00UTC INFO [NativeProcessFactory$] Jun 29 10:54:00.884 [notice] Opened Control listener connection (ready) on 127.0.0.1:40197
2022-06-29T15:54:01UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-06-29T15:54:01UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-06-29T15:54:01UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-06-29T15:54:01UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:01UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:01UTC INFO [VersionPrinter]
2022-06-29T15:54:01UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-06-29T15:54:01UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.016s)
2022-06-29T15:54:01UTC INFO [DbMigrate] Current version of schema "main": 6
2022-06-29T15:54:01UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-06-29T15:54:01UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:01UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:01UTC INFO [VersionPrinter]
2022-06-29T15:54:01UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-06-29T15:54:01UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.010s)
2022-06-29T15:54:01UTC INFO [DbMigrate] Current version of schema "main": 15
2022-06-29T15:54:01UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-06-29T15:54:01UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-06-29T15:54:01UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-06-29T15:54:01UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-06-29T15:54:01UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-06-29T15:54:02UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV walletName=None
2022-06-29T15:54:02UTC INFO [ChainAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@2a3032b to chain project
2022-06-29T15:54:02UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@16b4f3e6 to the wallet project
2022-06-29T15:54:02UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=1998ms
2022-06-29T15:54:02UTC INFO [BitcoinSServerMain] startBitcoinSBackend()
2022-06-29T15:54:02UTC INFO [BitcoinSServerMain] Chain work already calculated
2022-06-29T15:54:02UTC INFO [FeeProviderFactory$] Using fee provider: MempoolSpaceProvider(HourFeeTarget,MainNet,None)
2022-06-29T15:54:02UTC INFO [BitcoinSServerMain] Initialized chain api
2022-06-29T15:54:02UTC INFO [DLCAppConfig$] Using pre-existing wallet
2022-06-29T15:54:02UTC WARN [Server] RPC password is not set (rpchost=127.0.0.1)
2022-06-29T15:54:03UTC INFO [BitcoinSServerMain] Done configuring wallet, it took=1173ms
2022-06-29T15:54:03UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
2022-06-29T15:54:03UTC INFO [BitcoinSServerMain] Done configuring node, it took=1178ms
2022-06-29T15:54:03UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV
2022-06-29T15:54:03UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:03UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:03UTC INFO [VersionPrinter]
2022-06-29T15:54:03UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.012s)
2022-06-29T15:54:03UTC INFO [DbMigrate] Current version of schema "main": 15
2022-06-29T15:54:03UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-06-29T15:54:03UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: true
2022-06-29T15:54:03UTC INFO [Server] Started Bitcoin-S websocket at /127.0.0.1:19999
2022-06-29T15:54:03UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2022-06-29T15:54:03UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=1664ms
2022-06-29T15:54:03UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyaghYHAYjB4MDxtYH4VZpLhkbeQotz84fVi2p98XT6vxfgjPN9Kxp3v4SfJbYAugy5hB5h3dKXwir8751LV2cyzb49RoHuV walletName=None
2022-06-29T15:54:03UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@51488645 to the wallet project
2022-06-29T15:54:03UTC INFO [TorProtocolHandler] Tor version 0.4.6.10
2022-06-29T15:54:03UTC INFO [TorController$] Created hidden service with address=dmqnyzfhdeq4tdgnl7jtnrmwsklyzhf4lsbmwufmz3pzzongzxd3ilyd.onion:2862
2022-06-29T15:54:03UTC INFO [DLCServer] Bound at /0:0:0:0:0:0:0:0:2862
2022-06-29T15:54:05UTC INFO [WalletAppConfig] Starting wallet rebroadcast task
2022-06-29T15:54:22UTC INFO [TorAppConfig] Tor daemon is fully started, it took=22136ms
2022-06-29T15:54:22UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:22UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:22UTC INFO [VersionPrinter]
2022-06-29T15:54:22UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2022-06-29T15:54:22UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:22UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:22UTC INFO [VersionPrinter]
2022-06-29T15:54:22UTC INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.003s)
2022-06-29T15:54:22UTC INFO [DbMigrate] Current version of schema "main": 8
2022-06-29T15:54:22UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-06-29T15:54:22UTC INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@1d490cb5 to the dlc project
2022-06-29T15:54:22UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-06-29T15:54:22UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-06-29T15:54:22UTC INFO [VersionPrinter]
2022-06-29T15:54:22UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2022-06-29T15:54:22UTC INFO [DbValidate] Successfully validated 4 migrations (execution time 00:00.001s)
2022-06-29T15:54:22UTC INFO [DbMigrate] Current version of schema "main": 4
2022-06-29T15:54:22UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-06-29T15:54:22UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@38ce5860 migrations fro the node project
2022-06-29T15:54:22UTC INFO [NeutrinoNode] Starting node
2022-06-29T15:54:23UTC INFO [PeerFinder] Peer discovery disabled.
2022-06-29T15:54:23UTC INFO [PeerManager] Done starting PeerManager
2022-06-29T15:54:23UTC INFO [NeutrinoNode] Our node has been full started. It took=78ms
2022-06-29T15:54:23UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000000000919807edfc8d547da2dba17858b42f7b37b5c1f382c11 at height 742167, with 742129 filter headers and 742129 filters
2022-06-29T15:54:23UTC INFO [HikariDataSource] bitcoin-s-node-db - Starting...
2022-06-29T15:54:23UTC INFO [HikariDataSource] bitcoin-s-node-db - Start completed.
2022-06-29T15:54:23UTC ERROR [OneForOneStrategy] Read NULL value (null) for ResultSet column <computed>
slick.SlickException: Read NULL value (null) for ResultSet column <computed>
        at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:27)
        at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
        at slick.relational.ProductResultConverter.read(ResultConverter.scala:54)
        at slick.relational.ProductResultConverter.read(ResultConverter.scala:44)
        at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:134)
        at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:36)
        at slick.jdbc.StatementInvoker$$anon$2.extractValue(StatementInvoker.scala:67)
        at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
        at slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
        at slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
        at slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
        at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
        at slick.jdbc.Invoker.foreach(Invoker.scala:48)
        at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
        at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
        at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
        at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
        at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
        at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Christewart** [comment]
Our current working thesis of why i saw this bug: 

<img width="858" alt="Screen Shot 2022-06-29 at 4 31 57 PM" src="https://user-images.githubusercontent.com/3514957/176548695-65fcd411-fdde-46f7-b65f-557eac12726b.png">

**Comment by Christewart** [comment]
Closing this as I believe @shreyanshyad was correct

**Comment by user411** [comment]
`delete from peers where service_bytes is null;` in the nodedb.sqlite worked for me to correct.
