### ISSUE TITLE
Blockchain parsing failure for taproot txs

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4455]
I thought this was only on #3769 but seems to be in master as well (2b60bbb1c359737f896b4f3957af476a68dd0685)

```
2022-07-06T23:41:11UTC INFO [ScanBitcoind] Searching block at height=710040 hashBE=0000000000000000000b273de637ae22e33a76c7822c8bb79311ddeab3029f1e
2022-07-06T23:41:11UTC ERROR [ScanBitcoind] Failed to count witness v1 mempool txs
java.lang.IllegalArgumentException: requirement failed: DoubleSha256Digest must always be 32 bytes, got: 0
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.crypto.DoubleSha256Digest.<init>(HashDigest.scala:112)
        at org.bitcoins.crypto.DoubleSha256Digest$.fromBytes(HashDigest.scala:125)
        at org.bitcoins.crypto.DoubleSha256Digest$.fromBytes(HashDigest.scala:121)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.transaction.RawTransactionOutPointParser.read(RawTransactionOutPointParser.scala:22)
        at org.bitcoins.core.protocol.transaction.TransactionOutPoint$.fromBytes(TransactionOutPoint.scala:53)
        at org.bitcoins.core.protocol.transaction.TransactionOutPoint$.fromBytes(TransactionOutPoint.scala:48)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.transaction.RawTransactionInputParser.read(RawTransactionInputParser.scala:20)
        at org.bitcoins.core.protocol.transaction.TransactionInput$.fromBytes(TransactionInput.scala:58)
        at org.bitcoins.core.protocol.transaction.TransactionInput$.fromBytes(TransactionInput.scala:34)
        at org.bitcoins.core.util.BytesUtil.loop$1(BytesUtil.scala:33)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq(BytesUtil.scala:42)
        at org.bitcoins.core.util.BytesUtil.parseCmpctSizeUIntSeq$(BytesUtil.scala:21)
        at org.bitcoins.core.util.BytesUtil$.parseCmpctSizeUIntSeq(BytesUtil.scala:52)
        at org.bitcoins.core.protocol.transaction.BaseTransaction$.fromBytes(Transaction.scala:163)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:131)
        at org.bitcoins.core.protocol.transaction.Transaction$.fromBytes(Transaction.scala:109)
        at org.bitcoins.crypto.Factory.apply(Factory.scala:53)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.$anonfun$read$1(RawBlockSerializer.scala:19)
        at org.bitcoins.core.serializers.RawSerializerHelper.loop$1(RawBitcoinSerializerHelper.scala:29)
        at org.bitcoins.core.serializers.RawSerializerHelper.parseCmpctSizeUIntSeq(RawBitcoinSerializerHelper.scala:39)
        at org.bitcoins.core.serializers.blockchain.RawBlockSerializer.read(RawBlockSerializer.scala:19)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:73)
        at org.bitcoins.core.protocol.blockchain.Block$.fromBytes(Block.scala:48)
        at org.bitcoins.crypto.Factory.fromHex(Factory.scala:13)
        at org.bitcoins.commons.serializers.JsonReaders$BlockReads$.$anonfun$reads$17(JsonReaders.scala:298)
        at org.bitcoins.commons.serializers.SerializerUtil.processJsString(SerializerUtil.scala:51)
        at org.bitcoins.commons.serializers.JsonReaders$BlockReads$.reads(JsonReaders.scala:298)
        at play.api.libs.json.JsValue.validate(JsValue.scala:17)
        at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
        at play.api.libs.json.JsString.validate(JsValue.scala:89)
        at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
        at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
        at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
        at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:358)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
This is the problem transaction: https://blockstream.info/tx/a05213473724e2e7f489ae0cbe1d17eef4f6c1b9806e33e5115d85e71d81e994
