### ISSUE TITLE
Investigate `ERRCONNRESET` being returned when `sendoffer` doesn't work over tor

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4467]
I experienced this on 6f6315c1

I failed to send an offer to a user due to tor not working correctly. I cannot connect to the user in question

![Screenshot from 2022-07-08 11-07-11](https://user-images.githubusercontent.com/3514957/178029994-c3eb7d66-9983-41e9-abed-ff86e70d8de9.png)

When then disconnect the frontend which causes the UI to display this 

![Screenshot from 2022-07-08 11-03-05](https://user-images.githubusercontent.com/3514957/178030054-1bbbd7db-1277-483a-9943-7b524e1be167.png)

We need to gracefully handle this case and propagate a intelligent error message back to the UI.

From the developer console: 

![Screenshot from 2022-07-08 14-02-44](https://user-images.githubusercontent.com/3514957/178054783-f537229e-ca29-44f6-b9db-bde1a8bcbd79.png)
![Screenshot from 2022-07-08 14-02-17](https://user-images.githubusercontent.com/3514957/178054787-4078d6b3-e27a-4fe3-a5d0-377c92aac580.png)

**Comment by Christewart** [comment]
So it seems like our exception handler is being hit, we have this message logged. Its unclear to my why the connection is being reset in this case.

https://github.com/bitcoin-s/bitcoin-s/blob/f4d864fab860828fb46b9f42177dd5db09b80311/app/server-routes/src/main/scala/org/bitcoins/server/routes/Server.scala#L75

```
2022-07-08T16:05:04UTC INFO [Server] Unhandled error in server:
java.io.IOException: Cannot connect to gxc7rpq45fnhycoaapo6uckxa4f7p7z36g3xqfn77mkrtop5fs2r5wid.onion:2862 via Tor
        at org.bitcoins.dlc.node.DLCClient$$anonfun$socks5Connecting$1.$anonfun$applyOrElse$4(DLCClient.scala:90)
        at scala.Option.getOrElse(Option.scala:201)
        at org.bitcoins.dlc.node.DLCClient$$anonfun$socks5Connecting$1.applyOrElse(DLCClient.scala:89)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:96)
        at akka.event.LoggingReceive.apply(LoggingReceive.scala:70)
        at scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
        at scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
        at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:70)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at org.bitcoins.dlc.node.DLCClient.aroundReceive(DLCClient.scala:108)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
Unfortunately this isn't reproducible. I still cannot connect on a second attempt, but i didn't get a `ERRCONNRESET` error. I'm unsure of what server load was on the first attempt, but there was plenty of resources available according to `htop`

![Screenshot from 2022-07-08 12-52-30](https://user-images.githubusercontent.com/3514957/178044939-6d1bc581-60f0-4cd5-afb3-49edf6f0d4d7.png)

![Screenshot from 2022-07-08 12-53-10](https://user-images.githubusercontent.com/3514957/178045070-c434d5d4-0412-46ad-a6d7-4db3f8540fcd.png)

**Comment by Christewart** [comment]
I tried to simulate a resource contrained environment on my pi. You can see the core's saturated by i still don't get a `ERRCONNRESET` at the frontend

![Screenshot from 2022-07-08 13-11-45](https://user-images.githubusercontent.com/3514957/178048141-648da5eb-6a3e-4c78-be14-b0ac06a2068a.png)
