### ISSUE TITLE
testnet node doesn't start syncing on server startup

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4502]
This was running on 8e650737bf08b3f00e9846471db063d7f508d620 when testing the #4452 . I don't believe the root cause of this bug is on #4452 though. I believe i've seen this behavior before on other PRs.

If you look carefully at the timestamps on the logs

>2022-07-12T19:05:33UTC

and then when i queried bitcoind to see how many blocks it has

>2022-07-12T19:06:03UTC

and it still hasn't started syncing. 

![Screenshot from 2022-07-12 14-08-16](https://user-images.githubusercontent.com/3514957/178574731-d754995b-5fe3-4db0-b3e8-dca330644adc.png)

**Comment by Christewart** [comment]
So this eventually errors out, i'm attempting to connect to `neutrino.testnet3.suredbits.com:18333`. I'm looking into why i'm not connecting, but regardless it seems like this timeout is a long time. Perhaps we want to reduce that timeout especially the single peer case?

![Screenshot from 2022-07-12 14-19-28](https://user-images.githubusercontent.com/3514957/178576487-c3932afb-2cb7-4d41-ac5f-9ab495a8eb65.png)

**Comment by Christewart** [comment]
So i tried connecting to a local peer, startup seems really slow but it does start syncing eventually it seems

```
[DEBUG] [07/12/2022 14:23:40.138] [main] [EventStream] StandardOutLogger started
[DEBUG] [07/12/2022 14:23:40.548] [main] [EventStream(akka://bitcoin-s-server-1657653819704)] logger log1-Slf4jLogger started
[DEBUG] [07/12/2022 14:23:40.553] [main] [EventStream(akka://bitcoin-s-server-1657653819704)] Default Loggers started
2022-07-12T19:23:40UTC INFO [BitcoinSServerMain] version=1.9.2-77-8e650737-SNAPSHOT jdkVersion=18
2022-07-12T19:23:40UTC INFO [BitcoinSServerMain] Starting appServer
2022-07-12T19:23:41UTC WARN [TorAppConfig] Tor daemon was requested to start, but it is disabled in the configuration file. Not starting tor
2022-07-12T19:23:41UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:41UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:41UTC INFO [VersionPrinter]
2022-07-12T19:23:41UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/dlcdb.sqlite (SQLite 3.36)
2022-07-12T19:23:41UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:41UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:41UTC INFO [VersionPrinter]
2022-07-12T19:23:41UTC INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.009s)
2022-07-12T19:23:41UTC INFO [DbMigrate] Current version of schema "main": 8
2022-07-12T19:23:41UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-12T19:23:41UTC INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@745d6026 to the dlc project
2022-07-12T19:23:41UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:41UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:41UTC INFO [VersionPrinter]
2022-07-12T19:23:41UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/nodedb.sqlite (SQLite 3.36)
2022-07-12T19:23:41UTC INFO [DbValidate] Successfully validated 4 migrations (execution time 00:00.004s)
2022-07-12T19:23:41UTC INFO [DbMigrate] Current version of schema "main": 4
2022-07-12T19:23:41UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-12T19:23:41UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@1ea989c2 migrations fro the node project
2022-07-12T19:23:41UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=vpub5SLqN2bLY4WeaPvECr23tpgLY6JkWaXa9tcsU4qGNxcYT6T7oWUGxrJQaru3NWiHBVSqSkvMhXVVRwEvCuPa8bDKNmKNfhD5Y5k1VrAHj4o
2022-07-12T19:23:41UTC INFO [BitcoinSServerMain] Start on network TestNet3
2022-07-12T19:23:41UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:41UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:41UTC INFO [VersionPrinter]
2022-07-12T19:23:41UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/chaindb.sqlite (SQLite 3.36)
2022-07-12T19:23:41UTC INFO [DbValidate] Successfully validated 7 migrations (execution time 00:00.005s)
2022-07-12T19:23:41UTC INFO [DbMigrate] Current version of schema "main": 7
2022-07-12T19:23:41UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-12T19:23:42UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=vpub5SLqN2bLY4WeaPvECr23tpgLY6JkWaXa9tcsU4qGNxcYT6T7oWUGxrJQaru3NWiHBVSqSkvMhXVVRwEvCuPa8bDKNmKNfhD5Y5k1VrAHj4o
2022-07-12T19:23:42UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:42UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:42UTC INFO [VersionPrinter]
2022-07-12T19:23:42UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/chris/.bitcoin-s/testnet3/walletdb.sqlite (SQLite 3.36)
2022-07-12T19:23:42UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.010s)
2022-07-12T19:23:42UTC INFO [DbMigrate] Current version of schema "main": 15
2022-07-12T19:23:42UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-12T19:23:42UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-07-12T19:23:42UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-07-12T19:23:42UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-07-12T19:23:42UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-07-12T19:23:42UTC INFO [ChainAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@599b26de to chain project
2022-07-12T19:23:42UTC INFO [WalletAppConfig] Starting wallet with xpub=vpub5SLqN2bLY4WeaPvECr23tpgLY6JkWaXa9tcsU4qGNxcYT6T7oWUGxrJQaru3NWiHBVSqSkvMhXVVRwEvCuPa8bDKNmKNfhD5Y5k1VrAHj4o walletName=None
2022-07-12T19:23:42UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@53e4b82c to the wallet project
2022-07-12T19:23:42UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=1628ms
2022-07-12T19:23:42UTC INFO [BitcoinSServerMain] startBitcoinSBackend()
2022-07-12T19:23:42UTC INFO [BitcoinSServerMain] Chain work already calculated
2022-07-12T19:23:42UTC INFO [FeeProviderFactory$] Using fee provider: MempoolSpaceProvider(HourFeeTarget,TestNet3,None)
2022-07-12T19:23:43UTC INFO [BitcoinSServerMain] Initialized chain api
2022-07-12T19:23:43UTC INFO [DLCAppConfig$] Using pre-existing wallet
2022-07-12T19:23:43UTC WARN [Server] RPC password is not set (rpchost=127.0.0.1)
2022-07-12T19:23:43UTC INFO [BitcoinSServerMain] Done configuring wallet, it took=752ms
2022-07-12T19:23:43UTC INFO [BitcoinSServerMain] Done configuring node, it took=754ms
2022-07-12T19:23:43UTC INFO [DLCWallet$DLCWalletImpl] Starting Wallet
2022-07-12T19:23:43UTC INFO [NeutrinoNode] Starting node
2022-07-12T19:23:43UTC INFO [PeerFinder] Peer discovery disabled.
2022-07-12T19:23:43UTC INFO [PeerManager] Done starting PeerManager
2022-07-12T19:23:43UTC INFO [NeutrinoNode] Our node has been full started. It took=97ms
2022-07-12T19:23:43UTC INFO [NeutrinoNode] Started node, best block hash 0000000000000025e4429aab380fc620af2abef8c36c051226a6bb26c12f8c23 at height 2255787, with 2255787 filter headers and 2255787 filters
2022-07-12T19:23:43UTC INFO [KeyManagerAppConfig] Starting keymanager with seedPath=/home/chris/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=vpub5SLqN2bLY4WeaPvECr23tpgLY6JkWaXa9tcsU4qGNxcYT6T7oWUGxrJQaru3NWiHBVSqSkvMhXVVRwEvCuPa8bDKNmKNfhD5Y5k1VrAHj4o
2022-07-12T19:23:43UTC INFO [HikariDataSource] bitcoin-s-node-db - Starting...
2022-07-12T19:23:43UTC INFO [HikariDataSource] bitcoin-s-node-db - Start completed.
2022-07-12T19:23:43UTC INFO [PeerManager] Connected to peer Peer(127.0.0.1:18333) with filters. Connected peer count 1
2022-07-12T19:23:43UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-07-12T19:23:43UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-07-12T19:23:43UTC INFO [VersionPrinter]
2022-07-12T19:23:43UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.005s)
2022-07-12T19:23:43UTC INFO [DbMigrate] Current version of schema "main": 15
2022-07-12T19:23:43UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-07-12T19:23:43UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: false
2022-07-12T19:23:43UTC WARN [DLCServer$] Tor must be enabled to negotiate a dlc, you can set this with bitcoin-s.tor.enabled=true and bitcoin-s.control.enabled=true in your bitcoin-s.conf
2022-07-12T19:23:43UTC INFO [WalletAppConfig] Starting wallet with xpub=vpub5SLqN2bLY4WeaPvECr23tpgLY6JkWaXa9tcsU4qGNxcYT6T7oWUGxrJQaru3NWiHBVSqSkvMhXVVRwEvCuPa8bDKNmKNfhD5Y5k1VrAHj4o walletName=None
2022-07-12T19:23:43UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@7a13d0ca to the wallet project
2022-07-12T19:23:43UTC INFO [DLCServer] Bound at /[0:0:0:0:0:0:0:0]:2862
2022-07-12T19:23:43UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2022-07-12T19:23:43UTC INFO [Server] Started Bitcoin-S websocket at /127.0.0.1:19999
2022-07-12T19:23:43UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=1303ms
2022-07-12T19:23:44UTC INFO [WalletAppConfig] Starting wallet rebroadcast task
2022-07-12T19:23:44UTC INFO [NeutrinoNode] Syncing with Peer(127.0.0.1:18333)
2022-07-12T19:24:03UTC INFO [NeutrinoNode] Starting sync node, height=2255787 hash=0000000000000025e4429aab380fc620af2abef8c36c051226a6bb26c12f8c23
2022-07-12T19:24:03UTC INFO [BitcoinSServerMain] Done starting Main! It took 20570ms
2022-07-12T19:24:03UTC INFO [BitcoinSServerMain] Done start BitcoinSServerMain, it took=22198ms
2022-07-12T19:24:27UTC INFO [DataMessageHandler] Received headers message with 2000 headers from Peer(127.0.0.1:18333)
2022-07-12T19:24:27UTC INFO [NeutrinoNode] Syncing with Peer(127.0.0.1:18333)
2022-07-12T19:24:27UTC INFO [NeutrinoNode] Starting sync node, height=2255787 hash=0000000000000025e4429aab380fc620af2abef8c36c051226a6bb26c12f8c23
2022-07-12T19:25:10UTC INFO [ChainHandler] Processed headers from height=2255787 to 2257787. Best hash=0000000071411e6aaa7dc5cc6636695dbf2bc3896021a5f7a0eae03de467c7ab
2022-07-12T19:25:10UTC INFO [DataMessageHandler] Received maximum amount of headers in one header message. This means we are not synced, requesting more
2022-07-12T19:25:11UTC INFO [DataMessageHandler] Received headers message with 2000 headers from Peer(127.0.0.1:18333)
2022-07-12T19:25:12UTC ERROR [DataMessageHandler] Failed to handle data payload=HeadersMessage(CompactSizeUInt(2000),0000000000000012e90a85eecb995dca017eed066da4fe4ad4a635dc436120ae..0000000071411e6aaa7dc5cc6636695dbf2bc3896021a5f7a0eae03de467c7ab from Peer(127.0.0.1:18333)
java.lang.RuntimeException: Failed to connect any headers to our internal chain state, failures=Vector(Successful(BaseBlockchain(tip=BlockHeaderDb(height=2257787,hashBE=0000000071411e6aaa7dc5cc6636695dbf2bc3896021a5f7a0eae03de467c7ab,version=Int32Impl(536870912),prevBlockHashBE=00000000000699c52d60fb2d9bea4dc7f605c099aa28f47b768730d2cdc0582amerkleRootHashBE=0be82bd8f104570e74c3d7ca77e66c7ee9ec6ca4231e36e3ade6a784c1a1b6c2,time=UInt32Impl(1655379435),nBits=UInt32Impl(486599352),nonce=UInt32Impl(4094153227),chainWork=32014123370935434827779),last=BlockHeaderDb(height=2255771,hashBE=000000000000002c71d894c7997b46d94d0050fc626900a6d163802ca166f394,version=Int32Impl(536895488),prevBlockHashBE=0000000000000011c4af2d1adb9e18044ba104663c67b404424c5f24dfd38aa7merkleRootHashBE=12cad0a71b9f0c671bb40d2f85e7d502d31aa771f6a753c642a726222a5712f5,time=UInt32Impl(1655287806),nBits=UInt32Impl(424072486),nonce=UInt32Impl(1639232978),chainWork=31988861916027323628628),length=2017),Vector()))
        at org.bitcoins.chain.blockchain.ChainHandler.processHeadersWithChains(ChainHandler.scala:140)
        at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processHeaders$1(ChainHandler.scala:180)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-07-12T19:25:12UTC ERROR [DataMessageHandler] Error when processing headers message
java.lang.RuntimeException: Failed to connect any headers to our internal chain state, failures=Vector(Successful(BaseBlockchain(tip=BlockHeaderDb(height=2257787,hashBE=0000000071411e6aaa7dc5cc6636695dbf2bc3896021a5f7a0eae03de467c7ab,version=Int32Impl(536870912),prevBlockHashBE=00000000000699c52d60fb2d9bea4dc7f605c099aa28f47b768730d2cdc0582amerkleRootHashBE=0be82bd8f104570e74c3d7ca77e66c7ee9ec6ca4231e36e3ade6a784c1a1b6c2,time=UInt32Impl(1655379435),nBits=UInt32Impl(486599352),nonce=UInt32Impl(4094153227),chainWork=32014123370935434827779),last=BlockHeaderDb(height=2255771,hashBE=000000000000002c71d894c7997b46d94d0050fc626900a6d163802ca166f394,version=Int32Impl(536895488),prevBlockHashBE=0000000000000011c4af2d1adb9e18044ba104663c67b404424c5f24dfd38aa7merkleRootHashBE=12cad0a71b9f0c671bb40d2f85e7d502d31aa771f6a753c642a726222a5712f5,time=UInt32Impl(1655287806),nBits=UInt32Impl(424072486),nonce=UInt32Impl(1639232978),chainWork=31988861916027323628628),length=2017),Vector()))
        at org.bitcoins.chain.blockchain.ChainHandler.processHeadersWithChains(ChainHandler.scala:140)
        at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processHeaders$1(ChainHandler.scala:180)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-07-12T19:25:12UTC INFO [DataMessageHandler] Received headers message with 2000 headers from Peer(127.0.0.1:18333)
2022-07-12T19:25:49UTC INFO [ChainHandler] Processed headers from height=2257787 to 2259787. Best hash=000000000000d34acafa03c0cf59e8df34cbe986ae1be8131d4b879725faa1c6
2022-07-12T19:25:49UTC INFO [DataMessageHandler] Received maximum amount of headers in one header message. This means we are not synced, requesting more
2022-07-12T19:25:49UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
2022-07-12T19:25:49UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
2022-07-12T19:25:49UTC INFO [DataMessageHandler] Received headers message with 2000 headers from Peer(127.0.0.1:18333)
2022-07-12T19:26:22UTC INFO [ChainHandler] Processed headers from height=2259787 to 2261787. Best hash=00000000000a400a34c1d52a571a1dc97098d82305d821d82967e05f412fe9c7
2022-07-12T19:26:22UTC INFO [DataMessageHandler] Received maximum amount of headers in one header message. This means we are not synced, requesting more
2022-07-12T19:26:22UTC INFO [DataMessageHandler] Received headers message with 2000 headers from Peer(127.0.0.1:18333)
```

**Comment by Christewart** [comment]
EDIT: Ignore this, i misconfigured my node.

**Comment by Christewart** [comment]
I believe this is a duplicate of #4511
