### ISSUE TITLE
When running `appServerTest/test` error message `ERROR [DLCWallet$DLCWalletImpl] Cannot get fee rate` 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4536]
If you adjust the logging level on `logback-test.xml` to `INFO` and run `appServerTest/test` you should be able to reproduce logs that look like this

```
2022-07-24T20:11:39UTC ERROR [DLCWallet$DLCWalletImpl] Cannot get fee rate 
java.lang.RuntimeException: Unexpected error when getting fee rate
	at org.bitcoins.rpc.client.common.BitcoindRpcClient.$anonfun$getFeeRate$1(BitcoindRpcClient.scala:91)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-07-24T20:11:39UTC ERROR [DLCWallet$DLCWalletImpl] Cannot get fee rate 
java.lang.RuntimeException: Unexpected error when getting fee rate
	at org.bitcoins.rpc.client.common.BitcoindRpcClient.$anonfun$getFeeRate$1(BitcoindRpcClient.scala:91)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-07-24T20:11:40UTC INFO [DLCWallet$DLCWalletImpl] Processing block=7be8af82eee13f55e543ca7fb2c4bfb311eddeb687daac9074065853f45f11f8 heightOpt=Some(114)
2022-07-24T20:11:40UTC ERROR [DLCWallet$DLCWalletImpl] Cannot get fee rate 
java.lang.RuntimeException: Unexpected error when getting fee rate
	at org.bitcoins.rpc.client.common.BitcoindRpcClient.$anonfun$getFeeRate$1(BitcoindRpcClient.scala:91)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)

```

**Comment by Christewart** [comment]
I believe this was introduced in #4518 @rorp
