### ISSUE TITLE
Failed to startup with bitcoind backend `org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Loading P2P addresses…`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4618]
Saw this on my umbrel on b16a8ca6 after restarting. I"m not sure if this is fixed in master after this or not.

```
2022-08-12T14:23:19UTC INFO [BitcoinSServerMain] Stopped bitcoind node
2022-08-12T14:25:44UTC INFO [BitcoinSServerMain] version=1.9.2-66-b16a8ca6-SNAPSHOT jdkVersion=17.0.2
2022-08-12T14:25:44UTC INFO [BitcoinSServerMain] Starting appServer
2022-08-12T14:25:54UTC INFO [TorAppConfig] Tor provided to us, skipping start
2022-08-12T14:25:59UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK
2022-08-12T14:26:00UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-08-12T14:26:00UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-12T14:26:00UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-12T14:26:00UTC INFO [VersionPrinter] 
2022-08-12T14:26:00UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-12T14:26:00UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-12T14:26:00UTC INFO [VersionPrinter] 
2022-08-12T14:26:00UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2022-08-12T14:26:00UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-08-12T14:26:01UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK
2022-08-12T14:26:01UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.386s)
2022-08-12T14:26:01UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-12T14:26:01UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-12T14:26:01UTC INFO [VersionPrinter] 
2022-08-12T14:26:01UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-12T14:26:01UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-12T14:26:01UTC INFO [VersionPrinter] 
2022-08-12T14:26:01UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-08-12T14:26:01UTC INFO [DbMigrate] Current version of schema "main": 6
2022-08-12T14:26:01UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-12T14:26:02UTC INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.243s)
2022-08-12T14:26:02UTC INFO [DbMigrate] Current version of schema "main": 8
2022-08-12T14:26:02UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-12T14:26:02UTC INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@2d8eb3d to the dlc project
2022-08-12T14:26:02UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.419s)
2022-08-12T14:26:02UTC INFO [DbMigrate] Current version of schema "main": 15
2022-08-12T14:26:02UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-12T14:26:02UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-12T14:26:02UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-12T14:26:02UTC INFO [VersionPrinter] 
2022-08-12T14:26:02UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2022-08-12T14:26:03UTC INFO [DbValidate] Successfully validated 4 migrations (execution time 00:00.153s)
2022-08-12T14:26:03UTC INFO [DbMigrate] Current version of schema "main": 4
2022-08-12T14:26:03UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-12T14:26:03UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@3a318e22 migrations fro the node project
2022-08-12T14:26:04UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-08-12T14:26:05UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-08-12T14:26:06UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-08-12T14:26:06UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-08-12T14:26:06UTC INFO [ChainAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@3204ebbe to chain project
2022-08-12T14:26:06UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK walletName=None
2022-08-12T14:26:06UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@506fb86 to the wallet project
2022-08-12T14:26:06UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=22486ms
2022-08-12T14:26:06UTC INFO [BitcoinSServerMain] startBitcoindBackend()
2022-08-12T14:26:20UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
2022-08-12T14:26:20UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Loading P2P addresses…
2022-08-12T14:26:20UTC ERROR [BitcoinSServerMain] Failed to startup server!
org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Loading P2P addresses…
	at org.bitcoins.rpc.BitcoindException$.$anonfun$all$14(BitcoindException.scala:59)
	at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:126)
	at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
	at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
	at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
	at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:443)
	at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by Christewart** [comment]
```
2022-08-17T15:20:30UTC INFO [BitcoinSServerMain] version=1.9.2-66-b16a8ca6-SNAPSHOT jdkVersion=17.0.2
2022-08-17T15:20:30UTC INFO [BitcoinSServerMain] Starting appServer
2022-08-17T15:20:42UTC INFO [TorAppConfig] Tor provided to us, skipping start
2022-08-17T15:20:47UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-17T15:20:47UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-17T15:20:47UTC INFO [VersionPrinter] 
2022-08-17T15:20:47UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK
2022-08-17T15:20:47UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/dlcdb.sqlite (SQLite 3.36)
2022-08-17T15:20:47UTC INFO [BitcoinSServerMain] Start on network MainNet
2022-08-17T15:20:48UTC INFO [KeyManagerAppConfig] Starting key manager with seedPath=/home/bitcoin-s/.bitcoin-s/seeds/encrypted-bitcoin-s-seed.json, rootXpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK
2022-08-17T15:20:48UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-17T15:20:48UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-17T15:20:48UTC INFO [VersionPrinter] 
2022-08-17T15:20:48UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/chaindb.sqlite (SQLite 3.36)
2022-08-17T15:20:48UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-17T15:20:48UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-17T15:20:48UTC INFO [VersionPrinter] 
2022-08-17T15:20:48UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/walletdb.sqlite (SQLite 3.36)
2022-08-17T15:20:48UTC INFO [DbValidate] Successfully validated 6 migrations (execution time 00:00.376s)
2022-08-17T15:20:48UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-17T15:20:48UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-17T15:20:48UTC INFO [VersionPrinter] 
2022-08-17T15:20:48UTC INFO [DbMigrate] Current version of schema "main": 6
2022-08-17T15:20:48UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-17T15:20:49UTC INFO [DbValidate] Successfully validated 8 migrations (execution time 00:00.373s)
2022-08-17T15:20:49UTC INFO [DbMigrate] Current version of schema "main": 8
2022-08-17T15:20:49UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-17T15:20:49UTC INFO [DLCAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@28a0989f to the dlc project
2022-08-17T15:20:49UTC INFO [DbValidate] Successfully validated 15 migrations (execution time 00:00.645s)
2022-08-17T15:20:49UTC INFO [DbMigrate] Current version of schema "main": 15
2022-08-17T15:20:49UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-17T15:20:51UTC INFO [VersionPrinter] Flyway Community Edition 8.5.9 by Redgate
2022-08-17T15:20:51UTC INFO [VersionPrinter] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.9
2022-08-17T15:20:51UTC INFO [VersionPrinter] 
2022-08-17T15:20:52UTC INFO [BaseDatabaseType] Database: jdbc:sqlite:/home/bitcoin-s/.bitcoin-s/mainnet/nodedb.sqlite (SQLite 3.36)
2022-08-17T15:20:52UTC INFO [DbValidate] Successfully validated 4 migrations (execution time 00:00.155s)
2022-08-17T15:20:52UTC INFO [DbMigrate] Current version of schema "main": 4
2022-08-17T15:20:52UTC INFO [DbMigrate] Schema "main" is up to date. No migration necessary.
2022-08-17T15:20:52UTC INFO [NodeAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@386c766d migrations fro the node project
2022-08-17T15:20:54UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Starting...
2022-08-17T15:20:54UTC INFO [HikariDataSource] bitcoin-s-chain-db - Starting...
2022-08-17T15:20:55UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Start completed.
2022-08-17T15:20:55UTC INFO [HikariDataSource] bitcoin-s-chain-db - Start completed.
2022-08-17T15:20:56UTC INFO [WalletAppConfig] Starting wallet with xpub=zpub6jftahH18ngZyGkGNasn51ek8vjfXWBxz4ceK6w1gt79cKQ6xkSuxxWAMxcCNAWsYDmcf2YquaVbwpWhjwV2suZMiFeZCLnSnuodPcHFrfK walletName=None
2022-08-17T15:20:56UTC INFO [ChainAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@44f5a37b to chain project
2022-08-17T15:20:57UTC INFO [WalletAppConfig] Applied org.flywaydb.core.api.output.MigrateResult@3198fa4a to the wallet project
2022-08-17T15:20:57UTC INFO [BitcoinSAppConfig] Done starting BitcoinSAppConfig, it took=26446ms
2022-08-17T15:20:57UTC INFO [BitcoinSServerMain] startBitcoindBackend()
2022-08-17T15:21:11UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
2022-08-17T15:21:11UTC ERROR [BitcoindRpcClient] org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
2022-08-17T15:21:11UTC ERROR [BitcoinSServerMain] Failed to startup server!
org.bitcoins.rpc.BitcoindException$InWarmUp: Error -28: Verifying blocks…
	at org.bitcoins.rpc.BitcoindException$.$anonfun$all$14(BitcoindException.scala:59)
	at org.bitcoins.rpc.BitcoindException$.$anonfun$fromCodeAndMessage$2(BitcoindException.scala:88)
	at scala.Option.map(Option.scala:242)
	at org.bitcoins.rpc.BitcoindException$.fromCodeAndMessage(BitcoindException.scala:88)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$2(BitcoindException.scala:36)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1(BitcoindException.scala:35)
	at org.bitcoins.rpc.BitcoindException$$anon$1.$anonfun$reads$1$adapted(BitcoindException.scala:34)
	at play.api.libs.json.JsSuccess.flatMap(JsResult.scala:22)
	at org.bitcoins.rpc.BitcoindException$$anon$1.reads(BitcoindException.scala:34)
	at play.api.libs.json.JsValue.validate(JsValue.scala:17)
	at play.api.libs.json.JsValue.validate$(JsValue.scala:16)
	at play.api.libs.json.JsObject.validate(JsValue.scala:126)
	at play.api.libs.json.JsLookupResult.validate(JsLookup.scala:165)
	at play.api.libs.json.JsLookupResult.validate$(JsLookup.scala:164)
	at play.api.libs.json.JsDefined.validate(JsLookup.scala:188)
	at org.bitcoins.rpc.client.common.Client.parseResult(Client.scala:443)
	at org.bitcoins.rpc.client.common.Client.$anonfun$bitcoindCall$2(Client.scala:361)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
I saw this again today when updating to the 1.9.3 release on umbrel
 
<img width="1440" alt="Screen Shot 2022-09-10 at 9 56 36 AM" src="https://user-images.githubusercontent.com/3514957/189489007-9bd9c893-6be5-4397-8f32-7358f22e9944.png">
