### ISSUE TITLE
Node syncing fails `Failing because buffer is full and overflowStrategy is: [Fail] in stream [queueSource]`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4645]
This occurred on e65346f5

It seems to me our downstream consumers of the queue are not fast enough for the amount data we are fetching, leading to failure here: 

https://github.com/bitcoin-s/bitcoin-s/blob/2c2e03b2799d1a6807eb8f3e513c0acbb4eb45fc/node/src/main/scala/org/bitcoins/node/PeerManager.scala#L378

```
2022-08-23T11:55:36UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts
2022-08-23T11:55:41UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T11:55:44UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000000286b871b7a20160e80490416ad1d7eea6ce4fa204f2e. It took 20472ms
2022-08-23T11:55:48UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000065433f3a67c2d15f56c6947ca358f887f98580c3f27cd heightOpt=Some(712904)
2022-08-23T11:55:48UTC INFO [ChainHandler] Processed filters from height=715724 to 716723. Best filter.blockHash=000000000000000000036f0aff5c19a7ce4d177fb427cbf60b37582c3d43b760
2022-08-23T11:55:48UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2022-08-23T11:55:48UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=716724, stopBlockHash=00000000000000000004697dd8b94025f5df4ac9bb5122f27e399bb8b0266e74)
2022-08-23T11:55:48UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000097923ab89a63cfe440f54a5b79c17d35ce1d03f94c358
2022-08-23T11:55:48UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000acecfa1ce6bfb7b1e2fcbfe7e809ee06ebc9db2c5ef9e
2022-08-23T11:55:48UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts
2022-08-23T11:55:53UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T11:55:59UTC INFO [ChainHandler] Processed filters from height=716724 to 717723. Best filter.blockHash=00000000000000000004697dd8b94025f5df4ac9bb5122f27e399bb8b0266e74
2022-08-23T11:55:59UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2022-08-23T11:55:59UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=717724, stopBlockHash=00000000000000000002d03f5068ce1a188c9b79d929d4f2af95b551d7ce2288)
2022-08-23T11:55:59UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000b2924c2b933771fe1b604b97dc2cd963122283cd90c7a
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000067643c738a3f5b20a38f4ed630fc2f84adf132ea954ac
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000000731690b195e99ca8f252a464308cf534ea2c1527d3db
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000001d96dc51adcc76b5b708a337bac1485309211f3c87d3f
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000a181409c5624d6652e94ffe3178dce38f35dc05e4ae61
2022-08-23T11:56:02UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 1cf59d3409e41d15c49ed1b9c14ed6a45dbd31d079341f306713827ac23691fc:0 amt=100000 sats into DB
2022-08-23T11:56:02UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000003b916ab87adc1d66cd0033961dc04dc01e8086f09ddd5
2022-08-23T11:56:02UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=100000 sats it took=5719ms
2022-08-23T11:56:02UTC INFO [DLCWallet$DLCWalletImpl] Processing spent utxos in tx 1cf59d3409e41d15c49ed1b9c14ed6a45dbd31d079341f306713827ac23691fc for 1 DLC(s)
2022-08-23T11:56:03UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T11:56:07UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000065433f3a67c2d15f56c6947ca358f887f98580c3f27cd. It took 22350ms
2022-08-23T11:56:09UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000004198301b220f74464db452a70495d3c30a1be39bf0f7e heightOpt=Some(713095)
2022-08-23T11:56:09UTC INFO [ChainHandler] Processed filters from height=717724 to 718723. Best filter.blockHash=00000000000000000002d03f5068ce1a188c9b79d929d4f2af95b551d7ce2288
2022-08-23T11:56:09UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2022-08-23T11:56:09UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts
2022-08-23T11:56:09UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=718724, stopBlockHash=0000000000000000000a8fce7729758c1853e6212ba831447b931a75b342d359)
2022-08-23T11:56:09UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000001d77dcbd2fe8f77a8fd0107c3b136c8677fc4686773cc
2022-08-23T11:56:09UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000007f93ed320da9021db9d06b8d526b66e6acf9bc799a108
2022-08-23T11:56:12UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000000d83eda382566217be44e56081ea8064bb81a886b5550
2022-08-23T11:56:12UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000032281bc09cafeff97f28b60a3d7c2ff25fbdd44d26209
2022-08-23T11:56:12UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000055c66951318a8b2a3582804436c32c18b9252230516ce
2022-08-23T11:56:12UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000009356f679f3edf05e5eba8d3faa356dbd668d6ffe185bf
2022-08-23T11:56:13UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000a4ad84c49ddd562693dab90bbcfc8e4103cb76d2d122c
2022-08-23T11:56:13UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000551883def68101d6bf242288699cb093c4c93bc321b72
2022-08-23T11:56:13UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000006383716136833a702364fe5109c9642246cdb4dc97431
2022-08-23T11:56:13UTC ERROR [QueueSource] Failing because buffer is full and overflowStrategy is: [Fail] in stream [queueSource]
2022-08-23T11:56:13UTC ERROR [P2PClientSupervisor] Error while processing messages
akka.stream.StreamDetachedException: Stage with GraphStageLogic akka.stream.impl.QueueSource$$anon$1-queueSource stopped before async invocation was processed
2022-08-23T11:56:13UTC ERROR [OneForOneStrategy] Stage with GraphStageLogic akka.stream.impl.QueueSource$$anon$1-queueSource stopped before async invocation was processed
akka.stream.StreamDetachedException: Stage with GraphStageLogic akka.stream.impl.QueueSource$$anon$1-queueSource stopped before async invocation was processed
2022-08-23T11:56:14UTC ERROR [NodeCallbacks$NodeCallbacksImpl] onCompactFilterReceived Callback failed with error: 
java.lang.RuntimeException: IBD not started yet. Cannot query for blocks.
	at org.bitcoins.node.Node.downloadBlocks(Node.scala:196)
	at org.bitcoins.node.Node.downloadBlocks$(Node.scala:181)
	at org.bitcoins.node.NeutrinoNode.downloadBlocks(NeutrinoNode.scala:27)
	at org.bitcoins.wallet.Wallet.$anonfun$processCompactFilters$10(Wallet.scala:217)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-08-23T11:56:17UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000004198301b220f74464db452a70495d3c30a1be39bf0f7e. It took 9771ms
2022-08-23T11:56:17UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000094ab34bb35688c486f45da38a610c92d1edc0d877bfcc heightOpt=Some(713572)
2022-08-23T11:56:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000094ab34bb35688c486f45da38a610c92d1edc0d877bfcc. It took 12362ms
2022-08-23T11:56:29UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000062aa1ae75db7792637324fdc9366c29d30ca0bc9eff5f heightOpt=Some(713623)
2022-08-23T11:56:34UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000062aa1ae75db7792637324fdc9366c29d30ca0bc9eff5f. It took 5586ms
2022-08-23T11:56:34UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000052890ead810e7fd9001539689eeca608ac66818b28665 heightOpt=Some(713844)
2022-08-23T11:56:49UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000052890ead810e7fd9001539689eeca608ac66818b28665. It took 14932ms
2022-08-23T11:56:49UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000738fca74dbaa6851e50592a5db929fad37a69d6a6d467 heightOpt=Some(713855)
2022-08-23T11:56:56UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000738fca74dbaa6851e50592a5db929fad37a69d6a6d467. It took 7049ms
2022-08-23T11:56:56UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000b29966c0e0a9fa3bfacc912891294b68edce908276f76 heightOpt=Some(713901)
2022-08-23T11:57:03UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000b29966c0e0a9fa3bfacc912891294b68edce908276f76. It took 6982ms
2022-08-23T11:57:03UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006545b9f044e678c29be7c927c05b78f828c275c9fc870 heightOpt=Some(713981)
2022-08-23T11:57:19UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000006545b9f044e678c29be7c927c05b78f828c275c9fc870. It took 15544ms
2022-08-23T11:57:19UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000075d7890577c713966f234973dd6c533dab3e2b0bac201 heightOpt=Some(713982)
2022-08-23T11:57:29UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO a950c9b6fddfb4395f806cfebf1997251169abb1870bd61f4a1532e7c5e2f8e4:0 amt=309345 sats into DB
2022-08-23T11:57:29UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO a950c9b6fddfb4395f806cfebf1997251169abb1870bd61f4a1532e7c5e2f8e4:1 amt=1000000 sats into DB
2022-08-23T11:57:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 2 received outputs, balance=1309345 sats it took=841ms
2022-08-23T11:57:34UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000075d7890577c713966f234973dd6c533dab3e2b0bac201. It took 15466ms
2022-08-23T11:57:34UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006c70f6c31b812c0621c84fd44dd5f82ed8d41b9432301 heightOpt=Some(714010)
2022-08-23T11:57:45UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO c68e9fc3075e6ca7bcee17f3d64cd868987b68ce406846add3a722f1059da0b3:1 amt=807273 sats into DB
2022-08-23T11:57:45UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=807273 sats it took=458ms
2022-08-23T11:57:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000006c70f6c31b812c0621c84fd44dd5f82ed8d41b9432301. It took 13877ms
2022-08-23T11:57:48UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000705b7682dd27e0f5e3ad8c5c75d93500ba5835d029229 heightOpt=Some(714021)
2022-08-23T11:58:03UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000705b7682dd27e0f5e3ad8c5c75d93500ba5835d029229. It took 14650ms
2022-08-23T11:58:03UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000008fc562f2c164026731e527fb4e7162879aa1d6386e852 heightOpt=Some(714125)
2022-08-23T11:58:07UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000008fc562f2c164026731e527fb4e7162879aa1d6386e852. It took 3736ms
2022-08-23T11:58:07UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000097923ab89a63cfe440f54a5b79c17d35ce1d03f94c358 heightOpt=Some(715325)
2022-08-23T11:58:14UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000097923ab89a63cfe440f54a5b79c17d35ce1d03f94c358. It took 6912ms
2022-08-23T11:58:14UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000acecfa1ce6bfb7b1e2fcbfe7e809ee06ebc9db2c5ef9e heightOpt=Some(715550)
2022-08-23T11:58:28UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000acecfa1ce6bfb7b1e2fcbfe7e809ee06ebc9db2c5ef9e. It took 14618ms
2022-08-23T11:58:28UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000b2924c2b933771fe1b604b97dc2cd963122283cd90c7a heightOpt=Some(715783)
2022-08-23T11:58:29UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000b2924c2b933771fe1b604b97dc2cd963122283cd90c7a. It took 780ms
2022-08-23T11:58:29UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000067643c738a3f5b20a38f4ed630fc2f84adf132ea954ac heightOpt=Some(715997)
2022-08-23T11:58:39UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000067643c738a3f5b20a38f4ed630fc2f84adf132ea954ac. It took 10238ms
2022-08-23T11:58:39UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000000731690b195e99ca8f252a464308cf534ea2c1527d3db heightOpt=Some(716049)
2022-08-23T11:58:48UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000000731690b195e99ca8f252a464308cf534ea2c1527d3db. It took 8630ms
2022-08-23T11:58:48UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000001d96dc51adcc76b5b708a337bac1485309211f3c87d3f heightOpt=Some(716393)
2022-08-23T11:59:06UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000001d96dc51adcc76b5b708a337bac1485309211f3c87d3f. It took 17622ms
2022-08-23T11:59:06UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000a181409c5624d6652e94ffe3178dce38f35dc05e4ae61 heightOpt=Some(716644)
2022-08-23T11:59:10UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000a181409c5624d6652e94ffe3178dce38f35dc05e4ae61. It took 4919ms
2022-08-23T11:59:10UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000003b916ab87adc1d66cd0033961dc04dc01e8086f09ddd5 heightOpt=Some(716674)
2022-08-23T11:59:12UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000003b916ab87adc1d66cd0033961dc04dc01e8086f09ddd5. It took 1241ms
2022-08-23T11:59:12UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000001d77dcbd2fe8f77a8fd0107c3b136c8677fc4686773cc heightOpt=Some(716730)
2022-08-23T11:59:18UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000001d77dcbd2fe8f77a8fd0107c3b136c8677fc4686773cc. It took 6765ms
2022-08-23T11:59:18UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000007f93ed320da9021db9d06b8d526b66e6acf9bc799a108 heightOpt=Some(716743)
2022-08-23T11:59:28UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000007f93ed320da9021db9d06b8d526b66e6acf9bc799a108. It took 9606ms
2022-08-23T11:59:28UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000000d83eda382566217be44e56081ea8064bb81a886b5550 heightOpt=Some(716759)
2022-08-23T11:59:35UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000000d83eda382566217be44e56081ea8064bb81a886b5550. It took 6837ms
2022-08-23T11:59:35UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000032281bc09cafeff97f28b60a3d7c2ff25fbdd44d26209 heightOpt=Some(716798)
2022-08-23T11:59:41UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000032281bc09cafeff97f28b60a3d7c2ff25fbdd44d26209. It took 5600ms
2022-08-23T11:59:41UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000055c66951318a8b2a3582804436c32c18b9252230516ce heightOpt=Some(716857)
2022-08-23T11:59:45UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000055c66951318a8b2a3582804436c32c18b9252230516ce. It took 4789ms
2022-08-23T11:59:45UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000009356f679f3edf05e5eba8d3faa356dbd668d6ffe185bf heightOpt=Some(716869)
2022-08-23T11:59:50UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000009356f679f3edf05e5eba8d3faa356dbd668d6ffe185bf. It took 4779ms
2022-08-23T11:59:50UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000a4ad84c49ddd562693dab90bbcfc8e4103cb76d2d122c heightOpt=Some(717023)
2022-08-23T11:59:53UTC INFO [DLCWallet$DLCWalletImpl] Successfully inserted UTXO 6490d4741248da69312dc416ff4294e6534429584d11bff41bcf344980e8df93:4 amt=213296 sats into DB
2022-08-23T11:59:53UTC INFO [DLCWallet$DLCWalletImpl] Finished processing 1 received outputs, balance=213296 sats it took=462ms
2022-08-23T12:00:01UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000a4ad84c49ddd562693dab90bbcfc8e4103cb76d2d122c. It took 10641ms
2022-08-23T12:00:01UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000551883def68101d6bf242288699cb093c4c93bc321b72 heightOpt=Some(717447)
2022-08-23T12:00:15UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=0000000000000000000551883def68101d6bf242288699cb093c4c93bc321b72. It took 14370ms
2022-08-23T12:00:15UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000006383716136833a702364fe5109c9642246cdb4dc97431 heightOpt=Some(717505)
2022-08-23T12:00:31UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000006383716136833a702364fe5109c9642246cdb4dc97431. It took 15599ms
2022-08-23T12:06:13UTC ERROR [P2PClientActor] No supported peers found! Requested: ServiceIdentifier(network=false, compactFilters=true, getUtxo=false, bloom=false, witness=false, xthin=false, networkLimited=false)
java.lang.RuntimeException: No supported peers found! Requested: ServiceIdentifier(network=false, compactFilters=true, getUtxo=false, bloom=false, witness=false, xthin=false, networkLimited=false)
	at org.bitcoins.node.PeerManager$$anonfun$1.applyOrElse(PeerManager.scala:138)
	at org.bitcoins.node.PeerManager$$anonfun$1.applyOrElse(PeerManager.scala:135)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
From talking with @shreyanshyad on slack I think we both agree that the downstream consumers of the queue are slower than the upstream producers.

In my case, its likely because of the amount of blocks being processed by the wallet. Block processing is pretty slow, leading to accumulation of elements in the queue eventually causing an overflow. The fix to this is optimizing the wallet through PRs like #4640 

Shreyansh also says he has observed this behavior on IBD when process compact filters. This can also overwhelm the queue, i'm presuming because [`ChainHandler.processCompactFilters()`](https://github.com/bitcoin-s/bitcoin-s/blob/86463231d631726ec1bc29517c1a94c184d6dc79/chain/src/main/scala/org/bitcoins/chain/blockchain/ChainHandler.scala#L369) is too slow.

**Comment by Christewart** [comment]
Done in #4654
