### ISSUE TITLE
timeout for expected response `PeerMessageReceiver.$anonfun$handleExpectResponse$3(PeerMessageReceiver.scala:297`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4647]
Observed on 995589a9ec4f40d414389fdafe6ca01aaa635aee

It appears that there is a re-occuring foreign key violation after a expected response query timeouts out from a peer. This is ocurring during IBD of a node with a large wallet with a lot of addresses/utxos.

```
2022-08-23T13:32:02UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T13:32:06UTC INFO [ChainHandler] Processed filters from height=615724 to 616723. Best filter.blockHash=00000000000000000011cfe7917f10f2a12a9b281aec4befd7dc629a60ee458a
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2022-08-23T13:32:06UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=616724, stopBlockHash=0000000000000000000e1af05dd8fc98df03bcfe2264f315559cb6512fa181c1)
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000001044782e7e40fd12a48683f214611436764b37f67215b0
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000030638d4cfb649d7b0ad4886ca37da3d91029ed0818327
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000004e47de7b5bc8463ef2ede1cb4a539323b26f3f046a03
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 0000000000000000000d47411dec6c834ae2672997cb15313d907af2bade02cf
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000100de117f5def1fed879a20cb3525d7a51aa8f43b1205b
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000005824733267a2d6a18782c6bb8accb5ff8b0364d835f68
2022-08-23T13:32:06UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000109421be9bda76dcf4790e708baab0753be25ab91adfc1
2022-08-23T13:32:06UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts
2022-08-23T13:34:25UTC INFO [NeutrinoNode] Syncing with Peer(127.0.0.1:8333)
2022-08-23T13:34:25UTC ERROR [TaskInvocation] Future timed out after [10 seconds]
java.util.concurrent.TimeoutException: Future timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
        at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3450)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3433)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
        at scala.concurrent.Await$.result(package.scala:124)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.$anonfun$handleExpectResponse$3(PeerMessageReceiver.scala:297)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:479)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-08-23T13:34:28UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=616724, stopBlockHash=0000000000000000000e1af05dd8fc98df03bcfe2264f315559cb6512fa181c1)
2022-08-23T13:34:28UTC INFO [NeutrinoNode] Starting sync node, height=750746 hash=00000000000000000004dd8da777d6d693c31b0f7625614a0aec226e343d6d4b
2022-08-23T13:34:32UTC INFO [DataMessageHandler] Received headers message with 0 headers from Peer(127.0.0.1:8333)
2022-08-23T13:34:33UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T13:34:33UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=00000000000000000021e69f1c1ea8ebb99547ec69e2a9d50a2e3317ba63b8ec. It took 183636ms
2022-08-23T13:34:33UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000923625585db0f23b5044b244a0400378dc5a2f0a66618 heightOpt=Some(580462)
2022-08-23T13:34:40UTC INFO [ChainHandler] Processed filters from height=616724 to 617723. Best filter.blockHash=0000000000000000000e1af05dd8fc98df03bcfe2264f315559cb6512fa181c1
2022-08-23T13:34:40UTC INFO [DataMessageHandler] Received maximum amount of filters in one batch. This means we are not synced, requesting more
2022-08-23T13:34:40UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=617724, stopBlockHash=000000000000000000024a1363675fcbcce58a84dfba8a391a70057ea3904bcd)
2022-08-23T13:34:40UTC INFO [DLCWallet$DLCWalletImpl] Processing 1000 block filters for 12 utxos and 4067 scripts



2022-08-23T13:37:20UTC ERROR [TaskInvocation] Future timed out after [10 seconds]
java.util.concurrent.TimeoutException: Future timed out after [10 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:174)
        at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3450)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3433)
        at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:172)
        at scala.concurrent.Await$.result(package.scala:124)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.$anonfun$handleExpectResponse$3(PeerMessageReceiver.scala:297)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:479)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-08-23T13:37:31UTC INFO [NeutrinoNode] Syncing with Peer(127.0.0.1:8333)
2022-08-23T13:37:40UTC INFO [PeerMessageSender] Requesting compact filters from FilterSyncMarker(startHeight=617724, stopBlockHash=000000000000000000024a1363675fcbcce58a84dfba8a391a70057ea3904bcd)
2022-08-23T13:37:40UTC INFO [NeutrinoNode] Starting sync node, height=750746 hash=00000000000000000004dd8da777d6d693c31b0f7625614a0aec226e343d6d4b
2022-08-23T13:37:50UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000009888ccf6d78f0f4e43f9bf7e22d0cf0659f8e1a4cacf6
2022-08-23T13:37:50UTC INFO [DataMessageHandler] Received block message with hash 000000000000000000071d938ab1f226ef3930a4b4490133d497fb95d831da13
2022-08-23T13:37:50UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000009a0c7bb584735740042c1a80b6643d9b9138ab883a144
2022-08-23T13:37:50UTC INFO [DataMessageHandler] Received block message with hash 00000000000000000002886388686450816583bf285cd507345811153cac3ed6
2022-08-23T13:37:50UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T13:39:13UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2022-08-23T13:39:13UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2022-08-23T13:39:13UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(75a11f5bc77a4d81324282954b7aaed098c9c0f0ca3c01000000000000000000),ByteVector(32017 bytes, #1700427651)) from Peer(127.0.0.1:8333)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.DB.executeBatch(DB.java:832)
        at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-23T13:39:13UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T13:39:28UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2022-08-23T13:39:28UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2022-08-23T13:39:29UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(910229123df91227d6e4fb1b28c7eecc14bcc7f5909202000000000000000000),ByteVector(19501 bytes, #-931801423)) from Peer(127.0.0.1:8333)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.DB.executeBatch(DB.java:832)
        at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-23T13:39:29UTC INFO [DataMessageHandler] Processing 1000 filters
2022-08-23T13:39:41UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
2022-08-23T13:39:41UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
2022-08-23T13:39:41UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterMessage(Basic,DoubleSha256Digest(262ecf2f701e7fc9e2a7a16189861f852358e0203a070e000000000000000000),ByteVector(10196 bytes, #-2075447687)) from Peer(127.0.0.1:8333)
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfilters.block_hash)
        at org.sqlite.core.DB.newSQLException(DB.java:1030)
        at org.sqlite.core.DB.newSQLException(DB.java:1042)
        at org.sqlite.core.DB.throwex(DB.java:1007)
        at org.sqlite.core.DB.executeBatch(DB.java:832)
        at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
        at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
        at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
        at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-23T13:39:41UTC INFO [DataMessageHandler] Processing 1000 filters
//same exception keeps happening again and again
```

It does appear that JVM has heavy CPU usage and is hitting the max heap space allocation

![Screenshot from 2022-08-23 08-42-32](https://user-images.githubusercontent.com/3514957/186173909-b7ec5097-a211-4e2b-ba35-5c201c1c0603.png)

**Comment by Christewart** [comment]
Blocking removed in #5111
