### ISSUE TITLE
Primary Key issue when running docker-compose up

### ISSUE THREAD

**Issue by nkohen** [bitcoin-s/bitcoin-s#4660]
```
bitcoin-s-walletserver-1  | 2022-08-24T18:17:03UTC INFO [PeerManager] Connected to peer Peer(neutrino.suredbits.com:8333) with filters. Connected peer count 1
bitcoin-s-walletserver-1  | 2022-08-24T18:17:04UTC INFO [NeutrinoNode] Syncing with Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:08UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=524000, stopBlockHash=0000000000000000002e0d206573bf836809338f9fdff23171f4bbf143ca8fdf)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:08UTC INFO [NeutrinoNode] Starting sync node, height=750776 hash=00000000000000000008aa373522d04ec135e65f56ecaca8e822877869ed75f7
bitcoin-s-walletserver-1  | 2022-08-24T18:17:08UTC INFO [BitcoinSServerMain] Done starting Main! It took 7413ms
bitcoin-s-walletserver-1  | 2022-08-24T18:17:08UTC INFO [BitcoinSServerMain] Done start BitcoinSServerMain, it took=13646ms
bitcoin-s-walletserver-1  | 2022-08-24T18:17:08UTC INFO [DataMessageHandler] Received headers message with 167 headers from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:09UTC INFO [ChainHandler] Processed headers from height=750776 to 750943. Best hash=0000000000000000000952ed6945ff79710a61fcf214ee55ed5634ddb33d28b8
bitcoin-s-walletserver-1  | 2022-08-24T18:17:09UTC INFO [DataMessageHandler] Starting to fetch filter headers in data message handler.
bitcoin-s-walletserver-1  | 2022-08-24T18:17:09UTC INFO [DataMessageHandler] Now syncing filters from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:09UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
bitcoin-s-walletserver-1  | 2022-08-24T18:17:46UTC INFO [ChainHandler] Processed filters headers from height=524000 to 525999. Best filterheader.blockHash=0000000000000000002e0d206573bf836809338f9fdff23171f4bbf143ca8fdf
bitcoin-s-walletserver-1  | 2022-08-24T18:17:46UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=526000, stopBlockHash=000000000000000000299ce3ec9058c1a2697e4d183812c7d267e4b91248e55c)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:46UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
bitcoin-s-walletserver-1  | 2022-08-24T18:17:46UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 2022-08-24T18:17:46UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=005de030065f34e213510e4caedd9337ecec4df786f558fecb5906646e72cf19, stopHash=0000000000000000002e0d206573bf836809338f9fdff23171f4bbf143ca8fdf filterHeaders=8f9842f4171e4ab09f58ab1e88ab5a7e28f8270c975c3f13721ed8fa01693b86...edbd4fd3913cd0641ed0a923bfbe9973e0a714620ea779ada0b102509660b20e) from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.throwex(DB.java:1007)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.executeBatch(DB.java:832)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
bitcoin-s-walletserver-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
bitcoin-s-walletserver-1  | 2022-08-24T18:18:23UTC INFO [ChainHandler] Processed filters headers from height=526000 to 527999. Best filterheader.blockHash=000000000000000000299ce3ec9058c1a2697e4d183812c7d267e4b91248e55c
bitcoin-s-walletserver-1  | 2022-08-24T18:18:23UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=528000, stopBlockHash=000000000000000000181c0a0ff59c2bd709497fe2ea1f019a2cf5d5f3e662c4)
bitcoin-s-walletserver-1  | 2022-08-24T18:18:23UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
bitcoin-s-walletserver-1  | 2022-08-24T18:18:23UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Start completed.
```

**Comment by Christewart** [comment]
probably related to #4658

**Comment by nkohen** [comment]
```
bitcoin-s-walletserver-1  | 2022-08-24T18:45:03UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=612000, stopBlockHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634)
bitcoin-s-tor-1           | Aug 24 18:54:38.000 [notice] Your system clock just jumped 570 seconds forward; assuming established circuits no longer work.
bitcoin-s-walletserver-1  | 2022-08-24T18:54:47UTC INFO [NeutrinoNode] Syncing with Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:54:48UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=612000, stopBlockHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634)
bitcoin-s-walletserver-1  | 2022-08-24T18:54:48UTC INFO [NeutrinoNode] Starting sync node, height=750946 hash=00000000000000000000e42ec70e6b7abd1698292cd34022dadd951c7a17c28f
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DataMessageHandler] Received headers message with 1 headers from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [ChainHandler] Processed headers from height=750946 to 750947. Best hash=000000000000000000098443079a03074e9242826c2a5f830ddb205bdd6ff5aa
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DataMessageHandler] Starting to fetch filter headers in data message handler.
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DataMessageHandler] Now syncing filters from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DataMessageHandler] Received headers message with 1 headers from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [ChainHandler] Processed headers from height=750947 to 750948. Best hash=0000000000000000000899c516b66a6bbb0b1b9366ee8543d37d29605c123e89
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DataMessageHandler] Starting to fetch filter headers in data message handler
bitcoin-s-walletserver-1  | 2022-08-24T18:55:08UTC INFO [DLCWallet$DLCWalletImpl] 1 txos are now confirmed!
bitcoin-s-tor-1           | Aug 24 18:55:40.000 [notice] No circuits are opened. Relaxed timeout for circuit 85 (a General-purpose client 3-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC INFO [ChainHandler] Processed filters headers from height=612000 to 613999. Best filterheader.blockHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634
bitcoin-s-web-1           | [HPM] Upgrading to WebSocket
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC INFO [WalletRoutes] Retrieved fee rate 1 sats/vbyte, it took 7ms
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC INFO [PeerMessageSender] Requesting next compact filter headers from FilterSyncMarker(startHeight=614000, stopBlockHash=000000000000000000094101db4cef9ca039bf115f1ceae7647efbb9162e9966)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC INFO [DataMessageHandler] Received headers message with 2 headers from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [DataMessageHandler] Failed to handle data payload=HeadersMessage(CompactSizeUInt(2),000000000000000000098443079a03074e9242826c2a5f830ddb205bdd6ff5aa..0000000000000000000899c516b66a6bbb0b1b9366ee8543d37d29605c123e89 from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | org.bitcoins.chain.blockchain.InvalidBlockHeader: Failed to connect any headers to our internal chain state, failures=Vector(Successful(BaseBlockchain(tip=BlockHeaderDb(height=750948,hashBE=0000000000000000000899c516b66a6bbb0b1b9366ee8543d37d29605c123e89,version=Int32Impl(703496192),prevBlockHashBE=000000000000000000098443079a03074e9242826c2a5f830ddb205bdd6ff5aamerkleRootHashBE=5b815f13b59b82cd639830a4b3c0517bf6b856cb70968ae3e7e6a092e5088373,time=UInt32Impl(1661367172),nBits=UInt32Impl(386526600),nonce=UInt32Impl(2508991557),chainWork=16023801964351236561330870765),last=BlockHeaderDb(height=748932,hashBE=00000000000000000001d32e714b9f86e5f7ff5340e31c11f53bbfbe6007e944,version=Int32Impl(621993984),prevBlockHashBE=0000000000000000000318f4f69249bc4e8b5f6d89eed62405db89d9c9724a4amerkleRootHashBE=d8beac8b03c16145b637b927d290707c261c8b633d8fed334578873312247f27,time=UInt32Impl(1660192380),nBits=UInt32Impl(386530686),nonce=UInt32Impl(1001211222),chainWork=15779085858181557748770992230),length=2017),Vector()))
bitcoin-s-walletserver-1  | 	at org.bitcoins.chain.blockchain.ChainHandler.processHeadersWithChains(ChainHandler.scala:140)
bitcoin-s-walletserver-1  | 	at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processHeaders$1(ChainHandler.scala:180)
bitcoin-s-walletserver-1  | 	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
bitcoin-s-walletserver-1  | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
bitcoin-s-walletserver-1  | 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
bitcoin-s-walletserver-1  | 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
bitcoin-s-walletserver-1  | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
bitcoin-s-walletserver-1  | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
bitcoin-s-walletserver-1  | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
bitcoin-s-walletserver-1  | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=9660af8e6a6a4e9c9df5cbadf5cd5b3471c1ce364dcc9d805488265a538384d3, stopHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634 filterHeaders=85bda66689038d3f4736027aff214043c4c09c06346405454616932fa5dece12...c6661a58aac0ef6776b4e276d839538a814bb6321cdda5c28afceda940398fd5) from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.throwex(DB.java:1007)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.executeBatch(DB.java:832)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
bitcoin-s-walletserver-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:48UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=9660af8e6a6a4e9c9df5cbadf5cd5b3471c1ce364dcc9d805488265a538384d3, stopHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634 filterHeaders=85bda66689038d3f4736027aff214043c4c09c06346405454616932fa5dece12...c6661a58aac0ef6776b4e276d839538a814bb6321cdda5c28afceda940398fd5) from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.throwex(DB.java:1007)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.executeBatch(DB.java:832)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
bitcoin-s-walletserver-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:51UTC ERROR [SafeDatabase] Error when executing query SynchronousDatabaseAction.Fused
bitcoin-s-walletserver-1  | 2022-08-24T18:55:51UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 2022-08-24T18:55:51UTC ERROR [DataMessageHandler] Failed to handle data payload=CompactFilterHeadersMessage(filterType=Basic, previousFilterHeader=9660af8e6a6a4e9c9df5cbadf5cd5b3471c1ce364dcc9d805488265a538384d3, stopHash=00000000000000000007ed3eaa01fb5b34e247d529d8695c4b66e98266b51634 filterHeaders=85bda66689038d3f4736027aff214043c4c09c06346405454616932fa5dece12...c6661a58aac0ef6776b4e276d839538a814bb6321cdda5c28afceda940398fd5) from Peer(neutrino.suredbits.com:8333)
bitcoin-s-walletserver-1  | org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: cfheaders.hash)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1030)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.newSQLException(DB.java:1042)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.throwex(DB.java:1007)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.DB.executeBatch(DB.java:832)
bitcoin-s-walletserver-1  | 	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:64)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
bitcoin-s-walletserver-1  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:542)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
bitcoin-s-walletserver-1  | 	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
bitcoin-s-walletserver-1  | 	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
bitcoin-s-walletserver-1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
bitcoin-s-walletserver-1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Christewart** [comment]
Done in #4667
