### ISSUE TITLE
`A UNIQUE constraint failed (UNIQUE constraint failed: contacts.alias)` when multiple offers in the inbox

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4661]
Observed on 02f525fd

This was sent to my umbrel node when I already had an offer in my inbox. This offer came from a different contact than the other offer I had in my inbox. I did not have a contact setup for the second offer I received in my inbox.

```
2022-08-24T18:36:43UTC INFO [DLCServer] Received a connection from /10.21.0.11:45100
2022-08-24T18:36:44UTC INFO [DLCDataHandler] Received LnMessage SendOfferTLV
2022-08-24T18:36:44UTC ERROR [SafeDatabase] Error when executing query flatMap org.bitcoins.dlc.wallet.models.DLCContactDAO$$Lambda$4071/0x00000008016f6af0@22d8c68a
2022-08-24T18:36:44UTC ERROR [SafeDatabase] org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: contacts.alias)
2022-08-24T18:36:44UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(SendOfferTLV(gj7haoql2zovgr43lv4xyntzosss3gtf64obqzdem2jwcclet5x6q5qd.onion:2862,hi, over tor,DLCOfferTLV(None,0,DoubleSha256Digest(6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000),ContractInfoV0TLV(100000 sats,ContractDescriptorV0TLV(Vector((RED,0 sats), (GREEN,100000 sats), (OTHER,50000 sats))),OracleInfoV0TLV(OracleAnnouncementV0TLV(SchnorrDigitalSignature(SchnorrNonce(8d7c393b97d8613890e3f29c21f6ae3aecd14c2873669ac60ba96f30aa41b810),FieldElement(0a44edc3b9729cb54968e96812ed63f93e7804d5aeacfdd3b9dd1f0931ebf1e6)),SchnorrPublicKey(929a56f9131bd0efe55d75eeddeb3ad989102c7a4ac1228e9fa15df2d6fa4b9c),OracleEventV0TLV(IndexedSeq(SchnorrNonce(07f578f4cde193e60c001d363b6c66a1c8efbdd8d602522aec5ea473caffaa97)),UInt32Impl(1661410800),EnumEventDescriptorV0TLV(Vector(RED, GREEN, OTHER)),Color of BBBY candle on the close on Aug 25, 2022)))),ECPublicKey(034135819ba4dd4c27533eac2835748fd2aac4f1ecb2d10e039c3d8d4b1c92eb93),wpkh(20b80f4c5c39ed225f397c8d520a0eadf9c3ef04),UInt64Impl(10604316253256617563),50000 sats,Vector(FundingInputV0TLV(UInt64Impl(3973941809988776513),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(7c1bf15e2cdcbfa45868eeed2b7a021c604263ef09a3aebc63355d889268792f:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(a6c234254db35502465f6119ad033f7e1965ab8fcf253a0fc7b15df5b5c3862d:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(18735 sats,wpkh(109c78cdf6e6b6440186a0835c782180905dcbb9)), TransactionOutput(18945 sats,wpkh(43f2ab0ec48962f6e222e39442a7847657324b5c)), TransactionOutput(100850 sats,wsh(68be900c16142389b8c748a8adf2d2f2ede8156bf019355febe528e51aa99d2c))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(038025c05663c208b020bad13e3094dee8ab2932b3d5ad38a01fc1a01fe1bc4826, 304402201e43da3242551288e3f0de60de37272dbbeaec8477c08a421e8f4db25500c3bb02205b141af0212ca4f63271fbdd32ac4c2944a08c368b2b38bf1140e2209acb6b6601)), P2WPKHWitnessV0(List(0246f47ef69bcbc943400d37eec98a262a36363729bec4e0ac730f57fd7825b637, 304402205e8fa78ca2f91de33b9b4643a54f11e23b147b027208f1dc1002731a1916bf8402200718d4140cb2510c6ae04a324b232cc6e2fe71d49808062f7142aeaf2ca86db401)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(5042681967135330871),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(09b1845a48c2e11ea1b8031cbf39d7e196c7fb3cf68b297968fbaef43d84c604:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(937c85a3fe93e0f959e6e745ca633f9500a19a8c882c893d8043f0a2d599ab67:1),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(14389 sats,wpkh(3065307faccc3ebb7c44ff2bf62abce21cb623de)), TransactionOutput(20205 sats,wpkh(670937b2a323a5b0177d4ee7d0ad2aedb51b0501)), TransactionOutput(10170 sats,wsh(7eb1a4e7eff4f4784c1064f273d5c7f12df2eb6a20acf7797c46a39427fe1021))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(036d0946d68bf8342b1a5658cc5973cafb733c1b92639547e2f9c88565e73bdf82, 304402205b4662f074175983bb3aac04466940ef90d02cb0081ed348b651a51658e0c2a5022019efca190d69da8b2f48ffb98990055fd7e2e0463155c83dc55128b0303bd51d01)), P2WPKHWitnessV0(List(03a669d5033ee2f377da43d15a377f4a6a53fa69405142606b5c4279729d69050a, 304402203c9817eb02075cc09900b63286b5c7db7dab820a6550b063936750cf7673027302201c802e8eb9140f79340e71673ca32f64a2eb39cc0ca281da378934d26371b3c301)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(5329345518321554182),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(5eb76a17278bdc08170c1044f004e97d0087b8f27250fc6d986731d7e2f6412e:1),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(dd45b18129b8ed8b0f76b48abd6337ac0f342654452b357276d36ea3f5335366:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(e455bdea8b03729ec14f86e7fc13c45ca6f52a2f3153af4295aa020e1098e45c:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(e1f15e614b9832315bd5b7a8c991adb22bc631edf85dc6d3ddcba532e2752b56:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(7b923593fe85bbdfd4336348206a133803f43257b0a5f2e77d79cdc5f9cb75a8:0),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(2b8024b10af056138fba40d92bb93d3dbebc3f52d0e6dcafae8d5109bce3c98d:2),EmptyScriptSignature,UInt32Impl(4294967293)), TransactionInputImpl(TransactionOutPoint(650676f4947fb667f8e211ec58ea5cf7c2cd6e69e8f80790e88c2a37101c5daa:0),EmptyScriptSignature,UInt32Impl(4294967293))),Vector(TransactionOutput(4239 sats,wpkh(007c247051211f8ace7441e50765133eadeb8f3b)), TransactionOutput(507415 sats,wpkh(ae50b5f1b866689a1574cb91077cd93205689572)), TransactionOutput(100170 sats,wsh(9fab68c48f533c2f5a206aa5e597a703f513890699e0c4232e6be033118128c6))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(036349e7109d1f2e49d51b5c691791ffca0dbe27c21110418388d8163b1ffccc39, 304402207c67acbf10f0a0c57ca58d0bacd3d20bf5557cff1f532957dde81dc8e67bb81c022030f71f21e4e54f4928ecb6923a01a07c1c348227131876d71652556544fa975301)), P2WPKHWitnessV0(List(021c1edee4554441884751aecc425ccee04efe2db0a96618468e40dc3eb915b63e, 30440220131d7b9586008c61b9987b3181eb6c7569a6778e27fc58fd55566bfa0df4af3a02205960fb141cda399fcf43a9bff14fc065faaaf173a63467e4cda547cb8bfbdd5401)), P2WPKHWitnessV0(List(02c08ec35bbdcf70a80183340e198c2af795a8418039b157c676217163ffaa9d21, 3043021f5006bf4ea0199bf4b9a898316fe1d11a63a8ec3f4a28547b10de029af03f8b02207ed339d18c74060bb3e9eb2976412682a034877b7cb157b4d1753eeb63afbcd001)), P2WPKHWitnessV0(List(020cc26465e34468fe193855e43e051a712a6424d8fb5bf18e99f5fba98f577e59, 30440220755ce51619ff171476cdf2cc968f8fa1b2fef4d757a797eca0d1209b2593331702202634ef187781574f2d8e582775763f9dad876942c45febf8d3d1f55620ad62e801)), P2WPKHWitnessV0(List(0254bde8a03014c0bb2d045760bc9a63d0a34b2f3ffa813a34ee324acc1ad3c272, 30440220730e8bad13816c2b06cfc630b1027198b8c269272b8cb936e3e8ea66da2476c2022076c4756c01b265a94cf675980f87339c21255e60d345765527d7f19993936c6301)), P2WPKHWitnessV0(List(025fad744bfc51f2ed229592d11be99979cfc90f2b3a7d93ed1e4f66a7514075f7, 304402200e99c5b7945c6f6b39de38d07bff5e40151d64745481590b3d797101e83bd17902205385f8221b4fdfd67c8feb151150b1c31583de57da8f7f57674fd398ec080a4d01)), P2WPKHWitnessV0(List(02bcdf37d0f70faa6fa1f2f29d282384e97a8366451fa3f99793867f51ce985919, 3044022024dae32a49e35cc7855dc61cafe85489f598635a018b36636ab849a6e9889cf602204852d78e9bf3c4b0c72d6fc1d67e7dbbd70d5dc61685605e1195e0af0839094801)))),UInt32Impl(0),UInt32Impl(4294967293),UInt16Impl(107),None), FundingInputV0TLV(UInt64Impl(11409954876886158589),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(f9d068151a434085188e6c3063c9af4d29546148a0d33fa09e75c1202f747f73:0),EmptyScriptSignature,UInt32Impl(2147483648))),Vector(TransactionOutput(10000 sats,wsh(58378fce616df0c43c5051bac631f9e460ed492e84bf4ae4429400b82c9ff7db)), TransactionOutput(20783 sats,wpkh(c05e364952925812eb20c7adae7226cd70fdbb1d))),UInt32Impl(0),IndexedSeq(P2WPKHWitnessV0(List(02e4767065f9a7b7e903113046ddfc7a5deec3cee177451d1c6b08a3ccafc11fae, 3045022100e1c2f394ee3af2c2654de01c0a11b670c880424d953d922ba6d0aba5fb7c379e0220201c56991302889a23407284dc446e98f6813f69083dd2079880b5924416d60f01)))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(43227590544f80e32a896bf479b1c0c5ad231901),UInt64Impl(15178762206521023489),UInt64Impl(16421796939564349250),7 sats/vbyte,BlockTime(UInt32Impl(1661410800)),BlockTime(UInt32Impl(1662015600))))) 
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: contacts.alias)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.execute(DB.java:881)
	at org.sqlite.core.DB.executeUpdate(DB.java:922)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$15(JdbcActionComponent.scala:520)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:517)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Christewart** [comment]
fixed in #4663
