### ISSUE TITLE
Handle case where tor does not startup

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4714]
When working with a user today, I asked him to download the latest 1.9.3 release and startup his wallet. I told him that it would take ~30 minutes to sync with the bitcoin network.

1.5 hours later, he still wasn't synced. I asked him to send me logs and this is what the logs contained in it

It seems that the tor binary failed to start. This silently happens and the user is not informed of it. We need to figure out the best way to inform users that tor did not start.

```
2022-09-06T15:15:18UTC INFO [BitcoinSServerMain] version=1.9.3 jdkVersion=17.0.4.1
...
2022-09-06T15:15:22UTC INFO [Server] Started Bitcoin-S HTTP server at /127.0.0.1:9999
2022-09-06T15:15:22UTC INFO [Server] Started Bitcoin-S websocket at /127.0.0.1:19999
2022-09-06T15:15:22UTC INFO [BitcoinSServerMain] Done configuring node, it took=1393ms
2022-09-06T15:15:22UTC INFO [DLCNode] Binding server to /0.0.0.0:2862, with tor hidden service: true
2022-09-06T15:15:22UTC INFO [BitcoinSServerMain] Starting neutrino node sync, it took=1445ms
2022-09-06T15:15:22UTC INFO [TorProtocolHandler] Tor version 0.4.6.10
2022-09-06T15:15:22UTC INFO [TorController$] Created hidden service with address=ws5ugwb7cnjqx7hvlzccmumtdncjw4lxehhjoxxjwbo6gklp3ym6l3ad.onion/<unresolved>:2862
2022-09-06T15:15:22UTC INFO [DLCServer] Bound at /[0:0:0:0:0:0:0:0]:2862
2022-09-06T15:16:19UTC ERROR [TorAppConfig] Error starting TorAppConfig
java.lang.RuntimeException: Could not start tor, please try again in a few minutes
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:186)
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:184)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-09-06T15:16:19UTC ERROR [BitcoinSServerMain] Failed to startup server!
java.lang.RuntimeException: Could not start tor, please try again in a few minutes
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:186)
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:184)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-09-06T15:18:55UTC INFO [Server] Unhandled error in server:
java.lang.RuntimeException: Could not start tor, please try again in a few minutes
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:186)
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:184)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-09-06T15:19:09UTC INFO [Server] Unhandled error in server:
java.lang.RuntimeException: Could not start tor, please try again in a few minutes
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:186)
	at org.bitcoins.tor.config.TorAppConfig$$anonfun$isBinaryFullyStarted$3.applyOrElse(TorAppConfig.scala:184)
	at scala.util.Failure.recover(Try.scala:233)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:487)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-09-06T16:45:25UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2022-09-06T16:45:25UTC ERROR [BitcoinSServerMain] Exiting process
```

**Comment by Christewart** [comment]
Handled on the `bitcoin-s-ts` project: https://github.com/bitcoin-s/bitcoin-s-ts/pull/191
