### ISSUE TITLE
`java.lang.IllegalArgumentException: CET sigs provided are not valid!` 

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4772]
Offerers wallet version - 2d83210b
Acceptors wallet version - 0cfad33f

This occurred when my wallet (the accepter) accepted an offer. This log is coming from the offerers perspective 

```
2022-09-12 16:23:52,342UTC INFO [DLCServer] Received a connection from /127.0.0.1:44502
2022-09-12 16:23:53,000UTC INFO [DLCDataHandler] Received LnMessage DLCAcceptTLV
2022-09-12 16:23:53,042UTC INFO [DLCWallet$DLCWalletImpl] Received accept message, tempContractId=000b3acd0e129e155bfdf94c28c11b71f8bef7b1e488f0f537d56b7ee4e1db2f
2022-09-12 16:23:53,042UTC INFO [DLCWallet$DLCWalletImpl] Checking if DLC Accept with tempContractId 000b3acd0e129e155bfdf94c28c11b71f8bef7b1e488f0f537d56b7ee4e1db2f has already been registered
2022-09-12 16:23:53,048UTC INFO [DLCWallet$DLCWalletImpl] DLC Offer contractId=None dlcId=(881b2868b1e34117314ee4a22b6fbacc5550587052eefe15f56749d00af5dd59) found, adding accept data
2022-09-12 16:27:07,344UTC INFO [DLCWallet$DLCWalletImpl] Verifying 3 CET Signatures
2022-09-12 16:27:07,390UTC ERROR [DLCDataHandler] Failed to process lnMessage=LnMessage(DLCAcceptTLV(Sha256DigestImpl(000b3acd0e129e155bfdf94c28c11b71f8bef7b1e488f0f537d56b7ee4e1db2f),10000 sats,ECPublicKey(03fe763aeabd4644d5e734657325fa565e4026d99c090149d34fd22933b345b424),wpkh(5e1809b2a7932dbb06bc891565a4f606f576355b),UInt64Impl(10607596681483643343),Vector(FundingInputV0TLV(UInt64Impl(9835655859849634483),WitnessTransaction(Int32Impl(2),Vector(TransactionInputImpl(TransactionOutPoint(0e663a9b53dabaae564ca44f6cc2a8ec9828808276fdee1e6ebeb8b603cce88b:1),EmptyScriptSignature,UInt32Impl(4294967294))),Vector(TransactionOutput(50000 sats,wpkh(61f980ae794ec4c94953bc2ff3c0cc4449e418d4)), TransactionOutput(50000 sats,wpkh(ffd422cf65068c8fdf4db1f74d2f7f0caf22e49c))),UInt32Impl(1628726400),IndexedSeq(P2WSHWitnessV0(List(52210249392c057e687d7ea9e8e7d973b935e8bc31e75a09f455c6ced4a7135d6e502d2102e1e0e3c3c198783912a22c6cd276054220a53a3a35e7dca11706156f821354ae52ae, 304402201cbedc7e773500b78262e9e78a4a627a2ea15a313463c953e0867b4202ac2e8702206d9cf4ca978e71e502c0749b30a59953fb1bd85ebd5e2f08b52e514fee0e374201, 304402206d3a17e097b8c5535439dd69a6bd768db8b1a17cc36d3608348ea2a28a3e020702203c3d032be3e049292922fa73a44a356cce54581fd75dda2f03662ed8b33ea93301, )))),UInt32Impl(1),UInt32Impl(4294967293),UInt16Impl(107),None)),wpkh(95e38a5ab2099a385385b5153866ed0c7df7892a),UInt64Impl(3921256049505777738),org.bitcoins.core.protocol.tlv.CETSignaturesV0TLV@40baa971,ECDigitalSignature(3044022007b91409c839e46cecc844285ebf27a7870b212fcbe4e2c989166d451c47011b02202607f4f487e9b43fd89a5bdce0b6a8e26f8154c32b85e91679f71d5380e0cb7b),NoNegotiationFieldsTLV)) 
java.lang.IllegalArgumentException: CET sigs provided are not valid! got Vector((ECPublicKey(03fb67d468ac98c054caa7ee99c50366a2eb22c84a9a62bc2e1d3b28caf222ecea),ECAdaptorSignature(ByteVector(162 bytes, 0x02da2af108491a17850025c9399385daf4b15e4ad076718298c65991614f1d03a703f646b057faa7bbf358a986e09c6320fcfa3dabd58ec5ae5e954f4283a4ab9ba892fff61817ccdb8a5dfe0ac735e7963e7f80bd3a96df25b4983688149becbdf071735e56fbf21beca06834e2fb03290e4cf02ac77fc270e4607cba9ad14820cfc3b43456510e47c15113edcfe260e81a027c3eed7145aa19b59af18c4c7cb53d))), (ECPublicKey(029146ad4e687d2f6785c1a9e3f0dd3a34f0d5bbef154d6e77a8f8c8004c6c1f2c),ECAdaptorSignature(ByteVector(162 bytes, 0x033ff1d7c49b241c07992ef740787afb8447d4aa33564013ae81c84664da3e833e035627d04f87d226316047ec853633ad4432b6490918acbf9f57c6305737a166ffe4cd02636d623ba19df6e6dde65c0dddceeb1899926e44092246476c8eab975e6b12f2b4af1ac080a76ce6f654ddfa54fef606528fb8a86eef7a3c1686d7aba312b0fa423962ee35bc6e4c218c3d20d96620068ef2fc55e99dbb67322e98a0d7))), (ECPublicKey(03d65e6b2b9b22127cfe1252257e3152eb5f6f94ef0d007daef3efc3598fc2a2f0),ECAdaptorSignature(ByteVector(162 bytes, 0x03475b93411914051d5668cb241ad7277c6fbdc0cccde6b499ba1690dd23b287fd037d032ef33b7d60952b758a3ca9bce58cd40b263c87b11ca90b8fb8f3c0b1e9f7500b88aecf714a7cd3b7ce7c112696217dd0da94060274e78a667c36bf7de73a96c1b2bf8e9a6dd16a5b2fc9e7f6c61247f3ad16cdd73301b5c9d35d72c85894278ac93840ad6dbcfcf2f7dc009254351992ca9d7f505abc13c3dbe61526d31f))))
	at org.bitcoins.dlc.wallet.DLCWallet.$anonfun$registerDLCAccept$15(DLCWallet.scala:949)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Christewart** [comment]
This is because i previously accepted a DLC that the offeror cancelled. When the offeror created a 2nd offer, it used the same outpoints thus calculating the same `dlcId`. 

This leads to reading -- not recreating -- CET signatures in the database as an optimization to avoid re-computing CETs.

https://github.com/bitcoin-s/bitcoin-s/blob/f608c5d5e45413ed9453cc64d1795bac846bf57e/dlc-wallet/src/main/scala/org/bitcoins/dlc/wallet/util/DLCAcceptUtil.scala#L169

**Comment by Christewart** [comment]
Unfortunately this is likely going to lead to rekeying every table in `dlcdb.sqlite`. We made a really poor choice in keying based on `dlcId` which is not guaranteed to be unique. You can create an arbitrary amount of offers with the same dlcId, which leads to bugs everywhere in the dlc wallet.
