### ISSUE TITLE
`requirement failed: finder.getData called without any data on peer`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#4955]
Seen this error on e85b119c20df3bda471c3308c0242f57daf7579f when running  `P2PClientTest` 

```
2023-01-21 16:04:16,411UTC ERROR P2PClientActor - Failed to process message in time state=Initializing, msgs=Vector(version, verack)
java.lang.IllegalArgumentException: requirement failed: finder.getData called without any data on peer
        at scala.Predef$.require(Predef.scala:337)
        at org.bitcoins.node.PeerFinder.getData(PeerFinder.scala:231)
        at org.bitcoins.node.PeerManager.sendAddrReq$1(PeerManager.scala:299)
        at org.bitcoins.node.PeerManager.onInitialization(PeerManager.scala:329)
        at org.bitcoins.node.networking.peer.ControlMessageHandler.handleControlPayload(ControlMessageHandler.scala:57)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.handleControlPayload(PeerMessageReceiver.scala:254)
        at org.bitcoins.node.networking.peer.PeerMessageReceiver.handleNetworkMessageReceived(PeerMessageReceiver.scala:217)
        at org.bitcoins.node.networking.P2PClientActor.$anonfun$handleEvent$14(P2PClient.scala:447)
        at org.bitcoins.core.util.FutureUtil$.$anonfun$foldLeftAsync$2(FutureUtil.scala:50)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.testkit.CallingThreadDispatcher.executeTask(CallingThreadDispatcher.scala:241)
        at akka.dispatch.MessageDispatcher.unbatchedExecute(AbstractDispatcher.scala:166)
        at akka.dispatch.BatchingExecutor.execute(BatchingExecutor.scala:130)

```

**Comment by Christewart** [comment]
<img width="1006" alt="Screen Shot 2023-03-29 at 3 51 24 PM" src="https://user-images.githubusercontent.com/3514957/228664442-5878d15c-e290-4e9c-8a4a-393c95a58587.png">
<img width="1006" alt="Screen Shot 2023-03-29 at 3 51 29 PM" src="https://user-images.githubusercontent.com/3514957/228664449-b37b78b8-ebf1-4dc9-885a-4e4d58caf26f.png">


Another failure here: https://github.com/bitcoin-s/bitcoin-s/actions/runs/4557654598/jobs/8039572454?pr=5005#step:5:993
