### ISSUE TITLE
Failing to query p2p network for peers

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5116]
Observed on 1d82ed04 , likely introduced in #5111 

```
2023-06-26 14:44:21,722UTC INFO [DataMessageHandler] Received headers message with 2000 headers from peer=Peer(127.0.0.1:8333) state=HeaderSync(Peer(127.0.0.1:8333))
2023-06-26 14:44:24,393UTC INFO [ChainHandler] Processed headers from height=642000 to 644000. Best hash=000000000000000000050886dd33c984a06f3b6b9a063838a86c746fcd6aa060
2023-06-26 14:44:24,393UTC INFO [DataMessageHandler] Received maximum amount of headers in one header message. This means we are not synced, requesting more
2023-06-26 15:03:29,891UTC INFO [PeerFinder] Querying p2p network for peers...
2023-06-26 15:03:29,933UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer([2a00:ee2:1200:1900:8d3:d2ff:feb1:bc58]:8333)
2023-06-26 15:03:29,946UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(80.60.120.204:8333)
2023-06-26 15:03:29,958UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(5.137.28.9:8333)
2023-06-26 15:03:29,963UTC ERROR [PeerMessageSender] Failed disconnect callback with peer=Peer([2a00:ee2:1200:1900:8d3:d2ff:feb1:bc58]:8333)
akka.stream.StreamTcpException: Tcp command [Connect([2a00:ee2:1200:1900:8d3:d2ff:feb1:bc58]/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:29,963UTC ERROR [Materializer] [parseToNetworkMsgFlow] Upstream failed.
akka.stream.StreamTcpException: Tcp command [Connect([2a00:ee2:1200:1900:8d3:d2ff:feb1:bc58]/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:29,969UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(167.235.229.216:8333)
2023-06-26 15:03:29,984UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(46.223.207.142:8333)
2023-06-26 15:03:30,000UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(193.32.127.140:8333)
2023-06-26 15:03:30,014UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(185.194.93.135:8333)
2023-06-26 15:03:30,028UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(88.0.90.138:8333)
2023-06-26 15:03:30,038UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(88.172.210.207:8333)
2023-06-26 15:03:30,049UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(78.98.141.115:8333)
2023-06-26 15:03:30,060UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(218.32.237.155:8333)
2023-06-26 15:03:30,069UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(128.65.194.136:8333)
2023-06-26 15:03:30,079UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(66.29.129.218:8333)
2023-06-26 15:03:30,090UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(83.208.6.211:8333)
2023-06-26 15:03:30,099UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer([2a07:a880:4601:1062:b4b4:bd2a:39d4:7acf]:51401)
2023-06-26 15:03:30,110UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(84.22.139.57:8333)
2023-06-26 15:03:30,113UTC ERROR [Materializer] [parseToNetworkMsgFlow] Upstream failed.
akka.stream.StreamTcpException: Tcp command [Connect([2a07:a880:4601:1062:b4b4:bd2a:39d4:7acf]/<unresolved>:51401,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:30,113UTC ERROR [PeerMessageSender] Failed disconnect callback with peer=Peer([2a07:a880:4601:1062:b4b4:bd2a:39d4:7acf]:51401)
akka.stream.StreamTcpException: Tcp command [Connect([2a07:a880:4601:1062:b4b4:bd2a:39d4:7acf]/<unresolved>:51401,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:30,122UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(83.220.110.48:8333)
2023-06-26 15:03:30,132UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(8.210.18.56:8333)
2023-06-26 15:03:30,142UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer([2a00:1028:8382:bf22:5f7f:b78f:2737:7739]:8333)
2023-06-26 15:03:30,152UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(61.239.91.250:8333)
2023-06-26 15:03:30,157UTC ERROR [PeerMessageSender] Failed disconnect callback with peer=Peer([2a00:1028:8382:bf22:5f7f:b78f:2737:7739]:8333)
akka.stream.StreamTcpException: Tcp command [Connect([2a00:1028:8382:bf22:5f7f:b78f:2737:7739]/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:30,157UTC ERROR [Materializer] [parseToNetworkMsgFlow] Upstream failed.
akka.stream.StreamTcpException: Tcp command [Connect([2a00:1028:8382:bf22:5f7f:b78f:2737:7739]/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-06-26 15:03:30,161UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer([2600:1700:5b2b:5f::8040]:8333)
2023-06-26 15:03:30,170UTC INFO [PeerMessageSender] Attempting to connect to peer=Peer(103.198.192.14:20008)
2023-06-26 15:03:30,175UTC ERROR [PeerMessageSender] Failed disconnect callback with peer=Peer([2600:1700:5b2b:5f::8040]:8333)
akka.stream.StreamTcpException: Tcp command [Connect([2600:1700:5b2b:5f::8040]/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.SocketException: Network is unreachable
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:580)
	at java.base/sun.nio.ch.Net.connect(Net.java:587)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:880)
	at akka.io.TcpOutgoingConnection.$anonfun$register$1(TcpOutgoingConnection.scala:98)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection.register(TcpOutgoingConnection.scala:96)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.$anonfun$applyOrElse$2(TcpOutgoingConnection.scala:84)
	at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
	at akka.io.TcpOutgoingConnection$$anonfun$resolving$1.applyOrElse(TcpOutgoingConnection.scala:84)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
```

**Comment by Christewart** [comment]
fixed in #5121
