### ISSUE TITLE
Received invalid headers after syncing block filters

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5139]
Observed on 164443188d2a177532bfb5779c0a9d0cde9f45cb

```
//bunch of sync logs above here
2023-07-08 20:21:36,651UTC INFO [ChainHandler] Processed filters headers from height=796000 to 797827. Best filterheader.blockHash=0000000000000000000218ca02a1f816c514d9c086c37413f9e18a8193ac4391
2023-07-08 20:21:37,267UTC INFO [DataMessageHandler] Beginning to sync filters from startHeight=797343
2023-07-08 20:21:37,357UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=797344, stopBlockHash=0000000000000000000218ca02a1f816c514d9c086c37413f9e18a8193ac4391) with peer=Peer(neutrino.suredbits.com:8333)
2023-07-08 20:22:42,944UTC INFO [DataMessageHandler] Processing 484 filters
2023-07-08 20:22:43,708UTC INFO [ChainHandler] Processed filters from height=797344 to 797827. Best filter.blockHash=0000000000000000000218ca02a1f816c514d9c086c37413f9e18a8193ac4391
2023-07-08 20:22:43,726UTC INFO [DLCWallet$DLCWalletImpl] Processing 484 block filters for 0 utxos and 200 scripts
2023-07-08 20:22:45,824UTC INFO [DataMessageHandler] We are synced
2023-07-08 20:22:45,873UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:22:45,977UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:22:45,978UTC INFO [DataMessageHandler] Re-querying headers from Peer(neutrino.suredbits.com:8333). invalidMessages=1 peers.size=1
2023-07-08 20:22:46,537UTC INFO [DataMessageHandler] Received headers message with 4 headers from peer=Peer(neutrino.suredbits.com:8333) state=HeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:22:46,594UTC INFO [ChainHandler] Processed headers from height=797827 to 797831. Best hash=00000000000000000004db4e0a9e6ed1b7b55d1a65bdfafb8b5b983837d7c08f
2023-07-08 20:22:46,594UTC INFO [PeerManager$] Now syncing filter headers from Peer(neutrino.suredbits.com:8333) in state=HeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:22:47,158UTC INFO [DataMessageHandler] Received headers message with 4 headers from peer=Peer(neutrino.suredbits.com:8333) state=FilterHeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:22:47,158UTC ERROR [DataMessageHandler] Failed to handle data payload=HeadersMessage(CompactSizeUInt(4),00000000000000000002f3cb13b79f482f6aa501ec2da441c4145431fd80726d..00000000000000000004db4e0a9e6ed1b7b55d1a65bdfafb8b5b983837d7c08f from peer=Peer(neutrino.suredbits.com:8333) in state=FilterHeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333))) errMsg=Invalid state to receive headers in, got=FilterHeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
java.lang.RuntimeException: Invalid state to receive headers in, got=FilterHeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
        at scala.sys.package$.error(package.scala:27)
        at org.bitcoins.node.networking.peer.DataMessageHandler.$anonfun$handleDataPayloadValidState$1(DataMessageHandler.scala:330)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-07-08 20:22:47,668UTC INFO [ChainHandler] Processed filters headers from height=797828 to 797831. Best filterheader.blockHash=00000000000000000004db4e0a9e6ed1b7b55d1a65bdfafb8b5b983837d7c08f
2023-07-08 20:22:48,303UTC INFO [DataMessageHandler] Beginning to sync filters from startHeight=797827
2023-07-08 20:22:48,394UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=797828, stopBlockHash=00000000000000000004db4e0a9e6ed1b7b55d1a65bdfafb8b5b983837d7c08f) with peer=Peer(neutrino.suredbits.com:8333)
2023-07-08 20:22:49,479UTC INFO [DataMessageHandler] Processing 4 filters
2023-07-08 20:22:49,519UTC INFO [ChainHandler] Processed filters from height=797828 to 797831. Best filter.blockHash=00000000000000000004db4e0a9e6ed1b7b55d1a65bdfafb8b5b983837d7c08f
2023-07-08 20:22:49,534UTC INFO [DLCWallet$DLCWalletImpl] Processing 4 block filters for 0 utxos and 200 scripts
2023-07-08 20:22:49,589UTC INFO [DataMessageHandler] We are synced
2023-07-08 20:23:54,504UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:23:54,564UTC INFO [ChainHandler] Processed headers from height=797831 to 797832. Best hash=00000000000000000000346f7bd7c85ddc7311d6b3644a340ab990aaaab66aad
2023-07-08 20:23:54,565UTC INFO [PeerManager$] Now syncing filter headers from Peer(neutrino.suredbits.com:8333) in state=HeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:23:55,410UTC INFO [ChainHandler] Processed filters headers from height=797832 to 797832. Best filterheader.blockHash=00000000000000000000346f7bd7c85ddc7311d6b3644a340ab990aaaab66aad
2023-07-08 20:23:56,007UTC INFO [DataMessageHandler] Beginning to sync filters from startHeight=797831
2023-07-08 20:23:56,096UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=797832, stopBlockHash=00000000000000000000346f7bd7c85ddc7311d6b3644a340ab990aaaab66aad) with peer=Peer(neutrino.suredbits.com:8333)
2023-07-08 20:23:57,655UTC INFO [DataMessageHandler] Processing 1 filters
2023-07-08 20:23:57,662UTC INFO [ChainHandler] Processed filters from height=797832 to 797832. Best filter.blockHash=00000000000000000000346f7bd7c85ddc7311d6b3644a340ab990aaaab66aad
2023-07-08 20:23:57,674UTC INFO [DLCWallet$DLCWalletImpl] Processing 1 block filters for 0 utxos and 200 scripts
2023-07-08 20:23:57,717UTC INFO [DataMessageHandler] We are synced
2023-07-08 20:27:02,112UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:27:02,173UTC INFO [ChainHandler] Processed headers from height=797832 to 797833. Best hash=0000000000000000000555ead8814f7936f99e9c785969970ccb9900b22df610
2023-07-08 20:27:02,173UTC INFO [PeerManager$] Now syncing filter headers from Peer(neutrino.suredbits.com:8333) in state=HeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-07-08 20:27:03,012UTC INFO [ChainHandler] Processed filters headers from height=797833 to 797833. Best filterheader.blockHash=0000000000000000000555ead8814f7936f99e9c785969970ccb9900b22df610
2023-07-08 20:27:03,633UTC INFO [DataMessageHandler] Beginning to sync filters from startHeight=797832
2023-07-08 20:27:03,717UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=797833, stopBlockHash=0000000000000000000555ead8814f7936f99e9c785969970ccb9900b22df610) with peer=Peer(neutrino.suredbits.com:8333)
2023-07-08 20:27:04,530UTC INFO [DataMessageHandler] Processing 1 filters
2023-07-08 20:27:04,538UTC INFO [ChainHandler] Processed filters from height=797833 to 797833. Best filter.blockHash=0000000000000000000555ead8814f7936f99e9c785969970ccb9900b22df610
2023-07-08 20:27:04,550UTC INFO [DLCWallet$DLCWalletImpl] Processing 1 block filters for 0 utxos and 200 scripts
2023-07-08 20:27:04,580UTC INFO [DataMessageHandler] We are synced
```

**Comment by Christewart** [comment]
Related to #5154

**Comment by Christewart** [comment]
Another instance seen on this today on d559eb80

It appears a header is mined on the network while we are attempting to sync a compact filter on this peer.

I thought we would attempt to re-query block headers after filter sync is complete, but that didn't seem to happen? 
```
2023-08-06 15:14:26,380UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:14:26,444UTC INFO [ChainHandler] Processed headers from height=801945 to 801946. Best hash=00000000000000000001f3e340cb2ab50255961e2a56dae2e11341f52766992d
2023-08-06 15:14:26,445UTC INFO [PeerManager$] Now syncing filter headers from Peer(neutrino.suredbits.com:8333) in state=HeaderSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:15:25,291UTC INFO [ChainHandler] Processed filters headers from height=801946 to 801946. Best filterheader.blockHash=00000000000000000001f3e340cb2ab50255961e2a56dae2e11341f52766992d
2023-08-06 15:15:25,869UTC INFO [DataMessageHandler] Beginning to sync filters from startHeight=801945
2023-08-06 15:15:25,949UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=801946, stopBlockHash=00000000000000000001f3e340cb2ab50255961e2a56dae2e11341f52766992d) with peer=Peer(neutrino.suredbits.com:8333)
2023-08-06 15:15:53,728UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=FilterSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:15:53,728UTC ERROR [DataMessageHandler] Failed to handle data payload=HeadersMessage(CompactSizeUInt(1),00000000000000000003539fec6fb0f7dc04bdfe452a513a79a98c12a661bd0b..00000000000000000003539fec6fb0f7dc04bdfe452a513a79a98c12a661bd0b from peer=Peer(neutrino.suredbits.com:8333) in state=FilterSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333))) errMsg=Invalid state to receive headers in, got=FilterSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
java.lang.RuntimeException: Invalid state to receive headers in, got=FilterSync(Peer(neutrino.suredbits.com:8333),Set(Peer(neutrino.suredbits.com:8333)))
	at scala.sys.package$.error(package.scala:27)
	at org.bitcoins.node.networking.peer.DataMessageHandler.$anonfun$handleDataPayloadValidState$1(DataMessageHandler.scala:319)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:687)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2023-08-06 15:16:07,103UTC INFO [DataMessageHandler] Processing 1 filters
2023-08-06 15:16:07,112UTC INFO [ChainHandler] Processed filters from height=801946 to 801946. Best filter.blockHash=00000000000000000001f3e340cb2ab50255961e2a56dae2e11341f52766992d
2023-08-06 15:16:07,128UTC INFO [DLCWallet$DLCWalletImpl] Processing 1 block filters for 0 utxos and 400 scripts
2023-08-06 15:16:07,170UTC INFO [DataMessageHandler] We are synced
2023-08-06 15:16:51,806UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:16:51,898UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:16:51,946UTC WARN [DataMessageHandler] Received invalid header from peer=Peer(neutrino.suredbits.com:8333). Only have 1 peer so cannot re-query, state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:20:15,495UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:20:15,572UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:20:15,618UTC WARN [DataMessageHandler] Received invalid header from peer=Peer(neutrino.suredbits.com:8333). Only have 1 peer so cannot re-query, state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-08-06 15:35:55,794UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2023-08-06 15:35:55,795UTC ERROR [BitcoinSServerMain] Exiting process
2023-08-06 15:35:55,796UTC INFO [NeutrinoNode] Stopping node
2023-08-06 15:35:55,796UTC INFO [PeerManager] Stopping PeerManager
2023-08-06 15:35:55,796UTC INFO [PeerFinder] Stopping PeerFinder
2023-08-06 15:35:55,798UTC INFO [PeerFinder] Done stopping PeerFinder
2023-08-06 15:35:55,798UTC INFO [PeerMessageSender] Disconnecting peer=Peer(neutrino.suredbits.com:8333)
2023-08-06 15:35:55,799UTC INFO [PeerManager] Client stopped for Peer(neutrino.suredbits.com:8333) peers=Set() state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333))) forceReconnect=false finder.isDefined=true peerDataMap=List()
2023-08-06 15:35:56,803UTC INFO [PeerManager] Stopped PeerManager. Took 1007 ms 
2023-08-06 15:35:56,804UTC INFO [NeutrinoNode] Node stopped! It took=1008ms
2023-08-06 15:35:56,813UTC INFO [NodeCallbackStreamManager] Done draining akka streams for NodeCallbackStreamManager, it took=9ms
2023-08-06 15:35:56,814UTC INFO [HikariDataSource] bitcoin-s-node-db - Shutdown initiated...
2023-08-06 15:35:56,817UTC INFO [HikariDataSource] bitcoin-s-node-db - Shutdown completed.
2023-08-06 15:35:56,825UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Starting...
2023-08-06 15:35:56,826UTC ERROR [PoolBase] bitcoin-s.dlc.db - JMX name (bitcoin-s.dlc.db) is already registered.
```

**Comment by Christewart** [comment]
Saw another instance of this today on 922a6aae

```
2023-09-19 20:06:56,117UTC INFO [DLCWallet$DLCWalletImpl] Processing 250 block filters for 15 utxos and 4115 scripts
2023-09-19 20:06:56,895UTC INFO [PeerManager$] Requesting compact filters from FilterSyncMarker(startHeight=808223, stopBlockHash=000000000000000000016b509da1039b3daef81bdfd6a103a97b7a7ced923a0c) with peer=Peer(neutrino.suredbits.com:8333)
2023-09-19 20:07:16,933UTC INFO [ChainHandler] Processed filters from height=808223 to 808450. Best filter.blockHash=000000000000000000016b509da1039b3daef81bdfd6a103a97b7a7ced923a0c
2023-09-19 20:07:16,939UTC INFO [DataMessageHandler] We are synced
2023-09-19 20:07:16,982UTC INFO [DLCWallet$DLCWalletImpl] Processing 228 block filters for 15 utxos and 4115 scripts
2023-09-19 20:07:24,992UTC INFO [DataMessageHandler] Received block=000000000000000000012fc79b0bfa92ec5080fc36d7636af56d1fce84990f2f state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:07:24,993UTC INFO [DLCWallet$DLCWalletImpl] Processing block=000000000000000000012fc79b0bfa92ec5080fc36d7636af56d1fce84990f2f heightOpt=Some(808227)
2023-09-19 20:07:37,437UTC INFO [DLCWallet$DLCWalletImpl] Finished processing of block=000000000000000000012fc79b0bfa92ec5080fc36d7636af56d1fce84990f2f. It took 12445ms
2023-09-19 20:09:42,325UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:14:04,201UTC INFO [DataMessageHandler] Received block=00000000000000000002afe35469138772a1bf3f15c1c54fbb66de42fdb037c4, processing block's header... state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:14:04,202UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:14:04,257UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:14:04,287UTC WARN [DataMessageHandler] Received invalid header from peer=Peer(neutrino.suredbits.com:8333). Only have 1 peer so cannot re-query, state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:14:04,289UTC WARN [DLCWallet$DLCWalletImpl] Could not find blockheight for blockHash=00000000000000000002afe35469138772a1bf3f15c1c54fbb66de42fdb037c4, skipping processing in wallet
2023-09-19 20:14:04,289UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000002afe35469138772a1bf3f15c1c54fbb66de42fdb037c4 heightOpt=None
2023-09-19 20:14:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:19:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:24:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:29:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:34:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:36:23,639UTC INFO [DataMessageHandler] Received block=00000000000000000002b69a3a66b5d1449e95d58d5b9eca3c9ff904246189b0, processing block's header... state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:36:23,639UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:36:23,680UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:36:23,710UTC WARN [DataMessageHandler] Received invalid header from peer=Peer(neutrino.suredbits.com:8333). Only have 1 peer so cannot re-query, state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:36:23,712UTC WARN [DLCWallet$DLCWalletImpl] Could not find blockheight for blockHash=00000000000000000002b69a3a66b5d1449e95d58d5b9eca3c9ff904246189b0, skipping processing in wallet
2023-09-19 20:36:23,712UTC INFO [DLCWallet$DLCWalletImpl] Processing block=00000000000000000002b69a3a66b5d1449e95d58d5b9eca3c9ff904246189b0 heightOpt=None
2023-09-19 20:39:42,335UTC INFO [PeerManager] Running inactivity checks for peers=List(Peer(neutrino.suredbits.com:8333))
2023-09-19 20:42:14,883UTC INFO [DataMessageHandler] Received block=0000000000000000000471b4624b9751bd2b6d6e77d99156399cecd674e5eff4, processing block's header... state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:42:14,883UTC INFO [DataMessageHandler] Received headers message with 1 headers from peer=Peer(neutrino.suredbits.com:8333) state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:42:14,926UTC WARN [DataMessageHandler] Invalid headers of count CompactSizeUInt(1) sent from Peer(neutrino.suredbits.com:8333) in state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:42:14,954UTC WARN [DataMessageHandler] Received invalid header from peer=Peer(neutrino.suredbits.com:8333). Only have 1 peer so cannot re-query, state=DoneSyncing(Set(Peer(neutrino.suredbits.com:8333)))
2023-09-19 20:42:14,955UTC WARN [DLCWallet$DLCWalletImpl] Could not find blockheight for blockHash=0000000000000000000471b4624b9751bd2b6d6e77d99156399cecd674e5eff4, skipping processing in wallet
2023-09-19 20:42:14,955UTC INFO [DLCWallet$DLCWalletImpl] Processing block=0000000000000000000471b4624b9751bd2b6d6e77d99156399cecd674e5eff4 heightOpt=None
^C2023-09-19 20:43:38,781UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2023-09-19 20:43:38,782UTC ERROR [BitcoinSServerMain] Exiting process
```
