### ISSUE TITLE
503 Service Unavailable Travis CI failure

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#527]
We have been seeing these failure fairly frequently on travis CI. I believe it has something to do with starting bitcoind

https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/546681050#L576

```
[info] org.bitcoins.chain.blockchain.sync.ChainSyncTest *** ABORTED ***
[info]   com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[info]  at [Source: (String)"<HTML><HEAD>
[info] <TITLE>503 Service Unavailable</TITLE>
[info] </HEAD><BODY>
[info] <H1>Service Unavailable</H1>
[info] </BODY></HTML>
[info] "; line: 1, column: 2]
[info]   at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
[info]   at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
[info]   at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
[info]   at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1902)
[info]   at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
[info]   at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
[info]   at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3971)
[info]   at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
[info]   at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:255)
[info]   at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:16)
[info]   at play.api.libs.json.Json$.parse(Json.scala:171)
[info]   at org.bitcoins.rpc.client.common.Client.$anonfun$getPayload$2(Client.scala:288)
[info]   at scala.util.Success.$anonfun$map$1(Try.scala:255)
[info]   at scala.util.Success.map(Try.scala:213)
[info]   at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[info]   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[info]   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[info]   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
```

**Comment by Christewart** [comment]
This just ocurred here: https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/568849439#L1086

**Comment by Christewart** [comment]
There was a bunch of failures here https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/569952848#L1401
