### ISSUE TITLE
Queue deadlock happening when computer goes to sleep and re-awakes?

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5431]
Observed on 070b5d4a

[bitcoin-s.log](https://github.com/bitcoin-s/bitcoin-s/files/14423567/bitcoin-s.log)

```
2024-02-27 13:27:39,960UTC INFO [NeutrinoNode] Running health checks for peers=Set(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333))
2024-02-27 13:28:39,959UTC INFO [NeutrinoNode] Running health checks for peers=Set(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333))
2024-02-27 13:29:39,960UTC INFO [NeutrinoNode] Running health checks for peers=Set(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333))
2024-02-27 13:30:39,960UTC INFO [NeutrinoNode] Running health checks for peers=Set(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333))
2024-02-27 13:30:48,493UTC INFO [PeerConnection] Connection with peer=Peer(217.230.38.207:8333) failed with err=No elements passed in the last 1200000000000 nanoseconds.
2024-02-27 13:30:48,496UTC INFO [PeerManager] Disconnected peer=Peer(217.230.38.207:8333) peers=Set(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333)) state=DoneSyncing(Map(PeerWithServices(Peer(217.230.38.207:8333),ServiceIdentifier(network=true,compactFilters=true,getUtxo=false,bloom=false,witness=true,xthin=false,networkLimited=true)) -> PersistentPeerData(Peer(217.230.38.207:8333),PeerMessageSender(PeerConnection(Peer(217.230.38.207:8333),org.apache.pekko.stream.impl.QueueSource$$anon$1-queueSource))), PeerWithServices(Peer(83.21.44.92:8333),ServiceIdentifier(network=true,compactFilters=true,getUtxo=false,bloom=true,witness=true,xthin=false,networkLimited=true)) -> PersistentPeerData(Peer(83.21.44.92:8333),PeerMessageSender(PeerConnection(Peer(83.21.44.92:8333),org.apache.pekko.stream.impl.QueueSource$$anon$1-queueSource)))),HashSet(Peer(73.119.152.128:8333), Peer(92.204.40.189:8333), Peer(74.84.255.180:8333), Peer(96.82.119.149:8333), Peer(37.60.240.243:8333), Peer(69.249.34.31:8333)),PeerFinder(paramPeers=Vector())) forceReconnect=false peerDataMap=List(Peer(217.230.38.207:8333), Peer(83.21.44.92:8333))
2024-02-27 13:30:48,595UTC INFO [PeerManager] Starting sync node, height=832263 hash=00000000000000000002b2e0c8d66949ceac10962ab8e24812d89057c2a98cec filterHeaderCount=832263 filterCount=832263 syncPeer=Peer(217.230.38.207:8333)
2024-02-27 13:31:09,160UTC INFO [PeerConnection] Connection with peer=Peer(83.21.44.92:8333) failed with err=No elements passed in the last 1200000000000 nanoseconds.
2024-02-27 13:31:09,161UTC INFO [PeerManager] Disconnected peer=Peer(83.21.44.92:8333) peers=Set(Peer(83.21.44.92:8333)) state=HeaderSync(Peer(83.21.44.92:8333),Map(PeerWithServices(Peer(217.230.38.207:8333),ServiceIdentifier(network=true,compactFilters=true,getUtxo=false,bloom=false,witness=true,xthin=false,networkLimited=true)) -> PersistentPeerData(Peer(217.230.38.207:8333),PeerMessageSender(PeerConnection(Peer(217.230.38.207:8333),org.apache.pekko.stream.impl.QueueSource$$anon$1-queueSource))), PeerWithServices(Peer(83.21.44.92:8333),ServiceIdentifier(network=true,compactFilters=true,getUtxo=false,bloom=true,witness=true,xthin=false,networkLimited=true)) -> PersistentPeerData(Peer(83.21.44.92:8333),PeerMessageSender(PeerConnection(Peer(83.21.44.92:8333),org.apache.pekko.stream.impl.QueueSource$$anon$1-queueSource)))),HashSet(Peer(73.119.152.128:8333), Peer(92.204.40.189:8333), Peer(74.84.255.180:8333), Peer(96.82.119.149:8333), Peer(37.60.240.243:8333), Peer(69.249.34.31:8333)),PeerFinder(paramPeers=Vector())) forceReconnect=false peerDataMap=List(Peer(83.21.44.92:8333))
2024-02-27 13:31:09,237UTC INFO [PeerManager] Starting sync node, height=832263 hash=00000000000000000002b2e0c8d66949ceac10962ab8e24812d89057c2a98cec filterHeaderCount=832263 filterCount=832263 syncPeer=Peer(217.230.38.207:8333)
2024-02-27 13:31:09,238UTC ERROR [NeutrinoNode] Error occurred while processing p2p pipeline stream
java.lang.IllegalArgumentException: requirement failed: syncPeer must be a member of peers, syncPeer=Peer(217.230.38.207:8333) peers=Set()
	at scala.Predef$.require(Predef.scala:337)
	at org.bitcoins.node.SyncNodeState.<init>(NodeState.scala:125)
	at org.bitcoins.node.NodeState$HeaderSync.<init>(NodeState.scala:146)
	at org.bitcoins.node.NodeState$HeaderSync.copy(NodeState.scala:145)
	at org.bitcoins.node.NodeRunningState.replacePeers(NodeState.scala:46)
	at org.bitcoins.node.NodeRunningState.replacePeers$(NodeState.scala:40)
	at org.bitcoins.node.SyncNodeState.replacePeers(NodeState.scala:122)
	at org.bitcoins.node.PeerManager.$anonfun$onDisconnect$10(PeerManager.scala:406)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:57)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-02-27 13:31:39,959UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 13:57:51,819UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=25m48s166ms).
2024-02-27 13:57:51,820UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=25m48s165ms).
2024-02-27 13:57:51,820UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=25m48s165ms).
2024-02-27 13:57:51,820UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=25m48s165ms).
2024-02-27 13:57:52,096UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=25m48s165ms).
2024-02-27 13:57:58,119UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 14:15:01,948UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m10s128ms).
2024-02-27 14:15:01,948UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=17m10s128ms).
2024-02-27 14:15:01,948UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=17m10s128ms).
2024-02-27 14:15:01,948UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=17m10s129ms).
2024-02-27 14:15:02,223UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m10s127ms).
2024-02-27 14:31:04,982UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=16m3s34ms).
2024-02-27 14:31:04,982UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=16m3s34ms).
2024-02-27 14:31:04,982UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=16m3s34ms).
2024-02-27 14:31:04,982UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=16m3s34ms).
2024-02-27 14:31:05,257UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=16m3s34ms).
2024-02-27 14:31:11,276UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 14:47:26,866UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 14:47:50,566UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=15m45s601ms).
2024-02-27 14:47:50,566UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=15m45s601ms).
2024-02-27 14:47:50,566UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=15m45s601ms).
2024-02-27 14:47:50,566UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m45s601ms).
2024-02-27 14:47:50,842UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m45s602ms).
2024-02-27 14:48:26,858UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 15:06:06,262UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m45s696ms).
2024-02-27 15:06:06,262UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=17m45s696ms).
2024-02-27 15:06:06,262UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=17m45s697ms).
2024-02-27 15:06:06,262UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=17m45s696ms).
2024-02-27 15:06:06,536UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m45s695ms).
2024-02-27 15:06:42,553UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 15:24:18,042UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m41s777ms).
2024-02-27 15:24:18,043UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=17m41s778ms).
2024-02-27 15:24:18,043UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=17m41s778ms).
2024-02-27 15:24:18,043UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=17m41s778ms).
2024-02-27 15:24:18,318UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=17m41s780ms).
2024-02-27 15:24:54,331UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 15:40:27,704UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=15m39s657ms).
2024-02-27 15:40:27,704UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m39s658ms).
2024-02-27 15:40:27,704UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=15m39s657ms).
2024-02-27 15:40:27,704UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=15m39s657ms).
2024-02-27 15:40:27,978UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m39s656ms).
2024-02-27 15:41:03,981UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 15:56:51,540UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=15m53s841ms).
2024-02-27 15:56:51,540UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=15m53s841ms).
2024-02-27 15:56:51,540UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m53s841ms).
2024-02-27 15:56:51,543UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=15m53s843ms).
2024-02-27 15:56:51,817UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=15m53s843ms).
2024-02-27 15:57:27,824UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:09:58,323UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=12m36s778ms).
2024-02-27 16:09:58,323UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=12m36s777ms).
2024-02-27 16:09:58,323UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=12m36s777ms).
2024-02-27 16:09:58,325UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=12m36s778ms).
2024-02-27 16:09:58,600UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=12m36s777ms).
2024-02-27 16:10:34,608UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:11:34,608UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:12:34,608UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:13:34,607UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:14:34,606UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:15:34,605UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:16:34,605UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:17:34,604UTC INFO [NeutrinoNode] Running health checks for peers=Set()
...
2024-02-27 16:40:34,608UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:47:55,983UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=6m57s565ms).
2024-02-27 16:47:55,985UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=6m57s564ms).
2024-02-27 16:47:55,987UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=6m57s563ms).
2024-02-27 16:47:55,988UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=6m57s564ms).
2024-02-27 16:47:56,246UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=6m57s564ms).
2024-02-27 16:48:02,170UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 16:49:02,174UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 17:04:58,045UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=16m2s54ms).
2024-02-27 17:04:58,045UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=16m2s53ms).
2024-02-27 17:04:58,047UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=16m2s54ms).
2024-02-27 17:04:58,047UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=16m2s53ms).
2024-02-27 17:04:58,307UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=16m2s54ms).
2024-02-27 17:07:06,211UTC WARN [HikariPool] bitcoin-s-wallet-db - Thread starvation or clock leap detected (housekeeper delta=2m8s166ms).
2024-02-27 17:07:06,212UTC WARN [HikariPool] bitcoin-s-node-db - Thread starvation or clock leap detected (housekeeper delta=2m8s167ms).
2024-02-27 17:07:06,212UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=2m8s165ms).
2024-02-27 17:07:06,213UTC WARN [HikariPool] bitcoin-s-chain-db - Thread starvation or clock leap detected (housekeeper delta=2m8s166ms).
2024-02-27 17:07:06,473UTC WARN [HikariPool] bitcoin-s.dlc.db - Thread starvation or clock leap detected (housekeeper delta=2m8s166ms).
2024-02-27 17:07:12,389UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 17:08:12,387UTC INFO [NeutrinoNode] Running health checks for peers=Set()
...
2024-02-27 17:18:12,385UTC INFO [NeutrinoNode] Running health checks for peers=Set()
2024-02-27 17:18:38,375UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2024-02-27 17:18:38,378UTC ERROR [BitcoinSServerMain] Exiting process
2024-02-27 17:18:38,390UTC INFO [NeutrinoNode] Stopping NeutrinoNode
2024-02-27 17:18:38,393UTC INFO [PeerManager] Stopping PeerManager
2024-02-27 17:18:38,402UTC INFO [PeerConnection] Disconnecting peer=Peer(217.230.38.207:8333)
2024-02-27 17:18:38,405UTC ERROR [NeutrinoNode] Error occurred while processing p2p pipeline stream
java.util.concurrent.TimeoutException: No elements passed in the last 1200000000000 nanoseconds.
	at org.apache.pekko.stream.impl.Timers$Idle$$anon$3.onTimer(Timers.scala:120)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1678)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1667)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1667)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:477)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:528)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-02-27 17:18:38,408UTC INFO [PeerConnection] Disconnecting peer=Peer(83.21.44.92:8333)
2024-02-27 17:18:38,409UTC ERROR [NeutrinoNode] Error occurred while processing p2p pipeline stream
java.util.concurrent.TimeoutException: No elements passed in the last 1200000000000 nanoseconds.
	at org.apache.pekko.stream.impl.Timers$Idle$$anon$3.onTimer(Timers.scala:120)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1678)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1667)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1667)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:477)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:528)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-02-27 17:18:38,437UTC INFO [PeerManager] Stopped PeerManager. Took 44ms
2024-02-27 17:18:38,452UTC ERROR [NeutrinoNode] Error occurred while processing p2p pipeline stream
java.util.concurrent.TimeoutException: No elements passed in the last 1200000000000 nanoseconds.
	at org.apache.pekko.stream.impl.Timers$Idle$$anon$3.onTimer(Timers.scala:120)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.onInternalTimer(GraphStage.scala:1678)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1(GraphStage.scala:1667)
	at org.apache.pekko.stream.stage.TimerGraphStageLogic.$anonfun$getTimerAsyncCallback$1$adapted(GraphStage.scala:1667)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:477)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:528)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:545)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-02-27 17:18:38,453UTC INFO [PeerFinder] Stopping PeerFinder
2024-02-27 17:18:38,471UTC INFO [PeerFinder] Done stopping PeerFinder
2024-02-27 17:18:38,471UTC INFO [NeutrinoNode] Node stopped! It took=81ms
2024-02-27 17:18:38,479UTC INFO [NodeCallbackStreamManager] Done draining akka streams for NodeCallbackStreamManager, it took=8ms
2024-02-27 17:18:38,481UTC INFO [HikariDataSource] bitcoin-s-node-db - Shutdown initiated...
2024-02-27 17:18:38,483UTC INFO [HikariDataSource] bitcoin-s-node-db - Shutdown completed.
2024-02-27 17:18:38,485UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Shutdown initiated...
2024-02-27 17:18:38,486UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Shutdown completed.
2024-02-27 17:18:38,487UTC INFO [HikariDataSource] bitcoin-s-chain-db - Shutdown initiated...
2024-02-27 17:18:38,488UTC INFO [HikariDataSource] bitcoin-s-chain-db - Shutdown completed.
2024-02-27 17:18:38,492UTC INFO [TorClient] No process found, binary wasn't started!
2024-02-27 17:18:38,494UTC INFO [WalletAppConfig] Stopping wallet rebroadcast task
2024-02-27 17:18:38,494UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Shutdown initiated...
2024-02-27 17:18:38,497UTC INFO [HikariDataSource] bitcoin-s-wallet-db - Shutdown completed.
2024-02-27 17:18:38,497UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Shutdown initiated...
2024-02-27 17:18:38,498UTC INFO [HikariDataSource] bitcoin-s.dlc.db - Shutdown completed.
2024-02-27 17:18:38,499UTC INFO [DLCWalletNeutrinoBackendLoader] DLCWalletLoaderApi stopped
2024-02-27 17:18:38,517UTC INFO [ServerBindings] ServerBindings stopped
2024-02-27 17:18:38,520UTC INFO [BitcoinSServerMain] Stopped neutrino node
```

**Comment by Christewart** [comment]
unable to reproduce this now, closing for now
