### ISSUE TITLE
Queue deadlocks in `buildDataMessageStreamGraph`

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5655]
seen on c3288a72

```
2024-09-05 20:34:13,542UTC INFO [DataMessageHandler] Query timed out with in state=FilterSync(syncPeer=Peer(152.44.137.83:8333),peers=Set(Peer(152.44.137.83:8333)
```

```
2024-09-06 02:28:43,647UTC ERROR [TaskInvocation] Future timed out after [60 seconds]
java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)org.apache.pekko.dispatch.MonitorableThreadFactory$PekkoForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:191)
	at scala.concurrent.Await$.result(package.scala:124)
	at org.bitcoins.node.NeutrinoNode.$anonfun$healthChecksRunnable$1(NeutrinoNode.scala:231)
	at org.apache.pekko.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:124)
2024-09-06 03:18:45,497UTC INFO [NeutrinoNode] Sending out tx message for tx=Vector()
2024-09-06 07:18:45,496UTC INFO [NeutrinoNode] Sending out tx message for tx=Vector()
2024-09-06 11:18:45,500UTC INFO [NeutrinoNode] Sending out tx message for tx=Vector()
2024-09-06 11:18:45,501UTC ERROR [PeerManager] Failed to sendToPeer message=inv
java.lang.IllegalStateException: Too many concurrent offers. Specified maximum is 16. You have to wait for one previous future to be resolved to send another request
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.bufferElem(QueueSource.scala:125)
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.$anonfun$callback$1(QueueSource.scala:136)
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.$anonfun$callback$1$adapted(QueueSource.scala:130)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:478)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:528)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)

2024-09-06 12:46:08,434UTC INFO [BitcoinSServerMain$] @@@@@@@@@@@@@@@@@@@@@ Shutting down BitcoinSServerMain$ @@@@@@@@@@@@@@@@@@@@@
2024-09-06 12:46:08,434UTC INFO [BitcoinSServerMain] Exiting process
2024-09-06 12:46:08,437UTC INFO [NeutrinoNode] Stopping NeutrinoNode
2024-09-06 12:46:08,439UTC INFO [PeerManager] Stopping PeerManager

```
[bitcoin-s.log](https://github.com/user-attachments/files/16908295/bitcoin-s.log)

**Comment by Christewart** [comment]
Seems like this is related to #5429 / #5470

**Comment by Christewart** [comment]
Another example on 490e0217

```
2024-09-12 15:00:01,413UTC DEBUG [PeerManager] Got cfilter from peer=Peer(127.0.0.1:8333) in stream
2024-09-12 15:00:01,422UTC DEBUG [DataMessageHandler] Received cfilter, filter.blockHash=DoubleSha256BDigestBE(00000000000000000000e6b8a4e28644bdcd1b5dbafdb628c731c1436372f851) state=FilterSync(syncPeer=Peer(127.0.0.1:8333),peers=Set(Peer(127.0.0.1:8333)),waitingForDisconnection=Set(),filterBatchCache.size=207)
2024-09-12 15:00:01,426UTC DEBUG [PeerManager] Done processing cfilter in peer=Peer(127.0.0.1:8333) state=FilterSync(syncPeer=Peer(127.0.0.1:8333),peers=Set(Peer(127.0.0.1:8333)),waitingForDisconnection=Set(),filterBatchCache.size=208)
2024-09-12 15:00:01,427UTC DEBUG [PeerConnection] Sending msg=verack to peer=Peer(141.98.219.12:8333) socket=141.98.219.12/<unresolved>:8333
2024-09-12 15:00:01,428UTC DEBUG [PeerManager] Got cfilter from peer=Peer(127.0.0.1:8333) in stream
2024-09-12 15:00:01,438UTC DEBUG [DataMessageHandler] Received cfilter, filter.blockHash=DoubleSha256BDigestBE(000000000000000000020bd8864ba9f95d91e115ab83717b74494a3e4bf3deae) state=FilterSync(syncPeer=Peer(127.0.0.1:8333),peers=Set(Peer(127.0.0.1:8333)),waitingForDisconnection=Set(),filterBatchCache.size=208)
2024-09-12 15:00:01,442UTC DEBUG [PeerManager] Done processing cfilter in peer=Peer(127.0.0.1:8333) state=FilterSync(syncPeer=Peer(127.0.0.1:8333),peers=Set(Peer(127.0.0.1:8333)),waitingForDisconnection=Set(),filterBatchCache.size=209)
2024-09-12 15:00:01,443UTC DEBUG [PeerConnection] Sending msg=getaddr to peer=Peer(141.98.219.12:8333) socket=141.98.219.12/<unresolved>:8333
2024-09-12 15:00:01,443UTC DEBUG [PeerManager] Adding peer to db Peer(141.98.219.12:8333)
2024-09-12 15:00:08,655UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(97.86.52.70:8333) with errMsg=Tcp command [Connect(97.86.52.70/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:00:08,655UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(170.75.175.7:8333) with errMsg=Tcp command [Connect(170.75.175.7/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:00:08,655UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(89.117.72.66:8333) with errMsg=Tcp command [Connect(89.117.72.66/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:00:08,656UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(89.233.207.67:8333) with errMsg=Tcp command [Connect(89.233.207.67/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:00:54,188UTC DEBUG [NeutrinoNode] Running health checks for peers=Set(Peer(141.98.219.12:8333), Peer(127.0.0.1:8333))
2024-09-12 15:01:22,384UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(193.37.255.146:8333) with errMsg=Tcp command [Connect(193.37.255.146/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:01:26,479UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(81.44.7.115:8333) with errMsg=Tcp command [Connect(81.44.7.115/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:01:38,767UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(176.171.71.181:8333) with errMsg=Tcp command [Connect(176.171.71.181/<unresolved>:8333,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:01:46,959UTC DEBUG [PeerConnection] Failed to connect to peer=Peer(184.75.223.227:5141) with errMsg=Tcp command [Connect(184.75.223.227/<unresolved>:5141,None,List(KeepAlive(true)),None,true)] failed because of java.net.ConnectException: Connection timed out
2024-09-12 15:01:54,192UTC ERROR [TaskInvocation] Future timed out after [60 seconds]
java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
	at org.apache.pekko.dispatch.MonitorableThreadFactory$PekkoManagedBlocker.block(ThreadPoolBuilder.scala:179)
	at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3977)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3959)
	at org.apache.pekko.dispatch.MonitorableThreadFactory$PekkoForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:191)
	at scala.concurrent.Await$.result(package.scala:124)
	at org.bitcoins.node.NeutrinoNode.$anonfun$healthChecksRunnable$1(NeutrinoNode.scala:231)
	at org.apache.pekko.actor.LightArrayRevolverScheduler$$anon$1$$anon$2.run(LightArrayRevolverScheduler.scala:124)
	at org.apache.pekko.dispatch.TaskInvocation.run(AbstractDispatcher.scala:59)
	at org.apache.pekko.dispatch.ForkJoinExecutorConfigurator$PekkoForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:61)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
2024-09-12 15:20:02,137UTC DEBUG [PeerConnection] Connection with peer=Peer(127.0.0.1:8333) failed with err=No elements passed in the last 20 minutes.
2024-09-12 18:35:56,169UTC DEBUG [NeutrinoNode] Wrote tx=Vector() to broadcastable table
2024-09-12 18:35:56,169UTC INFO [NeutrinoNode] Sending out tx message for tx=Vector()
```
[bitcoin-s.log](https://github.com/user-attachments/files/16985681/bitcoin-s.log)

**Comment by Christewart** [comment]
Related to #5498
