### ISSUE TITLE
ERROR [NodeCallbacks$NodeCallbacksImpl] onBlockReceived Callback failed with error:

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5760]
For some reason we are not processing blocks via our callback system when we receive them on steady state operations for our node. This has been running a couple days.

Observed on aafac074

```
2024-11-07 15:18:51,899UTC INFO [ChainHandler] Processed filters from height=869297 to 869297. Best filter.blockHash=00000000000000000000edeeb5a7bb1075995f05115331df53a492f00b1dddc3
2024-11-07 15:18:51,905UTC INFO [DataMessageHandler] We are synced
2024-11-07 15:18:52,625UTC INFO [DataMessageHandler] Received block=00000000000000000000edeeb5a7bb1075995f05115331df53a492f00b1dddc3 state=DoneSyncing(peers=Set(Peer(51.158.54.115:8333), Peer(127.0.0.1:8333)),waitingForDisconnection=Set())
2024-11-07 15:18:58,346UTC ERROR [TransactionProcessing] Error processing of block=00000000000000000000edeeb5a7bb1075995f05115331df53a492f00b1dddc3.
java.util.concurrent.RejectedExecutionException: Task slick.util.AsyncExecutor$$anon$1$$anon$2@68052d1b rejected from java.util.concurrent.ThreadPoolExecutor@136f401a[Running, pool size = 1, active threads = 1, queued tasks = 4999, completed tasks = 18925732]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
	at slick.util.AsyncExecutor$DefaultAsyncExecutor$$anon$4.execute(AsyncExecutor.scala:281)
	at slick.basic.BasicBackend$BasicDatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:318)
```

[bitcoin-s.log](https://github.com/user-attachments/files/17663818/bitcoin-s.log)

**Comment by Christewart** [comment]
fixed in #5788
