### ISSUE TITLE
Error on Bitcoind server startup 

### ISSUE THREAD

**Issue by cwaldron97** [bitcoin-s/bitcoin-s#580]
When testing PR: #558 I ran into an error message that is difficult to parse what is throwing the error. 
```
[info] Running (fork) org.bitcoins.server.Main                                                                         
[info] 15:38:30.631 INFO Main$ - Using pre-existing wallet                                                             
[info] 15:38:32.884 INFO Main$ - Error on server startup!                                                              
[info] com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input              
[info]  at [Source: (String)""; line: 1, column: 0]                                                                    
[info]  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)          
[info]  at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)                         
[info]  at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3971)                              
[info]  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)                               
[info]  at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:255)                                 
[info]  at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:16)                                      
[info]  at play.api.libs.json.Json$.parse(Json.scala:171)                                                              
[info]  at org.bitcoins.rpc.client.common.Client.$anonfun$getPayload$2(Client.scala:288)                               
[info]  at scala.util.Success.$anonfun$map$1(Try.scala:255)                                                            
[info]  at scala.util.Success.map(Try.scala:213)                                                                       
[info]  at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)                                                    [info]  at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)                                               [info]  at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)                                        [info]  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)                                                [info]  at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)                        [info]  at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)                     [info]  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)                                      [info]  at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)                                      [info]  at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)                                [info]  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)                                               
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)     
[info]  at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)                                           
[info]  at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)                               
[info]  at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)                                       
[info]  at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)  
```
It does not run into an error that ends up causing it to error out and quit. It seems to be sitting waiting for the JSON to be processed correctly.
I had to add logic for windows machine then realized that I have to rewrite and figure out how to do it for subsystems as file directories and pathing are setup as windows but look like Linux effectively. Another error I found and clear is that rpcport needs to be specified to 18332 as default is now 18443 as of V16. https://bitcoincore.org/en/releases/0.16.0/

**Comment by cwaldron97** [comment]
Solved issue by making my bitcoin.conf more default and making sure rpcport was set to 18443. Runs fine now.
