### ISSUE TITLE
Failed to sendToPeer message=inv java.lang.IllegalStateException: Too many concurrent offers.

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/bitcoin-s#5806]
Observed on eb6edab2. Possibly related to #5805  (both occurred in the same `bitcoin-s.log`)

```
2024-12-11 06:25:03,194UTC ERROR [PeerManager] Failed to sendToPeer message=inv
java.lang.IllegalStateException: Too many concurrent offers. Specified maximum is 16. You have to wait for one previous future to be resolved to send another request
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.bufferElem(QueueSource.scala:125)
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.$anonfun$callback$1(QueueSource.scala:136)
	at org.apache.pekko.stream.impl.QueueSource$$anon$1.$anonfun$callback$1$adapted(QueueSource.scala:130)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:478)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:528)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:831)

```

[bitcoin-s.log](https://github.com/user-attachments/files/18115495/bitcoin-s.log)

**Comment by Christewart** [comment]
Another instance on eb6edab2 . It seems like we are having queries time out in these logs as well ( #5802 )

[bitcoin-s.log](https://github.com/user-attachments/files/18130805/bitcoin-s.log)

**Comment by Christewart** [comment]
Another example
[bitcoin-s.log](https://github.com/user-attachments/files/18219421/bitcoin-s.log)
