### ISSUE TITLE
bitcoin-s node sync error

### ISSUE THREAD

**Issue by rorp** [bitcoin-s/bitcoin-s#913]
In some cases bitcoin-s node appends a new mainnet block header to the chain database at the same height as an existing block header. It breaks syncing of compact filter headers.

**Comment by Christewart** [comment]
I received the same error when syncing this morning: 

>2020-01-30T12:19:41 INFO [P2P] Received headers message with 1444 headers
2020-01-30T12:19:42 INFO [chain-verification] Processed headers from height=1662914 to 1664357. Best hash=00000000000000be41fa6a4355109cc359a12970b1a0401ac5a5911831b10cbd
2020-01-30T12:19:42 INFO [P2P] Requesting compact filter headers from=1580955 to=DoubleSha256BDigestBE(00000000000b45ab48b5c5f076e8b638e1a8fd5539afdf8f3b83c6b0a9812678)
2020-01-30T12:19:42 INFO [P2P] Got 2000 compact filter header hashes
[ERROR] [01/30/2020 06:19:42.507] [bitcoin-s-akka.actor.default-dispatcher-4] [akka://bitcoin-s/user/P2PClient$-1580386719497] Filter header batch size does not match block header batch size 2000 != 2001
org.bitcoins.chain.blockchain.UnknownBlockHash: Filter header batch size does not match block header batch size 2000 != 2001
        at org.bitcoins.chain.blockchain.ChainHandler.$anonfun$processFilterHeaders$3(ChainHandler.scala:203)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
